.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

One important issue fixed - red cross on scceeded build: Handle empty matrix https://github.community/t/empty-matrix-fails-workflow/128736

[GHActions][Hotfix] Better matrix generating - fix red cross

---

iroha/src/event.rs
iroha_client/src/client.rs
iroha_data_model/src/events.rs

Closes #1115 
Replace JSON with SCALE for Webs Socket messages (Web Socket is used for chain events).
Clients will not need to have both JSON and SCALE serialization implementations at the same time.

Replace JSON with SCALE for WS messages

---

.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

[GHA][CI][HOTFIX] -DCMAKE_BUILD_TYPE

---

Cargo.lock
iroha/Cargo.toml
iroha/src/maintenance.rs

Removed exposing of system metrics due external watchdog can collect such information #1162

Removed exposing CPU and memory usage in system metrics

---

iroha/src/lib.rs
iroha/src/smartcontracts/isi/permissions.rs
iroha/src/smartcontracts/isi/query.rs
iroha/src/torii.rs
iroha/test_network/src/lib.rs
iroha_actor/src/lib.rs
iroha_cli/src/main.rs
iroha_client/src/client.rs
iroha_client/tests/add_account.rs
iroha_client/tests/multisignature_transaction.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_http_server/src/lib.rs
lints.toml

Closes #1155 
Check query permissions by account in torii endpoint
Planned project feature.

Check query permissions by account in torii endpoint

---

irohad/subscription/scheduler_impl.hpp
test/module/irohad/subscription/subscription_test.cpp

[SE] better detection of scheduler load.

[SE] fixed thread pool tasks balancer

---

iroha_p2p/src/network.rs
iroha_p2p/src/peer.rs

We need to have the possibility to get a count of alive peers.
We would not block on checking every peer for its state.

Implementation of peer counts, closes #1165.

---

Cargo.lock
iroha_actor/Cargo.toml
iroha_actor/src/lib.rs

Closes #1277
Actors can stop themselves.
This feature is needed for p2p lib.
See tests for examples

Schedule stop actors

---

iroha/benches/kura.rs
iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/smartcontracts/isi/permissions.rs
iroha/src/sumeragi/mod.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/test_network/tests/sumeragi_with_mock.rs

Closes #1153
Recursive check for query permissions inside of instructions
We have nested expressions which might also contain queries that have to be checked accordingly.
The checks are recursive which means with high nestedness they might cause stack overflow. This has to be prevented by max instruction number config or a special config for max nested instructions number.

Recursive check for query permissions inside of instructions

---

iroha_p2p/src/network.rs
iroha_p2p/src/peer.rs
iroha_p2p/tests/mod.rs

Follow-up PR for https://github.com/hyperledger/iroha/issues/1272
Implemented (app level) public key exchange.
Implemented elimination of twin-connects.

Implementation of peer public keys exchange, closes #1272.

---

.github/iroha1.inc.yml
.github/workflows/iroha1-on-issue-comment.yml
.github/workflows/iroha1-on-pull-request.yml
.github/workflows/iroha1-on-push.yml
.github/workflows/iroha1-on-schedule.yml
.github/workflows/iroha1-on-workflow-dispatch.yml

[GHA] test build

---

iroha/src/smartcontracts/isi/asset.rs
iroha/src/smartcontracts/isi/query.rs
iroha/test_network/src/lib.rs
iroha_client/src/client.rs
iroha_client/tests/permissions.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/query.rs
iroha_permissions_validators/Cargo.toml
iroha_permissions_validators/src/lib.rs

Closes #1156 
OOB Query Permissions:
1. Access only data of this account
2. Access only data of the account's domain
Also removed a duplicate query -> therefore API will change slightly.
Planned feature

OOB Query Permission Checks

---

iroha_crypto/src/lib.rs

Signed-off-by: 0x009922 <a.marcius26@gmail.com>
I updated the outdated docs with actual information that describes what is contained inside of `Signature` structure. Also, I renamed an argument of `Signature::verify` method from `message` to `payload` to keep consistency with `Signature::new` method.

docs(iroha_crypto): update `Signature` docs and align args of `verify`

---

.github/workflows/iroha2-dev.yml
iroha_data_model/src/events.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_schema/iroha_schema_bin/src/main.rs

Closes  #1265
Adds derive to every item in data model. Also adds schema generation to ci

Add derives for data model

---

docker/iroha-builder/Dockerfile

Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

[GHA][Docker] fix clang in iroha-builder

---

iroha/src/block_sync.rs
iroha/src/kura.rs
iroha/src/queue.rs
iroha/src/sumeragi/mod.rs
iroha/test_network/tests/sumeragi_with_mock.rs
iroha_actor/src/actor_id.rs
iroha_actor/src/broker.rs
iroha_actor/src/deadlock.rs
iroha_actor/src/lib.rs

Remove api change of broker fixup commit.

Remove subscription id from actor public API

---

docs/source/build/index.rst

Signed-off-by: Ry Jones <ry@linux.com>

Add missing brew dep

---

.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml
test/integration/acceptance/get_transactions_test.cpp

/build before-merge
Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

[GHA] CTest allowed to fail

---

iroha_actor/src/lib.rs

Execute on_start in actor synchronously. Closes #1363 
See #1363 
None found, as now we have 2 options - the previous option of parallel start is retained.

Execute on_start in actor synchronously

---

irohad/subscription/scheduler_impl.hpp

[SE] is busy fix

---

docs/source/references/api_spec.md
iroha/Cargo.toml
iroha/src/torii/mod.rs

Update api spec and fix health endpoint

Update api spec and fix health endpoint

---

docs/source/references/api_spec.md
iroha/src/torii/mod.rs
iroha_client/src/client.rs
iroha_client/src/http_client.rs

Change query endpoint to POST instead of GET

---

iroha_client_cli/src/main.rs

Fix iroha_client_cli::events (#1395)

---

Cargo.lock
iroha_actor/src/broker.rs
iroha_actor/src/lib.rs
iroha_actor/tests/deadlock.rs
iroha_cli/src/main.rs
iroha_client/Cargo.toml
iroha_futures/tests/basic.rs
iroha_logger/Cargo.toml
iroha_p2p/tests/mod.rs

Removal of unnecessary dependencies.
There were duplicating dependencies which we actually didnt used.
Faster build times

Remove unnecessary dependencies

---

test/benchmark/bm_query.cpp
test/framework/integration_framework/integration_test_framework.cpp
test/integration/acceptance/add_peer_test.cpp
test/integration/acceptance/fake_peer_example_test.cpp
test/integration/acceptance/fake_peer_fixture.hpp
test/integration/acceptance/remove_peer_test.cpp
test/regression/regression_test.cpp

/build before_merge
Fixes regression test for RocksDB implementation.

[TESTS] regression test fix

---

.github/CODEOWNERS

There are new team members, also some team members left - so the codeowners needs to be updated.

Update CODEOWNERS.md with new team members

---

iroha/src/smartcontracts/isi/query.rs
iroha/src/torii/mod.rs
iroha/src/torii/utils.rs
iroha_version/src/lib.rs

Http status code now are working.
Before hand every error status code was 500, because of weird warp crate architecture.
Proper error reporting in http

Fix http status codes

---

.github/workflows/push-nightly.yml

Add ci workflow to push iroha2 build to dockerhub with nightly tag and commit hash.
Devs building on Iroha2 can use a fixed version of docker container even though we have not released a stable version yet.

Add optional nightly tags with date

---

.github/workflows/iroha2-push-nightly.yml

Add ci workflow to push iroha2 build to dockerhub with nightly tag.
It has to be in the main branch due to limitations for `workflow_dispatch` event.
Closes #1447 
Devs building on Iroha2 can use a fixed version of docker container even though we have not released a stable version yet.

Adds Iroha2 workflow to push nightly build to Dockerhub

---

.github/workflows/iroha2-push-nightly.yml

Updates workflow so that it matches main - otherwise this workflow can not run on iroha2-dev.

Updates workflow so that it matches main

---

iroha/src/sumeragi/mod.rs
iroha_client/src/client.rs
iroha_client/tests/multisignature_transaction.rs

Make fields of client public to all of its users

Make fields public in client

---

iroha/src/tx.rs

Signed-off-by: s8sato <49983831+s8sato@users.noreply.github.com>
Same as the [solution](https://github.com/hyperledger/iroha/issues/1194#issuecomment-926405049)

Fix overflow when subtracting durations (#1194)

---

.github/workflows/iroha2-dev.yml
iroha/test_network/src/lib.rs
iroha/test_network/tests/test_client_config.json
iroha_client/Cargo.toml
iroha_client/config.json
iroha_client/src/client.rs
iroha_client/src/http_client.rs
iroha_client/tests/test_client_config.json
iroha_dsl/tests/dsl.rs
iroha_dsl/tests/test_client_config.json

Allow usage of HTTPS in Rust client lib by removing hardcoded HTTP.
Closes #1449

Allow usage of HTTPS in Rust client lib

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
iroha/src/queue.rs
iroha_client/tests/tests/multisignature_transaction.rs

Queue behavior change. Transactions are left in queue until they become visible in blockchain or until they expire

Queue fixup

---

iroha_client/Cargo.toml
iroha_client/src/client.rs
iroha_client/src/http_client.rs

Add http headers to client library.

Add header specification to client library

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-push-nightly.yml
.github/workflows/iroha2.yml
docker-compose.yml

Signed-off-by: s8sato <49983831+s8sato@users.noreply.github.com>
* Update docker publish target to `hyperledger/iroha2` #1453
* Update corresponding compose images #
* Update `docker/build-push-action` to `v2` #
* Unify `runs-on: ubuntu-latest` in docker-related jobs #
* Unify `actions/upload-artifact` to `v2` #
* Update `iroha2-dev.jobs.publish-artifacts.container` to `rust:1.55-buster` #
As we update both of publish target and compose source at the same time
composing may not work until images have published
so it may be better to plan the time to merge this PR

Update docker publish target to hyperledger/iroha2 #1453 Fix some workflows #

---

iroha/src/queue.rs
iroha/src/smartcontracts/isi/mod.rs
iroha/src/sumeragi/mod.rs
iroha/src/torii/mod.rs
iroha_client/src/client.rs
iroha_client/tests/tests/restart_peer.rs

- Queue stress test
- Some other minor tests added for queue cases
- Queue test fixes
- Fixes in the queue behavior due to improper rebase
- Unnecessary (due to removed functonaility) test with getting transactions on leader - removed
Closes #1483 
Closes #1476

Queue stress test

---

.github/TESTS_ALLOWED_TO_FAIL
.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

Better cathegories in CTest logs. Just a little improvement.
system_irohad_test now MAY FAIL, see #1554

[GHA] CTest categories

---

.github/build-iroha1.src.yml
.github/chatops-gen-matrix.sh
.github/workflows/build-iroha1.yml
cmake/Modules/Findursa.cmake
docker/iroha-builder/Dockerfile

Simplify GHA workflow matrix. Iroha+Ursa now is built, earlier it was a regular irohad.

[GHA] remake matrix to buildspec, fix build with URSA

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor_impl.hpp

/build all
Signed-off-by: kuvaldini <ivan@kuvaldini.pro>

[mst] #1489 clean up, prettify

---

irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
irohad/ordering/impl/on_demand_os_server_grpc.cpp
irohad/ordering/on_demand_ordering_service.hpp

Signed-off-by: Andrei Lebedev <lebdron@gmail.com>
Prevent OS server from creating blocks when there are not enough transactions in the pool.

Fix small blocks fixup

---

irohad/ametsuchi/impl/mutable_storage_impl.cpp
irohad/ametsuchi/impl/rocksdb_indexer.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp

Closes hyperledger#1339
Fix #1528

Commit WSV every 1000 blocks during reindex, and do not double commit, fix inconsistency, fix #1528

---

.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

gha fix dockerpush

---

client/src/client.rs
core/src/torii/mod.rs
data_model/src/query.rs
macro/derive/src/lib.rs
telemetry/src/ws.rs

Use VersionedQueryResult vs QueryResult for /query endpoint

---

.github/workflows/iroha2-add-label.yml
.github/workflows/iroha2-dev-pr-heavy.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-unstable.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr.yml
.github/workflows/iroha2-push-nightly.yml
.github/workflows/iroha2.yml
core/test_network/src/lib.rs

Testing the possibility to switch back to GitHub runners as there are currently problems with self hosted runners. 
Also updated log level for test network:
- bench - WARN
- other - INFO
Previous log level of TRACE had performance implications due to printing all logs to std out and also made debugging failed jobs in CI difficult.
Working CI
Possibly it will slow down the CI and might sometimes fail tests due to not enough parallelism.

Switch to GitHub Runners

---

core/src/block_sync.rs
core/src/sumeragi/mod.rs
core/test_network/src/lib.rs
p2p/src/network.rs
p2p/tests/p2p.rs

[Opt] `FuturesUnordered` instead of `join_all`

---

.github/workflows/iroha2-dev-pr-title.yml

Checks PR title format that was decided on status call
Example: `[feature] #1: Some new feature`
#1652 
Easier to generate change log and release notes in the future.

[feature] #1652: PR Title Formatting

---

actor/src/broker.rs
actor/src/lib.rs
docs/source/guides/actor.md
p2p/src/network.rs

Add markdown document with onboarding for actor system onboarding. Also fix some minor issues.
Related to #1649

[fix] #1649: Add actor doc and minor fixes

---

.github/CODEOWNERS

Remove i1i1 from maintainers

---

core/src/kura.rs

A tiny fix for static analysis error introduced in #1678.

[refactor]: Fix linter error

---

Cargo.lock
actor/Cargo.toml
client/Cargo.toml
client/src/http_client.rs
client_cli/Cargo.toml
core/Cargo.toml
core/src/queue.rs
core/test_network/Cargo.toml
lints.toml
p2p/Cargo.toml
p2p/src/peer.rs
telemetry/Cargo.toml

[refactor]: #1687 bump dependencies

---

docs/source/configure/index.rst
docs/source/getting_started/index.rst
docs/source/maintenance/metrics.rst

Added notes that in configuration proposal delay must be bigger than proposal_creation_timeout.
Tried to add some information on ports for metrics (please review it carefully, I am not very sure about that).
Also fixed a couple of indentation warnings for doc build. 
Better Docs
None

Docs: Small Fixes on Config and Docker Metrics

---

core/src/block.rs
version/derive/src/lib.rs
version/derive/tests/ui_fail/unknown_field_in_version_attribute.rs
version/derive/tests/ui_fail/unknown_field_in_version_attribute.stderr

Disallow unknown fields in `version` attribute

[fix] #0000: allow only known fields in version attribute

---

docker-compose.yml

[fix] #666: Fixed a problematic typo in previous PR.

---

core/src/torii/mod.rs
core/src/torii/tests.rs
core/src/torii/utils.rs
core/test_network/src/lib.rs
docs/source/references/config.md

Have `warp` filters in `Torii` only receive part of the state they require, not everything
Closes  #1725

[refactor] #1725: Remove global state in Torii

---

Cargo.lock
crypto/Cargo.toml
crypto/src/lib.rs
crypto/src/multihash.rs
crypto/src/varint.rs

* remove `serde_json` as dependency of `iroha_crypto`
* remove `openssl-sys` as direct dependency of `iroha_crypto`
* don't implement `TryFrom` for references to `PublicKey` and `Multihash`, use owned types

[refactor]: iroha_crypto dependencies

---

client/src/client.rs
core/src/event.rs
core/src/tx.rs
data_model/src/events.rs
data_model/src/transaction.rs
schema/bin/src/main.rs

Split `EventSocketMessage` into separate enums for transmitting / receiving
Less chance a wrong message will be sent over the socket

[refactor] #1210: Split event stream

---

.github/workflows/iroha2-dev.yml
Dockerfile.ci

Updated to Mold v1.0
None
Production-ready linker
None

[ci]: Update Mold 1.0

---

client/src/client.rs
core/src/block.rs
core/src/block_sync.rs
core/src/event.rs
core/src/lib.rs
core/src/stream.rs
core/src/torii/mod.rs
core/src/torii/tests.rs
core/src/wsv.rs
data_model/src/lib.rs
data_model/src/transaction.rs
docs/source/references/api_spec.md
schema/bin/src/main.rs

[feature] #1210 Block streaming - server side

---

client/tests/integration_tests/add_asset.rs
client/tests/integration_tests/asset_propagation.rs
core/test_network/src/lib.rs

Added test to verify that it's possible to both register and mint an asset in one `tx`. 
Closes #1404
More tests. 
More tests.

[fix] #1404: Verify fixed.

---

configs/peer/genesis.json

Updates the gensis block to work with the new `name` validation.
Fixes regression introduced in PR #1734 . 
Docker compose now works.
None

[fix] #1734: Update genesis to fit the new Domain validation.

---

configs/peer/config.json
core/src/genesis.rs
core/src/kura.rs
core/src/queue.rs
core/src/samples.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/view_change.rs
core/src/wsv.rs
core/test_network/tests/sumeragi_with_mock.rs
docs/source/references/config.md
p2p/src/peer.rs

Consensus fixes for #1751, #1715. It was previously merged into `2.0.0-pre.1.rc.1` branch. So for more details check previous PRs for these issues

[fix] #1751, #1715: Consensus fixes

---

core/src/lib.rs
core/src/wsv.rs

Apply additional review comments of #1764
Close #1772

[fix] #1772: Fix after #1764

---

core/src/sumeragi/mod.rs

[fix] #1794: Sign block by leader in single node deployment

---

Cargo.lock
client/src/client.rs
core/src/kura.rs
core/src/stream.rs
core/src/torii/tests.rs
data_model/src/transaction.rs
macro/Cargo.toml
macro/derive/Cargo.toml
macro/derive/src/lib.rs
macro/src/lib.rs
schema/Cargo.toml
schema/bin/Cargo.toml
schema/derive/src/lib.rs
schema/src/lib.rs
version/Cargo.toml
version/derive/Cargo.toml
version/derive/src/lib.rs
version/derive/tests/scale.rs
version/src/lib.rs

`data_model` depends on these libraries. Consider this PR a prerequisite for `no_std` support in `data_model`
Manually implemented `Display` trait for `iroha_version::Error` to have it also available in `no_std` context
Relates to #1749

[feature] #1749: no_std support for version, schema and macro libraries

---

Cargo.lock
core/src/block.rs
core/src/queue.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/view_change.rs
core/src/tx.rs
crypto/Cargo.toml
crypto/src/hash.rs
crypto/src/lib.rs
crypto/src/multihash.rs
crypto/src/signature.rs
crypto/src/varint.rs
crypto_cli/src/main.rs
data_model/src/transaction.rs
schema/derive/src/lib.rs

Make `iroha_crypto` `no_std` compatible
* remove `eyre` and implement custom error messages instead
closes #1794
relates to #1749

[feature] #1749: no_std support for iroha_crypto

---

Cargo.lock
cli/src/main.rs
core/Cargo.toml
core/src/config.rs
core/src/lib.rs
core/test_network/src/lib.rs
docs/source/references/config.md

Optional terminal colors for panic errors.
Logging to a file will be free of special symbols for terminal

[feature] #1805: Optional terminal colors for panic errors

---

.gitignore
irohad/ametsuchi/impl/database_cache/cache.hpp
irohad/ametsuchi/impl/rocksdb_block_query.cpp
irohad/ametsuchi/impl/rocksdb_block_storage.cpp
irohad/ametsuchi/impl/rocksdb_common.hpp
irohad/ametsuchi/impl/rocksdb_indexer.cpp
irohad/ametsuchi/impl/rocksdb_query_executor.cpp
irohad/ametsuchi/impl/rocksdb_temporary_wsv_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/main/application.cpp
irohad/main/impl/rocksdb_connection_init.cpp
irohad/ordering/impl/batches_cache.cpp
irohad/ordering/impl/batches_cache.hpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
irohad/ordering/on_demand_ordering_service.hpp
libs/common/radix_tree.hpp
test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.cpp
test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.hpp
test/module/irohad/ametsuchi/rocksdb_common_test.cpp
test/module/irohad/ordering/on_demand_connection_manager_test.cpp
test/module/irohad/ordering/on_demand_os_test.cpp
test/module/irohad/ordering/ordering_mocks.hpp
test/module/shared_model/interface_mocks.hpp

[fixed] Drop wsv flag behavior. Instead of a single big transaction to db it makes several fixed-size transactions. Prevent OOM.
[fixed] Signatory case insensetive checks.
[fixed] Txs status description 5 byte -> (1 byte if ```true``` or 0 byte if ```false```) per entry.
[added] Bloom filter in RDB.
[added] RadixTrie enumerate nodes by prefix filter
[added] RDB 2-layer cache for WSV.

Fix/Iroha v1.4-rc.1 fixes

---

core/src/sumeragi/mod.rs

Use Display for `eyre::Report` returned from Block validation errors. 
#1819 
Readability
None

[fix] #1819: Remove traceback from error report in validation.

---

crypto/src/hash.rs
crypto/src/signature.rs
data_model/src/expression.rs
data_model/src/merkle.rs
schema/bin/src/main.rs
schema/src/lib.rs

* fixed `IntoSchema` representation of some types
* added test to verify all types are present in the schema
* added `IntoSchema` for `MerkleTree<VersionedTransaction>` and `VersionedValidBlock`
Schemas of `MerkleTree` and `VersionedValidBlock` are not necessary for client/server communication because only their hashes are exhanged as in `HashOf<T>`. However, it may make sense for the client to validate the hashes and to do so it would need the format of the structure for which the hash is calculated.
I could have enforced that schema of `T` for every `T` in `HashOf<T>` be present in the schema. I didn't want to guarantee that schema is provided for every hashed structure. Would this be preferred?
`Hash<32>` will be added in a separate PR because the change is more complex
Closes #1801

[fix] #1801: add schema for `MerkleTree` / `VersionedValidBlock`, fix `HashOf` / `SignatureOf` schemas

---

Cargo.lock
client/benches/torii.rs
client/examples/million_accounts_genesis.rs
client/src/client.rs
client/src/config.rs
core/Cargo.toml
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/genesis.rs
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/wasm.rs
core/src/sumeragi/mod.rs
core/src/torii/mod.rs
core/src/tx.rs
core/src/wsv.rs
core/test_network/src/lib.rs
core/test_network/tests/sumeragi_with_mock.rs
data_model/src/transaction.rs
data_model/tests/data_model.rs
docs/source/references/config.md

[feature] #1425: add limits to wasm execution

---

.github/CODEOWNERS

[documentation]: Updates codeowners file

---

core/src/lib.rs
core/src/queue.rs
core/src/sumeragi/mod.rs
core/src/torii/mod.rs
core/src/torii/tests.rs
core/test_network/tests/sumeragi_with_mock.rs

[refactor]: add wsv reference to queue

---

crypto/src/lib.rs
crypto/src/signature.rs

Fix for incorrect formatting strings in error reports.
TBD
Fixes

[fix] #0000: Fix build error in Iroha JavaScript.

---

.github/CODEOWNERS

Add myself to the codeowners file
I'm gonna receive notificaitons from this repo

[documentation]: Add arjentix into codeowners file

---

core/src/smartcontracts/wasm.rs

Linear memory can be limited with `StoreLimits` via `store.limiter` and therefore, importing memory from host wasn't required and would only increase complexity of writing smartcontract for the user
closes #1767 
As of Wasmtime(0.33.0) the `Trap` returned is that of fuel consumed. I opened an issue with `Wasmtime` to fix that

[feature] #1767: Wasm limit memory

---

.gitchangelog.rc
CHANGELOG.rst

Added automatic changelog generation.
Closes #1928
Automatic changelog generation
Changelog format is not ideal. Missing significant portion of tags. Since long commit messages are not standardised, sometimes the squashed commits contain more information than they should.

[feature] #1928: implement changelog generation using `gitchangelog`

---

wasm/README.md

[documentation]: add wasm README

---

config/derive/Cargo.toml
core/src/lib.rs
version/src/lib.rs

Fixed improper feature flags. 
Closes #1939 
Pass QA tests. 
None

[fix] #1939: Proper features for `iroha_config_derive`.

---

docs/source/references/api_spec.md

[documentation]: Added missing docs to `api_spec.md`.

---

wasm/src/lib.rs

[fix] #1953: fix return value for QueryBox execution in wasm

---

.github/workflows/iroha2.yml

Signed-off-by: Ahmed Elkashef <ahmedelkashef2012@gmail.com>
- add +nightly to the arguments to fix coverage

update the environment variables to fix coverage

---

CONTRIBUTING.md
README.md
cli/Cargo.toml
cli/README.md
cli/src/lib.rs
client/README.md
core/Cargo.toml
core/src/init.rs
crypto_cli/README.md
docs/source/references/config.md
wasm/README.md

- Add telemetry to default features as per @Cre-eD 's request. 
- Update outdated `README.md` files. 
Closes #1979 
Default deployment has support for prometheus metrics
Increased binary size.

[ci]: Add telemetry to default features. 

---

client/tests/integration/mod.rs
client/tests/integration/roles.rs
core/src/smartcontracts/isi/mod.rs
core/src/wsv.rs
data_model/src/role.rs
permissions_validators/src/public_blockchain/mod.rs
permissions_validators/src/public_blockchain/transfer.rs

- Added new permission validator that checks for `Transfer` execution count and sets some limit per time period. I.e. it's possible to limit someone to **10** `Transfer` transactions per day
- Added test which demostrates it. Also there are additional comments so that someone from Orillion project could read this, cause this test is needed for their use-cases
Closes #2040 
One more permission validator and one more integration test
- I'm not sure if I used permission validators system on the right way
- Should this new validator participate in `default_permissions()`?

[feature] #2040: Add integration test with transaction execution limit

---

docs/source/requirements.txt

Signed-off-by: Sara G <lira.lemur@gmail.com>
Fixed broken requirement
Jinja2 and MarkupSafe had an issue. Now they are friends again :) 
Building docs
None
Tested on RTD on test acc - all works. 
[skip ci] (in case it works)

Docs: Fix Docs Build

---

cli/src/torii/tests.rs
client/Cargo.toml
client/benches/tps/README.md
client/benches/tps/config.json
client/benches/tps/dev.rs
client/benches/tps/lib.rs
client/benches/tps/oneshot.rs
client/src/client.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/triggers/time_trigger.rs
client_cli/src/main.rs
core/src/block.rs
data_model/src/events/pipeline.rs
docs/source/references/api_spec.md
docs/source/references/keypairs.md
scripts/analyze_telemetry.sh
telemetry/derive/src/lib.rs
telemetry/derive/tests/ui_fail/args_no_wsv.rs
telemetry/derive/tests/ui_fail/bare_spec.rs
telemetry/derive/tests/ui_fail/doubled_plus.rs
telemetry/derive/tests/ui_fail/no_args.rs
telemetry/derive/tests/ui_fail/non_snake_case_name.rs
telemetry/derive/tests/ui_fail/not_execute.rs
telemetry/derive/tests/ui_fail/not_return_result.rs
telemetry/derive/tests/ui_fail/return_nothing.rs
telemetry/derive/tests/ui_fail/trailing_plus.rs
telemetry/src/metrics.rs

Add a TPS benchmark for performance check during development
[Report sample](https://github.com/hyperledger/iroha/files/8395528/tps_4peers-80000interval_us-8192max_txs-5blocks-10samples.-.Criterion.rs.pdf)
* Closes #1952
* Benchmarks to publish official TPS will be left to another issue:
- #1230
- #1204
New standard for TPS optimizations
None
[README](https://github.com/s8sato/iroha/blob/feat/1952/client/benches/tps/README.md)

[feature] #1952: Add a TPS benchmark as a standard for optimizations

---

client/examples/million_accounts_genesis.rs
core/src/genesis.rs

Created a builder struct to ease the assembling of genesis blocks for used in tests and by a web tool.
#1623
Many of the tests can be made more efficient using this instead of client code to register accounts et cetera.
It is possible to create invalid genesis blocks using the builder as validation would slow it down and add complexity.

[fix] #1623: Create a RawGenesisBlockBuilder

---

.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2.yml
Dockerfile.ci
rust-toolchain.toml

Version bump. 
None
Update
None

[ci]: Bump rust, mold and nightly to 1.60, 1.2.0 and 1.62 respectively.

---

.github/CODEOWNERS

Added myself to the codeowners file
I can review PRs

[documentation] Add samhsmith to codeowners file

---

cli/Cargo.toml
cli/README.md
client/Cargo.toml
core/Cargo.toml
core/docs/Cargo.toml
core/src/lib.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/permissions.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/world.rs
core/src/wsv.rs
data_model/Cargo.toml
data_model/src/account.rs
data_model/src/events/data/events.rs
data_model/src/events/data/filters.rs
data_model/src/lib.rs
data_model/src/query.rs
permissions_validators/Cargo.toml
permissions_validators/src/private_blockchain/query.rs
schema/bin/Cargo.toml
tools/parity_scale_decoder/Cargo.toml

Removed `roles` feature from everywhere to provide (de-)serialization stability
* Closes #2111 
No more pain and hidden bug caused by roles feature
If we will need it back it's can be tricky to find all places where it should be conditional compiled or something like that

[fix] #2111: Remove `roles` feature

---

.github/CODEOWNERS

Add myself to CODEOWNERS
I can participate in development
I can participate in development

[documentation]: Add QuentinI to codeowners file

---

tools/kura_inspector/README.md

Add readme for Kura Inspector
Resolves #1991

[documentation] #1991: Add readme to Kura inspector

---

Dockerfile

Added missing dependencies to the `Dockerfile`
None

[ci]: Fix deploy pipeline.

---

.github/CODEOWNERS

Add Ekaterina (the tech writer for the project) to the list of codeowners

[documentation]: Add Ekaterina to the list of codeowners

---

Cargo.lock
client/Cargo.toml
client/src/client.rs
client/tests/integration/mod.rs
client/tests/integration/query_errors.rs

- `QueryResponseHandler` emits typed error, which can be either a certain error with decoded `QueryError` or some indeterminate `eyre` error
- Add some unit tests
- Add one integration test
Resolves #2105 
Client users will be able to handle query errors more precisely. Improves DX/UX. 
None

[feature] #2105: handle query errors in client

---

tools/parity_scale_decoder/src/main.rs

Signed-off-by: Daniil Polyakov <arjentix@gmail.com>
Previously `parity_scale_decoder` tests were using hardcoded string to compare with the result. Now objects are stored instead. It's easier to read and update.
I can't use `serde_json` here (as proposed in the issue), because this program output isn't exactly *json*. It's the output of `Debug` trait which has type name for every field.
* Closes #2159 
* Easier to read
* Easier to update
None
```bash
cargo test --package parity_scale_decoder --bin parity_scale_decoder -- tests --nocapture
```
We can change `parity_scale_decoder` implementation to use `serde::de::Serialize` instead of `Debug`. But I don't think we need it. This approeach will decrease the number of supported types and probably will give less info about a type

[fix] #2159: Improve `parity_scale_decoder` tests

---

README.md

Review README. View file: https://github.com/outoftardis/iroha/tree/doc-readme-review#hyperledger-iroha
Addresses #2181

[documentation] #2181: Review README

---

.github/workflows/iroha2-dev-pr-unstable.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
client/build.rs

[fix] #2215: Make nightly optional for building Iroha.

---

docs/source/guides/metrics.md
docs/source/references/api_spec.md

Add documentation for metrics: https://github.com/outoftardis/iroha/blob/doc-metrics/docs/source/guides/metrics.md
Partially addresses #1280

[documentation] #1280: Document Iroha metrics

---

Dockerfile.ci
cli/src/torii/mod.rs
client/src/client.rs
client/src/http_default.rs
client/tests/integration/transfer_asset.rs
client/tests/integration/triggers/time_trigger.rs
config/src/lib.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/domain.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/triggers.rs
core/src/smartcontracts/isi/tx.rs
core/src/smartcontracts/isi/world.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/events/execute_trigger.rs
data_model/src/events/pipeline.rs
data_model/src/isi.rs
data_model/src/lib.rs
data_model/src/pagination.rs
data_model/src/query.rs
data_model/src/role.rs
flakyness.org
p2p/src/network.rs
tools/parity_scale_decoder/src/generate_map.rs
tools/parity_scale_decoder/src/main.rs

- Expose `Mintable` and `MintabilityError` in `prelude`. 
- Replace `#[log]` annotations with explicit trace instructions. 
- Add `Transfer` implementations for `Asset`s of `Fixed` and `u128` types. 
- Refactor `Error` implementations. 
- Refactor `data_model`. 
Closes #2149
Closes #2036
Closes #2186 
Smaller code.
None.

[feature] #2186: Add transfer instructions for all asset types

---

CONTRIBUTING.md

Update the structure and wording of the CONTRIBUTING guide
https://github.com/outoftardis/iroha/blob/doc-contributing-review/CONTRIBUTING.md
Addresses #2192

[documentation] #2192: Review contributing guidelines

---

tools/kagami/README.md
tools/kagami/src/main.rs

Update the readme for Kagami: https://github.com/outoftardis/iroha/tree/doc-kagami/tools/kagami

[documentation] #2193: Update Kagami documentation

---

wasm/README.md
wasm/src/lib.rs

Reviewed readme: https://github.com/outoftardis/iroha/tree/doc-wasm/wasm

[documentation] #2193: Update README for wasm crate

---

macro/README.md

Updated `macro` readme: https://github.com/outoftardis/iroha/tree/doc-macro/macro#iroha-macros

[documentation] #2193: Update README for macro crate

---

core/src/kura.rs

Removed some development code I left in by accident.
#1149

[fix] #1149: Remove nocheckin code

---

cli/README.md

Updated readme: https://github.com/outoftardis/iroha/tree/doc-cli/cli#iroha-cli

[documentation] #2193: Update Iroha CLI documentation

---

client/README.md
client_cli/README.md

Updates readmes for:
- Iroha Client: https://github.com/outoftardis/iroha/tree/doc-client/client#iroha-client
- Iroha CLI Client: https://github.com/outoftardis/iroha/tree/doc-client/client_cli#iroha-cli-client

[documentation] #2193: Update Iroha Client and Iroha CLI Client documentation

---

flakyness.org

Updated `flakyness.org` (lightweight markup language rendered by GitHub, which has support for spreadsheets, and execution like an `ipython` notebook). 
None
Data
Takes long to gather.

[documentation]: Flakyness report

---

CONTRIBUTING.md
hooks/README.md

Updated the readme in `/hooks` and added a reference to it from the contributing guidelines

[documentation]: Update information on git hooks

---

.github/build-iroha1-fork.src.yml
.github/workflows/build-iroha1-fork.yml

[Draft] Iroha forks allow build

---

ffi/derive/src/bindgen.rs
ffi/derive/src/derive.rs
ffi/derive/src/impl_visitor.rs
ffi/derive/src/lib.rs
ffi/derive/tests/ui_fail/derive_skip_field.rs
ffi/derive/tests/ui_fail/derive_skip_field.stderr
ffi/derive/tests/ui_fail/derive_skip_struct.rs
ffi/derive/tests/ui_fail/derive_skip_struct.stderr
ffi/tests/bindgen_derive.rs
ffi/tests/ffi_bindgen.rs

[fix] #2282: improve FFI derives from getset implementation

---

.github/build-iroha1-fork.src.yml
.github/workflows/build-iroha1-fork.yml

Set read only permission for build windows job

Fix permissions for windows build job

---

client/tests/integration/triggers/by_call_trigger.rs
core/src/smartcontracts/isi/mod.rs
data_model/src/trigger/mod.rs
data_model/src/trigger/set.rs

Signed-off-by: Daniil Polyakov <arjentix@gmail.com>
* Added `Trigger`-related match arm in `RegisterBox` execution
* Added test with trigger unregistration
* Fixed real bug with removing from `trigger::Set`, see changes
* Closes #2295 
* Possibility to unregister trigger for external users
* New test
* Bug fixing
None
```bash
cargo test --package iroha_client --test mod -- integration::triggers::by_call_trigger::unregister_trigger --exact --nocapture 
```

[fix] #2295: Fix unregister trigger bug

---

.github/build-iroha1-fork.src.yml
.github/workflows/build-iroha1-fork.yml
docs/source/requirements.txt

Update develop from main

---

actor/src/lib.rs
cli/src/config.rs
cli/src/lib.rs
cli/src/samples.rs
cli/src/torii/tests.rs
core/src/block.rs
core/src/block_sync.rs
core/src/genesis.rs
core/src/kura.rs
core/src/sumeragi/config.rs
core/src/sumeragi/fault.rs
docs/source/references/config.md
p2p/src/network.rs
telemetry/src/config.rs
telemetry/src/retry_period.rs
telemetry/src/ws.rs

Refactor names of some parameter config variables to make them more descriptive, such as the omnipresent `mailbox`.
Resolves #2011.
Hopefully improved understanding of what the changed variables are meant to represent.
Quite a bit of API changes with env variables being renamed all over.

[refactor] #2011: More descriptive config params

---

README.md
cli/README.md

- Added a link to the tutorial + info about it to the README
- Fixed a broken link to one of its pages

[documentation]: Add links to the tutorial

---

.github/CODEOWNERS

Updates codeowners
None
Adds @pesterev to codeowners
None

[documentation]: Updates codeowners

---

.github/CODEOWNERS

-  Add @Erigara to CODEOWNERS.
None.
More people to participate in code review.
None.

[documentation]: Add @Erigara to CODEOWNERS

---

CHANGELOG.rst

[documentation] #2344: Generate CHANGELOG for 2.0.0-pre-rc.5-lts

---

Cargo.toml

Adds a profile in the workspace Cargo.toml.
#2358

[fix] #2358: Add release with debug profile

---

client/tests/integration/permissions.rs
permissions_validators/src/lib.rs
permissions_validators/src/private_blockchain/register.rs
tools/kagami/src/main.rs

- Added wrapper for tokens in private_blockchain
- Added `kagami tokens` subcommand to list those
Consistency mainly.
None

[refactor]: add permission token wrappers for private_blockchain

---

.github/build-iroha1-fork.src.yml
.github/build-iroha1.src.yml
.github/workflows/build-iroha1-fork.yml
.github/workflows/build-iroha1.yml

Removed path-ignore for both iroha1 workflows, as some checks are obligatory in branch protection rules
Pull request https://github.com/hyperledger/iroha/pull/2372 was stuck

Fix status checks

---

permissions_validators/src/private_blockchain/mod.rs

Add tests to all remaining queries in the private blockchain module. Finally closes the #2053 issue.
Resolves #2053 
More tests, more coverage.
None.

[feature] #2053: Add tests to all remaining queries in private blockchain

---

.github/TESTS_ALLOWED_TO_FAIL
irohad/consensus/yac/transport/impl/consensus_service_impl.cpp
irohad/consensus/yac/transport/impl/consensus_service_impl.hpp
irohad/consensus/yac/transport/impl/network_impl.cpp
irohad/consensus/yac/transport/impl/network_impl.hpp
irohad/main/application.cpp
irohad/main/iroha_conf_loader.cpp
irohad/main/iroha_conf_loader.hpp
irohad/main/server_runner.cpp
irohad/network/channel_constants.hpp
irohad/network/impl/channel_factory.cpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_os_client_grpc.cpp
schema/yac.proto
test/module/irohad/consensus/yac/network_test.cpp
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp

1. No cache synchronization on round switch
2. Send/Recv packets size become 128 Mb.

Minor fixes

---

client/tests/integration/permissions.rs
core/src/smartcontracts/isi/mod.rs
data_model/src/account.rs
data_model/src/expression.rs
data_model/src/lib.rs
data_model/src/metadata.rs
data_model/src/permissions.rs
data_model/src/query.rs

- `PermissonToken` now derives `PartialOrd` and `Ord`. Manual implementation that was using only token name used to cause collision and is the reason of the bug
- `PartialOrd` and `Ord` were derived for many other structs that `PermissionToken` depends on
- Added test to check this bug
While fixing this bug I have also found another bug which this PR also fixes.
`PermissionToken` collision used to make it possible to i.e. have a permission to modify only one asset, but the same permission was enough to modify any other asset.
The test I introduced checks that too.
- Closes #2420 
- Permission collision bug fixed
- One more test
None

[fix] #2420: Fix "Permission already exists" bug

---

.github/workflows/iroha2-lts-pr.yml
.github/workflows/iroha2-lts.yml
.github/workflows/iroha2-pr.yml
CHANGELOG.rst
Dockerfile
actor/src/lib.rs
cli/src/lib.rs
client/tests/integration/permissions.rs
client/tests/integration/query_errors.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/expression.rs
data_model/src/lib.rs
data_model/src/metadata.rs
data_model/src/name.rs
data_model/src/permissions.rs
data_model/src/query.rs
deny.toml
permissions_validators/src/public_blockchain/mod.rs
scripts/tests/panic_on_invalid_genesis.sh
tools/parity_scale_decoder/src/main.rs

[release]: 2.0.0-pre-rc.6-lts

---

client/benches/tps/lib.rs
client/src/client.rs
core/src/smartcontracts/isi/permissions/has_token.rs
core/test_network/src/lib.rs

* Fixed bug then permissions granted with roles wasn't counted at all
See also #2487 -- dev version of this PR
* Closes #2477
* Opens #2482
* Fixed important bug
None

[fix] #2477: Fix bug when permissions from roles weren't counted (lts)

---

client/benches/tps/lib.rs
client/src/client.rs
client/tests/integration/roles.rs
core/src/smartcontracts/isi/permissions/has_token.rs
core/test_network/src/lib.rs

* Fixed bug then permissions granted with roles wasn't counted at all
* Fixed test for roles
* Added `Client::submit_transaction_blocking()`
See also #2489 -- lts version of this PR
* Closes #2477
* Opens #2482
* Fixed important bug
* Fixed test
* Added possibility to send transaction and wait for its commitment
None
```bash
cargo test --package iroha_client --test mod -- integration::roles::register_and_grant_role_for_metadata_access --exact --nocapture
```

[fix] #2477: Fix bug when permissions from roles weren't counted

---

client/tests/integration/triggers/data_trigger.rs
data_model/src/trigger/set.rs

I've added a test that reproduces [this bug](https://github.com/hyperledger/iroha/issues/2492) and also changes that fix it. Also [see](https://github.com/hyperledger/iroha/pull/2495) these changes to `iroha2-lts` branch.
Fixes #2492 
Fixes triggers execution
None

[fix] #2492: Fixes not all triggers being executed that match an event

---

client/tests/integration/queries/role.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/lib.rs
data_model/src/role.rs

Introduce `Registrable` trait to create unified interface for building objects.
Closes #2253.
Unified interface.
None.

[refactor] #2253: Add `Registrable` trait to `data_model`

---

client/tests/integration/triggers/data_trigger.rs
client/tests/integration/triggers/mod.rs
data_model/src/trigger/set.rs

It adds a test that reproduces [this bug](https://github.com/hyperledger/iroha/issues/2492) and also changes that fix it. Also [see](https://github.com/hyperledger/iroha/pull/2493) these changes to `iroha2-dev` branch.
Fixes #2493 
Adds changes from #2493 directly into the LTS branch.
None

[fix] #2492: Fixes not all triggers being executed that match an event (lts)

---

client/tests/integration/asset.rs
client/tests/integration/triggers/by_call_trigger.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/triggers.rs

Signed-off-by: Ales Tsurko <ales.tsurko@gmail.com>
Validation for trigger execution is added. Now triggers are allowed to be executed only by the register and technical accounts.
Closes #1891

[feature] #1891: Validate trigger execution

---

docs/source/requirements.txt

upgrade the packages in requirements.txt

Updates to requirements

---

actor/src/broker.rs
actor/src/lib.rs
client/tests/integration/restart_peer.rs
client/tests/integration/unstable_network.rs
core/src/lib.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
data_model/src/trigger/set.rs
p2p/tests/integration/p2p.rs
telemetry/src/ws.rs

Remove explicit `drop` call through the codebase. 
There were 2 use cases for `drop`:
- Ignore `Result` and pass `clippy` linting: replaced with `let _result = some_func_call(...)`. IMO ideally we should handle errors not ignoring them;
- Actually free some resource: replaced with proper scope.
Closes #2419.
No code smell constructions.
None.

[refactor] #2419: Remove explicit `drop`s

---

flakyness.org

[documentation]: Update test flakyness

---

ffi/derive/src/derive.rs
ffi/derive/src/export.rs
ffi/derive/src/impl_visitor.rs
ffi/derive/src/lib.rs
ffi/derive/tests/ui_pass/valid.rs

Make `ffi::derive::export::gen_ffi_fn` working with freestanding functions, so `ffi_export` macro could be used for such functions.
Closes #2490

[feature] #2490: Implement ffi_export for freestanding functions

---

permissions_validators/src/public_blockchain/key_value.rs

[documentation]: Fix incorrect doc comment in permission validators

---

cli/src/torii/routing.rs
core/src/block_sync.rs
core/src/kura.rs
core/src/lib.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
p2p/src/network.rs

[fix] #2560: Added back in block_sync and peer disconnecting.

---

cli/src/torii/routing.rs
cli/src/torii/tests.rs
cli/src/torii/utils.rs
client/src/client.rs
client/tests/integration/mod.rs
client/tests/integration/pagination.rs
client/tests/integration/sorting.rs
client/tests/integration/tx_history.rs
data_model/src/lib.rs
data_model/src/query.rs
data_model/src/sorting.rs

I've added sorting parameter into ISI queries.
The sorting will apply only to entities that have metadata.
[More about here](https://github.com/hyperledger/iroha/issues/2553).
Resolves #2553 
Allows to sort the result of queries
None.

[feature] #2553: Add sorting to queries

---

ffi/derive/src/convert.rs
ffi/derive/src/ffi_fn.rs
ffi/derive/src/impl_visitor.rs
ffi/derive/src/util.rs
ffi/derive/tests/ui_fail/generics_are_forbiden_in_ffi.rs
ffi/derive/tests/ui_fail/generics_are_forbiden_in_ffi.stderr
ffi/tests/generics.rs

Derive `TryFromReprC` and `IntoFfi` for generic opaque structs.
Resolves #2611.
Make possible to define ffi functions with generic struct parametrized with concrete type as argument or return value.
None. 
```
cargo test --package iroha_ffi --test generics -- return_generic --exact --nocapture
```

[feature] #2611: Derive `TryFromReprC` and `IntoFfi` for generic opaque structs

---

config/base/derive/src/lib.rs
config/base/derive/src/proxy.rs
config/base/derive/src/view.rs
config/base/src/lib.rs

-------
Proxy structs in the `Combine` derive macro now also derive `LoadFromEnv`, as well
as have their `Builder` implementation fixed.
Resolves #2586 and #2616.
Getting closer to the aims of the corresponding epic.
Implementations still untested. Though they typecheck, thorough foolproofing
is a matter of future work.

[feature] #2586, #2616: `Builder` and `LoadFromEnv` for proxy structs

---

tools/kagami/src/main.rs

Display error if user try to provide seed shorter than 32 bytes for `secp256k1`.
Closes #2554. 
Clear message about what going wrong.
None.

[fix] #2554: Raise error if `secp256k1` seed shorter than 32 bytes

---

tools/kagami/src/main.rs

Display error if user try to provide seed shorter than 32 bytes for `secp256k1`.
Closes #2554. 
Clear message about what going wrong.
None.

[fix] #2554: Raise error if `secp256k1` seed shorter than 32 bytes (lts)

---

cli/src/lib.rs
client/benches/torii.rs
client/examples/million_accounts_genesis.rs
core/src/genesis.rs
core/test_network/src/lib.rs
crypto/src/merkle.rs
data_model/src/events/pipeline.rs
data_model/tests/data_model.rs

Signed-off-by: Jonathan Plasse <13716151+JonathanPlasse@users.noreply.github.com>
Replace `&Option<T>` by `Option<&T>` as described in  #2667

[fix] #2667: Refactor &Option<T> to Option<&T>

---

config/base/derive/src/documented.rs
config/base/derive/src/lib.rs
config/base/derive/src/proxy.rs
config/base/derive/src/utils.rs
config/base/derive/src/view.rs
config/base/src/lib.rs
config/base/tests/simple.rs
config/src/block_sync.rs
config/src/client.rs
config/src/genesis.rs
config/src/iroha.rs
config/src/kura.rs
config/src/logger.rs
config/src/network.rs
config/src/queue.rs
config/src/sumeragi.rs
config/src/telemetry.rs
config/src/torii.rs
config/src/wasm.rs
config/src/wsv.rs

* `iroha_config_base::proxy::Combine` trait properly implemented in crate's derive macros.
* All proxy-related functionality that previously was in `Combine` trait derive split into 4 separate macros for each respective trait derive and the `..Proxy` struct itself.
Resolves #2626, #2588.
Work towards the config epic.
None yet. The real tradeoffs can only be seen at the end of the epic, it seems.

[feature] #2626, #2588: `Combine` derive, split `config` macros

---

core/src/kura.rs

Stop a kura panic from aborting the tests.
Partial fix for #2678

[fix] #2678: Fix tests abort on Kura force shutdown.

---

cli/src/lib.rs
core/src/kura.rs
core/src/lib.rs
core/test_network/src/lib.rs

- Add `ThreadHandler` struct to shutdown iroha submodules threads on `Iroha` shutdown (RAII).
- Rewrite `Kura` block writing loop: on shutdown `Kura` writes remaining blocks and then exits.
- Add temporary directory to `Peer` struct to delete directory after `Iroha` (and thus `Kura` thread).  
Closes #2650.
Unified mechanism for stopping iroha submodules threads.
None.
Possibly better name for `ThreadHandler` :)

[refactor] #2650: Add `ThreadHandler` to shutdown iroha submodules

---

.github/workflows/iroha2-dev-pr-label.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-ui.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml

- Add a workflow that automatically label `api-changes` and `config-changes`
- None
- Automation
- None

[ci]: Auto-label `api-changes` and `config-changes`

---

client/tests/integration/triggers/time_trigger.rs
config/src/client.rs
config/src/sumeragi.rs
core/src/block.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/triggers.rs
core/src/smartcontracts/isi/world.rs

[fix] #2678: Fix tests on staging branch.

---

telemetry/src/metrics.rs

[fix] #2716: Make Duration in Uptime public

---

schema/src/lib.rs

[documentation]: Fix doc comment in schema/src

---

Cargo.lock
core/Cargo.toml
core/src/kura.rs

- Replaced `byteorder` functions with native.
Closes #2649.
Reduced number of dependencies.
None.

[refactor] #2649: Remove `byteorder` crate from `Kura`

---

.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

Fix publishing

---

Cargo.lock
cli/src/torii/routing.rs
client/Cargo.toml
client/src/client.rs

- Add TLS support for websockets
- Fix closing WebSocket bug
See also #2728   -- lts version of this PR
* Closes #2703 
* Opens #2725
* Opens #2726 
* Opens #2727
Two bugs fixed and no more annoying `ERROR` log in Iroha saying about wrong web-socket closing
I had to remove timeout in client when listening to events. To bring it back properly we need more work to be done

[fix] #2703: Fix orillion dev env bugs (dev)

---

Cargo.lock
cli/src/torii/routing.rs
client/Cargo.toml
client/src/client.rs

See details in #2724  -- dev-version of this commit
* Closes #2703
Tested manually. Using `Docker` to test locally and *Orillion dev environment* to test on remotely

[fix] #2703: Fix orillion dev env bugs (lts)

---

docs/source/iroha_2_whitepaper.md

[fix] #2638: Update white paper.

---

Cargo.lock
cli/Cargo.toml
cli/build.rs
cli/src/main.rs
client_cli/Cargo.toml
client_cli/build.rs
client_cli/src/main.rs

Add `build.rs` to extract git hash of build.
Closes #2502.
Easier to debug.
None.
```
cargo run --bin iroha_client_cli  -- --version
cargo run --bin iroha -- --version
```

[feature] #2502: Store GIT hash of build

---

cli/src/torii/mod.rs
cli/src/torii/routing.rs
client/src/client.rs
client/tests/integration/events/pipeline.rs
core/benches/validation.rs
core/src/block.rs
core/src/queue.rs
core/src/smartcontracts/isi/mod.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/message.rs
core/src/sumeragi/network_topology.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/block_value.rs
data_model/src/permission/validator.rs
data_model/src/transaction.rs
docs/source/references/api_spec.md
docs/source/references/schema.json
schema/gen/src/lib.rs
tools/parity_scale_decoder/src/generate_map.rs

- Renamed `Transaction/VersionedTransaction` to `SignedTransaction/VersionedTransaction`;
- Add `Transaction`: which represent transaction which do not receive sign yet; 
- Add `SignableTransaction` trait with method `sign` to create generic function accepting ether `Transaction` or `SignedTransaction` (multisig).
**For reviewers**: most important changes in `data_model/src/transaction.rs, client/src/client.rs`.
Closes #2478.
Allow to identify buggy behavior on type level.  
None.

[refactor] #2478: Add `SignedTransaction`

---

.github/build-iroha1-fork.src.yml
.github/build-iroha1.src.yml
.github/comment_body
.github/workflows/build-iroha1-fork.yml
.github/workflows/build-iroha1.yml

Feature/dops 1957/reduce ci runs

---

.github/build-iroha1-fork.src.yml
.github/workflows/build-iroha1-fork.yml

Update workflows, reduce CI runs

---

client/src/client.rs

* Reprhased two error messages
* Closes #2689
* More helpful error message for the end users
None

[feature] #2698: Fix unclear error message in `iroha_client`

---

tools/kura_inspector/src/main.rs

All of Victor's suggestions have been implemented.

[fix]: #2571: Better Kura Inspector UX.

---

tools/kagami/README.md
tools/kagami/src/main.rs

Add option to `kagami` to generate synthetic genesis with specified number of domains, accounts, assets.  
Closes #2765.
Possible to generate large genesis for load testing and blockchain explorer.
None.
```bash
cargo run --bin kagami genesis --synthetic --domains 1 --accounts-per-domain 1 --assets-per-domain 1
```
Could be separate script.

[feature] #2765: Generate synthetic genesis in `kagami`

---

.github/workflows/iroha2-dev-pr.yml
Cargo.lock
config/src/iroha.rs
configs/client_cli/config.json
scripts/check.sh
tools/kagami/Cargo.toml
tools/kagami/src/main.rs

* Added kagami sub-command to generate valid client config
* Added ci check
* New config was tested with `iroha_client_cli` and it works. Current config on `iroha2-dev` is not working
* Closes #2778 
* CI check for corrent client config
* Automatic way to generate valid config
None
```bash
scripts/check.sh client
```

[ci] #2778: Client config check

---

.github/ISSUE_TEMPLATE/stable-bug.yml

Updated bug report
The sorting of items has been changed in a logical order.
Other trivial improves...
Resolves #2811 
For simplicity and conciseness when creating defects.
None

Brand new bug report template

---

core/src/genesis.rs

Put warning in logs if genesis file is larger or equal 1Gb.
Partially closes #2548. 
Notify uses.
None.
Run iroha with genesis above 1Gb.
I take simplest possible approach, other designs could be considered.

[fix] #2548: Warn on large genesis file

---

client/examples/million_accounts_genesis.rs
config/base/tests/simple.rs
configs/peer/genesis.json
core/src/genesis.rs
core/src/smartcontracts/isi/permissions/checks.rs
lints.toml
tools/kagami/src/main.rs

Add extra examples which provide more context for SDK developers in case `genesis.json` syntax changes once again. 
Better examples
None
``` cargo run --bin kagami -- genesis ```

[refactor]: Add extra examples to `genesis.json`

---

config/src/kura.rs
configs/peer/config.json
core/src/block.rs
core/src/kura.rs
core/src/sumeragi/network_topology.rs
core/src/tx.rs
docs/source/references/config.md

[fix] #2379: Ability to dump new kura blocks to blocks.txt.

---

Cargo.lock
client/Cargo.toml
client/src/client.rs
client/src/http_default.rs
client/tests/integration/events/pipeline.rs
config/iroha_test_config.json

Closes #2725
- Timeout working again;
- No deadlock. 
Some transactions can fail.

[feature] #2725: Reintroduce timeout into `submit_transaction_blocking`

---

client/examples/tutorial.rs

Signed-off-by: 6r1d <vic.6r1d@gmail.com>
Adds example that mirrors tutorial examples, so that changes in the API can be propagated by directly taking them from GitHub. 
Addresses #2544 
Direct connection to tutorial
More code to test
```bash
cargo run --example tutorial
```

[documentation]: Add tutorial samples as a separate example file

---

scripts/check.sh

Remove temporary file usage.
Closes #2865
No tmp file.
None.

[ci] #2865: Remove usage of tmp file from `scripts/check.sh`

---

client/tests/integration/events/data.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/world.rs
core/src/wsv.rs
data_model/src/events/data/events.rs

- Add mechanism to return multiple events from `modify_*` functions;
- Fixed error when revoked role does not exist;
- Revoke/Grant role also produce `PermissionAdded/Removed` events.
Closes #2280.
More detailed events.
None.

[feature] #2280: Produce permission events when role is granted/revoked

---

client_cli/src/main.rs

Submit transaction and wait for result.
Closes #2804, #2863.
Less confusion.
None.
Try to reproduce cases in provided issues.
Leave as is.

[fix] #2804, #2863: `iroha_client_cli` submit transaction blocking

---

core/src/block_sync.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
p2p/src/network.rs

[fix] #2870: Reduce amount of ConnectPeer messages sent to p2p (lts)

---

cli/src/torii/routing.rs

- Fix block streaming.
Closes #2880.
Bug fixed.
None.

[fix] #2880: Fix block streaming (lts)

---

cli/src/event.rs
cli/src/torii/mod.rs
cli/src/torii/routing.rs
scripts/tests/panic_on_invalid_genesis.sh

Close websocket connection properly.
Closes #2880. 
Properly closed connection. 
None.

[fix] #2880: Close websocket connection properly

---

shared_model/validators/field_validator.cpp
shared_model/validators/field_validator.hpp

In my previous PR @iceseer left comment: https://github.com/hyperledger/iroha/pull/1776#issuecomment-1283796964
that is why I corrected the comment.
The only changes is type change + what it requires. Another small change is removing unused include.
More modern C++ code
The same code as used to test here: https://github.com/hyperledger/iroha/pull/1776

Follow-up: #1776: Configurable max past created hours - changed type

---

cli/src/event.rs
cli/src/torii/mod.rs
cli/src/torii/routing.rs
client/src/client.rs
client_cli/src/main.rs
scripts/tests/panic_on_invalid_genesis.sh

- Add support for block streaming into `iroha_client` and `iroha_client_cli`;
- Fix iroha block streaming.
Closes #2880, #2889.
Fixed bug, block streaming support.
None.
```
cargo run --bin iroha_client_cli blocks 1
```

[fix] #2880: Fix block streaming

---

.github/build-iroha1.src.yml
.github/workflows/build-iroha1.yml

Remove cache from main workflow

---

permissions_validators/src/public_blockchain/mint.rs

Skip validation if `AssetDefinitionId` doesn't exist.
Closes #2923.
Proper error message.
No.

[fix] #2923: Return `FindError` when `AssetDefinition` does not exist

---

client_cli/README.md
client_cli/src/main.rs
data_model/src/transaction.rs

Merge changes from #2898 and #2918 into LTS.
Close #2899 and #2508
Add a couple of subcommands into the LTS branch.
None

[feature] #2899, #2508: Add multi-instructions and wasm subcommands into 'client_cli'

---

ffi/derive/src/convert.rs
ffi/derive/tests/ui_fail/fallible_transmute_mut_ref.stderr
ffi/derive/tests/ui_fail/nested_owned_structure.stderr
ffi/src/ir.rs
ffi/src/lib.rs
ffi/src/option.rs
ffi/src/primitives.rs
ffi/src/repr_c.rs
ffi/src/std_impls.rs
ffi/tests/ffi_export.rs
primitives/src/conststr.rs

* simplified conversion process
* less code
* easier to understand

[refactor]: move parametrization into traits and remove FFI IR types

---

core/src/smartcontracts/isi/expression.rs
core/src/smartcontracts/isi/mod.rs
data_model/src/expression.rs
docs/source/references/schema.json
primitives/src/fixed.rs
tools/parity_scale_decoder/src/generate_map.rs

Extend arithmetic operations to support `NumericValue`  instead of only `u32`.
Closes #2905.
Arithmetic instructions support more types.
None.

[feature] #2905: Extend arithmetic operations to support `NumericValue` 

---

primitives/src/fixed.rs

Check that `Fixed` is not negative during decoding/deserialization. 
Closes #2850.
Corrent decoding/deserialization behavior.
None.
```
cargo test --package iroha_primitives --lib -- fixed::tests --nocapture
```

[fix] #2850: Fix deserialization/decoding of `Fixed`

---

Cargo.lock
core/Cargo.toml
core/src/kura.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs

[fix] #2858: Introduce parking_lot::Mutex instead of std.

---

cli/src/event.rs
cli/src/lib.rs
client/tests/integration/unstable_network.rs
core/src/block_sync.rs
core/src/p2p.rs

Hotfix for performance regression. 
None
Better `p2p` performance
None

[fix] #0000: Hotfix for performance regression

---

MAINTAINERS.md

This PR contains a new maintainer list, feel free to point out who should be added or removed.

[documentation] Fix #2957, update the MAINTAINERS.md file

---

README.md
wasm/README.md

Based on https://github.com/hyperledger/iroha-2-docs/pull/231

[documentation]: Update links to documentation

---

data_model/src/lib.rs

[fix] #2980: fix block value ffi type backport to lts

---

data_model/src/lib.rs

[fix] #2980: fix block value ffi type

---

core/benches/kura.rs
core/src/block.rs
core/src/block_sync.rs
core/src/lib.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/events/mod.rs
data_model/src/transaction.rs
primitives/src/small.rs

- Add `CommittedCandidateBlock` block state used for transferring between peers, requires hash revalidation to obtain `ComittedBlock`;
- Change `BlockComitted` message to send only hash and signatures;
Closes #2974, #2955.
More optimized communication.
Requires peer to preserve latest created block.

[refactor] #2974: Prevent block spoofing without full revalidation

---

client/tests/integration/multisignature_transaction.rs
core/src/smartcontracts/isi/expression.rs
core/src/tx.rs
data_model/src/account.rs
data_model/src/expression.rs
data_model/src/isi.rs
docs/source/references/schema.json
tools/parity_scale_decoder/src/generate_map.rs

[fix] #1967: Replace ValueName with Name

---

config/src/client.rs
data_model/src/account.rs
data_model/tests/data_model.rs

Signed-off-by: Wenfeng Sui suiwenfeng@qq.com

[refactor] #2675: Validate item names/ids without allocating Vec

---

cli/src/stream.rs
cli/src/torii/utils.rs
client/src/client.rs
core/src/kura.rs
core/src/smartcontracts/isi/expression.rs
core/src/smartcontracts/wasm.rs
crypto/src/signature.rs
data_model/src/domain.rs
data_model/src/name.rs
p2p/src/handshake.rs
p2p/src/peer.rs
primitives/src/fixed.rs
tools/kura_inspector/src/main.rs
tools/parity_scale_decoder/src/main.rs
version/derive/src/lib.rs
version/derive/tests/scale.rs
version/src/lib.rs
wasm/src/lib.rs

[fix] #2384: Replace decode with decode_all.

---

core/src/block.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs

[fix] #2998: Delete unused Chain code.

---

core/benches/sumeragi.rs
core/benches/validation.rs
core/src/block.rs
core/src/block_sync.rs
core/src/kura.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
core/src/sumeragi/view_change.rs
core/src/wsv.rs
crypto/src/hash.rs
data_model/src/block_value.rs
docs/source/references/schema.json
schema/src/lib.rs
tools/parity_scale_decoder/src/generate_map.rs

In order to achieve niche value optimization least significant bit of hash set to be always 1.  
Closes #3008.
Don't use all zero hash as null value, instead use `Option<Hash>` without loses in size. 
- Unsafe code
- Least significant bit of hash is always 1, which can cause compatibility issues with `blake2b` hashing algorithm. 
- Can't implement `Display` for `Option<Hash>`

[refactor] #3008: Add niche value into `Hash`

---

core/src/sumeragi/main_loop.rs

Remove `Option` in `transaction_cache`.
Closes #3022.
- Do not repeat code
- More convenient interface to work with 
None.

[refactor] #3022: Remove `Option` in `transaction_cache`

---

permissions_validators/src/public_blockchain/mod.rs

Burn validators weren't properly combined.
Closes #3013
None

[fix] #3013: properly chain burn validators

---

cli/src/lib.rs
core/src/block.rs
core/src/tx.rs

This PR fixes the incorrect block validation - applies WSV cloning on every block, not on every transaction.
Closes #2506
It fixes crashes on the Sumeragi main loop due to a lack of correct validation
None

[fix] #2506: Fix the block validation

---

core/src/block.rs

This test reproduces the root error of #2506. A detailed explanation of the bug is [here](https://github.com/hyperledger/iroha/issues/2506#issuecomment-1316913752).
Closes #2506
Add more tests on the block validation.
None

[test] #2506: Add more tests on block validation

---

cli/src/torii/routing.rs
cli/src/torii/utils.rs
version/src/lib.rs

Fix unhandled rejection inside `torii`.
Closes #2803.
Correct response from the iroha.
None.

[fix] #2803: Return correct status code for signature errors

---

docs/source/faq/index.rst
docs/source/index.rst

[documentation] #2579: mention Iroha 2 in Iroha docs

---

docs/source/faq/index.rst

Fix: typos
Signed-off-by: omahs <73983677+omahs@users.noreply.github.com>

doc: correct typos in `readme.md`

---

docs/source/references/api_spec.md

Currently, there is no mention of the sorting parameter in the API spec, so this PR adds it.
None
Update API spec
None

[documentation]: Add about `sort_by_metadata_key` into API spec

---

config/src/logger.rs

Fix deserialization.
Closes #2894.
`LOG_FILE_PATH` works as expected.
None.

[fix] #2894: Fix `LOG_FILE_PATH` env variable deserialization

---

configs/peer/genesis.json
data_model/src/isi.rs
data_model/src/lib.rs
data_model/src/role.rs
tools/kagami/src/main.rs
tools/parity_scale_decoder/samples/trigger.json

Omit `Identifiable`, `Id`, `object(_id)` fields in json deserialization.
Closes #2922 
Genesis take smaller amount of space, shorter to write.
None.
Field `Identifiable` is omitted:
```diff
{
"Register": {
-            "Identifiable": {
"NewDomain": {
"id": "wonderland",
"logo": null,
"metadata": {
"key": {
"String": "value"
}
}
-               }
}
}
```
```diff
{
"Register": {
-            "Identifiable": {
"NewAccount": {
"id": "alice@wonderland",
"signatories": [
"ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
],
"metadata": {
"key": {
"String": "value"
}
}
-               }
}
}
```
Fields `Id`, `object` and `object_id` are omitted:
```diff
{
"Mint": {
-            "object": {
"U32": 13
-            },
"destination_id": {
-              "Id": {
"AssetId": …
```

[feature] #2922: Simplify JSON deserialization

---

client/examples/tutorial.rs

Changes in tutorial: https://github.com/hyperledger/iroha-2-docs/pull/246
This way the code snippets are pulled directly from this repo to the tutorial

[documentation]: Update tutorial snippets

---

client_cli/README.md
client_cli/src/main.rs

[documentation]: Update Iroha Client CLI readme

---

client/tests/integration/events/data.rs
core/src/smartcontracts/isi/domain.rs
core/src/smartcontracts/isi/world.rs
core/src/wsv.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/events/data/events.rs
data_model/src/events/data/filters.rs
docs/source/references/schema.json

`Created` events now contain builder object which provide all necessary data.
Closes #3082 
Ease of use for orillion.
Events became heavier.

[feature] #3082: Provide full data in `Created` event

---

client/benches/tps/utils.rs
core/src/smartcontracts/isi/permissions/combinators.rs

Problem was that transaction submitter accidentally produced duplicate transactions and it's thread paniced without blockchain reaching enough blocks.
- Fix verification for `If` instruction;
- Add nonce to tps benchmark transactions;
- Log and ignore benchmark transaction submitter;
- Transfer assets if have at least 2;
- Maximum TTL for transaction on client side;
Closes #3056.
Stable benchmark.
None.
```bash
cargo bench --bench tps-dev
```

[fix] #3056: Fix `tps-dev` benchmark hanging

---

cli/src/torii/routing.rs
core/src/sumeragi/mod.rs
telemetry/src/metrics.rs

Closes #3119.
Fulfill DevOps request, provide more data to analyze iroha behavior. 
None.
Start iroha and send `/metrics` request.

[feature] #3119: Add `dropped_messages` metric

---

configs/peer/genesis.json
data_model/src/lib.rs
data_model/src/metadata.rs
data_model/src/transaction.rs
permissions_validators/src/public_blockchain/mod.rs

- Add test to check de/serialization consistency of `Parameter`.
- Fix `Parameter` de/serialization.
- Add `CanChangeConfigParameters` into default permission tokens.
Closes #3129.
No bug.
None.
```
cargo test --package iroha_data_model --lib -- tests::test_parameter_serialize_deserialize_consistent --exact --nocapture
```

[fix] #3129: Fix `Parameter` de/serialization

---

CHANGELOG.rst

[documentation]: Generate CHANGELOG for pre-rc.13

---

crypto/src/hash.rs
docs/source/references/schema.json
tools/parity_scale_decoder/src/generate_map.rs

Manually implement `IntoSchema` for `Hash`, to correctly serialize data on SDK side.
Closes #3141.
Work on SDK side.
None.

[fix] #3141: Manually implement `IntoSchema` for `Hash`

---

Cargo.lock
Cargo.toml
config/base/derive/Cargo.toml
config/base/derive/src/utils.rs
data_model/derive/Cargo.toml
data_model/derive/src/has_origin.rs
data_model/derive/src/lib.rs
data_model/src/events/data/events.rs
macro/utils/Cargo.toml
macro/utils/src/lib.rs

- Introduce `iroha_macro_utils` for macro building utilities reused through other crates;
- Add derive proc macro for `HasOrigin`.
Closes #2943.
DRY.
None.
Run macro doc tests.
```
cargo test --doc --package iroha_data_model_derive -- has_origin_derive --nocapture 
```

[refactor] #2943: Derive `HasOrigin`

---

cli/src/lib.rs
client/tests/integration/unstable_network.rs
core/test_network/src/lib.rs

[fix] #3113: Revise unstable network tests.

---

cli/src/lib.rs
core/test_network/src/lib.rs

[fix]: Add missing `#[cfg(debug_assertions)]`

---

config/iroha_test_config.json
config/src/iroha.rs
configs/client_cli/config.json
configs/peer/genesis.json
core/src/sumeragi/main_loop.rs
crypto/src/lib.rs
docs/source/references/schema.json
tools/parity_scale_decoder/src/generate_map.rs

Signed-off-by: Retssaze <Retssaze@GMail.Com>

 [refactor] #2123: use Algorithm for storing digest function

---

Cargo.lock
config/iroha_test_config.json
configs/client_cli/config.json
configs/peer/genesis.json
core/src/sumeragi/main_loop.rs
crypto/Cargo.toml
crypto/src/lib.rs

Return `PublicKey` to de/serialization from multihash string.
Closes #2123.
Reverse breaking change.
None.

[fix] #2123: Return to `PublicKey` de/serialization from multihash

---

wasm/Cargo.toml
wasm/src/lib.rs

Since [Rust 1.68](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#default-alloc-error-handler) default alloc error handler is stabilized

[refactor]: Use stable default allocator handler

---

.github/PULL_REQUEST_TEMPLATE.md

We've had an old issue template for a while now. About time we modernise it a little.

[CI]: New PR template

---

Cargo.lock
cli/Cargo.toml
client/Cargo.toml
client_cli/Cargo.toml
config/Cargo.toml
config/base/Cargo.toml
core/Cargo.toml
crypto/Cargo.toml
data_model/Cargo.toml
data_model/derive/Cargo.toml
data_model/src/events/data/filters.rs
data_model/src/expression.rs
data_model/src/lib.rs
futures/Cargo.toml
logger/Cargo.toml
p2p/Cargo.toml
permissions_validators/Cargo.toml
primitives/Cargo.toml
schema/Cargo.toml
telemetry/Cargo.toml
tools/kagami/Cargo.toml
tools/parity_scale_decoder/Cargo.toml
version/Cargo.toml
version/derive/Cargo.toml

Reverts hyperledger/iroha#3338

Revert "BACKPORT [fix] #3330: Fix `untagged` enum de-serialization with `u128` leaves"

---

.github/CODEOWNERS

[chore]: add @0x009922 to the CODEOWNERS

---

core/src/sumeragi/main_loop.rs

Add `update_topology` and `update_state` function to encapsulate common functionality. 
Resolves #3254.
DRY.
None.
I have tried const generic approach but it doesn't look very nice.

[refactor] #3254: Refactor `commit_block()` and `replace_top_block()`

---

core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/block_sync.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs

[fix] #3247: Removed fault injection from sumeragi.

---

data_model/Cargo.toml
data_model/src/account.rs
data_model/src/domain.rs
data_model/src/events/data/mod.rs
data_model/src/expression.rs
data_model/src/lib.rs

Fixed some problems which prevent build on nightly toolchain.
Note: modern clippy setup with `nightly-2022-12-22` fails for me, but these are errors in old lts code. My goal here was to just make it compilable.
* Closes #3402  
LTS can be build with nightly toolchain now

[fix] #3402: Fix nightly build

---

client/tests/integration/burn_public_keys.rs
core/src/queue.rs
core/src/sumeragi/main_loop.rs
primitives/src/riffle_iter.rs

- Fixed this flaky test
- Added some logs usefull for debugging
- Closes #3408  
- This test isn't flaky anymore
- More usefull logs

[fix] #3408: Fix `public_keys_cannot_be_burned_to_nothing` test

---

Cargo.lock
cli/Cargo.toml
cli/build.rs
client/Cargo.toml
client/build.rs
client_cli/Cargo.toml
client_cli/build.rs
flake.lock
flake.nix
telemetry/Cargo.toml
telemetry/build.rs
telemetry/src/ws.rs

Add a Nix flake with basic `packages`, `apps` and `devShells` as a basis for all future Nix-related endeavors. 
Closes #3415 
One-click runnable for people with Nix installed. Enables future Nix-based improvements as outlined in #3417

[feature] #3415: Nix flake

---

core/src/block.rs
core/src/block_sync.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
crypto/src/signature.rs
data_model/src/block.rs
data_model/src/peer.rs

Right now the signatures are not included in the block hash because the consensus needs to be able to refer to the block during the signing process. This is a security problem since the validity of the blockchain is rooted in the signatures and as we move closer to the whitepaper they also affect how the topology evolves. Therefore the hash should be split into a consensus used hash that refers to the contents of the block without signatures and the default hash should include signatures.

[fix] #3249: Split block hashes into partial and complete versions.

---

Cargo.lock
cli/src/torii/routing.rs
core/Cargo.toml
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/gossiper.rs
core/src/queue.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
data_model/Cargo.toml
data_model/src/transaction.rs
genesis/src/lib.rs

* Introduce sealed traits for block revalidation and accepting transactions
* Make wrappers around those two functions for public use
Closes #3363 
More idiomatic and self-descriptive usage.

[refactor] #3363: Genesis API

---

config/src/torii.rs
primitives/src/addr.rs

Closes #3496 
Iroha can be started.

[fix] #3496: Fix `SocketAddr` field parsing

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/network_topology.rs
primitives/src/addr.rs

[refactor]: Refactor and add tests for topology

---

core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs

- Remove redundant fields from sumeragi;
- Fix soft-fork detection and signatrue validation;
- Add tests.
Closes #3498 
Topology work correctly + new tests.

[fix] #3498: Fix soft-fork detection

---

CONTRIBUTING.rst

Spelling Mistake

---

docs/source/getting_started/index.rst

Changed the URL to install docker under prerequisites in the quick start guide section

[documentation] Changed the URL to install docker under prerequisites in the quick start guide section

---

core/src/sumeragi/main_loop.rs

Closes https://github.com/hyperledger/iroha/issues/3075

[fix] #3075: Panic on invalid tx in genesis.

---

configs/peer/genesis.json
docs/source/references/schema.json
genesis/src/lib.rs
tools/kagami/src/main.rs

[fix] #3552: Fix validator path schema repr

---

client/tests/integration/triggers/time_trigger.rs

Change order in which we submit first transaction and start listening for events.
Closes #3546 
Test doesn't get stuck.

[fix] #3546: Fix time trigger tests get stuck

---

config/base/tests/simple.rs

Update failing `configuration_proxy_from_env_returns_err_on_parsing_error` test.
_No linked issue_

[fix] #0000:  configuration macro test

---

.github/workflows/iroha2-release.yml
configs/client/lts/config.json
configs/client/stable/config.json
scripts/update_configs.sh

[fix] #3592: fix config files updating on release

---

client/benches/tps/utils.rs
core/src/queue.rs
core/src/smartcontracts/isi/block.rs
core/src/smartcontracts/isi/query.rs
core/src/wsv.rs

Store block height to which transaction belong.
Closes #3063 
Don't need to scan whole blockchain for single transaction.

[refactor] #3063: Map transaction hash to block height in wsv

---

client_cli/src/main.rs

Pass closure inside subcomands to do printing. 
Closes #3596 
Works correctly.

[fix] #3596: `iroha_client_cli` show blocks/events

---

core/src/sumeragi/main_loop.rs

Don't involve observing peers in consensus when view_change_index == 0.
#3246
I have verified that this PR has the intended effect by observing the output of the unstable network tests.

[fix] #3246: Don't involve observing peer without fault.

---

core/src/block.rs
core/src/sumeragi/main_loop.rs

Replace eyre error messages with structured errors.
Partially closes #3353 
Less vague errors.

[refactor] #3353: Remove eyre from block.rs

---

core/src/sumeragi/main_loop.rs

Simple fix for attached issue but needs to be confirmed by QA.
Closes #3195

[fix] #3195: Also panic when receiving rejected genesis.

---

version/src/lib.rs

Turns out this issue is kind of already fixed. I've just simply corrected the error message to exactly match the *expected* section of the issue.

[fix] #3042: Fix bad request message.

---

core/src/smartcontracts/isi/asset.rs

[fix] #3543: Increment quantity change, not total

---

cli/src/main.rs
core/src/sumeragi/main_loop.rs

[refactor]: reject incorrect config topology early

---

Cargo.lock
ffi/derive/Cargo.toml
ffi/derive/src/util.rs
version/derive/Cargo.toml
version/derive/src/lib.rs

[refactor] #3672: Replace HashMap with FxHashMap in derive macros

---

MAINTAINERS.md

Requested in https://github.com/hyperledger/governance/issues/118

[chore]: #3679 add @DCNick3 to the MAINTAINERS.md

---

.github/dependabot.yml

[ci]: update dependabot

---

.github/dependabot.yml

mentioned [here](https://github.com/hyperledger/iroha/pull/3676#discussion_r1254235642)

[ci]: add non-workspace projects to dependabot

---

core/src/validator.rs

This improves the error message experienced in https://github.com/hyperledger/iroha/pull/3686#issuecomment-1625195109

[refactor]: Include the actual error message in InternalError

---

.github/workflows/iroha2-ci-image.yml
.github/workflows/iroha2-dev-nightly.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-ui.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release-pr.yml
.github/workflows/iroha2-release.yml
Dockerfile
Dockerfile.build
wasm_builder/src/lib.rs

Caution, make sure all CI checks pass before merging.

[bump]: Rust toolchain and CI container to `nightly-2023-06-25`

---

cli/src/torii/routing.rs

Fixed the bug where `GET /configuration` was working, but `POST ..` wasn't.
Closes #3445. 
All working as expected. Too bad there's no integration test to catch this regression?

[fix] #3445: make `POST configuration` work again

---

iroha-lib/README.md
iroha-lib/model/Query.cpp
iroha-lib/model/Query.hpp
iroha-lib/model/generators/QueryGenerator.cpp
iroha-lib/model/generators/QueryGenerator.hpp

Add `GetPeers`  Query to **iroha_lib_model**

Add GetPeers Query to iroha-lib

---

tools/kagami/src/crypto.rs

A small Kagami help update
Closes #3802

[documentation] #3802: Unicode "kagami crypto" seed

---

cli/src/torii/mod.rs
cli/src/torii/routing.rs

Fix shutdown of iroha.
Closes #3805 
Iroha shutdown correctly.
Check original issues for steps to reproduce.

[fix] #3805: Fix iroha graceful shutdown 

---

.github/workflows/iroha2-release-pr.yml
configs/peer/stable/config.json
configs/peer/stable/genesis.json
scripts/test_env.sh
scripts/tests/genesis.sh
scripts/tests/panic_on_invalid_genesis.sh
scripts/tests/register_mint_quantity.sh

[fix]: Update stable configs

---

core/benches/kura.rs
core/src/kura.rs
tools/kura_inspector/src/main.rs

[fix] #3059: Simplify kura lock file code

---

MAINTAINERS.md

Signed-off-by: 6r1d <vic.6r1d@gmail.com>
Closes #3836
Requested by TOC

#3836: Add Bogdan Yamkovoy to MAINTAINERS.md file

---

docs/source/lts_selection.org
docs/source/release_procedure.org

Added two documents describing the release process and cadence recommendations.

[documentation]: Formalise the release process

---

wasm/validator/src/permission.rs

[fix] #3843: Fix genesis validation

---

wasm/validator/src/permission.rs

BACKPORT [fix] #3843: Treat genesis account as owner during validation

---

client/tests/integration/triggers/by_call_trigger.rs
data_model/src/query/mod.rs

- `QueryExecutionFail::Find` variant is now transparent
- `FindError` derives `displaydoc::Display` and not `derive_more::Display`
- Closes #3337 
Better error message:
```
Error:
0: Failed to mint asset of type `NumericValue::U32`
1: Failed to submit transaction V1(SignedTransaction { signatures: iroha_crypto::signature::SignaturesOf<iroha_data_model::transaction::model::TransactionPayload> { signatures: {iroha_crypto::signature::SignatureOf<iroha_data_model::transaction::model::TransactionPayload>({ pub_key: ed01207233BFC89DCBD68C19FDE6CE6158225298EC1131B6A130D1AEB454C1AB5183C0, payload: 95E2E087054FDBC56BEC183723C23E6BCD114A90B240DA7C255A508C7C5463E4F2153BA93499F3FFAF37C7A254A39107E3EECF5A6F0FC31FE0D2B544644A2B0B })} }, payload: TransactionPayload { creation_time_ms: 1693853747365, …
```

[fix] #3337: Better error message for query find error

---

client/src/client.rs

[refactor] #3875: Fix authentication/authorization docstring

---

data_model/src/isi.rs

[refactor]: Replace Registered with Identifiable in ISI bounds

---

core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
data_model/src/block.rs
docs/source/references/schema.json

[refactor] #3895: move `commit_topology` into block payload

---

core/src/tx.rs
data_model/src/evaluate.rs

let's not pollute public API with internal stuff

[refactor]: move expression len out of public API into core

---

scripts/update_configs.sh

[fix] #0000: Fix executor downloading in update_configs.sh

---

Cargo.lock
Cargo.toml
core/Cargo.toml
data_model/Cargo.toml
p2p/Cargo.toml
tools/swarm/Cargo.toml

[refactor]: remove unused dependencies

---

CHANGELOG.rst
Cargo.toml
client/tests/integration/smartcontracts/Cargo.toml
default_executor/Cargo.toml
wasm_codec/Cargo.toml

[bump]: Bump Iroha version to RC20

---

Cargo.lock
scripts/test_env.py

The title is self-explanatory.
Closes #3898. 
Expected mode of termination on failure.

[fix]: #3898: Make `scripts/test_env.py` stop peers when aborting

---

client/src/client.rs
client/src/lib.rs
client/src/query_builder.rs
client/tests/integration/pagination.rs
client/tests/integration/sorting.rs
client/tests/integration/tx_history.rs
client_cli/src/main.rs

Added `QueryRequestBuilder` to get rid of boilerplate `request_with_*`  methods.
Closes #3124

[refactor] #3124: Introduced Query request builder into Client API

---

Cargo.lock
core/src/block.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs

[BACKPORT] #3995: Fix topology mismatch

---

client_cli/src/main.rs
tools/kagami/src/main.rs

[BACKPORT] #4014: Fix build of client_cli

---

.gitignore
client_cli/pytests/README.md

Fixes the pytests README
None
Correct README

[documentation]: Fixes the pytests README

---

core/src/block.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs

[fix] #3995: Fix topology mismatch

---

configs/client/stable/config.json
configs/peer/stable/config.json
configs/peer/stable/genesis.json

[fix] #0000: update stable config files

---

client_cli/src/main.rs

[BACKPORT] #4041: Add git commit SHA to client_cli

---

.github/workflows/iroha2-ci-image.yml
.github/workflows/iroha2-dev-nightly.yml
.github/workflows/iroha2-dev-pr-label.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-ui.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release-pr.yml
.github/workflows/iroha2-release.yml

[BACKPORT]: Add iroha2 stable tag only publishing (#4044)

---

Cargo.lock
Cargo.toml
configs/client/stable/config.json
core/src/smartcontracts/wasm.rs
logger/Cargo.toml
smart_contract/executor/derive/src/default.rs
wasm_builder/Cargo.toml

[fix] #0000: fix stable client config

---

cli/src/lib.rs
p2p/src/lib.rs
p2p/src/network.rs
p2p/src/peer.rs
p2p/tests/integration/p2p.rs

Backport for recently merged #4069

[BACKPORT] #4065: Prevent pub key spoofing in p2p

---

client/tests/integration/triggers/mod.rs
client/tests/integration/triggers/trigger_rollback.rs
core/src/wsv.rs

Fix trigger atomicity by cloning wsv.
Closes #4106

[fix] #4106: Fix trigger atomicity

---

.github/workflows/iroha2-release-pr.yml

[BACKPORT]: replace test_env.sh with test_env.py in CI

---

.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/lts-bug.yml
.github/ISSUE_TEMPLATE/stable-bug.yml

This PR changes the issue templates for Iroha.

[chore]: #4102 Update issue templates

---

client/src/http_default.rs

Fixed the web socket bug which gives HTTP 400.
All library versions saved as-is
- Closes #4099

[BACKPORT] #4099: Fix of the websocket request builder

---

Cargo.lock
core/Cargo.toml
core/clippy.toml
core/src/block_sync.rs
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
core/src/sumeragi/view_change.rs
core/src/wsv.rs
data_model/clippy.toml

[BACKPORT] #0000: On-chain predictable iteration order

---

Cargo.lock
client/examples/tutorial.rs
client/src/client.rs
client/src/lib.rs
client/tests/integration/add_account.rs
client/tests/integration/add_domain.rs
client/tests/integration/asset.rs
client/tests/integration/asset_propagation.rs
client/tests/integration/connected_peers.rs
client/tests/integration/events/mod.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/mod.rs
client/tests/integration/multiple_blocks_created.rs
client/tests/integration/multisignature_account.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/restart_peer.rs
client/tests/integration/tx_history.rs
client/tests/integration/unregister_peer.rs
client/tests/integration/unstable_network.rs
client_cli/Cargo.toml
client_cli/src/main.rs

[refactor]: Export iroha_config through iroha_client

---

core/src/sumeragi/mod.rs

Update current topology with block view change index.
Closes #4164 
Peer restarts correctly.
Use block store with where blocks have view change index > 0 and try to restart peer.

[fix] #4164: Fix topology update on restart

---

client/tests/integration/triggers/by_call_trigger.rs
core/src/smartcontracts/isi/triggers/set.rs

- See also #4160
- Closes #4133

[fix] #4133: Count identical wasm for triggers

---

crypto/src/signature/secp256k1.rs

This is an interoperability problem between OpenSSL and newer cryptographic libraries, see [BIP-0062](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#user-content-Low_S_values_in_signatures) for details
This fixes the flaky secp256k1_sign test
Also includes a drive-by cleanup of useless `assert(result.is_ok())`
Closes #4155
Fixes the flaky test! Less flaky tests is obviously better

[fix] #4155: ensure the secp256k1 signatures coming out of OpenSSL are normalized

---

client/tests/integration/restart_peer.rs

Use free port in integration test.

[fix] #0000: Use free port in test

---

Dockerfile

Fix was successfully tested by @timofeevmd 
- Closes #4192

[fix] #4192: Fix musl archiver name in Docker

---

client/src/client.rs

Added Client's headers to the requests
* Closes #4177

[fix] #4177: Fixed (get|set)_config 401 HTTP.

---

cli/src/lib.rs
core/src/query/store.rs
core/src/sumeragi/mod.rs

Bug was initially found in #4049
Closes #4211

[fix] #4211: Fix async blocking bug when starting Sumeragi

---

core/src/smartcontracts/isi/asset.rs
core/src/sumeragi/mod.rs
core/src/validator.rs
core/src/wsv.rs

[BACKPORT]: Fix tx amount metric

---

core/benches/blocks/apply_blocks.rs
core/benches/blocks/apply_blocks_benchmark.rs
core/benches/blocks/apply_blocks_oneshot.rs
core/benches/blocks/common.rs
core/benches/blocks/validate_blocks.rs
core/benches/blocks/validate_blocks_benchmark.rs
core/benches/blocks/validate_blocks_oneshot.rs

Followup fix for the same problem in benchmarks.
Closes #4211 
Benchmarks works.

[fix] #4211: Fix call blocking methods within async context

---

MAINTAINERS.md

Vladislav Amuzinski is now with us, but Vladimir and Ilia aren't working on Iroha anymore.

[chore] #4231: Update MAINTAINERS

---

client_cli/pytests/.gitignore
client_cli/pytests/README.md

Updated README (and `.gitignore`) in pytests because I found it confusing.

[documentation]: update Pytests README

---

MAINTAINERS.md

Let's replace `iroha2-dev` MAINTAINERS file with a fresh version.

[chore]: #4231 Update MAINTAINERS (dev branch)

---

MAINTAINERS.md

Let's add @s8sato back to the list of maintainers

[chore] #4255: Update Maintainers, add Sato-san

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release.yml
docker-compose.local.yml
docker-compose.single.yml
docker-compose.yml
scripts/tests/consistency.sh
tools/swarm/Cargo.toml
tools/swarm/src/cli.rs
tools/swarm/src/compose.rs
tools/swarm/src/main.rs

1. Add community docker-compose files CI check before image pushing
2. Update community docker-compose files
#3889 
Validate community docker-compose files integrity and serviceability.

[ci] #3889: Add docker-compose files run check into iroha2 CI

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/network_topology.rs

[BACKPORT] #4083: Introduce predictable ordering after too many failed view changes

---

client_cli/src/main.rs

Follow-up to the #4175 as more detailed description was requested by @timofeevmd in #3974 
Closes #3974 
Better UX

[fix] #3974: Update domain::metadata::Set value description

---

.github/CODEOWNERS

https://github.com/hyperledger/iroha/issues/4268
Current code owner list:
* @s8sato
* @mversic
* @arjentix
* @SamHSmith
* @outoftardis
* @Erigara
* @0x009922
* @DCNick3
* @vamuzing
* @Asem-Abdelhady
* @horizenight

Codeowners 2024

---

crypto/src/encryption/chacha20poly1305.rs

Fix MinSize for ChaCha20Poly1305 & add a test for minimal message size; see linked issue for detailed explanation 
Closes #4395

[fix] #4395: Fix MinSize for ChaCha20Poly1305

---

.github/build-iroha1-fork.src.yml
.github/build-iroha1.src.yml
.github/chatops-gen-matrix.sh
.github/workflows/build-iroha1-fork.yml
.github/workflows/build-iroha1.yml

Feature/dops 3159/ci docker main

---

cli/src/lib.rs
core/src/block.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/tx.rs

Verify that genesis transaction is indeed signed by genesis. 
Closes #4253 
Not possible to submit wrong genesis.

[fix] #4253: Check genesis pub key in genesis round

---

.github/workflows/iroha2-dev-pr-label.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-title.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-label.yml
.github/workflows/iroha2-pr-ui.yml
.github/workflows/iroha2-release-pr.yml
.github/workflows/iroha2-release.yml

Update workflows triggers for iroha2 `stable/lts` branch

[ci]: Update iroha2 stable/lts branch workflows triggers

---

data_model/src/events/data/filters.rs

Trigger filter match arm was missing.

[fix]: Fix trigger filters

---

.github/workflows/iroha2-profiling-image.yml
.github/workflows/iroha2-release.yml

Modify `iroha2-stable` and `iroha2-profiling` images tags regarding release publishing.
Closes #4459

[ci] #4459: New iroha2-stable images release tags

---

.github/dependabot.yml
.github/workflows/iroha2-dev-pr-title.yml

[ci] Recognize `chore` in PR titles

[ci]: Configure dependabot to follow commit message format

---

.github/workflows/iroha2-dev-pr-title.yml

"[fix]" in PR title breaks the check due to a malformed regex pattern

[fix]: fix broken regex in PR title action

---

.rustfmt.toml
client/src/http.rs
core/src/block.rs
core/src/executor.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/smartcontracts/isi/world.rs
core/src/smartcontracts/wasm.rs
core/src/tx.rs
crypto/src/encryption/mod.rs
data_model/derive/src/lib.rs
data_model/src/query/predicate.rs
ffi/derive/src/lib.rs
ffi/src/repr_c.rs
p2p/src/network.rs
primitives/src/unique_vec.rs
smart_contract/derive/src/lib.rs
smart_contract/executor/derive/src/lib.rs
telemetry/derive/src/lib.rs
tools/parity_scale_cli/src/main.rs
tools/swarm/src/util.rs
wasm_builder/src/lib.rs

[chore]: format doc comments

---

.github/dependabot.yml

chore(dependabot): follow conventional commits

---

.github/labeler.yml
.github/workflows/label-pr.yml

Label PRs targeting `iroha1-main` with `iroha1`
Linked to #4501

ci: Set up PR labeler for I1

---

core/test_network/src/lib.rs

Warn if a peer status request is failed. Helped me debug my misconfigured proxy failing tests when ran in IDE...
This also refactors a function a bit, because IMO it was a bit hard to read with the fold and `map_or`
Closes #4542
`+` Easier debugging if something went wrong with requests
`-` Can introduce log noise, but shouldn't happen if the actual connection to the node is OK

fix: Report if a request to check peer status in test_network fails

---

CHANGELOG.md
Cargo.toml
client/tests/integration/smartcontracts/Cargo.toml
default_executor/Cargo.toml
docs/source/references/schema.json
genesis/src/lib.rs
schema/gen/src/lib.rs
wasm_codec/Cargo.toml

fix: export RawGenesisBlockFile instead of RawGenesisBlock in schema

---

core/src/smartcontracts/isi/triggers/set.rs
core/src/smartcontracts/isi/triggers/specialized.rs
core/src/state.rs

Properly serialize trigger set.
Closes #4588

fix: trigger set is correctly serialized

---

config/src/client.rs

[BACKPORT]: support https URL scheme in config

---

core/test_network/src/lib.rs

Fix how `myself` is updated in `trusted_peers` for `test_network`.
Closes #4613

fix(test_network): Set myself in trusted_peers

---

client/src/config.rs
client/src/config/user.rs

feat: support `https` for `torii_url` (#4601)

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs

- if error  shutdown happened while iroha was listening for genesis exit happens gracefully
- loading blocks now respect fallback peer order
Closes #4604

fix(sumeragi): Use proper view_change_index on init block load

---

smart_contract/executor/src/default.rs
smart_contract/executor/src/lib.rs

refactor(executor): remove `Visit` bound from `Validate`

---

CHANGELOG.md
Cargo.toml
client/tests/integration/smartcontracts/Cargo.toml
default_executor/Cargo.toml
version/src/lib.rs
wasm_codec/Cargo.toml

chore(debug): Improve deserialization error message

---

client/tests/integration/permissions.rs
data_model/src/permission.rs
version/src/lib.rs

fix(BACKPORT): compare permission payloads as `serde_json::Value`

---

cli/src/lib.rs
cli/src/main.rs
client/tests/integration/triggers/time_trigger.rs
core/test_network/src/lib.rs

Simplify iroha startup + fix in integration test.
Closes #4562 
Simpler code.

refactor(irohad): always start torii as task

---

client/tests/integration/events/pipeline.rs
client/tests/integration/smartcontracts/executor_custom_data_model/src/complex.rs
client/tests/integration/smartcontracts/executor_custom_data_model/src/simple.rs
client_cli/pytests/README.md
core/src/block.rs
core/src/block_sync.rs
core/src/kura.rs
core/src/metrics.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/wasm.rs
core/src/snapshot.rs
core/src/state.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
core/src/sumeragi/view_change.rs
core/test_network/src/lib.rs
data_model/src/block.rs
data_model/src/events/pipeline.rs
data_model/src/lib.rs
docs/source/references/schema.json
smart_contract/executor/derive/src/permission.rs
smart_contract/executor/src/lib.rs
telemetry/src/metrics.rs
tools/parity_scale_cli/src/main.rs
torii/src/routing.rs

would you welcome this change?

refactor: replace u64 with usize internally

---

docs/source/references/schema.json

Add missing types into the schema.

fix: update schema.json

---

Cargo.lock
configs/swarm/genesis.json
data_model/src/block.rs
data_model/src/query/mod.rs
data_model/src/transaction.rs
docs/source/references/schema.json
genesis/Cargo.toml
genesis/src/lib.rs
schema/gen/src/lib.rs
tools/kagami/src/genesis/generate.rs

fix: restore RawGenesisTransaction schema

---

client/tests/integration/sorting.rs

refactor: Add #[ignore] to the sorting test

---

core/benches/blocks/validate_blocks_oneshot.rs

Fix error with double initialization of logger.

fix(validate_blocks): remove loger double initialiation

---

configs/swarm/docker-compose.local.yml
configs/swarm/docker-compose.single.yml
configs/swarm/docker-compose.yml
core/src/kura.rs
tools/swarm/src/lib.rs
tools/swarm/src/schema.rs

fix(docker): propagate SIGTERM to irohad

---

.github/workflows/iroha2-dev-sonar-dojo.yml

Removed lines that were bound to previous workflow.
fixes this sonar_dojo [workflow](https://github.com/hyperledger/iroha/actions/runs/9978526258)

ci: fix sonar dojo workflow

---

p2p/src/peer.rs

Remove adding garbage to p2p handshake.
Closes #4888 
No redundant code.

refactor(p2p): remove `garbage`

---

CHANGELOG.md
Cargo.toml
client/tests/integration/smartcontracts/Cargo.toml
client/tests/integration/smartcontracts/multisig/Cargo.toml
client/tests/integration/smartcontracts/multisig_register/Cargo.toml
default_executor/Cargo.toml

chore: version bump to RC22

---

.github/ISSUE_TEMPLATE/bug.yml

fix: delete exited colleges

---

CHANGELOG.md
Cargo.lock
Cargo.toml
client/Cargo.toml
wasm_samples/Cargo.toml
wasm_samples/multisig/Cargo.toml
wasm_samples/multisig_register/Cargo.toml

Current version should be whatever we're currently working on. 
In this case it should be `rc.1` and not `rc.22` which we have already released

chore: version bump to rc.1.0

---

torii/src/routing.rs

Closes #4218
Simplify API endpoints `/health` and `/api_version`

refactor: Simplify /health and /api_version

---

Cargo.lock
Cargo.toml

- `wasmtime` is quite outdated
- bump `wasmtime` version

chore: bump wasmtime version

---

.github/dependabot.yml

Groups dependabot updates for pytests to avoid conflicts.
---

ci(deps): group pytest dependabot updates

---

crates/iroha_core/src/block.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_primitives/src/const_vec.rs

Small PR to fix compilation and also fixes one warning for `ConstVec`

fix: Fix compilation

---

crates/iroha_data_model_derive/src/lib.rs

Check #4321.
Fix example in documentation.

fix(docs): fix model macro example in docs

---

Cargo.lock
crates/iroha/Cargo.toml
crates/iroha_config/Cargo.toml
crates/iroha_executor_data_model_derive/Cargo.toml
crates/iroha_futures/Cargo.toml
crates/iroha_genesis/Cargo.toml
crates/iroha_kagami/Cargo.toml
crates/iroha_test_samples/Cargo.toml

- Describe the objective or issue this PR addresses, as well as the impact of the change.
- Try to keep the description accessible to newcomers.
- If you're resolving a specific issue, add "Fixes #issue_number" or "Closes #issue_number".
---

chore: remove unused dependencies

---

crates/iroha/tests/mod.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/event_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs

Restores `queries` and some other integration tests

fix: Restore some integration tests

---

crates/iroha_wasm_builder/src/main.rs

fix: Don't use spinner when building wasm on CI

---

MAINTAINERS.md

**- The list of Iroha 2 maintainers was updated.**

chore: Updated MAINTAINERS.md

---

defaults/genesis.json

- https://github.com/hyperledger-iroha/iroha/pull/5283#discussion_r1920243721
- Replace Alice (ed0120..8B03) in `genesis.json`, which will be burnt on the image and eliminate the need to edit it
I'm going to merge regardless of checks as integration tests should fail without Alice

chore(testnet): replace Alice in `genesis.json`

---

crates/iroha_cli/src/main.rs
crates/iroha_executor/src/default/isi/multisig/transaction.rs
crates/iroha_executor_data_model/src/isi.rs
docs/source/references/schema.json

fix(BACKPORT): revise NonZeros

---

.github/workflows/iroha2-dev-pr.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha_cli/CommandLineHelp.md
crates/iroha_cli/README.md
crates/iroha_cli/docs/multisig.md
crates/iroha_cli/samples/parameter.json
crates/iroha_cli/samples/query.json
crates/iroha_cli/src/main.rs
crates/iroha_core/src/smartcontracts/wasm/cache.rs
crates/iroha_data_model/src/parameter.rs
crates/iroha_smart_contract_utils/src/lib.rs
scripts/tests/tick.json
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

- Backport the changes from #5291 to #5289

docs(cli, testnet/2.0.0-rc.1): fixup #5291

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha_core/src/peers_gossiper.rs
crates/iroha_p2p/src/network.rs
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

fix(BACKPORT): reset online peers

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha_core/src/peers_gossiper.rs
crates/iroha_p2p/src/network.rs
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

Backport to testnet of https://github.com/hyperledger-iroha/iroha/pull/5325

fix(Testnet, Backport): Reset online peers

---

.github/workflows/iroha2-dev-sonar-dojo.yml

Official `Sonarqube` GitHub Action has the error regarding script installation.
Try to update Action to the latest version to resolve the issue.

ci: Bump Sonarqube Action version

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/extra_functional/connected_peers.rs
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/status_response.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/query/dsl/predicates.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
docs/source/references/schema.json
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

feat!(Backport): Finalize non-empty blocks by allowing empty blocks after them

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/extra_functional/connected_peers.rs
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/status_response.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/query/dsl/predicates.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
docs/source/references/schema.json
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

feat(Testnet, Backport)!: Finalize non-empty blocks by allowing empty blocks after them

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/query/dsl/predicates.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
docs/source/references/schema.json
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

fix(Backport): Revert empty blocks

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/query/dsl/predicates.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
docs/source/references/schema.json
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

fix(Testnet, Backport): Revert empty blocks

---

crates/iroha_core/src/kura.rs

perf(kura): Prevent redundant block writes to disk

---

rust-toolchain.toml

build: include `rust-toolchain.toml`

---

.github/workflows/pr.yml

chore: do not run Pull Request CI on push to main

---

.github/workflows/pr.yml
scripts/tests/consistency.sh

Changes:
- Support `--update` argument to update target files in-place
- Support `all` argument to check/update all targets at once (no fail fast)
- Refactored code, less repetition

feat: enhance `consistency.sh`

---

.github/workflows/publish_xx.yml

ci(xx): add buildx setup step

---

.github/workflows/pr.yml
.github/workflows/publish_xx.yml

Yet another hot fix of the workflow file.

ci: add checkout to `publish_xx`; add some ignores to `pr.yml`

---

crates/iroha_data_model/src/isi.rs
crates/iroha_data_model/src/parameter.rs
crates/iroha_ffi/src/handle.rs
crates/iroha_smart_contract_utils/src/lib.rs

fix some minor issues in the comments
---

chore: fix some minor issues in the comments

---

crates/iroha_core/src/kura.rs

```rs
// Prune all blocks in the storage with height > 5
block_store.prune(5)?;
```
This function is not used anywhere in Iroha, but is needed for Explorer (https://github.com/soramitsu/iroha2-block-explorer-backend/issues/79).
Explorer maintains its own copy of the blockchain and keeps synchronising with Iroha. It is possible that Iroha (specified simply as URL) restarts with an entirely (or partially) different block chain. For this, Explorer needs to re-initialise Kura, pruning all (or some) stored blocks.
Most of the diff comes from tests.

feat(core): implement blocks storage pruning

---

crates/iroha/src/http.rs
crates/iroha_core/src/lib.rs
crates/iroha_core/src/queue.rs
crates/iroha_ffi/src/repr_c.rs
crates/iroha_schema_derive/src/trait_bounds.rs
crates/iroha_test_network/src/lib.rs

fix some minor issues in comments
correct it.
---

chore: fix some minor issues in comments

---

.github/workflows/pr.yml
.github/workflows/pr_docker_compose.yml
crates/iroha_config/src/parameters/actual.rs
crates/iroha_p2p/src/network.rs
crates/iroha_smart_contract/README.md
crates/iroha_swarm/src/schema.rs
lychee.toml

This PR:
1. Resolves trigger conditions for workflow #5438
2. Adds caching for the lychee checks #5412
3. Addresses clippy warnings

fix: ci workflows
