hyperledger-iroha/iroha

deploy/ansible/ansible.cfg
example/python/Makefile

- Restore gitignored ansible and python example files
- Restore kubespray submodule

Restore gitignored files and submodule

---

irohad/ametsuchi/impl/temporary_wsv_impl.cpp

Pull request fixes asan issue (see https://gist.github.com/luckychess/f830ab0d50d31ac4f340d5a4fd61bbc9 for details).
No more issue :-)
None.
Run irohad under asan and then run python example - no issues should be reported.
Similar issues and docs:
- https://github.com/SOCI/soci/pull/659/files (same issue fix)
- http://soci.sourceforge.net/doc/3.2/exchange.html#bind_local - check _Object lifetime and immutability_ section
P.S.: I don't understand why an old code even compiles.

Fix asan issue for soci::use

---

.github/issue_template.md

Adding issue template so the contributors filing the issue could do that in Jira directly. 
People will be aware their issue will be in Jira
Not that I'm aware of

Create GitHub issue template

---

test/framework/integration_framework/fake_peer/fake_peer.cpp
test/framework/integration_framework/fake_peer/fake_peer.hpp
test/integration/acceptance/acceptance_fixture.hpp

Pull request fixes 2 data races in tests.
No races ^^
None?
Tsan still reports about different issues but they are considered as false positives. If you remove tbb completely tsan output is clear.

Fix several tsan issues in tests

---

deploy/ansible/roles/iroha-docker/README.md
deploy/ansible/roles/iroha-docker/defaults/main.yml
deploy/ansible/roles/iroha-docker/handlers/main.yml
deploy/ansible/roles/iroha-docker/tasks/config-gen.yml
deploy/ansible/roles/iroha-docker/tasks/deploy.yml
deploy/ansible/roles/iroha-docker/tasks/init-vars.yml
deploy/ansible/roles/iroha-docker/tasks/main.yml
deploy/ansible/roles/iroha-docker/templates/docker-compose.yml.j2

This is a PR transferred without any modifications from the old repo: https://github.com/hyperledger-archives/iroha/pull/2219

Refactor Ansible role

---

docker/dependencies/Dockerfile
docker/develop/Dockerfile

Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
Switch from Oracle JDK to OpenJRE. PPA we were using for a while is [not supported anymore](https://askubuntu.com/a/1136128) :(
Java is still required by SonarQube -- static analysis tool
Possible incompatibility with Oracle JDK that may break SonarQube

Switch from Oracle JDK to OpenJRE

---

cmake/Modules/Findpq.cmake
cmake/Modules/Findsoci.cmake
docker/dependencies/Dockerfile
docker/develop/Dockerfile
irohad/ametsuchi/CMakeLists.txt
snap/snapcraft.yaml
test/framework/CMakeLists.txt
test/module/irohad/ametsuchi/CMakeLists.txt
test/system/CMakeLists.txt

Update SOCI version in order to use failover for database reconnection
- Recent version of SOCI
- New features for simpler database reconnection
None?

Bump SOCI version

---

docs/source/core_concepts/index.rst
docs/source/getting_started/cli-guide.rst
docs/source/getting_started/index.rst
docs/source/getting_started/python-guide.rst
docs/source/guides/build.rst
docs/source/guides/configuration.rst
docs/source/guides/deployment.rst
docs/source/maintenance/permissions.rst

https://jira.hyperledger.org/browse/IR-433
Separated CLI guide and Getting Started guide. Added Python guide that goes though python transaction example explaining it. 
Better Getting started guide that helps the newcomers a lot. 
Python guide might confuse someone but it can be fixed.

Fix getting started docs 

---

test/integration/pipeline/batch_pipeline_test.cpp

This pr is reopened instead of #32 
Add two more tests for transaction batch pipeline.
Make checks in existing cases more strict.
The new tests were created due to occurred Iroha endpoints misuse.
Torii endpoint was used instead of ListTorii when it was needed to update set of batch signatures.
That is why I created tests that check that everything is ok when correct endpoints are used.
Increased test coverage.
Not known.
`batch_pipeline_test`

Add tests for batch pipeline

---

shared_model/validators/query_validator.hpp

Pull request adds missing validation for 2 optional fields in GetAccountDetail query.
All fields in GetAccountDetail are validated.
None?

 Add missing validation for Key and Writer fields for GetAccountDetail

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.hpp
irohad/ametsuchi/storage.hpp
irohad/ametsuchi/wsv_restorer.hpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/irohad.cpp
libs/common/result.hpp
test/module/irohad/ametsuchi/mock_storage.hpp

Changes in this PR is based on  MBoldyrev's changes in https://github.com/hyperledger/iroha/pull/41. 
Same as the original PR but with two modifications:
* revert Result interface
* rework initialization of Irohad with monadic bind

[Reworked] Startup: check initial peers presence

---

cmake/Modules/Findrxcpp.cmake
docker/dependencies/Dockerfile
docker/develop/Dockerfile
snap/snapcraft.yaml

Pull request updates rxcpp version to the latest one (at the moment)
Rxcpp had a data race which was recently fixed in its repository.
None?

Bump rxcpp version to the latest available

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/k_times_reconnection_strategy.cpp
irohad/ametsuchi/impl/k_times_reconnection_strategy.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/reconnection_strategy.hpp
irohad/main/application.cpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/k_times_reconnection_strategy_test.cpp
test/module/irohad/ametsuchi/storage_init_test.cpp

Signed-off-by: Fedor Muratov <muratovfyodor@yandex.ru>
Add reconnection to PG using Soci interface
Easy way to reconnect
Lack of tests and documentation for now

Add functionality of reconnection to storage_impl

---

deploy/ansible/roles/iroha-docker/README.md
docs/source/getting_started/python-guide.rst
docs/source/guides/build.rst
docs/source/guides/configuration.rst

Add Windows build guide.
Fix Sphinx compilation warnings.
Fix Iroha configuration parameters descriptions.
Increased docs coverage.

Prepare docs for Iroha release

---

docs/source/guides/configuration.rst

Pull request adds documentation for `initial_peers` config option
It's now clear how to use it.
Lack of word wrapping for example line.

Add docs for initial_peers config option

---

irohad/main/iroha_conf_loader.cpp

- adds vector parsing from JSON array
- makes created pointers unique (it is strange to create a shared object from JSON)
- fixes public key format of initial peers
this time it seems to work

Config loader fix

---

Jenkinsfile-new

reopen of https://github.com/hyperledger/iroha/pull/62
Last time then I add tag build support, I was unable to test in (tags do not created often)
Here small fix 
Tags build automatically
None

Fix build tag

---

irohad/ametsuchi/impl/storage_impl.cpp

Correct connection failure check, refactoring.
Fixed the connection that is checked for errors here:
https://github.com/hyperledger/iroha/blob/b953c835e5bfb918a6a149f22d5709c1016f883b/irohad/ametsuchi/impl/storage_impl.cpp#L146
We should rather check the newly created connection.
Also applied a little simplifying refactoring.

Ametsuchi: fixed soci reconnection loop

---

shared_model/schema/transaction.proto
shared_model/validators/protobuf/proto_transaction_validator.cpp
test/framework/test_logger.cpp
test/framework/test_logger.hpp
test/fuzzing/block_loader_fixture.hpp
test/fuzzing/consensus_fuzz.cpp
test/fuzzing/ordering_service_fixture.hpp
test/fuzzing/request_proposal_fuzz.cpp
test/fuzzing/retrieve_blocks_fuzz.cpp
test/fuzzing/send_batches_fuzz.cpp
test/fuzzing/standalone_fuzz_target_runner.cpp
test/fuzzing/torii_fuzz.cpp
test/module/irohad/consensus/yac/supermajority_checker_test.cpp

- 5 issues: [one](https://jira.hyperledger.org/browse/IR-500), [two](https://jira.hyperledger.org/browse/IR-501), [three](https://jira.hyperledger.org/browse/IR-502), [four](https://jira.hyperledger.org/browse/IR-503), [five](https://jira.hyperledger.org/browse/IR-504) are fixed.
- MacOS build is fixed.
Fuzzing is ready to OSS-fuzz integration.
None?
Run `cmake -DFUZZING=ON ..` and then `make mst_fuzz` (or any other fuzzing target).

Fuzzing fixes

---

test/module/irohad/ametsuchi/postgres_query_executor_test.cpp

Added a check for empty collection and fixed an assertion.
Better readable test errors.

postgres_query_executor_test: micro fix

---

irohad/ametsuchi/impl/postgres_command_executor.cpp

Just make the `setAccountDetail` statement simpler.
Simplicity, readability.
setAccountDetail

PostgreSQL command executor: simplify setAccountDetail statement

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp

removed `StorageImpl::block_store_dir_`.
several bytes less in irohad memory footprint =)

StorageImpl: removed unused member 

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/temporary_wsv_impl.cpp
irohad/ametsuchi/impl/temporary_wsv_impl.hpp

Removed unused constructor argument.
Several bytes less in stack frame during constructor call when not using optimizations! And one dependency less.

TemporaryWsvImpl: removed CommonObjectsFactory from constructor arguments

---

irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/postgres_wsv_command.cpp
shared_model/backend/protobuf/impl/permissions.cpp
shared_model/backend/protobuf/impl/proto_permission_to_string.cpp
shared_model/backend/protobuf/impl/proto_query_response_factory.cpp
shared_model/builders/protobuf/builder_templates/transaction_template.hpp
shared_model/interfaces/impl/permissions.cpp
shared_model/interfaces/permissions.hpp
test/module/irohad/ametsuchi/postgres_executor_test.cpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/shared_model/backend_proto/permissions_test.cpp

Previous implementation of `PermissionSet` used to inherit from `std::bitset`, which is widely considered a very bad practice. Such design has no visible reasons. This change makes `std::bitset` a private member.
Better design.

PermissionSet: refactoring

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor_impl.hpp
irohad/network/mst_transport.hpp
test/framework/integration_framework/fake_peer/network/mst_message.hpp
test/framework/integration_framework/fake_peer/network/mst_network_notifier.cpp
test/framework/integration_framework/fake_peer/network/mst_network_notifier.hpp
test/framework/test_subscriber.hpp
test/module/irohad/multi_sig_transactions/mst_mocks.hpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp

Backport of https://github.com/hyperledger/iroha/pull/56

MST: fixed expired incoming state logic

---

test/module/shared_model/CMakeLists.txt
test/module/shared_model/mock_objects_factories/mock_query_factory.cpp
test/module/shared_model/mock_objects_factories/mock_query_factory.hpp
test/module/shared_model/query_mocks.hpp

Mocks of `shared_model::interface::Query::QueryVariantType` variant types (specific queries like `GetAccountTransactions`).
Easier and more lightweight tests need such mocks.
One more step towards `ExecutorItf`.

Testing: query mocks

---

.jenkinsci-new/build.groovy
.jenkinsci-new/builders/x64-linux-build-steps.groovy
.jenkinsci-new/text-variables.groovy
Jenkinsfile-new
docker/develop/Dockerfile
sonar-project.properties

fix sonar sonarqube report 
add clang-format
fix mac test `/bin/bash` - recently we changed Jenkins defualt shell to `sh`, mac test start fail.   
sonarqube report will be available in PR
clang-format report will be available in PR
None

DOPS-12 Refactor SonarQube rules

---

test/module/shared_model/mock_objects_factories/mock_query_factory.cpp
test/module/shared_model/mock_objects_factories/mock_query_factory.hpp
test/module/shared_model/query_mocks.hpp

This fixes a bad merge of #120 that was not tested before the merge to trunk.

fixed mock query for paginated account details

---

Jenkinsfile-new

While fixing the conflicts in previous PR two flags change the order (doxygen, packageBuild )
fix builds
None

Fix packageBuild

---

docs/source/guides/configuration.rst
irohad/ametsuchi/impl/postgres_options.cpp
irohad/ametsuchi/impl/postgres_options.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/main/CMakeLists.txt
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/impl/pg_connection_init.cpp
irohad/main/impl/pg_connection_init.hpp
irohad/main/iroha_conf_literals.cpp
irohad/main/iroha_conf_literals.hpp
irohad/main/iroha_conf_loader.cpp
irohad/main/iroha_conf_loader.hpp
irohad/main/irohad.cpp
test/framework/CMakeLists.txt
test/framework/config_helper.cpp
test/framework/config_helper.hpp
test/framework/integration_framework/iroha_instance.cpp
test/framework/integration_framework/iroha_instance.hpp
test/framework/integration_framework/test_irohad.hpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/postgres_options_test.cpp
test/module/irohad/ametsuchi/storage_init_test.cpp
test/system/irohad_test.cpp

Since we are not controlling PostgreSQL setup on the target nodes, we need to be both flexible and secure about a database name we can use to connect to DBMS in order to manage the databases we use for data storage. Previously we relied on the availability of the default database that has the same name as the user. This change makes the management database explicit in connection options.
With the next major release we should make the user provide the exact name of management database.
Explicit control over destination database.
Complicated logic to preserve old behaviour.

PostgresOptions: separate working & management database names

---

irohad/ametsuchi/impl/mutable_storage_impl.cpp
irohad/ametsuchi/impl/mutable_storage_impl.hpp
irohad/ametsuchi/impl/postgres_wsv_query.cpp
irohad/ametsuchi/impl/postgres_wsv_query.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/consensus/yac/CMakeLists.txt
irohad/consensus/yac/impl/yac_crypto_provider_impl.cpp
irohad/consensus/yac/impl/yac_crypto_provider_impl.hpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/impl/consensus_init.cpp
irohad/main/impl/consensus_init.hpp
shared_model/backend/plain/CMakeLists.txt
shared_model/backend/plain/impl/signature.cpp
shared_model/backend/plain/signature.hpp
test/framework/integration_framework/fake_peer/fake_peer.cpp
test/fuzzing/consensus_fuzz.cpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/postgres_executor_test.cpp
test/module/irohad/ametsuchi/storage_init_test.cpp
test/module/irohad/ametsuchi/wsv_query_command_test.cpp
test/module/irohad/consensus/yac/yac_crypto_provider_test.cpp

Removed excessive dependency, now storage and yac don't a dependency on common-object-factory, thus they don't a dependency on config 
More flexible, now config can be initialized with information from the storage
None

Removed dependency storage and yac on common-object-factory

---

test/framework/CMakeLists.txt
test/framework/executor_itf/CMakeLists.txt
test/framework/executor_itf/executor_itf.cpp
test/framework/executor_itf/executor_itf.hpp
test/framework/executor_itf/executor_itf_helper.hpp
test/framework/result_gtest_checkers.hpp

This PR brings the base of new shiny Executor ITF. It is still not useable in this state, because some important features like DB connection are coming in separate PRs to alleviate reviews.
This ITF is a weapon against the devil hiding in Ametsuchi Test debris. With it we will be able to chop down most of its children (and grand children) and restrict it's domain to minimum.
The rest of this project can be seen in #155. There are also some tests done on it.
Clear and easy to use design. Use of mocks (which should soon be replaced by plain model, which is even more simple). Convenient handles (even more to come in Fixture).

Testing: Executor ITF

---

cmake/Modules/Findgrpc.cmake
cmake/Modules/Findprotobuf.cmake
docker/develop/Dockerfile
irohad/ametsuchi/block_query.hpp
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/main/application.cpp
irohad/main/server_runner.cpp
irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
irohad/network/impl/block_loader_impl.cpp
irohad/network/impl/block_loader_impl.hpp
irohad/network/impl/block_loader_service.cpp
irohad/network/impl/grpc_channel_builder.hpp
irohad/torii/impl/query_client.cpp
irohad/torii/query_client.hpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/network/block_loader_test.cpp

This sets the GRPC clients up to retry the call transparently for the request issuing code. The solution is based on a not fully ready feature of GRPC that is described [here](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) (there is also an [implementation discussion thread](https://groups.google.com/forum/#!topic/grpc-io/zzHIICbwTZE)).
The way it is used is not totally correct, since the involved method of setting service config [is intended to be used in tests only](https://github.com/grpc/grpc/blob/master/doc/service_config.md#apis).
Also there is no API reference for the used configuration, so this should be considered an experimental change.
Seamless, transparent and resource-effective native super retry policy.
Using not officially production ready feature.
No …

GRPC: client will retry on failure

---

docs/source/api/commands.rst
irohad/ametsuchi/command_executor.hpp
irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/postgres_command_executor.hpp
shared_model/backend/protobuf/CMakeLists.txt
shared_model/backend/protobuf/commands/impl/proto_command.cpp
shared_model/backend/protobuf/commands/impl/proto_compare_and_set_account_detail.cpp
shared_model/backend/protobuf/commands/proto_compare_and_set_account_detail.hpp
shared_model/interfaces/CMakeLists.txt
shared_model/interfaces/commands/command.hpp
shared_model/interfaces/commands/command_variant.hpp
shared_model/interfaces/commands/compare_and_set_account_detail.hpp
shared_model/interfaces/commands/impl/compare_and_set_account_detail.cpp
shared_model/schema/commands.proto
shared_model/validators/field_validator.cpp
shared_model/validators/field_validator.hpp
shared_model/validators/transaction_validator.hpp
test/module/irohad/ametsuchi/postgres_executor_test.cpp
test/module/shared_model/command_mocks.hpp
test/module/shared_model/mock_objects_factories/mock_command_factory.cpp
test/module/shared_model/mock_objects_factories/mock_command_factory.hpp
test/module/shared_model/validators/field_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

Add CompareAndSetAccountDetail command, which set new value after old values ​​match.
Pre-write protection - more control
None
```postgres_executor_test```

CompareAndSetAccountDetail command

---

.jenkinsci/utils/docker-pull-or-build.groovy

Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
CI builds did not leverage Docker image (`:develop-build`) cache always building it from scratch (See https://jenkins.soramitsu.co.jp/blue/rest/organizations/jenkins/pipelines/iroha/pipelines/iroha-hyperledger/branches/PR-185/runs/1/nodes/37/steps/127/log/?start=0). 
Enable caching with `--cache-from` and some workaround with base image pulling (https://github.com/moby/moby/issues/31613)
Faster builds due to caching
None

CI builds using Docker cache

---

.jenkinsci-new/builders/x64-linux-build-steps.groovy

Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
Backport changes from #192

Disable Docker pushes for tags (backport to 1.0.x)

---

libs/common/result.hpp

Removed erroneous use of an equally-named function which caused an infinite recursion.

expected::Result: fixed type helper

---

.jenkinsci-new/builders/x64-linux-build-steps.groovy

Signed-off-by: Artyom Bakhtin <a@bakhtin.net>
Backport changes from #192

Disable Docker pushes for tags (backport to 1.1.x)

---

irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/postgres_wsv_command.cpp
irohad/main/impl/pg_connection_init.cpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp

Pull request removes `data` field from Asset table.
The `data` field is unused anyway so let's remove it to make a db model consistent to the shared model.
None?

Remove unused json data field from Asset

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/consensus/yac/CMakeLists.txt
shared_model/backend/plain/CMakeLists.txt
shared_model/backend/plain/account_detail_record_id.hpp
shared_model/backend/plain/impl/account_detail_record_id.cpp
shared_model/backend/protobuf/impl/proto_query_response_factory.cpp
shared_model/backend/protobuf/proto_query_response_factory.hpp
shared_model/builders/CMakeLists.txt
shared_model/builders/protobuf/builder_templates/query_template.hpp
shared_model/interfaces/common_objects/types.hpp
shared_model/interfaces/iroha_internal/query_response_factory.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/irohad/torii/processor/CMakeLists.txt
test/module/shared_model/backend_proto/CMakeLists.txt
test/module/shared_model/backend_proto/proto_query_response_factory_test.cpp

…_model::plain::AccountDetailRecordId
moved `AccountDetailRecordId` from `shared_model::interface::types` to `shared_model::plain`
While keeping the benefits of simple structure, it now inherits the corresponding interface type, which makes it useable in tests instead of mock objects.

SharedModel: moved AccountDetailRecordId from shared_model::interface::types to shared_model::plain

---

irohad/ametsuchi/CMakeLists.txt
test/framework/executor_itf/CMakeLists.txt
test/framework/executor_itf/executor_itf.cpp
test/framework/executor_itf/executor_itf.hpp
test/framework/executor_itf/executor_itf_param.hpp
test/framework/test_db_manager.cpp
test/framework/test_db_manager.hpp

This change makes Executor ITF decoupled from the command & query executors implementations.
One more step towards functional ExecutorItf.

ExecutorItf: parametric backend

---

irohad/main/application.cpp
irohad/main/application.hpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_gate.hpp
shared_model/validators/block_validator.hpp
shared_model/validators/transaction_batch_validator.cpp
shared_model/validators/transactions_collection/transactions_collection_validator.cpp
shared_model/validators/transactions_collection/transactions_collection_validator.hpp
shared_model/validators/validators_common.cpp
shared_model/validators/validators_common.hpp
test/module/irohad/common/validators_config.hpp
test/module/irohad/ordering/CMakeLists.txt
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
test/module/irohad/simulator/simulator_test.cpp
test/module/shared_model/backend_proto/proto_batch_test.cpp
test/module/shared_model/builders/protobuf/builder_templates/proposal_template.hpp
test/module/shared_model/builders/protobuf/transport_builder_test.cpp
test/module/shared_model/validators/batch_validator_test.cpp
test/module/shared_model/validators/block_validator_test.cpp
test/module/shared_model/validators/proposal_validator_test.cpp

Now, if there are two or more identical transactions in the collection, this will be perceived as an invalid collection
Also excluded the scenario that the rejected transaction is contained in the main transactions
Security, сollections coming from the network are checked more carefully
None
`on_demand_ordering_gate_test.cpp`, `transport_builder_test.cpp`, `block_validator_test.cpp`, `batch_validator_test.cpp`

Fix Transactions' Collections Validation (IR-585)

---

test/framework/executor_itf/executor_itf.hpp
test/framework/executor_itf/executor_itf_helper.hpp

Fixed the problem of copying query response when converting to specific response. Changed general query execution functions to return general response, and added a separate call to return converted specific response.
No response copying. On-demand response conversion.

ExecutorItf: rework query execution funcs

---

test/framework/executor_itf/executor_itf.cpp
test/framework/executor_itf/executor_itf.hpp
test/framework/executor_itf/executor_itf_param.hpp

Added control over validation in command executor.
One more step towards the new shiny Executor ITF.

ExecutorItf: command validation setup

---

test/integration/CMakeLists.txt
test/integration/executor/CMakeLists.txt
test/integration/executor/executor_fixture.cpp
test/integration/executor/executor_fixture.hpp
test/integration/executor/executor_fixture_param.cpp
test/integration/executor/executor_fixture_param.hpp

`ExecutorTestBase` is a common base class for Executor ITF tests. It supports various backends as parameter.
`BasicExecutorTest` is an implementation of Executor ITF test class that gets backend parameters from Google test framework. It is supposed to be the used in most test cases. Though there are test cases where it is not suitable - the ones that require more complex parameters than just the Executor ITF backend. An example can be seen in my WIP branch:
https://github.com/hyperledger/iroha/blob/9ac7d8106eafdfac5c1adb826f4278c4b4630b27/test/integration/executor/query_permission_test.hpp#L37-L42
One more step towards the new shiny Executor ITF.

Executor ITF: common base fixture

---

test/integration/executor/CMakeLists.txt
test/integration/executor/executor_fixture_param_postgres.cpp
test/integration/executor/executor_fixture_param_postgres.hpp
test/integration/executor/executor_fixture_param_provider.cpp
test/integration/executor/executor_fixture_param_provider.hpp

PostgreSQL backend parameter for Executor Fixture.
One more step towards the new shiny Executor ITF.

Executor ITF: PostgreSQL backend

---

irohad/ametsuchi/impl/postgres_command_executor.cpp

Permissoins check happens before signatory addition. Some query simplification.
Signatory is not added when aaccount creation permission check fails.
Somewhat more effective and readable queries.

PostgresCommandExecutor: fixed unconditional signatory addition

---

test/system/irohad_test.cpp

(Hopefully) fixed a test that sometimes failed due to port binding failure.
-1 reason for a test failure

IrohadTest: added waiting for TLS server

---

irohad/ametsuchi/impl/postgres_block_storage.cpp
irohad/ametsuchi/impl/postgres_block_storage.hpp

fixed a case when empty block table crashed irohad. also did some refactoring.
crash fixed. removed class member template function.

PostgresBlockStorage: fix missing blocks handling & refactor

---

docs/image_assets/Pipeline diagram_soucefile.xml

https://jira.hyperledger.org/browse/IR-101
Here I add the original file of the architecture diagram – so if anything needs changes, it would be right there in image folder. 
We're prepared for any changes in architecture and can easily fix the diagram in docs.
+1 file in repo

Docs/ Adding original file of the pipeline diagram

---

irohad/main/application.cpp

While the code is not Bft, we should use Cft mode explicitly to avoid misunderstanding and tolerate more failing peers.

Yac: switch supermajority checker to CFT

---

README.md
docs/source/before_start/architecture.rst
docs/source/index.rst
docs/source/overview.rst

Since YAC is CFT at the moment, in this PR I fixed all the docs stating otherwise to avoid confusion. 
Clear info
There are still papers that have BFT info with a research

Docs/ CFT YAC

---

.jenkinsci/build.groovy

We updated the sonar to latest version, some parameters are deprecated and have to be removed. 
No
We will see

Fix the sonar

---

irohad/network/impl/grpc_channel_builder.hpp

Add UNAVAILABLE to list of retryable codes as suggested in https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
Avoid transient failures during nodes reconnection
Some tests take too much time to pass

gRPC: add UNAVAILABLE to list of retryable codes

---

irohad/consensus/yac/transport/impl/network_impl.cpp

Force recreation of channel and stub in Yac send state method to avoid issues with reconnection when another node went down and turned back up
Less issues with connection restore on network failures
Channel and stub creation overhead? Need to research the correct way to handle retries and channel handling

Yac: recreate channel and stub on each send

---

CONTRIBUTING.rst
docs/source/before_start/architecture.rst
docs/source/before_start/glossary.rst
docs/source/build/index.rst
docs/source/deploy/troubles.rst
docs/source/develop/api.rst
docs/source/develop/api/queries.rst
docs/source/faq/index.rst
docs/source/getting_started/index.rst
docs/source/getting_started/python-guide.rst
docs/source/index.rst
docs/source/integrations/index.rst
docs/source/overview.rst

Added information about integrations and how to build Iroha with Ursa! 
Bonus: fixed links broken after the restructure.
We could announce Ursa integration because we now have info about how to use it. 
Also - fixed links
Information about integrations if not full yet - will add more after Burrow is fully integrated

adding some integrations info and fixing many broken links

---

shared_model/backend/protobuf/query_responses/impl/proto_signatories_response.cpp

for some reason, mac pipeline failed to initialize a vector.

Hotfix: mac build

---

docs/source/develop/api/commands.rst

@MBoldyrev noticed inconsistent info here: https://iroha.readthedocs.io/en/latest/develop/api/commands.html#id68 and we fixed it. 
One error less
None that I could think of

Docs/ Fixed inconsistent info about Set Account Detail Command

---

README.md
docs/source/develop/index.rst

Recently @claudiocandio contributed an example app based on Iroha. We wanted to add a reference to it. 
Thank you, Claudio! 
Up-to-date example app
¯\_(ツ)_/¯

Docs/ Example App

---

shared_model/interfaces/common_objects/impl/amount.cpp
test/module/shared_model/interface/common_objects/amount_test.cpp

fixed amount octocrash

---

irohad/multi_sig_transactions/hash.hpp
irohad/multi_sig_transactions/impl/hash.cpp
irohad/multi_sig_transactions/storage/CMakeLists.txt
irohad/multi_sig_transactions/storage/mst_storage_impl.hpp
irohad/network/CMakeLists.txt
irohad/network/impl/channel_factory.cpp
irohad/network/impl/channel_factory.hpp
irohad/network/impl/channel_factory_tls.cpp
irohad/network/impl/channel_factory_tls.hpp
irohad/network/impl/channel_pool.cpp
irohad/network/impl/channel_pool.hpp
irohad/network/impl/channel_provider.hpp
irohad/network/impl/client_factory.hpp
irohad/network/impl/client_factory_impl.hpp
irohad/network/impl/generic_client_factory.cpp
irohad/network/impl/generic_client_factory.hpp
irohad/network/impl/grpc_channel_params.hpp
shared_model/cryptography/CMakeLists.txt
shared_model/cryptography/blob_hasher.cpp
shared_model/cryptography/blob_hasher.hpp

still not employed in main code.

Network: added client factory source files

---

docs/source/_extra/googlecdeea2ebc420b97a.html
docs/source/conf.py

Now it is possible to add files to the documentation build. Here I added a verification file for Google Search Console (to help re-index our documentation) – that file can be removed or changed. 
We'll be able to initialise indexing and attract crawlers
Do not see any atm

Docs/ New option for additional documentation files

---

docker/develop/Dockerfile

python3.6 is in the main ubuntu repo, so we don't need to add a ppa. the ppa was closed (https://launchpad.net/~jonathonf) and prevents our ci from building the docker image for tests.

fixed docker develop image python3.6

---

irohad/ametsuchi/impl/postgres_command_executor.cpp

SOCI captures parameters by constref, so their lifetime must be guaranteed by the caller side.

Bugfix: soci statement parameter lifetime

---

docker/develop/Dockerfile

Changed the ppa for python3.6 in ubuntu16.04
the ppa of Jonathon F was closed (https://launchpad.net/~jonathonf) and prevents our ci from building the docker image for tests. So I switched to another ppa.

v1.0.x docker: fixed docker develop image python3.6 ppa

---

irohad/ametsuchi/impl/postgres_indexer.cpp
irohad/ametsuchi/impl/postgres_indexer.hpp

Employ SOCI [bulk insert](http://soci.sourceforge.net/doc/master/binding/#bulk-operations).
avoid homemade string concatenations.

PostgresIndexer: bulk insert

---

vcpkg/oss/VCPKG_SKIP_DEPS
vcpkg/oss/build_deps.sh

`benchmark` faills on oss fuzz, but we do not need it there, so I remove it.
hopefully fix oss fuzz build

exclude benchmark from oss fuzz vcpkg deps

---

docs/source/maintenance/index.rst
docs/source/maintenance/restarting_node.rst

adds docs on how to reuse existing WSV for faster restart.

Documentation: reuse WSV

---

docs/source/maintenance/restarting_node.rst

Docs: added --reuse_state flag

---

.jenkinsci/text-variables.groovy
.jenkinsci/utils/vars.groovy
Jenkinsfile
cmake/Modules/Findursa.cmake
docker/develop/Dockerfile
docker/release/Dockerfile
docs/source/guides/build.rst
sonar-project.properties

Backport of this two pr: 
https://github.com/hyperledger/iroha/pull/287
https://github.com/hyperledger/iroha/pull/353

Backport gcc9 and ci option "push demo"  [1.1.x]

---

.jenkinsci/builders/x64-mac-build-steps.groovy

Signed-off-by: Sofiane Benahmed <benahmed@soramitsu.co.jp>
Fix the path to the CMAKE_TOOL_CHAIN_FILE path in Macos jenkins build file
Fixes macOS builds 
None

fix macos cmake tool chain file path

---

.jenkinsci/builders/x64-win-build-steps.groovy
.packer/win/files/packages.config
.packer/win/scripts/vcpkg.ps1
docker/develop/Dockerfile
docs/source/guides/build.rst
vcpkg/build_iroha_deps.sh

Backport of this two pr:
https://github.com/hyperledger/iroha/pull/221
https://github.com/hyperledger/iroha/pull/305

Backport vcpkg scripts [1.1.x]

---

irohad/ametsuchi/impl/storage_impl.cpp
libs/common/irohad_version.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/mock_wsv_query.hpp
test/module/irohad/consensus/yac/yac_synchronization_test.cpp

fixed MockWsvCommand

---

test/integration/binary/CMakeLists.txt

`FindPythonInterp` is [deprecated](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html) and was used wrong (see the note in cmake docs).
This replaces the module with suggested alternative: `FindPython3`.
Hopefully this fixes mac ci.

CMake: fixed python3 search

---

irohad/main/CMakeLists.txt
irohad/main/impl/on_demand_ordering_init.cpp
irohad/main/impl/on_demand_ordering_init.hpp
libs/common/CMakeLists.txt
libs/common/permutation_generator.cpp
libs/common/permutation_generator.hpp
test/module/libs/common/CMakeLists.txt
test/module/libs/common/permutation_generator_test.cpp

as the tests on commit ea13a8e show, our builds on [gnu/linux](https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-336/11/tests) and [mac](https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-336/12/tests) produce different algorithms when using `std::seed_seq` and `std::shuffle` functions.
This change adds a simple implementation of permutation generator relying on Mersene Twister 19937 generator from standard library. It seems to be implemented the same way on all our tested platforms.
When this permutation generator is used in consensus (after #333) and ordering (in this PR), a single Iroha network of nodes built on different toolchains will become …

Permutation generator: portability across platforms

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp

quick and dirty fix for a flaw in MST propagation. before this change, any diff sent once would be recent eternally until MST is completed or invalidated, because the sender would never know if the recipient got the diff.
hopefully fixes enormous resource usage in MST propagation.

MST: assume state diff recieved

---

irohad/multi_sig_transactions/state/impl/mst_state.cpp
shared_model/interfaces/base/signable.hpp
test/module/irohad/multi_sig_transactions/storage_test.cpp

Refactor https://github.com/hyperledger/iroha/pull/359 to encapsulate logic within MstState
Agreed with @MBoldyrev offline
Simpler code
Might have slightly worse performance due to signature comparison

MST: fix propagation of updates from Torii

---

docs/source/guides/configuration.rst
example/config.sample

Added a few lines of config docs for #363
Changed an example config as well (added this parameter)
Better docs
¯\_(ツ)_/¯

Docs for #363

---

.travis.yml
CHANGELOG.md
Cargo.toml
README.md
src/lib.rs
src/main.rs
src/model.rs
src/storage/kura.rs
src/storage/mod.rs
tests/assets.rs

Initial Kura API.

---

src/cache/mod.rs
src/cache/mst_cache.rs
src/cache/pending_tx_cache.rs
src/consensus/mod.rs
src/main.rs
src/model/mod.rs
src/model/model.rs
src/networking/mod.rs
src/networking/torii.rs
src/storage/kura.rs
src/validation/mod.rs
src/validation/stateful.rs
src/validation/stateless.rs
tests/assets.rs

Signed-off-by: 武宮誠 <takemiya@soramitsu.co.jp>
Initial directory structure and outline of code for Iroha v2.
We can use this as a basis to flesh out the code in more detail and set up things like networking.
No major drawbacks.

Initial outline of iroha2 code

---

src/cache/mst_cache.rs
src/cache/pending_tx_cache.rs
src/main.rs
src/networking/torii.rs

Signed-off-by: 武宮誠 <takemiya@soramitsu.co.jp>
Remove .new() initializers and replace with default, which is less code and simpler.
Simpler solution.

Add default initializer to structs

---

src/model/model.rs
src/storage/kura.rs
tests/assets.rs

Transfer asset test and functionality.

---

src/model/model.rs
src/storage/kura.rs

Fixed tests and World State View initialization.

---

Cargo.toml
src/model/model.rs
src/storage/kura.rs
tests/assets.rs

Resolves issue: [RH2-1] Implement Disk Storage prototype 
1. File structure improvements
2. Reading from file
3. Async disk read and write with **async_std**
4. Disk storage tests now cleanup folders after themselves
Introduces the prototype of disk storage. Right now as agreed 1 block = 1 file.
Dependency on async_std.

Disk storage prototype

---

Cargo.toml
src/model/mod.rs
src/storage/kura.rs
tests/assets.rs

1. Adds block hash function with the use of blake2 crate.
2. Serialization for Hash struct
Hash function implemented

Blake2 Hash

---

src/cache/pending_tx_cache.rs
src/model/mod.rs
src/networking/torii.rs
src/storage/kura.rs
src/validation/mod.rs
src/validation/stateful.rs
src/validation/stateless.rs

Initial Merkle Tree functionality with tests.

---

CONTRIBUTING.rst

Rule about mod.rs in Contributing guide.

---

Cargo.toml
src/model/mod.rs
src/validation/mod.rs

Use ursa::blake2 instead of original blake2 crate.
We already plan to use ursa, so this way we will not add additional dependencies.

use ursa::blake2

---

.github/workflows/rust.yml
CHANGELOG.md
src/model/commands/accounts.rs
src/model/commands/assets.rs
src/model/commands/domains.rs
src/model/commands/peers.rs
src/model/tx.rs
src/storage/kura.rs
src/validation/merkle.rs
tests/assets.rs

References usage instead of ownership for de/serialization.

---

docs/source/build/index.rst

this is needed to download things via https
ca-certs are required to establish https connections. at least one is needed to clone repo.
errors caused by missing CAs may seem quite misleading. hopefully this change prevents some.

Docs: add ca-certs to linux prereqs

---

Cargo.toml
src/storage/kura.rs

Write to disk and WSV update are happening concurrently. As requested in issue RH2-14.
It should improve performance of Kura::store function.
Introduces another dependency: [futures crate](https://crates.io/crates/futures).

Parallel Kura::store execution

---

src/cache/pending_tx_cache.rs
src/client.rs
src/client/command.rs
src/client/query.rs
src/consensus/sumeragi.rs
src/lib.rs
src/main.rs
src/model/block.rs
src/model/commands/accounts.rs
src/model/commands/assets.rs
src/model/commands/domains.rs
src/model/commands/isi.rs
src/model/commands/mod.rs
src/model/commands/peers.rs
src/model/tx.rs
src/networking/torii.rs
src/storage/kura.rs
src/validation/merkle.rs
tests/assets.rs
tests/bdd.rs

BDD like test scenario - transfer assets.

---

.github/workflows/rust.yml
Cargo.toml
benches/torii.rs
docs/references/cqrs_api.raml
docs/references/transfer_asset_sequence.puml
src/client/query.rs
src/consensus/sumeragi.rs
src/main.rs
src/model/block.rs
src/model/tx.rs
src/networking/torii.rs
src/storage/kura.rs
tests/bdd.rs

Get and Put requests handling for Torii.

---

benches/torii.rs
config.json
src/config.rs
src/lib.rs
src/main.rs
src/networking/torii.rs
tests/bdd.rs
tests/example_config.json

External configuration via environment variables.

---

vcpkg/patches/0003-fix-tbb-repo-in-vcpkg.patch

originated in #415, this is a fix of the vcpkg problem ported from https://github.com/microsoft/vcpkg/pull/10456. 
due to vcpkg design, we have to monitor and backport fixes of their tool to our repo by ourselves.

vcpkg: fix tbb repo

---

iroha_2_whitepaper.md

A proposed design for conditional multisig is presented.

add proposed design for conditional multisig

---

.github/workflows/rust.yml

Additional CI caches.

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/src/client.rs
iroha_client/tests/client.rs

Usage of integer constants error-prone and hard to maintain. This PR adds Instruction trait and Contract enum. Custom ISIs are out of scope.

Transformation of Commands into ISI contracts.

---

Cargo.toml
iroha/Cargo.toml
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/block.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/peer.rs
iroha/src/query.rs
iroha/src/tx.rs
iroha_macro/Cargo.toml
iroha_macro/iroha_derive/Cargo.toml
iroha_macro/iroha_derive/src/lib.rs
iroha_macro/iroha_derive/tests/serialize.rs
iroha_macro/src/lib.rs

Derive macro for `Io` traits replaces boilerplate of writing `From` traits manually.

`Io`, `IntoContract` and `IntoQuery` traits and derive macros.

---

docker/develop/Dockerfile

[DOPS-947]: Fix Iroha develop `dockerfile`.
We have got broken CI process for Iroha. The problem was in `pip` unsatisfied dependency. The problem has been solved. Also, the solution has been tested.
None

[DOPS-947] Python dependencies have been fixed

---

Cargo.toml
iroha_network/Cargo.toml
iroha_network/src/lib.rs

Extracts TCP and network request logic into a separate crate called `network`. Completes RH2-51 issue.
Less code duplication. Unified networking in all iroha crates.
Usage examples are shown as tests in the root `lib.rs` file of `network` crate.

Networking

---

test/fuzzing/find_fuzz.cpp

mock query executor creator lacked method expectation, which returned nullptr by default.

fixed find fuzz test

---

.github/workflows/rust.yml
iroha/src/asset.rs
iroha/src/block.rs
iroha/src/isi.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/merkle.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/src/client.rs
iroha_network/src/lib.rs

Initial validation logic for transactions.

---

iroha/Cargo.toml
iroha/src/asset.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/query.rs
iroha/src/torii.rs
iroha/src/wsv.rs
iroha_client/Cargo.toml
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/client.rs
iroha_macro/iroha_derive/src/lib.rs
iroha_macro/iroha_derive/tests/serialize.rs
iroha_network/Cargo.toml
iroha_network/src/lib.rs

Usage of iroha_network in torii and client.

---

test/module/irohad/pending_txs_storage/pending_txs_storage_test.cpp

Refactor pending txs storage test.
Jira ticket IR-573.
Improves readability. DRY.
There is still some code repetitive in terms of creating expected response, could possibly be  improved by adopting builder pattern.

Refactor pending txs storage test.

---

iroha/src/lib.rs
iroha/src/peer.rs
iroha_network/src/lib.rs

Introduces p2p module based on iroha_network.

Initial p2p module structure

---

docker/release/Dockerfile

[Maintenance]: Fix Iroha release `dockerfile`.
The `apt` cache is updated after adding of test PPA repository.
None

[Maintenance] Fix/python dependencies

---

iroha/src/lib.rs
iroha/src/main.rs
iroha/src/tx.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_network/src/lib.rs

Fixed bug with missing byte in u128 scale encoded TCP packet.

---

iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/tx.rs

Periodically forward pending transactions.

forward pending transactions

---

iroha/src/lib.rs

Fixes the bug that would create blocks with empty vector of transaction

fixes rh2-59

---

iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/src/client.rs

Changes in Transactions API - better creation and work with requests.

---

iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/src/client.rs

Blockchain entity was removed to clean up codebase. 

---

.github/workflows/rust.yml
iroha/src/asset.rs
iroha/src/crypto.rs
iroha/src/query.rs

Implementation of Iroha signature.

---

iroha/src/crypto.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/Cargo.toml
iroha_client/src/client.rs
iroha_network/src/lib.rs

Fixed bug in Request deserialization.

---

iroha/src/crypto.rs
iroha/src/tx.rs

Verify signatures on transaction acceptence.

---

.github/workflows/rust.yml
CONTRIBUTING.rst
iroha/src/account.rs
iroha/src/crypto.rs
iroha/src/domain.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/tx.rs
iroha/src/wsv.rs

Validation of transaction instructions on world state view clone before commit to store and test coverage.

---

iroha/src/block.rs
iroha/src/crypto.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/sumeragi.rs

Introduces initial structure of Sumeragi module and also implements a base case of consensus, when everything goes according to plan.

sumeragi initial

---

iroha/src/block.rs
iroha/src/crypto.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/src/client.rs

Crypto functions placed on top of the module and work with ursa signer encapsulated into Signature.

---

iroha/src/block.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/sumeragi.rs

Block sign with timestamp and previous block hash as payload.

---

iroha/src/block.rs
iroha/src/crypto.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/src/client.rs

 Encapsulation of crypto logic inside crypto module.

---

CONTRIBUTING.rst
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/src/client.rs

Encapsulation of network requests handling inside Torii

---

CONTRIBUTING.rst
iroha/src/config.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs

Peers communication via trusted peers list

---

iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/wsv.rs

Add Peer instruction implemented instead of hardcode handling

---

iroha/Cargo.toml
iroha/benches/sumeragi.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs

Integration of sumeragi into the main iroha loop.
Also improves performance of `sort_peers`

Integrates sumeragi

---

iroha/src/lib.rs
iroha_client/benches/torii.rs
iroha_client/tests/transfer_asset.rs

Benchmarks tuning

---

Cargo.toml
iroha/src/domain.rs
iroha/src/lib.rs
iroha/src/main.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/Cargo.toml
iroha_client_cli/README.md
iroha_client_cli/config.json
iroha_client_cli/src/main.rs

Iroha CLI client.

---

iroha/src/account.rs
iroha/src/config.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs

The test now correctly uses 4 peers consensus through sumeragi

Sumeragi basic scenario

---

.dockerignore
Dockerfile
Dockerfile.debug
docker-compose.yml
iroha/src/config.rs
iroha/src/main.rs

Docker packaging of Iroha executable.

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs

 Perfomance optimizations in transaction processing loop

---

.github/workflows/rust.yml
iroha/Cargo.toml
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_network/Cargo.toml
iroha_network/src/lib.rs

Network mock cargo feature

---

iroha/Cargo.toml
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_network/src/lib.rs

Migration to async-std API.

---

iroha/Cargo.toml
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_network/Cargo.toml
iroha_network/src/lib.rs
iroha_network/src/mock.rs

 Mocking module for Iroha Network crate implemented via channels.

---

iroha/Cargo.toml
iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/crypto.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/main.rs
iroha/src/merkle.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_network/src/mock.rs

Transactions and blocks states

---

iroha/benches/validation.rs
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs

Reimplementation of Iroha Special Instructions.

---

iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/wsv.rs

Sumeragi decoupling from Kura with channels

---

.github/workflows/rust.yml
iroha/Cargo.toml
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_network/src/lib.rs
iroha_network/src/mock.rs

Now that we have separated Kura and mock network, we can safely test sumeragi.

Consensus tests with network mock

---

.github/workflows/rust.yml
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/block.rs
iroha/src/config.rs
iroha/src/crypto.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/query.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs

Documentation linting rule.

---

iroha/benches/validation.rs
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/config.rs
iroha/src/domain.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/merkle.rs
iroha/src/peer.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs

 ISI related methods for domain entities. 

---

iroha/src/block.rs
iroha/src/kura.rs

Block header

---

iroha/src/crypto.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha_network/Cargo.toml

Commit timeout handling

---

iroha/benches/validation.rs
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/wsv.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs
iroha_network/Cargo.toml

Reimplementation of Asset model into EC-S-.

---

Cargo.toml
iroha/Cargo.toml
iroha/src/bridge.rs
iroha/src/dex.rs
iroha/src/lib.rs
iroha_substrate/Cargo.toml
iroha_substrate/src/lib.rs

Module for Dex and crates for Bridges.

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/wsv.rs

Iroha Permissions

---

iroha_2_whitepaper.md

Faulty leader cases clarification

---

iroha/src/config.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs

Introduces receipts from leader on getting forwarded transaction. Also handles the case when the leader does not send a receipt.

Transaction Receipt handling

---

.jenkinsci/artifacts.groovy
.jenkinsci/build.groovy
.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/builders/x64-mac-build-steps.groovy
.jenkinsci/builders/x64-win-build-steps.groovy
.jenkinsci/utils/docker-pull-or-build.groovy
.jenkinsci/utils/utils.groovy
Jenkinsfile

Run Linux compiler builds in parallel
- First compiler in the list is used with all passed parameters, such as coverage, image build, and analysis.
- Coverage or analysis is not run with other compilers
- Faster builds
- Multiple redundant builds of Docker image on Dockerfile possible, because different machines are used

CI: parallel builds for Linux compilers

---

shared_model/cryptography/crypto_provider/crypto_signer.cpp

fix compilation on gcc 7.4

---

docs/source/develop/index.rst
docs/source/develop/keys.rst

Some multihash docs
Some data on multihash in Iroha
Might not be enough but something to start with

Docs: Multihash

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/block.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/tx.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs

Injection of Permission checks into OOB ISI.

---

test/framework/integration_framework/fake_peer/behaviour/behaviour.cpp
test/framework/integration_framework/fake_peer/behaviour/behaviour.hpp
test/framework/integration_framework/fake_peer/behaviour/honest.cpp
test/integration/acceptance/add_peer_test.cpp

Testing: fixed fake peer destruction behaviour

---

irohad/network/impl/block_loader_impl.cpp
irohad/network/impl/grpc_channel_builder.hpp
test/integration/grpc_retry_test.cpp

grpc: added default client timeout

---

iroha/src/isi.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/wsv.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/transfer_asset.rs

Initial work with Iroha changes listeners.

---

iroha/Cargo.toml
iroha/src/bridge.rs
iroha/src/crypto.rs
iroha/src/domain.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/wsv.rs

Adds basic Bridge structures and ISI for bridge registration.

Bridge and RegisterBridge ISI

---

iroha/src/kura.rs

[IR-756] Genesis Block functionality for Kura.

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs

Sumeragi Messages in the message module

---

iroha/src/asset.rs
iroha/src/lib.rs
iroha/src/permission.rs
iroha/src/wsv.rs

Add Permission entity with transformation from Instructions.

---

iroha/benches/sumeragi.rs
iroha/src/sumeragi.rs

Introduces NetworkTopology struct

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/bridge.rs
iroha/src/isi.rs
iroha/src/peer.rs
iroha/src/query.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs

Replacement of hardcoded bridge model with origin Iroha model.

---

iroha/benches/sumeragi.rs
iroha/src/config.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/test_config.json
iroha_client/tests/transfer_asset.rs

Block creation timeout handling

---

iroha/docs/references/glossary.md
iroha/src/event.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/wsv.rs

[IR-754] Iroha Special Instructions related to Iroha events.

---

iroha/benches/sumeragi.rs
iroha/src/sumeragi.rs

[IR-766] Separates construction from initialization in NetworkTopology

---

iroha/src/event.rs
iroha/src/sumeragi.rs

TransactionReceipt validation refactoring

---

iroha/src/sumeragi.rs

Minimum votes logic inside NetworkTopology

---

CONTRIBUTING.md
iroha/Cargo.toml
iroha/benches/sumeragi.rs
iroha/benches/validation.rs
iroha/docs/guides/develop-iroha-module.md
iroha/docs/references/glossary.md
iroha/src/block.rs
iroha/src/bridge.rs
iroha/src/config.rs
iroha/src/crypto.rs
iroha/src/event.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/merkle.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/Cargo.toml
iroha_client/src/client.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/Cargo.toml
iroha_client_cli/src/main.rs
iroha_macro/Cargo.toml
iroha_network/Cargo.toml

Crates preparation for publish.

---

iroha/src/block.rs
iroha/src/crypto.rs
iroha/src/event.rs
iroha/src/sumeragi.rs
iroha/src/wsv.rs

Signature validation in Sumeragi messages

---

iroha/src/config.rs
iroha/src/crypto.rs
iroha/src/sumeragi.rs

Replace [u8;64] type alias with PrivateKey struct.

---

iroha/src/bridge.rs

Bridge: register external asset

---

iroha/src/sumeragi.rs

Validates the block before signing in Sumeragi

---

iroha/src/sumeragi.rs

Sumeragi: peers in set b related TODO fixes

---

iroha/src/account.rs
iroha/src/bridge.rs
iroha/src/permission.rs

Also added:
- AddSignatory ISI
- CanAddSignatory permission

Bridge clients registration

---

iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/permission.rs
iroha/src/wsv.rs

Demint ISI

---

iroha/src/lib.rs
iroha/src/maintenance.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client/tests/check_health.rs

Simple Maintenance endpoint.

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/bridge.rs
iroha_client/tests/transfer_asset.rs

Bridge: manual external transfers handling

---

iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/merkle.rs
iroha/src/sumeragi.rs

Block chaining

---

iroha/src/sumeragi.rs

Not enough votes Sumeragi test 

---

iroha/Cargo.toml
iroha/src/lib.rs
iroha/src/maintenance.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client/tests/scrape_metrics.rs

Simple metrics endpoint.

---

iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/sumeragi.rs
iroha/src/wsv.rs

AddPeer ISI

---

irohad/synchronizer/impl/synchronizer_impl.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp

- when a block loader connection fails, we retry with the same peer, if previous attempt applied successfully.
- if something was committed in synchronizer, pass the commit event to pipeline
hopefully completes fixing the problem addressed in #518
ugly tests need refactoring
the change in synchronizer could be somehow rewritten with rxcpp tools to look nicer

fixed synchronization

---

iroha/Cargo.toml
iroha/src/asset.rs
iroha/src/bridge.rs
iroha/src/domain.rs
iroha/src/event.rs
iroha/src/lib.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/Cargo.toml
iroha_client/src/client.rs
iroha_client/tests/subscribe_to_changes.rs
iroha_network/src/lib.rs
iroha_network/tests/connect.rs

Connect to Iroha functionality.

---

iroha/docs/uml/block_sync/activity.puml
iroha/docs/uml/block_sync/sequence.puml

Block synchronization: diagrams

---

iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/merkle.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs

- Transactions are validated on Validating Peers now, invalid transactions are dropped.
- Corrected bug in proxy tail, when it considered the block that it originally received to be true and put signatures into it. Now it has a hashmap with the votes.
- Transactions pipeline can now easily integrate merkle tree logic - the block logic was corrected to allow that.

Block validation corrections

---

iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client/src/config.rs
iroha_network/src/lib.rs

Configuration of connect functionality.

---

iroha/benches/validation.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/src/client.rs
iroha_client/src/config.rs

Transactions TTL

---

iroha/src/lib.rs
iroha/src/sumeragi.rs

Moves Sumeragi message handling into message impl

---

irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/postgres_command_executor.hpp
shared_model/backend/protobuf/CMakeLists.txt
shared_model/backend/protobuf/commands/impl/proto_call_model.cpp
shared_model/backend/protobuf/commands/impl/proto_command.cpp
shared_model/backend/protobuf/commands/proto_call_model.hpp
shared_model/interfaces/CMakeLists.txt
shared_model/interfaces/commands/call_model.hpp
shared_model/interfaces/commands/command.hpp
shared_model/interfaces/commands/command_variant.hpp
shared_model/interfaces/commands/impl/call_model.cpp
shared_model/interfaces/commands/impl/command.cpp
shared_model/interfaces/permissions.hpp
shared_model/schema/commands.proto
shared_model/schema/primitive.proto
shared_model/validators/transaction_validator.hpp
test/module/shared_model/validators/field_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

This adds CallModel class proto files and interfaces.
Implementation of client side being able to add new data models.
The functions added in ametsuchi and validator are basically to avoid error in building not ready for function call.

Client Iface and proto class: CallModel command

---

.github/workflows/rust.yml
iroha/Cargo.toml
iroha/src/event.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/Cargo.toml
iroha_network/Cargo.toml
iroha_network/src/lib.rs
iroha_network/src/mock.rs

Events sending of transactions and blocks.

---

docs/source/getting_started/index.rst
docs/source/maintenance/restarting_node.rst

Added references to migration scripts to the docs regarding node restart with existing WSV
Fixed Asciinema videos on getting started
Better docs
Who knows

Docs: Fixed Getting Started asciinema and Added References Regarding WSV Restart 

---

iroha_client/src/client.rs
iroha_client/src/config.rs
iroha_client/tests/subscribe_to_changes.rs

IR-802 Subscription to blocks statuses changes. 

---

iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs

eprintln to log macro

---

libs/crypto/keys_manager_impl.cpp
shared_model/cryptography/crypto_provider/crypto_signer.cpp
test/module/libs/crypto/keys_manager_test.cpp

keypair loader now verifies the keypair using generic signer. also added tests for it using different crypto provider.
functional ed25519/sha2

fixed keypair validation

---

iroha/src/block.rs
iroha/src/kura.rs
iroha/src/merkle.rs
iroha/src/tx.rs

Merkle tree root hash for block transactions

---

docs/source/requirements.txt

Updated Alabaster theme version to (hopefully) fix RTD builds
Might fix the problem with build of versions
Might not help - we wouldn't know before we add it to RTD

Docs: RTD Theme Fix

---

.github/workflows/iroha2master.yml

Update Github Actions workflows.

---

.github/workflows/iroha2master.yml

Fixes in master workflow.

---

iroha/src/event.rs
iroha/src/torii.rs
iroha_network/src/lib.rs

Event connections

---

iroha/src/event.rs
iroha_client/tests/subscribe_to_changes.rs

Events filter

---

iroha/src/event.rs
iroha_client/src/client.rs
iroha_client/src/lib.rs
iroha_client/tests/subscribe_to_changes.rs
iroha_client_cli/src/main.rs

Events cli improvements

---

docs/source/guides/monitor-iroha-peer.md
docs/source/index.rst
iroha_client_cli/src/main.rs

Iroha Monitor Guide and CLI.

---

docs/source/develop/api/queries.rst

[IR-855](https://jira.hyperledger.org/browse/IR-855)

Docs: fixed GetEngineReceipts description

---

.github/workflows/iroha2master.yml

Bench master workflow fix

---

cmake/Modules/Findursa.cmake

[IR-839](https://jira.hyperledger.org/browse/IR-839)
removed a file that has no generation rules from dependencies of ursa. 
should fix some builds (Ninja)

ursa build deps fix

---

iroha_client_cli/src/main.rs

Replaces hardcoded config path with cli param

---

.github/workflows/iroha2master.yml
.github/workflows/iroha2pr.yml
docs/source/features/bridge.feature
docs/source/guides/write-custom-instruction.md
docs/source/references/glossary.md
docs/source/tutorials/mint-your-first-asset.md
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/query.rs
iroha_client/Cargo.toml
iroha_client/src/client.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/single_config.json

Iroha custom ISI guide and Cucumber tests.

---

.github/CODEOWNERS

CODEOWNERS for Iroha 2 branches

---

test/framework/make_peer_pointee_matcher.hpp
test/integration/acceptance/fake_peer_fixture.hpp
test/module/irohad/ametsuchi/wsv_query_test.cpp

Fix build with Ninja generator. Transitive header include in wsv_query_test required unneeded files which are generated, and are not depended on by the test.
Build works
None

Fix ninja build in wsv_query_test

---

docs/source/features/exchange.feature

DEX Features.

---

docs/source/features/bridge.feature
docs/source/features/exchange.feature
docs/source/features/queries.feature
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/query.rs
iroha/src/wsv.rs
iroha_client/Cargo.toml
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs
iroha_client_no_std/tests/transfer_asset.rs

IR-860: Iroha Queries and tests. 

---

iroha_crypto/src/lib.rs
iroha_crypto/src/multihash.rs
iroha_crypto_cli/src/main.rs

Secp256k1 keypair support

---

iroha_crypto/src/lib.rs
iroha_crypto_cli/src/main.rs

Print generated keypair as json

---

iroha/README.md
iroha_crypto_cli/README.md

README updates for key generation

---

docs/source/references/glossary.md
docs/source/references/isi.md
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/bridge.rs
iroha/src/domain.rs
iroha/src/event.rs
iroha/src/isi.rs
iroha/src/peer.rs
iroha/src/permission.rs
iroha/src/query.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/tests/tx_rollback.rs

[IR-868] Support transactions rollback\commit

---

docs/source/develop/api/commands.rst

Caller in callEngine is an account id and not a hex string.
Documentation is fixed.
No

fix docs comment Caller in callEngine

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/lib.rs
iroha/src/query.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client_no_std/src/account.rs
iroha_client_no_std/src/asset.rs
iroha_client_no_std/src/client.rs
iroha_client_no_std/src/query.rs
iroha_client_no_std/tests/add_asset.rs
iroha_client_no_std/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client_no_std/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client_no_std/tests/high_load_transfer.rs
iroha_client_no_std/tests/transfer_asset.rs
iroha_crypto/src/lib.rs

Also fixes a bug with signature verification.

Introduces SignedQueryRequest

---

.github/workflows/iroha2master.yml
iroha/benches/validation.rs
iroha/src/lib.rs
iroha/src/permission.rs

Also fixes a bug with tarpauline segfault.

Fixes tx validation errors during benchmark tests

---

docs/source/build/index.rst
docs/source/develop/api/queries.rst

Docs: query ordering

---

.github/workflows/iroha2master.yml
README.md

1. Replaces tarpaulin with grcov (because of tarpaulin being unstable and periodically failing with segfaults)
2. Publish test coverage report to codecov.io
The issue https://github.com/xd009642/tarpaulin/issues/190 with tarpaulin segfaults has been said to be fixed several times, but there were always people for whom it did not work, therefore I suggest to switch to grcov.

Test coverage pipeline improvements 

---

iroha_client/benches/torii.rs

1. Disabled logging in benchmarks
2. Added success ratio assert

Torii Benchmarks improvements

---

.gitignore
CONTRIBUTING.md
Cargo.toml
iroha_client/Cargo.toml
iroha_crypto/src/lib.rs
iroha_data_model/Cargo.toml
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_dsl/Cargo.toml
iroha_dsl/src/lib.rs

[IR-875] Implement DSL prototype

---

docker-compose-single.yml
docker-compose.yml
iroha/config.json
iroha/src/config.rs
iroha/src/init.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/tests/test_config.json
iroha_client/tests/single_config.json
iroha_client/tests/test_config.json
iroha_client_cli/tests/test_config.json

Initial domains improvements

---

iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha_client/src/client.rs

It is done to better fit our current tx pipeline.

Refactors transaction stages

---

docker/develop/Dockerfile
example/data_models/test_kv/__init__.py
example/data_models/test_kv/irohad.conf
example/data_models/test_kv/kv_schema.proto
example/data_models/test_kv/test_send_cmd.py
irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/data_models/CMakeLists.txt
irohad/ametsuchi/data_models/data_model.hpp
irohad/ametsuchi/data_models/data_model_python.cpp
irohad/ametsuchi/data_models/data_model_python.hpp
irohad/main/CMakeLists.txt
irohad/main/iroha_conf_literals.cpp
irohad/main/iroha_conf_literals.hpp
irohad/main/iroha_conf_loader.cpp
irohad/main/iroha_conf_loader.hpp
irohad/main/irohad.cpp
shared_model/interfaces/CMakeLists.txt
shared_model/interfaces/common_objects/data_model_id.hpp
shared_model/interfaces/common_objects/impl/data_model_id.cpp
vcpkg/VCPKG_HEAD_DEPS_LIST

this adds the `DataModel` interface that represents a modular data model module, an implementation of it for Python modules and a sample python module.
this will help building data model registry

Modular Data Models: python adapter

---

docs/source/develop/api/commands.rst
irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/postgres_setting_query.cpp
irohad/ametsuchi/impl/postgres_setting_query.hpp
irohad/ametsuchi/impl/setting_query.cpp
irohad/ametsuchi/setting_query.hpp
irohad/main/application.cpp
shared_model/builders/protobuf/builder_templates/transaction_template.hpp
shared_model/validators/field_validator.cpp
shared_model/validators/field_validator.hpp
shared_model/validators/protobuf/proto_block_validator.cpp
shared_model/validators/protobuf/proto_command_validator.cpp
shared_model/validators/protobuf/proto_query_validator.cpp
shared_model/validators/protobuf/proto_transaction_validator.cpp
shared_model/validators/transaction_validator.hpp
shared_model/validators/validators_common.cpp
shared_model/validators/validators_common.hpp
test/integration/acceptance/transfer_asset_test.cpp
test/module/irohad/common/validators_config.hpp
test/module/shared_model/validators/batch_validator_test.cpp
test/module/shared_model/validators/field_validator_test.cpp

originally this stateful check was implemented in stateless validator (#133), which introduced design difficulties and even a bug ([IR-867](https://jira.hyperledger.org/browse/IR-867)). here it is reworked as a stateful check. relevant code is reverted.

Fix: TransferAsset description stateful validation

---

.jenkinsci/builders/x64-mac-build-steps.groovy
Jenkinsfile
cmake/Modules/Findursa.cmake
goSrc/src/vmCaller/CMakeLists.txt
goSrc/src/vmCaller/iroha/char_buffer.go
goSrc/src/vmCaller/iroha/commands.go
goSrc/src/vmCaller/iroha/storage.go

Enable Ursa and Burrow builds on Mac CI
Automatically test that there are no issues regarding Ursa and Burrow on Mac
None

Infrastructure: enable Ursa and Burrow builds on Mac CI

---

Dockerfile
Dockerfile.debug

This patches the Dockerfile to include symlinks that prevent the error **error while loading shared libraries: libssl.so.10: cannot open shared object file:** when running docker-compose
Iroha2 starts on docker-compose.
I'm not sure why this may not be happening to other devs, because libssl.so.1.0.0 was replaced with libssl.so.1.1 according to the following thread https://askubuntu.com/questions/1173587/e-package-libssl1-0-0-has-no-installation-candidate
Whichever module is using libssl.so.1.0.0 should probably be updated to use libssl.so.1.1
I don't believe this is an issue with my local computer but rather with the base image version that is being used in the Dockerfile.

Patched libssl.so.1.0.0 with symlink

---

Cargo.toml
iroha_http_server/Cargo.toml
iroha_http_server/src/lib.rs
iroha_network/Cargo.toml

Introduces http server crate

---

iroha_crypto/Cargo.toml
iroha_crypto/src/lib.rs
iroha_crypto/src/multihash.rs
iroha_crypto_cli/src/main.rs

Adds BLS signatures support

---

iroha_http_server/Cargo.toml
iroha_http_server/src/lib.rs

Also
1. Adds HttpResponse::ok()
2. Adds HttpResponse::upgrade_required(..)
3. Fixes consume bytes TODO

Url query params parsing

---

.jenkinsci/text-variables.groovy
.jenkinsci/utils/vars.groovy
Jenkinsfile
docker/develop/Dockerfile
docker/release/Dockerfile
docs/source/build/index.rst

Bump Ubuntu version in Dockerfiles to prevent build issue like this https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-688/1/pipeline
>undefined reference to `__wrap_memcpy'
Build works, and no external repos
None

Dockerfiles: bump Ubuntu to 20.04

---

iroha_client_cli/src/main.rs

Implementation transfer isi for iroha_CLI
Possible to use "Transfer" isi with iroha_CLI

Implementation transfer isi to Iroha_CLI

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/burrow_vm_caller.cpp
irohad/ametsuchi/impl/burrow_vm_caller.hpp
irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/vm_caller.hpp
test/integration/executor/call_engine_test.cpp
test/integration/executor/get_engine_receipts_test.cpp
test/module/irohad/ametsuchi/mock_vm_caller.hpp

Port https://github.com/hyperledger/iroha/pull/641

Ametsuchi: remove sql dependency from VmCaller

---

README.md

Added Katacoda scenario link to README
Might be used by the community
Iroha version might get outdated?

Docs: Adding katacoda link to README among other resources

---

docs/source/deploy/index.rst
docs/source/index.rst

This PR adds a warning on the main documentation page and a security notice on Deploy index page. All to make people aware of the possible issue with Socket exhaustion issue (?)
Informed decisions 
If this ever gets fixed, we'll need to get rid of those ugly warnings
Fix this issue :(

Docs: Add Warning About GRPC Issue

---

docs/source/develop/keys.rst
docs/source/getting_started/python-guide.rst

Added examples of how to create key pair (Ursa and no-Ursa) using python lib. 
People will know how to create keys
¯\_(ツ)_/¯

Documentation: Python Examples for Key Pair Creation

---

CONTRIBUTING.rst
README.md
docs/source/build/index.rst

Small fixes in the docs: 
- links to katacoda and l10n (in README and CONTRIBUTING)
- build command fix
Docs ready for release
Still need to finish l10n repo

Docs: Iroha v1 Doc fixes

---

iroha_client/Cargo.toml
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs

Signed-off-by: 武宮誠 <mtakemiya@tennodou.local>
Update cucumber_rust lib

update the cucumber_rust lib

---

.jenkinsci/build.groovy

Jenkins warning plugin is deprecated, we should use [Warnings Next Generation](https://plugins.jenkins.io/warnings-ng/)
fix ccpcheck report 
none
https://jenkins.soramitsu.co.jp/job/iroha/job/iroha-hyperledger/job/PR-722/4/cppcheck/

[fix] cppCheck

---

iroha/src/block.rs
iroha/src/tx.rs

Removes mutable WSV references for validation

---

iroha/src/block_sync.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/wsv.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_crypto/src/lib.rs
iroha_logger/src/lib.rs
iroha_network/src/lib.rs

- Added info level logs to consensus
- Marked network communication logs as trace level
- Removed block vector from WSV as it is a duplication and it showed all the blockchain in logs
- Set info log level as default
Fixes bug reported in [IR-895](https://jira.hyperledger.org/browse/IR-895) and also improves logging in general.

Logging level improvements

---

iroha/benches/sumeragi.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/merkle.rs
iroha/src/query.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs

Wraps Hash in a struct
- Better hex Display
- Better type checking
None

Wraps Hash in a struct

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr.yml
.github/workflows/iroha2.yml
iroha_client/tests/multiple_blocks_created.rs

- long tests only ran on PR into iroha2
- publish docker images only from iroha2
None

Adds support for iroha2 branch in CI pipeline

---

docs/source/build/index.rst

Signed-off-by: Sara <sara@Sara.Sara>
https://jira.hyperledger.org/browse/IR-924
Building Iroha with Burrow and without GO doesn't work.
Added a note about the need to install GO. 
Better docs
None

Docs: Burrow Build Note

---

docs/source/configure/index.rst

Signed-off-by: Sara <sara@Sara.Sara>
In https://github.com/hyperledger/iroha/pull/705 we introduced the option of setting up configuration via env variables instead of config file. Here I add some docs for that.
Documented change
Might need some elaboration?

Docs: Add information on Environment Variables configuration

---

docs/source/configure/index.rst

Added a little more info on configuring crypto providers.
More docs
HSM will be added later — should be added into the docs too.

Docs: Crypto Providers Configuration

---

docs/source/configure/index.rst
docs/source/develop/keys.rst

Add note about pattern selection behavior for logger component.
Less confusion with config.
None

Documentation: add note about logging patterns

---

docs/source/maintenance/index.rst
docs/source/maintenance/troubleshooting.rst

Signed-off-by: Andrei Lebedev <lebdron@gmail.com>

Documentation: add troubleshooting section for hard shutdown

---

.gitignore
Cargo.toml
iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/main.rs
iroha/src/permissions.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_data_model/src/lib.rs
iroha_dsl/tests/dsl.rs
iroha_permissions_validators/Cargo.toml
iroha_permissions_validators/src/lib.rs

Introduces permissions framework. Out of box implementations for multiple ISI checks will be added in later PRs.
For more details see [Permissions RFC](https://wiki.hyperledger.org/display/iroha/Permissions)

Permissions

---

.github/workflows/iroha2-add-label.yml

Sets up pipeline to add necessary labels to each iroha2 PR

Adds labels to Iroha2 PRs with Github Actions

---

iroha/src/permissions.rs
iroha_permissions_validators/src/lib.rs

Introduces a builder to better combine various permission checks.

Introduces permissions validator builder

---

iroha/Cargo.toml
iroha/src/config.rs
iroha/src/genesis.rs
iroha/src/lib.rs
iroha/src/main.rs
iroha/tests/genesis.json

`cargo run -- --genesis tests/genesis.json`

Add genesis block's components

---

iroha/benches/validation.rs

Fixes benchmarks for world struct PR

---

iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/permissions.rs
iroha/src/wsv.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/tx_rollback.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_permissions_validators/Cargo.toml
iroha_permissions_validators/src/lib.rs

Unregister ISI permission

---

iroha_permissions_validators/src/lib.rs

Burn, Mint permission checks

---

iroha_client/Cargo.toml
iroha_client/tests/permissions.rs
iroha_permissions_validators/src/lib.rs

Integration test for permissions 

---

iroha/Cargo.toml
iroha/src/event.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/events.rs
iroha_data_model/src/lib.rs

- Provides different statuses and filters for pipeline (Transaction, Block) and data (Account, Asset, etc.) events.
- Web Socket connection for events introduced.
- Events moved into `iroha_data_model`.

Pipeline and Data events separation

---

iroha/src/block.rs
iroha/src/event.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha_client/src/client.rs
iroha_client/src/config.rs
iroha_client/src/http_client.rs
iroha_client/tests/events.rs
iroha_client/tests/permissions.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/events.rs

Pipeline events are sent

---

iroha_client/benches/torii.rs

Account config benchmarks fix

---

iroha/benches/validation.rs
iroha/src/expression.rs
iroha/src/genesis.rs
iroha/src/isi.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/permissions.rs
iroha/tests/genesis.json
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/events.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/expression.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_dsl/tests/dsl.rs
iroha_permissions_validators/src/lib.rs

Integrates expressions and ISIs

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/expression.rs
iroha/src/query.rs
iroha/src/torii.rs
iroha/src/world.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_dsl/tests/dsl.rs

- Makes it possible to use queries in expressions.
- For this purpose also makes Queries return a standard Value type instead of custom QueryResult.

Query execution in Expressions

---

docs/source/references/api_spec.md
iroha_data_model/src/expression.rs

The spec for client developers.

Client API spec

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs

Add wait for active peers

---

iroha/src/expression.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/tests/events.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/expression.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs

Updates the transaction pipeline to support conditional MST according to this [RFC](https://wiki.hyperledger.org/display/iroha/Multisignature+transactions).
Client support and API updates will be in the next PR.

Introduces Conditional MST

---

docs/source/develop/api/commands.rst
docs/source/getting_started/python-guide.rst
docs/source/maintenance/add_peer.rst
docs/source/maintenance/index.rst
docs/source/maintenance/restarting_node.rst

Added more information about adding peers
More docs
Need a Troubleshooting section, maybe a full example of a python transaction?

Docs/Add Peer + Minor Fixes

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-pr.yml
Dockerfile.debug
docker-compose.yml
iroha/genesis.json
iroha/src/block.rs
iroha/src/lib.rs
scripts/test_genesis_docker_compose.sh

Signed-off-by: Sonoko Mizuki <sonoko@mizuki.io>

docker-compose using genesis.json

---

iroha/config.json
iroha/src/account.rs
iroha/src/config.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/tests/test_config.json
iroha_client/src/client.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client_cli/Cargo.toml
iroha_client_cli/src/main.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_network/src/lib.rs

Introduces a possibility for clients to submit MST.

Client API support for MST

---

iroha_client/tests/account_with_multiple_signatories.rs

Introduces a test for a scenario where new signatory is added to account and the next transaction is signed by this signatory.

Adds test for account with multiple signatories

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-pr.yml

The Iroha build became useless as it is now done in docker image itself. So the CI only builds the client cli which is used in tests.

Removes unnecessary full Iroha build in CI docker test 

---

iroha/src/account.rs
iroha_data_model/src/lib.rs

Sets default signature condition in parity scale codec format.

Default signature check condition for account

---

docker-compose-single.yml

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>
Add genesis option for docker-compose-single.yml

add genesis for docker-compose-single.yml

---

.github/workflows/iroha2-dev-pr.yml
docker-compose-single.yml
scripts/cleanup_iroha2_java_api.sh
scripts/test_genesis_docker_compose.sh
scripts/test_iroha2_java_api.sh

GitHub iroha2 java api check

---

shared_model/backend/protobuf/common_objects/signature.hpp

Segfault fixup on signature zombie-object.

Segfault fixup

---

.github/workflows/iroha2-dev-pr.yml
iroha/benches/validation.rs
iroha/src/config.rs
iroha/src/expression.rs
iroha/src/permissions.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_client/benches/torii.rs
iroha_client/tests/account_with_multiple_signatories.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/events.rs
iroha_client/tests/genesis_submission_with_offline_peers.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_network/tests/connect.rs
iroha_permissions_validators/src/lib.rs
iroha_substrate/src/lib.rs

Fix warning of clippy on runs like:
```
$ cargo clippy --tests
$ cargo clippy --tests --all-features
$ cargo clippy --benches
$ cargo clippy --benches --all-features
```
Remove unnecessary clones on tests on benchmarks.
Change `iterator.find(closure).is_some()` to `iterator.any(closure)`.

Fix clippy tests and benches warnings

---

iroha/benches/validation.rs
iroha/src/genesis.rs
iroha/src/query.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs

Fixup todo removing `Verify` and `Accept` traits and replacing them with `TryFrom`.

Replaced Verify and Accept traits with TryFrom

---

iroha_data_model/src/lib.rs

Add documentation to `BlockTime` and `CommitTime` variants of `Parameter`.

Add docs to block time and commit time parameters

---

CONTRIBUTING.md

Adds some of the rules that were used by maintainers but not added to the guide.

Updates contributing guide

---

iroha/src/block.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/tests/unstable_network.rs
iroha_crypto/src/lib.rs

1. Introduces transaction gossiping, not to loose transactions in unstable network
2. Shows a test scenario with unstable network that does not lose txs
3. Fixes several bugs related to unnecessary change views in Sumeragi, by checking the state in messages.
4. Also fixes a repeated transaction attack vulnerability in the process.

Gossip transactions

---

.github/CODEOWNERS

Add i1i1 to code owners

---

iroha_data_model/src/events.rs
iroha_data_model/src/expression.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_macro/iroha_derive/Cargo.toml
iroha_macro/iroha_derive/src/lib.rs

This derive macro is used for making `From<Variant>` trait for enums.

Add FromVariant macro and cleanup codebase

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_gate_impl.hpp
irohad/main/application.cpp
irohad/main/impl/consensus_init.cpp
irohad/main/impl/consensus_init.hpp
test/module/irohad/consensus/yac/yac_gate_test.cpp

Handle case when votes for the next round are received before actually voting.
No node crash in the described case.
None

Yac: do not consider next round as Future

---

.github/workflows/iroha2-pr.yml
iroha/benches/sumeragi.rs
iroha/src/block_sync.rs
iroha/src/genesis.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/unstable_network.rs

Shuffle topology at change view if more than N shifts were already performed without a result.
Relates to [Change View improvements RFC](https://wiki.hyperledger.org/display/iroha/Change+View+Drawback+in+Sumeragi)

Topology shuffle at change view

---

iroha/src/sumeragi.rs
iroha_client/Cargo.toml
iroha_client/tests/unstable_network.rs

Fixes commit timeout not being sent in 4 peer network

---

iroha/benches/validation.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/query.rs
iroha/src/world.rs
iroha_client/benches/torii.rs
iroha_client/tests/account_with_multiple_signatories.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/events.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/query.rs
iroha_dsl/tests/dsl.rs
iroha_permissions_validators/src/lib.rs

Simplifies register and unregister ISIs.
After this there will be less duplication and therefore less space for errors for client library developers.

Simplifies register and unregister ISIs

---

iroha/genesis.json
iroha/tests/genesis.json
iroha_client/tests/genesis.json
iroha_client/tests/unstable_network.rs

The destination was removed from register ISI in previous commits.

Removes outdated lines from genesis files

---

iroha/src/query.rs
iroha_data_model/Cargo.toml
iroha_data_model/src/query.rs

Replace timestamp with typesafe wrapper

---

docker-compose-single.yml
docker-compose.yml
docs/source/features/instructions.feature
iroha/README.md
iroha/config.json
iroha/genesis.json
iroha/src/config.rs
iroha/tests/genesis.json
iroha/tests/test_config.json
iroha_client/config.json
iroha_client/tests/genesis.json
iroha_client/tests/single_config.json
iroha_client/tests/test_client_config.json
iroha_client/tests/test_config.json
iroha_client_cli/config.json
iroha_client_cli/tests/test_config.json
iroha_crypto/src/lib.rs
iroha_crypto/src/multihash.rs
iroha_crypto/src/varint.rs
iroha_dsl/tests/genesis.json
iroha_dsl/tests/test_client_config.json
iroha_dsl/tests/test_config.json

It is a bugfix for public key decoding and encoding. Multihash uses Variable length uints. This commits adds varuint.

Add varint encoding decoding

---

docs/source/maintenance/restarting_node.rst
irohad/ametsuchi/block_query.hpp
irohad/ametsuchi/block_storage.hpp
irohad/ametsuchi/impl/flat_file/flat_file.cpp
irohad/ametsuchi/impl/flat_file/flat_file.hpp
irohad/ametsuchi/impl/flat_file_block_storage.cpp
irohad/ametsuchi/impl/flat_file_block_storage.hpp
irohad/ametsuchi/impl/in_memory_block_storage.cpp
irohad/ametsuchi/impl/in_memory_block_storage.hpp
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/postgres_block_query.hpp
irohad/ametsuchi/impl/postgres_block_storage.cpp
irohad/ametsuchi/impl/postgres_block_storage.hpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.hpp
irohad/ametsuchi/key_value_storage.hpp
irohad/ametsuchi/wsv_restorer.hpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/irohad.cpp
irohad/main/startup_params.hpp
test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/integration_test_framework.hpp
test/framework/integration_framework/iroha_instance.cpp
test/framework/integration_framework/iroha_instance.hpp
test/framework/integration_framework/test_irohad.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/mock_block_query.hpp
test/module/irohad/ametsuchi/mock_block_storage.hpp
test/system/irohad_test.cpp

add --drop_state param, param --reuse_state is default
Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>

add wsv restore mode - sync blockstore

---

docker-compose.yml
docs/source/references/api_spec.md
iroha/src/asset.rs
iroha/src/torii.rs
iroha/src/world.rs
iroha/src/wsv.rs
iroha_client/src/client.rs
iroha_client/src/http_client.rs
iroha_client/tests/pagination.rs
iroha_data_model/src/lib.rs

Add pagination

---

iroha/benches/validation.rs
iroha/test_network/src/lib.rs
iroha_client/benches/torii.rs

Fix benchmarks

---

Cargo.toml
iroha_macro/iroha_derive/Cargo.toml
iroha_macro/iroha_derive/src/lib.rs
iroha_version/Cargo.toml
iroha_version/iroha_version_derive/Cargo.toml
iroha_version/iroha_version_derive/src/lib.rs
iroha_version/iroha_version_derive/tests/as_version.rs
iroha_version/iroha_version_derive/tests/json.rs
iroha_version/iroha_version_derive/tests/scale.rs
iroha_version/iroha_version_derive/tests/ui.rs
iroha_version/iroha_version_derive/tests/ui/fail_invalid_range_equal.rs
iroha_version/iroha_version_derive/tests/ui/fail_invalid_range_equal.stderr
iroha_version/iroha_version_derive/tests/ui/fail_invalid_range_less.rs
iroha_version/iroha_version_derive/tests/ui/fail_invalid_range_less.stderr
iroha_version/iroha_version_derive/tests/ui/ok_declare_several_vesrioned.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned_json.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned_scale.rs
iroha_version/src/lib.rs

Introduces message versioning according to [RFC](https://wiki.hyperledger.org/display/iroha/Message+Versioning).

Introduces container versioning primitives

---

.github/issue_template.md

Closes #827 
As we decided to move issues back to GitHub, Issue template needed fixing which is done here 
Issue template that makes sense. 
Still need to rewrite contributions guide if we fully move from Jira to GH Issues

Issue Template Fix

---

.jenkinsci/build.groovy
.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/text-variables.groovy
.jenkinsci/utils/doxygen.groovy
Jenkinsfile

Rename `master` branch to `main`
No
Need to changes habits.

[DOPS-1289] Rename master branch

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2.yml
iroha_network/src/lib.rs

Fix nightly version for iroha-dev builds

---

Cargo.toml
iroha/src/account.rs
iroha/src/asset.rs
iroha/src/block_sync.rs
iroha/src/domain.rs
iroha/src/expression.rs
iroha/src/isi.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha_client/src/client.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/events.rs
iroha_data_model/src/lib.rs
iroha_error/Cargo.toml
iroha_error/iroha_error_macro/Cargo.toml
iroha_error/iroha_error_macro/src/display.rs
iroha_error/iroha_error_macro/src/error.rs
iroha_error/iroha_error_macro/src/lib.rs
iroha_error/iroha_error_macro/tests/error/01-basic-test.rs
iroha_error/iroha_error_macro/tests/error/02-fail-debug.rs
iroha_error/iroha_error_macro/tests/error/03-unnamed-field-variant.rs
iroha_error/iroha_error_macro/tests/trybuild.rs
iroha_error/src/lib.rs

Add derive(Error) for enums

---

iroha/src/torii.rs
iroha_data_model/src/lib.rs

Fixes the cases when pagination may unnecessarily through errors, now returns empty collections instead.

Infallible pagination

---

irohad/main/CMakeLists.txt
irohad/main/impl/subscription.cpp
irohad/main/subscription.hpp

Creates Subscription engine object to use in project as notification transport system.

Subscription engine singleton

---

docs/source/iroha_2_whitepaper.md

Whitepaper versioning description

---

iroha/Cargo.toml
iroha_crypto/Cargo.toml
iroha_data_model/Cargo.toml
iroha_macro/Cargo.toml
iroha_macro/iroha_derive/Cargo.toml
iroha_network/Cargo.toml
iroha_version/Cargo.toml
iroha_version/iroha_version_derive/Cargo.toml
iroha_version/iroha_version_derive/src/lib.rs

According to the [changelog](https://github.com/paritytech/parity-scale-codec/blob/master/CHANGELOG.md) there should not be any changes in the codec itself, so the client API should stay the same.

Upgrades SCALE version to 2

---

iroha/Cargo.toml
iroha/src/query.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_data_model/Cargo.toml
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_http_server/Cargo.toml
iroha_http_server/src/lib.rs
iroha_version/Cargo.toml
iroha_version/iroha_version_derive/src/lib.rs
iroha_version/iroha_version_derive/tests/json.rs
iroha_version/iroha_version_derive/tests/scale.rs
iroha_version/src/lib.rs

Change api of endpoints for http server. Now endpoint can have types like:
``` rust
async fn handle_instructions(
State,
TryFrom<PathParams>,
TryFrom<QueryParams>,
TryFrom<HttpRequest>,
) -> TryInto<HttpRequest>;
```
where all arguments and return type as an error have something which implements `HttpResponseError` trait. It is basically nice decoupling of `Into<HttpRequest>` which you can partly change and it will do. For example you can change only status code and body output, there are exactly 2 methods for http errors.
As for torii many endpoint errors are converted to enum which implements `HttpResponseError`. It reduces conversions of types in endpoints.

Rewrite iroha_http_server and rework torii errors

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/event.rs
iroha/src/genesis.rs
iroha/src/isi.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/world.rs
iroha_client/src/client.rs
iroha_client/src/http_client.rs
iroha_crypto/src/lib.rs
iroha_crypto/src/multihash.rs
iroha_crypto/src/varint.rs
iroha_data_model/src/expression.rs
iroha_data_model/src/lib.rs
iroha_error/src/lib.rs
iroha_http_server/src/lib.rs
iroha_network/src/lib.rs
iroha_version/iroha_version_derive/src/lib.rs

Substitute Error::msg with error macro

---

iroha/src/event.rs
iroha/src/query.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_version/iroha_version_derive/src/lib.rs
iroha_version/iroha_version_derive/tests/as_version.rs

Add into_v* for versioning

---

iroha/src/expression.rs
iroha_data_model/src/expression.rs

Add mul,div,mod,raise_to expressions

---

.github/workflows/iroha2-dev-pr.yml

Fixup ci linting repetitions.

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/block.rs
iroha/src/isi.rs
iroha/src/permissions.rs
iroha/src/query.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_client/tests/account_with_multiple_signatories.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/genesis_submission_with_offline_peers.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/unstable_network.rs
iroha_data_model/src/events.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
scripts/test_docker_compose.sh
scripts/test_genesis_docker_compose.sh

- Support for key-value instructions in asset
- Asset types as an enum
- Overflow vulnerability in asset ISI fix

Updates asset structure

---

iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/genesis.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/merkle.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/wsv.rs
iroha_data_model/src/lib.rs
iroha_http_server/src/lib.rs
iroha_permissions_validators/src/lib.rs
iroha_version/iroha_version_derive/src/lib.rs
iroha_version/iroha_version_derive/tests/json.rs
iroha_version/iroha_version_derive/tests/scale.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_several_vesrioned.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned_json.rs
iroha_version/iroha_version_derive/tests/ui/ok_declare_versioned_scale.rs
iroha_version/src/lib.rs

Add versioning of blocks

---

iroha/genesis.json
iroha/src/account.rs
iroha/src/isi.rs
iroha/src/query.rs
iroha/tests/genesis.json
iroha_client/tests/genesis.json
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_dsl/tests/genesis.json

Introduces key-value metadata support for Account

---

CONTRIBUTING.md

Fix typo in URL to Iroha 2 community in Telegram

Fix typo in URL to Iroha 2 community in Telegram

---

Dockerfile
Dockerfile.debug
iroha/config.json
iroha/src/config.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/test_network/src/lib.rs
iroha/tests/test_config.json
iroha/tests/test_trusted_peers.json
iroha/trusted_peers.json
iroha_client/benches/torii.rs
iroha_client/tests/account_with_multiple_signatories.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/events.rs
iroha_client/tests/pagination.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/test_config.json
iroha_client/tests/test_trusted_peers.json
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_client/tests/unstable_network.rs
iroha_dsl/tests/dsl.rs
iroha_dsl/tests/test_config.json
iroha_dsl/tests/test_trusted_peers.json

Re PR of https://github.com/hyperledger/iroha/pull/790

Separate trusted_peers from config.json

---

CONTRIBUTING.rst

Docs: Contributing Guide Fix

---

docs/source/develop/api/queries.rst

Signed-off-by: Sara G <sara@Sara.dell>
https://jira.hyperledger.org/browse/IR-960
Correct docs 
Not that I can see

Docs/ Small Fix in Queries

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/expression.rs
iroha_client/src/client.rs
iroha_client_cli/src/main.rs
iroha_crypto_cli/src/main.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_error/iroha_error_macro/src/error.rs
iroha_http_server/Cargo.toml
iroha_macro/iroha_derive/src/lib.rs
iroha_macro/iroha_derive/tests/from_variant/02-double-from.stderr
iroha_macro/iroha_derive/tests/from_variant/04-container-from.stderr
iroha_macro/iroha_derive/tests/from_variant/05-struct.stderr
iroha_macro/src/lib.rs
iroha_version/Cargo.toml
iroha_version/iroha_version_derive/Cargo.toml

Jira issue: https://jira.hyperledger.org/browse/IR-1028

Add expressions inside queries

---

.dockerignore
Dockerfile
iroha/src/config.rs
iroha/src/sumeragi.rs
iroha_client/src/client.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs
scripts/metadata.json
scripts/setup_docker_test_env.sh
scripts/test_docker_compose.sh

Introduces transaction metadata

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/config.rs
iroha/src/lib.rs
iroha/src/query.rs
iroha/src/wsv.rs
iroha_client/src/client.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs

Introduces configurable metadata limits

---

iroha/benches/validation.rs
iroha/genesis.json
iroha/src/asset.rs
iroha/src/isi.rs
iroha/src/query.rs
iroha/tests/genesis.json
iroha_client/benches/torii.rs
iroha_client/tests/account_with_multiple_signatories.rs
iroha_client/tests/add_asset.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/events.rs
iroha_client/tests/genesis.json
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client/tests/pagination.rs
iroha_client/tests/permissions.rs
iroha_client/tests/restart_peer.rs
iroha_client/tests/transfer_asset.rs
iroha_client/tests/tx_rollback.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs
iroha_dsl/tests/dsl.rs
iroha_dsl/tests/genesis.json
iroha_permissions_validators/src/lib.rs
scripts/test_docker_compose.sh

Add types for asset definition

---

iroha/benches/validation.rs
iroha/genesis.json
iroha/src/domain.rs
iroha/src/isi.rs
iroha/tests/genesis.json
iroha_client/benches/torii.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/genesis.json
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/multisignature_transaction.rs
iroha_client/tests/permissions.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs
iroha_dsl/tests/dsl.rs
iroha_dsl/tests/genesis.json

Add new primitive for account registration

---

.github/issue_template.md
docs/source/develop/api/commands.rst
docs/source/develop/api/queries.rst
docs/source/getting_started/python-guide.rst
docs/source/maintenance/add_peer.rst
docs/source/maintenance/index.rst

Adds missing commits with docs update from master
Updated documentation
None

Missing docs from master

---

iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs

🦀Rust🦀 1.51 is 🎉released🎉. 🔢Const 😎generics😎 are finally here☝️!
But now 📎clippy📎 ⚠️warnings can 👊break our ci checks😧. But this 👩‍💻fix👨🏻‍🔬 is already here!
👩‍💻Code🧑‍💻 will become in some parts 🧐readable.
Giving too much 💪power💪 to 🚓machines🚓 may end up with 👯us fight to ai🤖.

Fix updated clippy

---

iroha/src/permissions.rs
iroha_permissions_validators/src/lib.rs

https://jira.hyperledger.org/browse/IR-1030
Adds validation of ability to write to metadata. Only if user created them they can change it.

Add validation of permissions for store and restructure of permission validators

---

docs/source/deploy/single.rst
irohad/ametsuchi/impl/postgres_options.cpp
irohad/main/impl/pg_connection_init.cpp

Anyway database initialization required:
```
initdb ~/iroha/noda3_db/
postgres -D ~/iroha/noda3_db/ -d1 -p5432 &
createuser -s iroha_user -p5432
createdb iroha_user -p5432 -Oiroha_user
```
Closes #881

881 no --drop-state flag for first run

---

.jenkinsci/build.groovy
.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/text-variables.groovy
.packer/README.md
.packer/win/scripts/vcpkg_for_multiple_branch.ps1
Jenkinsfile

Remove outdated usages of master branch
Faster builds, since dockerfile won't be compared to the one in master branch
None

Infrastructure: use main branch where required

---

iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha_data_model/src/lib.rs

We already have ddos protection, but forgot to put it in consensus.
We disable attack vector of flooding during consensus
Runtime instruction length check.
https://jira.hyperledger.org/browse/IR-1038

Fix of transaction size check during consensus

---

Cargo.lock
iroha/src/genesis.rs
iroha/src/sumeragi.rs
iroha/test_network/Cargo.toml
iroha/test_network/src/lib.rs
iroha_client/benches/torii.rs
iroha_client/src/client.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/tests.rs
iroha_client/tests/tests/tests/account_with_multiple_signatories.rs
iroha_client/tests/tests/tests/add_asset.rs
iroha_client/tests/tests/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/tests/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/tests/tests/events.rs
iroha_client/tests/tests/tests/genesis_submission_with_offline_peers.rs
iroha_client/tests/tests/tests/multiple_blocks_created.rs
iroha_client/tests/tests/tests/multisignature_transaction.rs
iroha_client/tests/tests/tests/pagination.rs
iroha_client/tests/tests/tests/permissions.rs
iroha_client/tests/tests/tests/restart_peer.rs
iroha_client/tests/tests/tests/transfer_asset.rs
iroha_client/tests/tests/tests/tx_history.rs
iroha_client/tests/tests/tests/tx_rollback.rs
iroha_client/tests/tests/tests/unstable_network.rs

https://jira.hyperledger.org/browse/IR-1008
This pr reworks tests with simple test library. Also removes timeouts and adds polling with timeout.
Tests won't unconditionally fail because of weird environment.
Sometimes tests can be slower, but at least they won't signal false positive breaking of iroha.

Add polling for tests and fix rarely breaking tests

---

Cargo.lock
iroha/Cargo.toml
iroha/docs/src/main.rs
iroha/src/permissions.rs
iroha_config/src/lib.rs
iroha_data_model/src/expression.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs
iroha_permissions_validators/src/lib.rs

Introduces Grantable Permissions based on the Permission Validator framework that we currently have.
It will be possible for users to grant permissions to apply some actions with their data on blockchain. This is a must have for DEX smart contracts for example.
https://jira.hyperledger.org/browse/IR-944
See `iroha_permission_validators::tests::transfer_granted_assets` for an example.

Introduces grantable permissions

---

.github/workflows/iroha2-dev-pr.yml
Cargo.lock
lints.toml
scripts/check_docs.sh

Add doc change check and deny dbg macro in code.
No debug tools in repo will be used. Also we won't forget to generate new docs if config changes.

Ci doc check

---

docs/source/references/config.md
iroha/src/domain.rs
iroha/src/sumeragi.rs
iroha/src/world.rs
iroha/src/wsv.rs
iroha_client/tests/tests/tests.rs
iroha_client/tests/tests/tests/add_account.rs
iroha_client/tests/tests/tests/add_asset.rs
iroha_client/tests/tests/tests/add_domain.rs
iroha_data_model/src/lib.rs

https://jira.hyperledger.org/browse/IR-1036
Added new configuration in wsv crate to limitate length of identifiers in `NewAccount`, `AssetDefinition` and `Domain`. When instruction to create an item is executed, then invoked method `validate_len` that can emit an error if length of id is not in the applicable range.
Users won't be able to create assets, domain and account with too long identifiers
It is crucial to not forget to invoke `validate_len` if we would have another way to apply the items to wsv

Added configuration for string length limits and validation of id's for NewAccount, Domain and AssetDefinition IR-1036

---

irohad/main/subscription.hpp
irohad/subscription/subscriber_impl.hpp
test/module/irohad/subscription/subscription_test.cpp

Additional creation-process checks for subscribers.

[SE] Subscriber::create, deny Subscriber on stack

---

test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp

Signed-off-by: Andrei Lebedev <lebdron@gmail.com>

AmetsuchiTest: add condition for prepared block tests

---

iroha/src/account.rs
iroha/src/isi.rs
iroha/src/permissions.rs
iroha_client/tests/tests/tests/permissions.rs
iroha_data_model/src/events.rs
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_permissions_validators/src/lib.rs

Grant instruction and traits for corresponding specific for Grant permission checks.
Now it will be possible to grant Permission Tokens.
None found.
https://jira.hyperledger.org/browse/IR-944
See `grant_transfer_of_my_assets` test.

Grant Instruction

---

iroha/src/permissions.rs
iroha/src/tx.rs
iroha_permissions_validators/src/lib.rs

Permission Validators use references in checks
It should improve performance as there will be a lot less clones in permission checks.
None found.

Permission Validators use references in checks

---

iroha_network/src/lib.rs

Fixup of iroha-network bug. Now it will always listen on port even if it failed to accept connection.

Iroha network fixup

---

iroha/src/domain.rs

Remove all assets when their definition was removed
This fixes a bug of state inconsistency, where assets would stay even if their definition was removed.

Remove all assets when their definition was removed

---

irohad/main/CMakeLists.txt
irohad/main/impl/async_dispatcher.cpp
irohad/main/impl/subscription.cpp
irohad/main/impl/sync_dispatcher.cpp
irohad/main/subscription.hpp
irohad/subscription/async_dispatcher_impl.hpp
irohad/subscription/dispatcher.hpp
irohad/subscription/subscription_manager.hpp
irohad/subscription/sync_dispatcher_impl.hpp
test/module/irohad/subscription/CMakeLists.txt
test/module/irohad/subscription/subscription_test.cpp

Async dispatcher implementation. Manager now contains IDispatcher reference and we can change it to sync one for tests.

[SE] sync/async dispatchers

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
iroha_network/src/lib.rs

Fix ulimit, make tests on master threaded and increase timeout for iroha_network
There won't be issues with too many opened internet connections and also tests on master will be faster. Added timeout for iroha_network

Fix ulimit, make tests on master threaded and increase timeout for iroha_network

---

iroha_client/tests/tests/tests/permissions.rs
iroha_permissions_validators/src/lib.rs

Adds Grant Instruction and Permission Token ownership checks for all the existing permissions.
Grant logic is supported for all existing operations permission checks.
None found.
https://jira.hyperledger.org/browse/IR-1060

IR-1060 Adds Grant checks for all the existing permissions

---

iroha/src/account.rs
iroha/src/asset.rs
iroha/src/domain.rs
iroha/src/isi.rs
iroha/src/tx.rs
iroha/src/world.rs
iroha_macro/iroha_derive/src/lib.rs

This pr changes api for Execute trait and adds types for errors.
Change of api for Execute removes unnecessary clones of world state view. Errors would allow runtime investigation of errors in future.

Rework of Execute trait for instructions

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2.yml
Dockerfile.crypto_cli

Add push docker images from dev branch
Faster iterations on test stand.

Add push docker images from dev branch

---

Dockerfile
Dockerfile.cli
Dockerfile.crypto_cli
Dockerfile.debug

Updating package name because of ubuntu naming.

Update libssl version

---

Cargo.lock
iroha/Cargo.toml
iroha/src/account.rs
iroha/src/isi.rs
iroha/src/permissions.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/src/world.rs
iroha_data_model/Cargo.toml
iroha_data_model/src/isi.rs
iroha_data_model/src/lib.rs
iroha_permissions_validators/Cargo.toml
iroha_permissions_validators/src/lib.rs

Introduces Roles, which are tags for a group of permission.
The logic is that you can grant a user a role only if you can grant each of the permissions that it comprises of.
Permissioned networks will benefit from native support of roles in Iroha2.
Conditional compilation might introduce bugs which are difficult to detect.
https://jira.hyperledger.org/browse/IR-1023

Introduces Roles

---

iroha/test_network/Cargo.toml
iroha_network/Cargo.toml
iroha_network/src/lib.rs

Add compilation feature for opting test timeout for tests.
No timeouts for tests.

Network timeout fix

---

cmake/dependencies.cmake
irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/command_executor.hpp
irohad/ametsuchi/impl/command_executor.cpp
irohad/ametsuchi/impl/executor_common.cpp
irohad/ametsuchi/impl/executor_common.hpp
irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/impl/rocksdb_command_executor.cpp
irohad/ametsuchi/impl/rocksdb_command_executor.hpp
irohad/ametsuchi/impl/rocksdb_common.hpp
irohad/ametsuchi/impl/rocksdb_specific_query_executor.cpp
irohad/ametsuchi/impl/rocksdb_specific_query_executor.hpp
shared_model/backend/plain/impl/peer.cpp
shared_model/backend/plain/peer.hpp
shared_model/interfaces/common_objects/types.hpp
shared_model/interfaces/impl/permissions.cpp
shared_model/interfaces/permissions.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/rocksdb_common_test.cpp
test/module/vendor/CMakeLists.txt
test/module/vendor/rocksdb_test.cpp
vcpkg/VCPKG_DEPS_LIST

Adds rocksdb initialization and basic functionality.

[RocksDB] db init

---

iroha/src/account.rs
iroha/src/query.rs
iroha/src/world.rs
iroha_data_model/src/lib.rs
iroha_data_model/src/query.rs

Queries for:
1. Account permission tokens
2. All roles
3. Roles of the account
Now we can query these things :)
None found
https://jira.hyperledger.org/browse/IR-1069

Queries for roles and permissions

---

docs/source/maintenance/add_peer.rst
docs/source/maintenance/shepherd.rst

This PR fixes some links described in https://jira.hyperledger.org/browse/IR-1025
Fixed links
The issue also mentions inconsistent dashes in help and in docs and based on information here - https://en.wikipedia.org/wiki/Command-line_interface#Arguments - in Unix-like systems it should be double - dashes there. So will appreciate help in finding the files that describe help for the shepherd.

Docs: Fix Links

---

docs/source/conf.py
docs/source/configure/index.rst
docs/source/requirements.txt

Added more information about Iroha configuration parameters. Also fixed links in "Contributing" file and changed one of the extensions for sphinx that is a fork of the previously used extension that is no longer maintained.
More docs, less problems 
Still have a task https://jira.hyperledger.org/secure/Dashboard.jspa to fix broken links (unfortunately, atm Jira is not working for me for some reason, so will have to come back to this later).

Docs: Additional Information About Configuration + Small Fixes

---

docs/source/deploy/flags.rst
docs/source/deploy/index.rst
docs/source/maintenance/shepherd.rst

Adds description of metrics flags to the documentation
S'more docs
Might need to change the phrasing in the --help too but that is not a critical thing. 
Resolves #845

Docs: Documentation about metric flags

---

.github/workflows/iroha2-dev-pr.yml
Cargo.lock
iroha/Cargo.toml
iroha/test_network/Cargo.toml
iroha_client/Cargo.toml

Use unique_port and cargo-lints from crates.io instead of github links to master branch. This can be done as we finally published the first version of these crates.
Standard versioning.
None found.

Use unique_port and cargo-lints from crates.io

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/wsv.rs
iroha/test_network/src/lib.rs
iroha_client/tests/tests/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/tests/tests/multisignature_transaction.rs
iroha_client/tests/tests/tests/unstable_network.rs
iroha_error/iroha_error_macro/tests/display_inner.rs
iroha_http_server/src/lib.rs
iroha_substrate/src/lib.rs

Spawn blocking CPU intensive tasks in separate threads, where it is impossible yeild control manually to executor, to give other tasks chance to run.
Also adds several corrections in tests, they were initially mistakenly rewritten, so this PR reverts these things.
Should reduce the possibility of starvation in async tasks.
Code complexity increases.
https://jira.hyperledger.org/browse/IR-1094

Spawn blocking CPU intensive tasks in separate threads

---

irohad/ametsuchi/impl/flat_file/flat_file.cpp

Signed-off-by: Andrei Lebedev <lebdron@gmail.com>

FlatFile: close file before rename

---

Cargo.lock
Cargo.toml
iroha_actor/Cargo.toml
iroha_actor/src/broker.rs
iroha_actor/src/deadlock.rs
iroha_actor/src/envelope.rs
iroha_actor/src/lib.rs
iroha_actor/tests/deadlock.rs
lints.toml

https://jira.hyperledger.org/browse/IR-1092
https://jira.hyperledger.org/browse/IR-1093
This commit adds actor framework message broker for actors.
Using actor framework can benefit architecture by clearing relationships between actors a lot.
Look at doc tests and tests

Add simple actor framework

---

iroha/README.md
iroha/src/main.rs
iroha/trusted_peers.json

- Manual deploy section added to readme
- More information about configuring peers added to readme
- Also corrected a bug with trusted peers file not being read
Better docs
None found
https://jira.hyperledger.org/browse/IR-986
https://jira.hyperledger.org/browse/IR-1102

Manual deploy and configuration added to README

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr.yml
.github/workflows/iroha2.yml

Update github workflows for new runners
Github actions are updated for new runners.

Update workflows to new runners

---

docs/source/guides/build.rst
docs/source/guides/raspberrypi.rst

According to talk on community meeting on 6th November I've added new file with instructions how to build iroha on raspberry pi. I've also changed one of file (building.rst) to include my file. Because it necessairy to wrap g++ command to build iroha I've added short program to wrap that command.
Many people on chat are asking about how to build iroha on RPI. I've managed to and described on wiki (https://wiki.hyperledger.org/pages/viewpage.action?pageId=41584046), then Sara suggested to add instructions to documentation instead of wiki.
None (only documentation changes, no impact to source code)
This is documentation so no tests (only manual).
Alternative was Wiki, but Sara asked me to add that kind of description to documentation.

Support/1.1.x Added instructions how to build iroha on raspberry pi 3 and 4

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr.yml
.github/workflows/iroha2.yml

also formatting corrections
Disambiguates workflow names
Workflows are no longer displayed with the same name when they are different.
None found

Disambiguates workflow names

---

.github/CODEOWNERS

Removes Aler from codeowners
Aler no longer is an active contributor and code owner.

Removes Aler from codeowners

---

.github/workflows/iroha2-dev-pr.yml
iroha_actor/Cargo.toml
iroha_actor/src/deadlock.rs
iroha_actor/src/lib.rs
iroha_actor/tests/deadlock.rs

1. adds deadlock detection test to CI
2. Adds task local storage for actor id for deadlock detection case
3. Fixes test for deadlock detection - previously it would run forever
Deadlock detection works without changing the API after tokio migration.
None found

Adds task local storage for actor id

---

docs/source/iroha_2_whitepaper.md

Fixed a typo in whitepaper.
More clear text.
None.

Fix small typo in whitepaper.

---

.github/CODEOWNERS

Added self to codeowners.
I will be able to work on this project in full power.
None.

Add self to codeowners.

---

.github/workflows/iroha2-add-label.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml

Fixes Docker publish and iroha2-dev push CI
- Docker images will be published on iroha2-dev push
- iroha2-dev CI will not be failing
- Moves coverage and bench into PR CI
- Fixes add label action

Fixes Docker publish and iroha2-dev push CI

---

.github/workflows/iroha2-dev.yml

Fixes wrong username secret in Docker publish

Fixes wrong username secret in Docker publish

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml

1. Fixes repository name for dockerhub
2. Fixes inaccurate coverage diffs
Accurate coverage diffs and docker containers correctly pushed on iroha2-dev CI completion

Fixes repository name for dockerhub and coverage diff

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2.yml
Dockerfile

1. Fixed multiple build-args format
2. Redeclared ARG for intermediate build containers

Fixed multiple build-args format and redeclared ARG for intermediate build containers

---

codecov.yml

- The project status check will fail if the relative decrease in coverage is more than 5%
- Check for percentage of new code coverage disabled
For more information see https://docs.codecov.io/docs/commit-status
Sane defaults that we agreed on as a team for coverage status check.

Configures codecov status checks

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-pr.yml

Uses a fixed Rust version in CI. This PR fixes the last places where not a fixed, but latest rust version was used.
We will migrate to new version explicitly from now on. This will prevent version migration failures in unrelated to the migration PRs.

Uses a fixed Rust version in CI

---

irohad/ametsuchi/impl/rocksdb_command_executor.cpp

```Invalid precision``` test fixup for rocksdb impl

fix precision

---

Dockerfile

Removes unnecessary dependencies from docker image
- The existence of these dependencies will not confuse people, and will not imply that Iroha needs them
- The docker image start will be faster
None found

Removes unnecessary dependencies from docker image

---

docs/source/references/api_spec.md

API spec web socket corrections. 
API corresponds to code.

API spec web socket corrections

---

iroha/src/block.rs
iroha/src/lib.rs
iroha/src/smartcontracts/isi/permissions.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/test_network/src/lib.rs
iroha/test_network/tests/mock.rs
iroha_permissions_validators/src/lib.rs

PermissionValidator trait renamed to IsAllowed and corresponding other name changes.
As agreed in previous PR discussion.
https://jira.hyperledger.org/browse/IR-1154

PermissionValidator trait renamed to IsAllowed

---

iroha_schema/iroha_schema_bin/src/main.rs

https://jira.hyperledger.org/browse/IR-1159

Changed object-models to create schema IR-1159

---

Cargo.lock
iroha/Cargo.toml
iroha/benches/kura.rs
iroha/src/kura.rs

Adds block size metric.
This way for projects building on Iroha2 it will be easier to estimate the needed disk space.
https://jira.hyperledger.org/browse/IR-1163

Adds block size metric

---

iroha/benches/sumeragi.rs
iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/genesis.rs
iroha/src/lib.rs
iroha/src/sumeragi/mod.rs
iroha/src/sumeragi/network_topology.rs
iroha/test_network/src/lib.rs
iroha/test_network/tests/simeragi_with_mock.rs
iroha_futures/src/lib.rs
iroha_logger/src/telemetry.rs
iroha_network/src/lib.rs
iroha_telemetry/src/futures.rs

Introduces network topology builder.
Cleaner and more modular code, less code duplication in critical places.
Will be needed for storing proofs of view changes.

Network topology builder

---

iroha_p2p/src/lib.rs
iroha_p2p/src/network.rs
iroha_p2p/src/peer.rs

* Fixed issues from https://github.com/hyperledger/iroha/pull/1083
* Added connection listening code.

Fixed small issues, added connection listen code.
