irohad/consensus/yac/impl/yac_gate_impl.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp

The case when a node is not voted yet but has received votes for a round is possible.
That was a root cause of a rare issue, when a node was not switched to the next round (when reject commit message arrived).
As a result, the whole network can stop working (if there are enough of that buggy peers).
The change brings the correct round number propagation from Yac gate to Synchronizer.
Thus the peer goes to the correct round despite what was happen or received.
The new tests are created (`yac_gate_test -> CommitFromTheFuture` tests)
Proper Yac gate behavior.
¯\(°_o)/¯
`yac_gate_test`

Yac gate behaves itself when a commit message from the future arrives

---

test/framework/integration_framework/fake_peer/fake_peer.cpp
test/framework/integration_framework/fake_peer/fake_peer.hpp
test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/integration_test_framework.hpp
test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/add_peer_test.cpp
test/integration/acceptance/fake_peer_example_test.cpp

[IR-450](https://jira.hyperledger.org/browse/IR-450)
Test for `addPeer` command. Two cases:
- addPeer command gets committed and the WSV has old peers plus the added one;
- peer gets incomplete MST and then new peer is added; MST state propagates to new peer.
- peer gets started with genesis block that does not contain it, and must synchronize with a running network after it has a corresponding addPeer command committed.
increased test coverage
more time to wait for CI (~3.3sec)
`add_peer_test`

add peer test

---

irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/impl/block_loader_init.cpp
shared_model/backend/protobuf/impl/proto_block_factory.cpp
shared_model/validators/transaction_batch_validator.cpp
shared_model/validators/transaction_batch_validator.hpp
shared_model/validators/validators_common.cpp
shared_model/validators/validators_common.hpp
test/module/shared_model/validators/CMakeLists.txt
test/module/shared_model/validators/batch_validator_test.cpp

The missing logic of batches validation was added.
Now in some cases, we check only the order of transactions appearance in batch meta of an "ordered" batch.
The equality of batch meta hashes quantity to batch transactions quantity is required for:
* atomic batches - always
* ordered batches - only when we handle user's input and the batch was not submitted for stateful validation yet (after the stateful validation, some transactions can fail the validation and be removed from the batch, but the batch meta remains untouched)
Proper batch validation.
No issues when partial ordered batches are received within blocks acquired from synchronizer or wsv restorer.
Unit tests are going to be created.
Also it is GOOD TO HAVE integration test.
No …

Fix batch validator for use in block loader

---

irohad/consensus/yac/transport/impl/network_impl.cpp
irohad/consensus/yac/transport/yac_pb_converters.hpp
test/fuzzing/CMakeLists.txt
test/fuzzing/consensus_fuzz.cpp

The test for consensus fuzzing now compiles and works.
The test uses not mocked consensus implementation.
The issue found by the test is fixed.
Increased test coverage.
The issue with votes deserialization in consensus transport is fixed.
Need to manually update consensus dependencies alongside with its usage in `application.cpp`
```
scripts/run-iroha-dev.sh
cmake -H. -Bbuild -DLIB_SUFFIX=64 -DFUZZING=ON -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7
cmake --build build --target consensus_fuzz -- -j4
build/test_bin/consensus_fuzz
```

Fix consensus transport and its fuzzing test

---

shared_model/builders/protobuf/builder_templates/transaction_template.hpp
test/framework/integration_framework/integration_test_framework.hpp
test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/acceptance_fixture.hpp
test/integration/acceptance/hex_keys_test.cpp

This pr replaces #25 
Some time ago the format of the way keys are passed to commands was changed from bytes arrays to strings.
This change introduces a set of tests for font case sensitivity for keys fields.
Increased test coverage.
Potentially the test can be written without ITF usage.
`hex_keys_tests`

Add tests for font case sensivity of hex keys

---

test/framework/batch_helper.hpp
test/module/shared_model/validators/CMakeLists.txt
test/module/shared_model/validators/batch_validator_test.cpp

This pr is opened instead of #31 
Add tests for the new logic inside batch validator.
Relates to #27
Increased tests coverage.
Not known
`batch_validator_test`

Add tests for batch validator

---

cmake/Modules/Findpq.cmake
irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/ametsuchi/impl/postgres_wsv_query.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/main/application.cpp
irohad/network/impl/block_loader_impl.cpp
irohad/ordering/impl/on_demand_os_client_grpc.cpp
irohad/torii/processor/impl/transaction_processor_impl.cpp
libs/common/files.cpp
libs/logger/logger.hpp
test/framework/sql_query.cpp

Pull request fixes irohad crash on receiving SetAccountDetail transaction with value field set to `"{}"`.
No crash^^
Command doesn't pass stateful validation with message `command 'SetAccountDetail' with index '0' did not pass verification with code '1'`. Code 1 means "internal error" which isn't a user friendly message. I suggest either to create additional stateless validation rule or improve error message (or maybe even so some escaping for Postgres).

Fix issue with uncaught exception in logger

---

irohad/ametsuchi/block_query.hpp
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/postgres_block_query.hpp
irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/main/application.cpp
irohad/main/irohad.cpp
irohad/network/block_loader.hpp
irohad/network/impl/block_loader_impl.cpp
irohad/network/impl/block_loader_impl.hpp
irohad/network/impl/block_loader_service.cpp
irohad/network/impl/block_loader_service.hpp
irohad/simulator/impl/simulator.cpp
irohad/simulator/impl/simulator.hpp
irohad/torii/impl/command_service_impl.cpp
schema/loader.proto
test/framework/integration_framework/fake_peer/behaviour/honest.cpp
test/framework/integration_framework/fake_peer/network/loader_grpc.cpp
test/framework/integration_framework/fake_peer/network/loader_grpc.hpp
test/framework/integration_framework/fake_peer/types.hpp
test/integration/acceptance/fake_peer_example_test.cpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/ametsuchi/mock_block_query.hpp
test/module/irohad/network/block_loader_test.cpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/simulator/simulator_test.cpp

Remove vectors from `BlockQuery` interface to avoid large runtime containers.
- Refactor `BlockLoader::retrieveBlock` with height to avoid linear blockstore search, and not to store `O(n)` blocks in memory.
- Refactor `BlockLoader::retrieveBlocks` not to store `O(n)` blocks in memory.
Possibility to synchronize a large blockstore
None

Remove vectors from BlockQuery interface

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/ametsuchi/storage.hpp
libs/common/result.hpp
test/module/irohad/ametsuchi/mock_storage.hpp

Create MutableStorage which does not store blocks, allowing to reindex existing blocks and commit WSV without taking additional space
Restore WSV without using additional storage
BlockStorageStub looks like a crutch, but it seems as the most viable solution which does not require major modifications to existing codebase

Refactor WsvRestorer to reuse existing block store

---

irohad/main/impl/on_demand_ordering_init.cpp
irohad/main/impl/on_demand_ordering_init.hpp

Reopened https://github.com/hyperledger/iroha/pull/30
Fix the case when the delayed events for previous round are scheduled after the most recent commit, making unnecessary requests to the Ordering Service and invocations of Simulator.
No more `Irohad/Simulator Last block height: 287, proposal height: 287` warnings.
No more useless requests to the ordering service
- OnDemandOrderingInit is not unit-testable 😿
- `log_` and `last_received_round_` are captured by `this`, which may cause use-after-free if the observable lifetime is not managed carefully.

Fix ordering event scheduling

---

cmake/Modules/Finded25519.cmake
irohad/ametsuchi/impl/flat_file/flat_file.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/consensus/yac/storage/impl/buffered_cleanup_strategy.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
libs/logger/CMakeLists.txt
libs/logger/logger.hpp
libs/logger/logger_manager.cpp
libs/logger/logger_spdlog.cpp

Fix Windows build with the current codebase:
- Add missing ed25519 library link with bcrypt
- Fix compilation issue with boost::make_optional in FlatFile
- Fix undefined behavior with parameter evaluation in OrderingService
- Add missing logger library link with boost
Successful build and run of irohad and iroha-cli with MSVC
None

Fix Windows build with MSVC

---

.jenkinsci-new/builders/x64-linux-build-steps.groovy
.jenkinsci-new/text-variables.groovy
.jenkinsci-new/utils/docker-pull-or-build.groovy
Jenkinsfile-new
docker/manifest.yaml

Development in the develop branch will be terminated. CI never builds artifacts for develop branch.
Artifacts for the master branch will be build with the "master" Docker Hub tag.
It is a requirement of the development team.

CI never builds artifacts for develop branch

---

.jenkinsci-new/builders/x64-linux-build-steps.groovy

reopen of https://github.com/hyperledger/iroha/pull/54
If **Before merge to trunk** build was started  after  10 pm, it runs tests for all compiler, and name of report can contain name of second day for last compiler tests. 
this pr will clean old reports before run tests 
fix error  https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-51/2/pipeline
None

DOPS-486 Fix two test reports

---

irohad/ametsuchi/impl/mutable_storage_impl.cpp
irohad/ametsuchi/impl/mutable_storage_impl.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/ledger_state.hpp
irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/main/application.cpp
irohad/simulator/block_creator.hpp
irohad/simulator/impl/simulator.cpp
irohad/simulator/impl/simulator.hpp
irohad/synchronizer/impl/synchronizer_impl.cpp
test/integration/acceptance/add_peer_test.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/consensus/yac/yac_hash_provider_test.cpp
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
test/module/irohad/simulator/simulator_mocks.hpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp
test/module/irohad/torii/processor/transaction_processor_test.cpp

Remove block query dependency from Simulator by passing top block hash with LedgerState from storage commit
This is a part of https://github.com/hyperledger/iroha/pull/13
Less dependencies in Simulator
None

Add top block hash to ledger state

---

test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/integration_test_framework.hpp
test/integration/acceptance/add_peer_test.cpp
test/integration/acceptance/fake_peer_example_test.cpp

The problem was in missing synchronization of synchronizatin events 0_o. The assumption that `sendTxAwait` will wait for the corresponding synchronization event is false.
Fixed the test.

Fixed add peer test

---

test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/iroha_instance.cpp
test/framework/integration_framework/iroha_instance.hpp

When iroha fails initialization, ITF tests should not proceed normally, but rather an informative message should be displayed (if the error was not expected). This change makes ITF check the iroha initialization result and throw an exception with descriptive details on error.
Easier ITF tests debugging.

ITF: fixed init failure handling

---

.jenkinsci-new/builders/x64-mac-build-steps.groovy

Recently we changed Jenkins default `shell` from `bash` to empty line to support windows. 
Some build now fail. This pr is aimed to fix it. 
Fix mac ci
None

Fix mac ci

---

.jenkinsci-new/build.groovy
.jenkinsci-new/builders/x64-linux-build-steps.groovy
.jenkinsci-new/builders/x64-mac-build-steps.groovy
.jenkinsci-new/text-variables.groovy
Jenkinsfile-new
irohad/ametsuchi/impl/soci_utils.hpp

Enable build of fuzzing targets by default on Linux and Mac, since compiler support was added by @luckychess .
No more pull requests fixing fuzzing targets build
None

Enable fuzzing build in CI by default

---

irohad/main/application.cpp
irohad/main/impl/on_demand_ordering_init.cpp
irohad/main/impl/on_demand_ordering_init.hpp

Removed unneeded call to peer query in ordering creator. Current peers can be obtained from ledger state object.
Performance & Simplicity
someobody's piece of hard work, 23 lines of well-formatted code, are put to the edge of extinction by 5 arrogant lines

Ordering init: removed peer query from ordering peers map

---

docs/source/guides/configuration.rst
irohad/ametsuchi/impl/postgres_options.cpp
irohad/ametsuchi/impl/postgres_options.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/postgres_options_test.cpp

When a user does not specify the database name, a default one gets used, and a deprecation warning is displayed.
Uniform DB handling.

ametsuchi: use a default database name when user does not provide one

---

test/framework/common_constants.cpp
test/framework/common_constants.hpp
test/integration/acceptance/hex_keys_test.cpp
test/integration/acceptance/query_permission_common_tests.cpp
test/integration/acceptance/query_permission_test_base.cpp

Renamed *spectator*-related constants to a broader *another user*, which is applicable to a wider variety of tests.
More tests can reuse common constants related to additional users.

Tests: renamed some common constants

---

libs/common/result.hpp
test/framework/result_gtest_checkers.hpp

- use `std::decay<T>` when needed
- added `operator |=` which is a shortcut for `Result = Result | function`
- added helpers to expect and assert `Error` and `Value`, printing `toString()` in case of failure.
Better type deduction in `Result`-related functions. New operator makes code prettier.

expected::Result improvements

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/postgres_block_storage.cpp
irohad/ametsuchi/impl/postgres_block_storage.hpp
irohad/ametsuchi/impl/postgres_block_storage_factory.cpp
irohad/ametsuchi/impl/postgres_block_storage_factory.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/postgres_block_storage_test.cpp

Pull request adds implementation of BlockStorage interface based on Postgres database.
FlatFile storage implementation doesn't work well with large amount of blocks. Postgres-based implementation should provide a better scalability and an overall performance.
- `PostgresBlockStorage::forEach` fetches all block ids into the memory what could be a problem if storage contains too many blocks. My intention here is this function should not be called for very large storages since it will take too much time regardless of implementation.
- There is a [known issue](https://github.com/SOCI/soci/issues/501) with SOCI which leads to inability for a simple usage of Postgres's `bytea` data type; `text` type should be used so far. There is a [workaround](https://github.com/SOCI/soci/issues/501#issuecomme …

Postgres block storage

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor_impl.hpp
irohad/network/mst_transport.hpp
test/framework/integration_framework/fake_peer/network/mst_message.hpp
test/framework/integration_framework/fake_peer/network/mst_network_notifier.cpp
test/framework/integration_framework/fake_peer/network/mst_network_notifier.hpp
test/framework/test_subscriber.hpp
test/module/irohad/multi_sig_transactions/mst_mocks.hpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp

This resurrects #9
This change removes a very strange line the rationale behind which was not found:
https://github.com/hyperledger/iroha/blob/6c77597ab55163667931591e774f6a04d91b403b/irohad/multi_sig_transactions/impl/mst_processor_impl.cpp#L104
...and adds early removal of expired batches from incoming MstState. Also move semantics get used.
see above
There remains a possibility that the removed line of code was helpful...
Regarding the removed line, it broke no tests when it was commented out.
Regarding the outdated batches, please see mst_processor_test `MstProcessorTest.receivedOutdatedState` test.

MST: fixed expired incoming state logic

---

.jenkinsci-new/build.groovy
docker/develop/Dockerfile

- Update clang-format version from 3.8 to 7.1. Old version produced incorrect output
- Fix extension regexp for clang-format input. Now it does not include generic extensions starting with the letter c, only "c++".
Correct output, less misunderstandings from contributors
None

Fix clang-format output on CI

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/main/impl/pg_connection_init.cpp
irohad/main/impl/pg_connection_init.hpp

Subj. This change is needed to be able to reset the tables in tests that do not use `StorageImpl` (strictly speaking the upcoming `ExecutorItf`).
Table manipulation statements gathered in single place.
This place is called <pre>PgConnection**Init**</pre> anthough it does more than that.

SQL: moved reset sql statements to PgConnectionInit

---

test/framework/config_helper.cpp
test/framework/config_helper.hpp

The static member `AmetsuchiTest::pgopt_` used the global constant `kDefaultPostgresCreds` defiined in another translation unit for initialization, which caused a race. Thanks @luckychess for pointing that out. This PR fixes the race.
Unbugging.

Testing: fixed initialization race of PostgreSQL credentials

---

.jenkinsci-new/build.groovy
.jenkinsci-new/text-variables.groovy
Jenkinsfile-new

Signed-off-by: Roman Gavrilov <kogeler@gmail.com>
Added nightly builds for CI.
It includes:
- x64linux_compiler_list = ['gcc5','gcc7', 'clang6' , 'clang7']
- mac_compiler_list = ['appleclang']
- win_compiler_list = ['msvc']
- testing = true
- testList = '()'
- coverage = true
- cppcheck = true
- sonar = true
- codestyle = true
- useBTF = true
- sanitize = true
- packagePush=false
- doxygen=false
We can check the quality of the code as much as possible in the off-peak hours

Added nightly builds for CI

---

irohad/main/application.hpp

The root cause of the problem is the captured `this` pointer of `SynchronizerImpl` that is passed to an observer of consensus gate outcomes. This PR is a quick fix that only solves it in a near perspective, with a risk to face it somewhere else in the future. The solution method is making the consensus outcomes observable destroy before the synchronizer object pointed to by the captured `this`.
fixed segfault during destruction.
Delaying a thorough solution.

Irohad: moved consensus objects earlier in destruction order

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/temporary_wsv_impl.cpp
irohad/ametsuchi/impl/temporary_wsv_impl.hpp

Move TransactionExecutor init to StorageImpl to simplify CommandExecutor construction management
Simpler dependency management
None

Ametsuchi: move TransactionExecutor init to StorageImpl

---

iroha-cli/CMakeLists.txt
irohad/ametsuchi/CMakeLists.txt
irohad/model/CMakeLists.txt
irohad/model/converters/CMakeLists.txt
irohad/model/generators/CMakeLists.txt
libs/parser/CMakeLists.txt
test/module/irohad/model/CMakeLists.txt

Fix BUILD_SHARED_LIBS CMake flag, which did not work previously due to cyclic dependencies between libraries.
Possible to build components as shared libraries, which reduces the build directory size on gcc 5.5 from ~27GB to ~4GB.
None?
Configure the project with `-DBUILD_SHARED_LIBS=ON`

CMake: fix BUILD_SHARED_LIBS flag

---

docs/source/api/commands.rst
irohad/ametsuchi/impl/postgres_command_executor.cpp
test/framework/CMakeLists.txt
test/framework/common_constants.cpp
test/framework/common_constants.hpp
test/integration/acceptance/add_asset_qty_test.cpp
test/integration/acceptance/transfer_asset_test.cpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/postgres_executor_test.cpp

Prior to this change, the maximum asset quantity was computed as `2^(256-p)`, where `p` is the asset precision. This had a weird consequence that an asset with greater `p` would have a greater significand* limit that will not fit a 256-bit integer.
___
*) significand means `M` in `N = M * e ^ p` floating point notation
Now the мантисса limit is always uint256_max, regardless the asset precision. Also the involved SQL got prettified (to my taste).
See the `*Overflow*` tests in `add_asset_qty_test` and `postgres_executor_test`.

Ametsuchi: fixed asset quantity overflow detection

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/mutable_storage_impl.cpp
irohad/ametsuchi/impl/postgres_block_index.cpp
irohad/ametsuchi/impl/postgres_block_index.hpp
irohad/ametsuchi/impl/postgres_indexer.cpp
irohad/ametsuchi/impl/postgres_indexer.hpp
irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/indexer.hpp
irohad/main/impl/pg_connection_init.cpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/system/irohad_test.cpp

Separate `PostgresBlockIndexer` into block parser & entity indexers (like tx position by hash, by creator, etc.).
Low-level indexers reusable in tests. Decoupled block indexer from PostgreSQL backend.

PostgresBlockIndexer: split to abstract block indexer & backend entity indexer

---

irohad/ametsuchi/CMakeLists.txt
test/framework/CMakeLists.txt
test/framework/test_db_manager.cpp
test/framework/test_db_manager.hpp

This change brings a test database manager, that creates a database to be used in tests and drops it on being destroyed. It is needed to share a database across multiple test runs and by doing so avoid the overhead of creating and dropping database for each test.
Will increase performance of executor tests.

Test Framework: TestDbManager

---

irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/ametsuchi/impl/postgres_specific_query_executor.hpp
irohad/ametsuchi/specific_query_executor.hpp
test/module/irohad/ametsuchi/mock_query_executor_visitor.hpp

`SpecificQueryExecutor` had methods to set internal fields for query hash & creator, while the `Query` object passed for execution provides them as well. This chamge removes the ambiguous side effect methods and sets the fields from `Query` object.
Disambiguation. Less code.

SpecificQueryExecutor: removed ambiguous setCreatorId and setQueryHash

---

irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/ametsuchi/impl/postgres_specific_query_executor.hpp

Remove creator id and query hash fields from PostgresSpecificQueryExecutor
No query-dependent state, possible to call nested queries with different creator id and query hash
None?
Add creator id and query hash fields to specific query types. That will require rather major refactor of shared_model classes

PostgresSpecificQueryExecutor: remove creator id and query hash fields

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/main/CMakeLists.txt
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/impl/pending_transaction_storage_init.cpp
irohad/main/impl/pending_transaction_storage_init.hpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/storage_init_test.cpp

Pass dependencies for query executor creation in constructor in order to be able to create query executor as a dependency of command executor.
Possible to pass query executor as a dependency to command executor
Even greater coupling
Make storage as a dependency of query executor and create executors outside storage

Ametsuchi: pass dependencies for query executor creation

---

irohad/main/CMakeLists.txt
irohad/main/impl/pg_connection_init.cpp
irohad/main/impl/pg_connection_init.hpp
test/system/CMakeLists.txt
test/system/irohad_test.cpp

`libpg_connection_init` depends from `libametsuchi` and vice versa. Though the first dependency seems odd and thus is removed. Also one include is substituted with forward declaration.
Now the project can be configured with shared libs.

CMakeLists: removed circular dependency between ametsuchi & pg_connection_init

---

.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/text-variables.groovy
Jenkinsfile

- Add option to use shared libraries in CMake for Linux builds
- Add step for "Before merge to trunk" scenario to use shared libraries
- Can potentially make it default to reduce build time when tests are fixed
- More configurations tested
None

CI: add option to use BUILD_SHARED_LIBS flag on Linux

---

test/integration/executor/CMakeLists.txt
test/integration/executor/query_permission_test.cpp
test/integration/executor/query_permission_test.hpp

This adds an implementation of common base fixture - a parametric test class for query permission testing on the new shiny Executor ITF.
All you need to create a permission test using this class is:
https://github.com/hyperledger/iroha/blob/b01dc38a6a58077a9cd7ee7343a8814da660bb65/test/integration/executor/get_signatories_test.cpp#L94-L112

Executor ITF: query permissions common test

---

test/fuzzing/CMakeLists.txt

Pull request adds a single target for all fuzzing targets.
It was asked in https://github.com/google/oss-fuzz/pull/2753. 
Have to maintain target list.
`cmake -DFUZZING=ON; make fuzzing`

Introduce cmake target for all fuzzing targets

---

docs/source/architecture/index.rst
docs/source/guides/torii-tls.rst

Fix small RST syntax issues in documentation.
Sphinx compiler has been complaining about the following:
```
iroha/docs/source/architecture/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
iroha/docs/source/guides/torii-tls.rst:26: WARNING: Error in "code" directive:
maximum 1 argument(s) allowed, 4 supplied.
.. code:: sh
$ openssl list-public-key-algorithms
```
No Sphinx compilation issues
None
```bash
cd docs/source
make permissions
make html
```

Fix RST syntax issues in docs

---

irohad/consensus/gate_object.hpp
irohad/consensus/yac/impl/yac.cpp
irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_gate_impl.hpp
irohad/consensus/yac/outcome_messages.hpp
irohad/consensus/yac/storage/impl/buffered_cleanup_strategy.cpp
irohad/consensus/yac/storage/storage_result.hpp
irohad/consensus/yac/yac.hpp
irohad/consensus/yac/yac_gate.hpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/impl/consensus_init.cpp
irohad/main/impl/consensus_init.hpp
irohad/synchronizer/impl/synchronizer_impl.cpp
irohad/synchronizer/impl/synchronizer_impl.hpp
shared_model/cryptography/ed25519_ursa_impl/crypto_provider.cpp
test/module/irohad/consensus/yac/mock_yac_hash_gate.hpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/consensus/yac/yac_simple_cold_case_test.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp

- Fix handling consensus messages from future and past - they are not applied to storage, because the number of peers may not correspond to the current cluster order size.
- Refactor synchronizer to emit commit events due to current logic in OrderingInit class
- Pass optional peers list to consensus instead of WSV, because the state peers list should correspond to the top block in the ledger
Working synchronization on AddPeer commands
Might not be the best or most optimal solution overall, however the changes are localized in Yac and Synchronizer. Please check alternate designs
Please check changed files in test directory
- Pass optional peers list together with corresponding round in config
- Refactor OrderingInit to update hashes on events from storage

Fix synchronization

---

irohad/ametsuchi/impl/postgres_block_storage.cpp
irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/ametsuchi/impl/soci_utils.hpp

Disambiguate calls to `iroha::ametsuchi::apply`, because it clashes with `std::apply` if compiled with C++17 standard.
Compilation with C++17 standard
No CI pipeline for C++17 standard yet

Ametsuchi: remove ambiguous call to apply

---

README.md

https://iroha.readthedocs.io/en/latest/build/index.html is a working
link to build iroha
Signed-off-by: Eric Curtin <ericcurtin17@gmail.com>

Build guide link broken

---

.packer/win/windows-build-server.json

Allow reboot exit code on chocolatey install because dotnet may require reboot after install
Successful Windows image build
None

Windows Packer: allow reboot exit code for chocolatey

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/main/impl/on_demand_ordering_init.cpp
irohad/synchronizer/impl/synchronizer_impl.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp

- Several FutureMessages can be queued up in Yac worker, leading to incorrect synchronization attempt when the same FutureMessage is processed the second time. A conditional is added to ignore the next attempts to process FutureMessage if the node is already synchronized.
- Fix rounds being incorrectly dropped in OnDemandOrderingInit when commit happened after several reject rounds (e.g. block being committed after round (i, 5), because event contained round (i, 0) instead)
- Generate peer permutations in OnDemandOrderingInit on each event, because it is not known in synchronization events observable whether any blocks were committed.
Correct behavior
None
YacGateTest.Future, YacGateTest.OutdatedFuture

Synchronization: fix FutureMessage handling and SynchronizationEvent round numbers

---

irohad/main/CMakeLists.txt
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/iroha_conf_literals.cpp
irohad/main/iroha_conf_literals.hpp
irohad/main/iroha_conf_loader.cpp
irohad/main/iroha_conf_loader.hpp
irohad/network/CMakeLists.txt
irohad/network/impl/peer_tls_certificates_provider_root.cpp
irohad/network/impl/peer_tls_certificates_provider_root.hpp
irohad/network/impl/peer_tls_certificates_provider_wsv.cpp
irohad/network/impl/peer_tls_certificates_provider_wsv.hpp
irohad/network/peer_tls_certificates_provider.hpp

This change adds peer certificate provider interface and 2 its implementations: one returns root certificate for every peer, and another gets certificates from WSV. The code to initialize cert provider is also added.
In the cert provider interface, the method accepting `interface::Peer` is required for client side, and is very effective when using both root and WSV impleentations, because all the data is stored in memory. The method accepting `interface::types::PubkeyType` is required for server side, which gets the peer's public key from its sertificate, and is as effetcive as the first only with root certs, because the WSV info has to be queried separately on demand. So it is not reasonable to restrict the interface only to either …

P2P TLS: added peer tls certificate providers

---

.jenkinsci/text-variables.groovy
.jenkinsci/utils/vars.groovy
Jenkinsfile
cmake/Modules/Findursa.cmake
docker/develop/Dockerfile
docker/release/Dockerfile
docs/source/build/index.rst
sonar-project.properties

- Bump Ubuntu version to 18.04
- Replace gcc5 with gcc9 to avoid compiler errors and enable C++17 support
Updated environment
Less legacy support?

Infrastructure: replace gcc5 with gcc9, replace Ubuntu 16.04 with 18.04

---

irohad/torii/impl/command_service_impl.cpp
test/module/irohad/torii/command_service_test.cpp

A query for a transaction status could return Committed instead of Rejected for a transaction processed long time ago.
Correct behavior
Miserable code redundancy

GetStatus can return Rejected for a tx

---

iroha-cli/main.cpp
irohad/model/converters/impl/pb_block_factory.cpp
irohad/model/converters/impl/pb_query_factory.cpp
irohad/model/converters/impl/pb_transaction_factory.cpp
irohad/model/generators/impl/transaction_generator.cpp
libs/common/blob.hpp
shared_model/cryptography/ed25519_sha3_impl/crypto_provider.cpp
shared_model/cryptography/ed25519_sha3_impl/crypto_provider.hpp
shared_model/cryptography/ed25519_sha3_impl/signer.cpp
shared_model/cryptography/ed25519_sha3_impl/verifier.cpp

[IR-650](https://jira.hyperledger.org/browse/IR-650)
This change started as removal of uncaught exception in favour of a `Result` object. Then several optimizations of blobs conversions were also made.
Removed uncaught exception in blob conversion. Optimized conversions.
The code under old cli and `irohad/model` was fixed fast and dirty, just to keep the old behaviour before it gets purged.

crypto blobs: reworked passthrough

---

irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/ametsuchi/impl/postgres_specific_query_executor.hpp

In case of inconsistency between transaction index and block storage, an unhandled out-of-range exception was thrown. After this change the range violation will result in an internal error response with explanation. also a small refactoring was done.
less reasons to crash. less objects moving.

Ametsuchi: transactions query detects missing transactions

---

.jenkinsci/builders/x64-win-build-steps.groovy
.packer/win/files/packages.config
docs/source/build/index.rst

Update MSVC version from 2017 to 2019 due to compilation issues of operators inside lambdas.
Standard-conformant code compiles on Windows.
Less compatibility with older compilers.

Infrastructure: replace MSVC 2017 with MSVC 2019

---

.jenkinsci/builders/x64-linux-build-steps.groovy

Docker build could have failed when Dockerfile was changed and committed to master branch because the new Dockerfile was compared to itself instead of previous version.
https://jenkins.soramitsu.co.jp/job/iroha/job/iroha-hyperledger/job/master/218/consoleText
Successful master build on Dockerfile changes
None

Jenkins: fix Docker image build on Linux for master branch

---

shared_model/backend/protobuf/impl/block.cpp
shared_model/backend/protobuf/impl/transaction.cpp
shared_model/backend/protobuf/queries/impl/proto_blocks_query.cpp
shared_model/backend/protobuf/queries/impl/proto_query.cpp
shared_model/backend/protobuf/queries/proto_blocks_query.hpp
test/module/shared_model/backend_proto/CMakeLists.txt
test/module/shared_model/backend_proto/shared_proto_add_signature_test.cpp

Update blob field of Signable classes when addSignature is called, so that it reflects the updated internal state of the object.
Correct behavior.
None.
SharedProtoAddSignatureTest.AddSignature
Make data objects immutable, and create new ones when they have to be modified.

Shared model: update blob on addSignature

---

docker/develop/Dockerfile

Changed the ppa for python3.6 in ubuntu16.04
the ppa of Jonathon F was closed (https://launchpad.net/~jonathonf) and prevents our ci from building the docker image for tests. So I switched to another ppa.

v1.1.x docker: fixed docker develop image python3.6 ppa

---

libs/common/result.hpp
test/module/libs/common/result_test.cpp

- Fixed a bug in `assumeError` (tests added)
- Added `Reslut` construction from another `Result` when possible (with tests)
- Removed unused `PolyMorphicReSult` (with tests)
Casts not needed when returning a `Result` with base type from a function that creates a `Result` with derived type.
`Result` just got bigger.

Result: fixes and new constructor

---

cmake/functions.cmake
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/query_executor_factory.hpp
irohad/ametsuchi/storage.hpp
irohad/torii/impl/query_service.cpp
irohad/torii/processor/impl/query_processor_impl.cpp
irohad/torii/processor/query_processor.hpp
irohad/torii/processor/query_processor_impl.hpp
test/framework/result_gtest_checkers.hpp
test/module/irohad/ametsuchi/mock_storage.hpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/irohad/torii/processor/mock_query_processor.hpp
test/module/irohad/torii/processor/query_processor_test.cpp
test/module/irohad/torii/torii_queries_test.cpp

in case of any runtime failure, if a query executor cannot be created, return an `expected::Error` instead of a `nullptr`.
hopefully fixes a bug discovered by oss fuzzer

Ametsuchi: query executor creator returns result

---

.jenkinsci/text-variables.groovy
.jenkinsci/utils/vars.groovy
Jenkinsfile
docker/develop/Dockerfile

- Replace clang-6.0 with clang-9 to avoid compiler errors and enable C++17 support
https://bugs.llvm.org/show_bug.cgi?id=33222
Updated environment
Less legacy support?

Infrastructure: replace clang-6.0 with clang-9

---

.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/builders/x64-mac-build-steps.groovy
.jenkinsci/builders/x64-win-build-steps.groovy
.jenkinsci/helpers/hash.py
.jenkinsci/utils/utils.groovy

Currently, it is very difficult to test changes in vcpkg dependencies. For mac and windows, we can use only one dependence in the build agent, which affects all builds. This pr allows to install several vcpkg dependencies on build agent, manage their version and also build vcpkg dependencies if the required version does not exist.
1. added stage "Prepare <Platform> environment" to see how long docker or vcpkg builds take.
2. added python script to calculate hash for vcpkg folder, it is universal and return same hash for linux, windows, mac, python2 and python3 
```
./.jenkinsci/helpers/hash.py vcpkg
```
3. added `build_vcpkg()` function to `utils.groovy`, it ensures that host have vcpkg with given hash.
1. No need run manual update for vcpkg dependencies for windows and mac.
2. vcpkg …

[DOPS-886] Runtime vcpkg

---

libs/logger/logger.hpp

Remove fmt version from exception type to allow building it independent from versions.
No explicit version dependency in code.
None

Logger: remove fmt version from exception

---

Cargo.toml
src/storage/kura.rs
tests/assets.rs

1. implemented read_all
2. reorganized storage tests
3. turned tests with async functions into async tests
Right now read_all assumes that we read blocks starting from `0` and finish when we can't find the block with the next height, meaning there can be no gaps in the sequence. This is an intended behavior.
Read all - implemented
What should we do when the sequence on disk is corrupted?
Read all files in a directory and then check and reorder them.

Implemented read_all blocks and reorganized storage tests

---

.jenkinsci/helpers/hash.py

(cherry picked from commit 0ae6b59d18ef5beb1f1e188180fc82f8b2af5b85)
We had problem with windows path(Path is too lobg). In this pr we decries the length of hash https://github.com/hyperledger/iroha/pull/376
1. Backport: Decries the length of hash 
Windows vcpkg builds on master works.
Hash collision.

Backport Short hash

---

.github/workflows/rust.yml
Makefile.toml
src/storage/kura.rs
tests/assets.rs

1. Introduces test_helper_fns module with a function to cleanup directory with blocks
2. Calls this function in all of the tests that use default block directory
3. Adds makefile for cargo-make to automatically cleanup blocks folder after test completion
Fixes bug mentioned in the issue RH2-22. The bug was that the tests might fail if there was already a folder with blocks, which contained blocks with different structure from previous versions of iroha2.
To run tests with cleanup:
1. Install cargo-make on your machine `cargo install --force cargo-make`
2. Run tests with `cargo make test-flow`

FIX: Clean up directory with blocks

---

.packer/win/scripts/vcpkg.ps1
vcpkg/build_iroha_deps.sh
vcpkg/patches/0001-iroha-ed25519-Initial-port.patch
vcpkg/patches/0003-tbb-Update-to-new-repository.patch

- `tbb` repository has been changed to https://github.com/oneapi-src/oneTBB from https://github.com/intel/tbb, causing the related hash to be modified. This patch allows to successfully build vcpkg considering the change.
- Backport changes for ignoring whitespaces to successfully apply patches on Linux and Windows.
Build works
None

vcpkg: update tbb to new repository

---

libs/cache/abstract_cache.hpp
libs/cache/cache.hpp
libs/common/ring_buffer.hpp
test/module/libs/cache/cache_test.cpp

Redesign cache with ring buffer. It shows much better performance.
performance profit

Cache redesign

---

docker/release/Dockerfile
docker/release/entrypoint.sh

The docker entrypoint was changed, to allow run iroha with custom flags. Also it was changed as recommended in docker best-practices: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint
1. Run iroha with custom flags 
2. Run iroha tools from container:
```
docker run -it  soramitsu/iroha:PR-425 iroha-cli
```
I did not find information about positional arguments in iroha. If we will have it, we should rewrite docker entrypoint.sh .
```
docker pull soramitsu/iroha:PR-425 
```
https://github.com/hyperledger/iroha-deploy/pull/19

DOPS-935 Iroha support cli option in docker entrypoint.sh

---

docker/develop/Dockerfile

[DOPS-947]: Fix Iroha develop `dockerfile`.
We have got broken CI process for Iroha. The problem was in `pip` unsatisfied dependency. The problem has been solved. Also, the solution has been tested.
None

[DOPS-947] Python dependencies have been fixed

---

docker/release/Dockerfile

[Maintenance]: Fix Iroha release `dockerfile`.
We have got broken CI process for Iroha. The problem was in `iroha.deb` unsatisfied dependency. New PPA repository was added.
None

[Maintenance] Fix/python dependencies

---

iroha_network/src/lib.rs

1. Pass state as the param for listen functions in iroha_network
2. Errors are represented as `String` instead of `Box<dyn Error>`
Now it will be possible to capture state in async functions (as async currently does not support closures). Also it in general simplifies work with the shared state.
Example can be found in `single_threaded_async_stateful` test.

Pass state as the param for listen functions in iroha_network

---

irohad/main/impl/pending_transaction_storage_init.cpp
irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor.hpp
irohad/multi_sig_transactions/mst_processor_impl.hpp
irohad/multi_sig_transactions/mst_types.hpp
irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
irohad/multi_sig_transactions/transport/impl/mst_transport_stub.cpp
irohad/multi_sig_transactions/transport/mst_transport_grpc.hpp
irohad/multi_sig_transactions/transport/mst_transport_stub.hpp
irohad/network/impl/async_grpc_client.hpp
irohad/network/mst_transport.hpp
irohad/torii/processor/impl/transaction_processor_impl.cpp
test/module/irohad/consensus/yac/peer_orderer_test.cpp
test/module/irohad/multi_sig_transactions/mock_mst_transport.hpp
test/module/irohad/multi_sig_transactions/mock_mst_transport_notification.hpp
test/module/irohad/multi_sig_transactions/mst_mocks.hpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp
test/module/irohad/multi_sig_transactions/transport_test.cpp
test/module/shared_model/interface_mocks.hpp

- Add response callback parameter to AsyncGrpcClient. Now it is possible to process responses for asynchronous network calls.
- Add response status handling to MST transport. Allows not to assume that the diff was received as in https://github.com/hyperledger/iroha/pull/362 , but to make a decision based on the status instead.
It is also possible to implement an alternative approach to https://github.com/hyperledger/iroha/pull/364 based on an alternative response structure.
Ability to process responses for asynchronous network calls
None

MST: use response from transport

---

docker/release/Dockerfile

[Maintenance]: Fix Iroha release `dockerfile`.
The `apt` cache is updated after adding of test PPA repository.
None

[Maintenance] Fix/1.1.x python dependencies

---

Jenkinsfile

Command `git describe --tags --exact-match 561526112dc2666cdfdbd888984a9fef9b8ed66d` returns only one tag, but we can have situation then 2 tags have same commit (e.g: `latest` and `1.1.3`)
This command will return only first tag `1.1.3`.
This PR uses build in Jenkins variable  `env.TAG_NAME` it contains current building tag or `Null`
Can have multiple tags on single commit. 
Complicated to test, we will test it with next release.

DOPS-967  Update ci, push the right tag

---

irohad/synchronizer/impl/synchronizer_impl.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp

grpc does not support changing call deadline after the call was started. this means that for long calls, like blocks stream, we either should not use deadline, or be able to split long calls into shorter ones. This implements the second approach for synchronizer.
when block loader is unable to provide the full chain before the call deadline, we can still apply it in parts with multiple calls, keeping the progress.

synchronizer: continue applying blocks after failure on halfway

---

iroha/src/config.rs
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs

Problems and fixes:
1. task::spawn not executing -> `futures::join`
2. keys were not generated in the test -> are generated now
3. Sumeragi was constantly locked, so handle_message was not called -> introduced time interval

Fixes integration test with asset creation with several peers

---

.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/text-variables.groovy
Jenkinsfile
docker/develop/Dockerfile

- Add option to enable Hyperledger Burrow support in CMake for Linux builds
- Add step for "Before merge to trunk" scenario to use Burrow
Catch regressions regarding Burrow support
None

Infrastructure: add USE_BURROW option to Jenkins CI

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor_impl.hpp
irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
irohad/multi_sig_transactions/transport/impl/mst_transport_stub.cpp
irohad/multi_sig_transactions/transport/mst_transport_grpc.hpp
irohad/multi_sig_transactions/transport/mst_transport_stub.hpp
irohad/network/mst_transport.hpp
test/framework/integration_framework/fake_peer/fake_peer.cpp
test/module/irohad/multi_sig_transactions/mock_mst_transport.hpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp
test/module/irohad/multi_sig_transactions/transport_test.cpp

Fix the changes done in https://github.com/hyperledger/iroha/pull/442
`composite_subscription` was unsubscribed after the first response, leading to all subsequent calls to `sendState` being not done. A more idiomatic approach with `flat_map` is used now.
MST propagates state more than once...
`MstState` is copied to callback for example, but a more efficient solution will require changes in interfaces

MST: fix rx usage to send state 

---

irohad/consensus/yac/impl/yac_crypto_provider_impl.cpp
libs/common/hexutils.hpp
shared_model/builders/protobuf/unsigned_proto.hpp
shared_model/cryptography/CMakeLists.txt
shared_model/cryptography/crypto_provider/crypto_model_signer.hpp
shared_model/cryptography/crypto_provider/crypto_signer.cpp
shared_model/cryptography/crypto_provider/crypto_signer.hpp
test/integration/acceptance/tx_acceptance_test.cpp
test/module/irohad/multi_sig_transactions/mst_test_helpers.hpp
test/module/irohad/torii/processor/transaction_processor_test.cpp
test/module/shared_model/backend_proto/shared_proto_queries_test.cpp
test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
test/module/shared_model/cryptography/crypto_usage_test.cpp

Note: This PR is based on the changes in #263, so that should be reviewed before this one. 
This change modifies the `CryptoSigner` to run the correct signing implementation, depending on the input public key type. 
`KeysManagerImpl` also had to be changed so it can correctly load both ursa-keys and iroha-keys from files, depending only on the imported public key. This also assumes Iroha is compiled with the build flag `LIBURSA=ON`.
During runtime, Iroha can correctly load ursa-generated keys or iroha-generated keys from files, and use them to sign and verify blocks. 
None

Use the crypto provider corresponding to public key type during runtime

---

test/integration/pipeline/multisig_tx_pipeline_test.cpp

Pending storage is cleared after commit now. Tests depended on previous logic when pending storage was cleared when proposal was received. Tests now wait for commit before making pending transactions queries.
Less nondeterministic behavior
None

MST tests: wait for commit before get pending query

---

irohad/ametsuchi/block_storage.hpp
irohad/ametsuchi/impl/flat_file_block_storage.cpp
irohad/ametsuchi/impl/flat_file_block_storage.hpp
irohad/ametsuchi/impl/in_memory_block_storage.cpp
irohad/ametsuchi/impl/in_memory_block_storage.hpp
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/postgres_block_storage.cpp
irohad/ametsuchi/impl/postgres_block_storage.hpp
irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
shared_model/backend/protobuf/impl/transaction.cpp
shared_model/backend/protobuf/transaction.hpp
shared_model/interfaces/common_objects/range_types.hpp
shared_model/interfaces/transaction.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/ametsuchi/in_memory_block_storage_test.cpp
test/module/irohad/ametsuchi/mock_block_storage.hpp
test/module/shared_model/interface_mocks.hpp

remove transactions copy

---

iroha/benches/validation.rs
iroha/src/account.rs
iroha/src/bridge.rs
iroha/src/crypto.rs
iroha/src/event.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/permission.rs
iroha/src/wsv.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/high_load_transfer.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs

Removed keypair generation for a bridge account, keyless accounts are used instead.
Removed `owner_asset` asset, because all bridge-related information is stored in `bridge_asset` already.
Added `Fail` ISI for explicit errors.

Bridge registration changes & tests

---

iroha/src/asset.rs
iroha/src/bridge.rs

Currently, all values in the asset-store are stored as a `String`. This imposes some limitations when storing arbitrary binary data (for example an object serialized with `parity-scale-codec`) due to strong Rust's assumptions that all strings contain valid UTF-8 encoded data. So if one wants to store such data, he will need to use unsafe code.
This PR proposes the first iteration for resolving the issue.
An ability to store any data in a compact format
Non-human-readable data

Binary-value asset store (first iteration)

---

iroha/src/account.rs
iroha/src/bridge.rs
iroha/src/isi.rs
iroha/src/lib.rs
iroha/src/permission.rs

Signed-off-by: Maksim Surkov <modbrin@gmail.com>
Added `isi::remove_client` function in `bridge` module in accordance with `UnregisterBridgeClientComponent` function of Bridge Contract. Added required underlying functionality, in particular: Remove ISI, RemoveSignatory ISI, CanRemoveSignatory permission.
Possibility to remove bridge client so it will not participate in quorum and therefore have no effect on transaction processing.
Tests may need to be extended and de-duplicated as of similar fragments with isi::add_client function.

Bridge: remove clients

---

Cargo.toml
iroha_client_no_std/Cargo.toml
iroha_client_no_std/src/account.rs
iroha_client_no_std/src/asset.rs
iroha_client_no_std/src/client.rs
iroha_client_no_std/src/config.rs
iroha_client_no_std/src/domain.rs
iroha_client_no_std/src/event.rs
iroha_client_no_std/src/isi.rs
iroha_client_no_std/src/lib.rs
iroha_client_no_std/src/peer.rs
iroha_client_no_std/src/permission.rs
iroha_client_no_std/src/query.rs
iroha_client_no_std/src/tx.rs

This PR introduces new `iroha_client_no_std` crate with extracted from Iroha basic domain models like `Instruction`, `Peer`, `Domain`, `Account` etc. This should help in porting Iroha to `no_std` and ease client libraries.

Extract Iroha domain entities for no-std client

---

irohad/ametsuchi/impl/postgres_command_executor.cpp
test/integration/executor/create_account_test.cpp

fixed bug:
root permission was not enough when creating an account in a domain with default role that is not a subset of creator's permissions.
make root great again

Ametsuchi: fixed root permission for account creation

---

irohad/main/impl/pg_connection_init.cpp

before this, after a temporary failure in connection to PostgreSQL, the database was changed from working to maintenance, which is wrong and is fixed in this PR.
hopefully working reconnection
lack of autotests

PostgreSQL: reconnect to working database after failure

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/burrow_vm_caller.cpp
irohad/ametsuchi/impl/burrow_vm_caller.hpp
irohad/ametsuchi/impl/postgres_command_executor.cpp
irohad/ametsuchi/vm_caller.hpp
test/integration/executor/call_engine_test.cpp
test/integration/executor/get_engine_receipts_test.cpp
test/module/irohad/ametsuchi/mock_vm_caller.hpp

Remove sql dependency from VmCaller, so that other backends can pass their own BurrowStorage instead.
Other potential backends can use VmCaller
None

Ametsuchi: remove sql dependency from VmCaller

---

irohad/ametsuchi/impl/postgres_query_executor.cpp
test/integration/acceptance/hex_keys_test.cpp

Due to changes of shared_model, hex strings are now passed directly to validation and have to be checked without considering the case of individual characters.
Query validation works with any character case of public key
None

Make query signature check case-insensitive

---

docs/source/develop/api/commands.rst
irohad/ametsuchi/impl/postgres_command_executor.cpp
shared_model/backend/protobuf/commands/impl/proto_compare_and_set_account_detail.cpp
shared_model/backend/protobuf/commands/proto_compare_and_set_account_detail.hpp
shared_model/interfaces/commands/compare_and_set_account_detail.hpp
shared_model/interfaces/commands/impl/compare_and_set_account_detail.cpp
shared_model/schema/commands.proto
test/module/irohad/ametsuchi/postgres_executor_test.cpp
test/module/shared_model/command_mocks.hpp
test/module/shared_model/mock_objects_factories/mock_command_factory.cpp
test/module/shared_model/mock_objects_factories/mock_command_factory.hpp
test/module/shared_model/validators/field_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

there was a bug in 1.1.x when `CompareAndSetAccountDetail` was first added it did not check for old_value in command to be empty when the old value in WSV was empty. this was fixed in 1.2, but since it was already part of stable API, we need the the buggy behaviour (sic!) by default. This PR adds a flag that allows to turn this bug off, which should be done explicitly.
yay a flag to turn bugs off
messy API

Commands: added CompareAndSetAccountDetail.need_to_check_empty for legacy compat

---

docker/develop/Dockerfile

Prevent build errors such as here https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-666/2/pipeline
```
commands.CommandError: We expect a missing `_needs_stub` attribute from older versions of setuptools. Consider upgrading setuptools.
```
Dockerfile build works
None

Develop Dockerfile: install setuptools and wheel

---

cmake/Modules/Findursa.cmake

[IR-839](https://jira.hyperledger.org/browse/IR-839)
the flags in question were previously ignored with a warning, and now produce an error to avoid misleading usage. this means, all previous usage and testing was with the default features enabled, and thus it seems reasonable to keep them.
HL Ursa builds on cargo 1.40+.

building: remove ursa feature build flags

---

shared_model/validators/protobuf/proto_command_validator.cpp

As precision type in shared model is uint8, uint32 precision in protobuf was not checked for overflows. This PR adds range check before casting it into shared model type.
No precision overflows.
Backward compatibility issues

ProtoCommandValidator: add precision validation

---

irohad/ametsuchi/impl/postgres_specific_query_executor.cpp

Case-insensitive hash checks in PostgresSpecificQueryExecutor, which allow queries not to fail with valid hashes.
Previous correct behavior restored
None

PostgresSpecificQueryExecutor: case-insensitive hash checks

---

CMakeLists.txt

Enable LTO for Release builds when available using compiler-independent CMake flag
Potential performance improvements
None

Enable LTO for Release builds when available

---

iroha_http_server/Cargo.toml

Signed-off-by: 武宮誠 <takemiya@soramitsu.co.jp>
updates the async-tungstenite dependency

update out of date lib

---

irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/ametsuchi/impl/wsv_restorer_impl.hpp
irohad/main/application.cpp
shared_model/validators/protobuf/proto_block_validator.cpp
shared_model/validators/protobuf/proto_block_validator.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/regression/regression_test.cpp

Add stateless validation for blocks in WsvRestorer
Detect modified block store
None

WsvRestorer: add chain and block object validation

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/main/application.hpp
irohad/main/impl/on_demand_ordering_init.cpp
irohad/main/impl/on_demand_ordering_init.hpp
irohad/synchronizer/synchronizer_common.hpp
test/framework/integration_framework/integration_test_framework.cpp
test/integration/acceptance/add_peer_test.cpp
test/integration/acceptance/fake_peer_example_test.cpp
test/integration/acceptance/remove_peer_test.cpp

Before
```
/tmp/bloaty/bloaty /tmp/build/irohad/main/CMakeFiles/application.dir/impl/on_demand_ordering_init.o -d shortsymbols
FILE SIZE        VM SIZE    
--------------  -------------- 
96.3%   380Mi   0.0%       0    [section .debug_str]
1.7%  6.70Mi  64.7%   618Ki    [5655 Others]
0.5%  2.03Mi   0.0%       0    [section .rela.debug_info]
0.4%  1.75Mi   0.0%       0    [section .debug_info]
0.2%   882Ki   0.0%       0    [section .shstrtab]
0.2%   614Ki   0.0%       0    [ELF Headers]
0.1%   318Ki   0.0%       0    [section .symtab]
0.1%   304Ki   0.0%       0    [section .strtab]
0.1%   269Ki  28.2%   269Ki    [section .eh_frame]
0.1%   266Ki   0.0%       0    [section .debug_line]
0.1%   264Ki   0.0%       0    [section .rela.debug_ranges]
0.1%   220Ki   0.6%  5.40Ki    std::move<>() …
```

Reduce rxcpp debug symbols size

---

.jenkinsci/builders/x64-linux-build-steps.groovy
.jenkinsci/text-variables.groovy
.jenkinsci/utils/doxygen.groovy

We use `https://iroha.readthedocs.io` instead of `docs.iroha.tech` to store the Iroha documentation.
We don't need the push step anymore. Documentation is built on the `readthedocs.io` side.
Signed-off-by: Roman Gavrilov <gavrilov@soramitsu.co.jp>

Documentation push step was deleted

---

iroha/config.json

Signed-off-by: Sonoko Mizuki <sonoko@mizuki.io>
Add `TRUSTED_PEERS` to the default config
`TRUSTED PEERS` contains public key same as in docker-compose.yml
Even if trusted peers does not run, Iroha doesn't stop.

add default trusted peers to the config

---

iroha/Cargo.toml

As you may have noticed our coverage CI job have failed recently, due to compilation errors.
With the new nightly version 1.49 rustc improvements (rust-lang/rust#77638) were introduced, that fail the compilation of our dependencies in nightly rust and our coverage tool uses nightly rust.
Therefore it is needed to increment `heim` library version, where the problems are fixed in its dependency `uom` library.
The master branch coverage job should work correctly after this fix.

Fixes coverage job

---

.jenkinsci/builders/x64-mac-build-steps.groovy

Set LOCATION search policy for Python3 explicitly, so that it uses the first found Python from path instead of searching for the highest available version.
Correct Python is used from the environment.
None

Infrastructure: use LOCATION Python3 search policy for CMake

---

iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/tests/restart_peer.rs

- tx queue limit for pending tx introduced
- fixes for initialization logic: sumeragi gets blockhash and height after kura has loaded all the blocks
- test for peer restart

Queue tx tx number limit and Iroha initialization fixes

---

docs/source/iroha_2_whitepaper.md
iroha/benches/validation.rs
iroha/src/isi.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/permissions.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/src/world.rs
iroha/src/wsv.rs
iroha_client/benches/torii.rs
iroha_client/tests/add_asset_should_propagate_to_another_peer.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/cucumber.rs
iroha_client/tests/multiple_blocks_created.rs
iroha_client/tests/transfer_asset.rs
iroha_client_cli/src/main.rs
iroha_data_model/src/lib.rs
iroha_dsl/tests/dsl.rs
iroha_permissions_validators/src/lib.rs

Introduces World struct to improve top level ISI design (e.g. `Register<World, Domain>`). Previously to register the domain for example we had to do the following `Register<Peer, Domain>` and supply `PeerId` in there, but this peer id would be useless and will only confuse users. Instead now this instructions have `World` as their target.
Also this PR removes `Peer` from `WorldStateView` as the peer id is not needed there.

Introduces World struct

---

iroha_data_model/Cargo.toml
iroha_data_model/src/expression.rs
iroha_data_model/src/lib.rs

Instruction are designed in a way that they mutate state.
But for smart contract logic, we mostly want to mutate state only in the end, at first we need to perform some calculations.
Therefore expressions are introduced, which are a composable dsl, allowing to perform calculations and use them in instructions.

Expressions for ISI

---

Dockerfile
Dockerfile.debug
DockerfileCLI
iroha_client_cli/config.json

Signed-off-by: Alexey-N-Chernyshov <alexey.n.chernyshov@gmail.com>
Build moved to docker.
Add ACCOUNT_ID to client config.
Can build on different architectures.
Can be simplified with `cargo install --path .` if it is supported in build manifest.
Alternative docker base can be used, not only Alpine linux.

Build in docker

---

iroha_macro/iroha_derive/Cargo.toml
iroha_macro/iroha_derive/src/lib.rs
iroha_macro/iroha_derive/tests/from_variant.rs
iroha_macro/iroha_derive/tests/from_variant/01-big-enum.rs
iroha_macro/iroha_derive/tests/from_variant/02-double-from.rs
iroha_macro/iroha_derive/tests/from_variant/03-container-enums.rs
iroha_macro/iroha_derive/tests/from_variant/04-container-from.rs
iroha_macro/iroha_derive/tests/from_variant/05-struct.rs

Add easy way to add other containers to FromVariant macro. Now it supports deriving from Mutex, Box, Cell, RefCell, RwLock, Rc, Arc.

Add other containers for FromVariant derive macro

---

iroha/src/block.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_client/src/client.rs
iroha_client/tests/permissions.rs
iroha_data_model/src/events.rs

Add more type-safety to RejectionReason via enum.
It is more typesafe and gives more context to users. Also in future it can allow other implentations of Iroha2.
Some errors are interconnected between several crates and cannot be fully contained in RejectionReason so some variants will always be String.

Add RejectionReason enum for pipeline events

---

docs/source/conf.py
docs/source/getting_started/python-guide.rst
docs/source/requirements.txt

Previously there was a page with step-by step description of the example that was actually changing: https://iroha.readthedocs.io/en/master/getting_started/python-guide.html and it is not working - neither conceptually as pieces of code nor de facto as the code is outdated.
So it was decided to simply include the actual example code there and just move the comments to the example itself. Here is the part that 1) includes the example; 2) provides the necessary extensions to allow this idea to build. Also see https://github.com/hyperledger/iroha-python/pull/68
Closes #872
Consistent example 
Python repo is not yet moved to main from master. Will need to update the include, otherwise it will simply break at some point.

Docs: Fixing Getting Started Python Example

---

.packer/win/windows-build-server.json
vcpkg/patches/0004-vcpkg_find_acquire_program-Use-msys-for-pkg-config.patch

Increase disk size for Windows machines in order to have enough space for builds.
Windows builds work.
None

Infrastructure: increase Windows CI disk size

---

iroha/src/queue.rs
iroha/src/torii.rs
iroha_client/src/config.rs
iroha_network/src/lib.rs
iroha_network/src/mock.rs

https://jira.hyperledger.org/browse/IR-1035
Rust 1.50.0 introduced better const fns. Some constants has value of power of 2 and was written as literals. In this PR such constants  was represented as result of const function invocation.
More clear how the const was designated

Replace constants with power of 2 IR-1035

---

irohad/ordering/impl/on_demand_ordering_service_impl.cpp

Remove `boost::adaptors::filter` which could be dereferenced multiple times causing performance decrease.
Simpler code
None

OnDemandOrderingServiceImpl: remove boost::adaptors::filter usage

---

.github/CODEOWNERS

Signed-off-by: Aler Denisov <aler.zampillo@gmail.com>
Adding @alerdenisov as the code owner.
Code owners are automatically requested for review when someone opens a pull request that modifies code that they own
Not found

Add @alerdenisov as a code owner of iroha2-dev branch

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs

Unwrap Arc<RwLock<Sender/Reciever>>, because channels synchronised inside, so no need for locks. Also make some torii parts of requests blocking.
There will be less of useless deadlocks in future.

Remove Arc and Rwlock for channels

---

iroha/src/asset.rs
iroha/src/query.rs
iroha/src/wsv.rs

https://jira.hyperledger.org/browse/IR-1061
Fixup of panic on adding asset to blockchain. It could panic if there is no account for asset.
No panics and accidental peer crush.

Fix wsv panic at adding asset IR-1061

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
iroha/src/event.rs

This pr fixes ci by adding more time for timeout to requests to peers in tests.
CI with extremely fast network speed (as it is within one device) doesn't handle incoming messages fast enough, so it fills up with messages and peers have to wait.
Longer ci times

Ci timeout test fix

---

iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha_config/iroha_config_derive/src/lib.rs
iroha_config/src/lib.rs
iroha_config/tests/simple.rs
iroha_logger/src/lib.rs

Pr removes setting of config variables inside locks, leaving only getting field and docs.
No unused code in repo

Remove old code from iroha_config

---

.gitignore
Cargo.lock
docs/source/references/api_spec.md
iroha/Cargo.toml
iroha/src/maintenance.rs
iroha/src/torii.rs
iroha_client_cli/Cargo.toml

https://jira.hyperledger.org/browse/IR-1076
Fixup health endpoint. Now it responds with nice text output with current status of peer. Updated some of the libraries like heim. 
Heim is now of version 0.1.0-rc.1 unfortunately 0.0 version doesn't support aarch64 which is in tier 1 support list for rust toolchain.

Fixup health endpoint

---

iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/kura.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/src/wsv.rs

https://jira.hyperledger.org/browse/IR-1047
Blocks right now are in kura which supposed to be used for initialization from disk, while we have world state view which supposed to have all blocks (as name suggests and according to whitepaper).
Queries will be easier to implement.

Move blocks from kura to wsv IR-1047

---

Cargo.lock
docs/source/references/config.md
iroha/src/lib.rs
iroha/src/sumeragi.rs
iroha/src/torii.rs
iroha/test_network/src/lib.rs
iroha_logger/Cargo.toml
iroha_logger/src/layer.rs
iroha_logger/src/lib.rs
iroha_logger/src/telemetry.rs
iroha_logger/tests/telemetry.rs

https://jira.hyperledger.org/browse/IR-1056
This pr adds telemetry for future prometheus endpoint. It is done by using tracing and its specific filters.
Easy and transparent telemetry gathering.
Slowing down of system.

Tracing telemetry subscriber

---

irohad/main/server_runner.cpp

when waiting response to a big (more than 4MB) message.
Send long transactions batch (more than 250)
```
from iroha import *
def public_key_from_private(private_key: str):
return IrohaCrypto.derive_public_key(private_key).decode('utf-8')
def send_signed_batch_transaction(txs, net):
net.send_txs(txs)
for tx in txs:
print(f'Transaction hash = {calculate_hash_of_transaction(tx)}')
for status_name, status_code, error_code in net.tx_status_stream(tx, timeout=20):
print(f'\tstatus_name:{status_name}, status_code:{status_code}, error_code:{error_code}')
def calculate_hash_of_transaction(transaction_with_payload):
h = IrohaCrypto.hash(transaction_with_payload)
return binascii.hexlify(h).decode("utf-8")
if __name__ == '__main__':
IROHA_HOST_ADDR = os.getenv('IROHA_HOST_ADDR', 'localhost') …
```

826 fix grpc msg size

---

Cargo.lock
iroha/src/config.rs
iroha/src/main.rs
iroha/src/torii.rs
iroha_client/src/config.rs
iroha_client/tests/end_to_end/unstable_network.rs
iroha_client_cli/src/main.rs
iroha_crypto_cli/src/main.rs
iroha_error/Cargo.toml
iroha_error/src/lib.rs
iroha_error/src/reporter.rs
iroha_logger/Cargo.toml
iroha_logger/src/lib.rs

https://jira.hyperledger.org/browse/IR-1019
Add panic handler with stacktrace and error reporting. Add error reporter for `iroha_error::Error`. Now it can be nicely formatted  everywhere if needed.
More context where needed on errors.

Add nice panic and error reporters

---

iroha_error/src/wrap_err.rs

Fix of error reporter. Beforehand we skipped one error and just went to its source (this was unintentional). This pr goes straight to wrapped error's error as source.
All error level printings. No error skipping.

Reporter fixup

---

Cargo.lock
docs/source/tutorials/mint-your-first-asset.md
iroha_client_cli/Cargo.toml
iroha_client_cli/README.md
iroha_client_cli/src/main.rs
iroha_crypto/Cargo.toml
iroha_crypto/src/lib.rs
iroha_data_model/src/lib.rs
scripts/test_docker_compose.sh
scripts/test_genesis_docker_compose.sh

https://jira.hyperledger.org/browse/IR-1082
This pr migrates from using clap for parsing cli arguments to structopt crate. Also it introduces simple queries for accounts, assets and domains.
There will be typesafe descriptive structures for cli arguments which remove all boilerplate code. It will also let us easier add new commands to cli and manage existing ones. Apart from that it would be more error prune than our previous implementation.
Also now we are able to query domains, accounts, and assets via cli.

Migrate from clap to structopts for cli

---

Cargo.lock
Cargo.toml
Dockerfile
docker-compose-single.yml
docker-compose.yml
iroha/Cargo.toml
iroha_cli/Cargo.toml
iroha_cli/README.md
iroha_cli/src/main.rs

This commit separates iroha and iroha_cli and makes permissions in iroha 2 for public blockchain use cases.

Move main.rs into separate crate and enable default permissions for public blockchain

---

iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/config.rs
iroha/src/kura.rs
iroha/src/smartcontracts/isi/account.rs
iroha/src/smartcontracts/isi/asset.rs
iroha/src/smartcontracts/isi/domain.rs
iroha/src/smartcontracts/isi/tx.rs
iroha/src/smartcontracts/mod.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha_config/src/lib.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/events.rs
iroha_data_model/src/lib.rs
iroha_error/src/lib.rs
iroha_error/src/message_error.rs
iroha_logger/src/layer.rs
iroha_logger/src/lib.rs
iroha_macro/iroha_derive/src/lib.rs
iroha_version/iroha_version_derive/src/lib.rs
iroha_version/src/lib.rs

Right now structs, enums and etc. are mentioned by simply putting them in ``.
I changed them to actual links instead, so that documentation will be easier to browse.
Documentation is easier to browse.
None.

Changed text entities to links in docs.

---

iroha/src/sumeragi.rs

If trusted peers' file could not be opened it is not clear which file failed to load. Now it will log file type and path.
https://jira.hyperledger.org/browse/IR-1129
It will be clearer what file is missing or unavailable.
I create an error message ahead of opening the file because otherwise the path will be taken by `Path::open()`, and we have no clear type of parameter, it couldn't be cloned.
I think one such string allocation on the start of app is no big deal.

Added clear error text and filename if TrustedPeers could not be loaded.

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr.yml
Cargo.lock
Dockerfile
iroha_crypto/Cargo.toml

Fixed dependency on pkg-config for using OpenSSL sources from the system. It will compile them from `openssl-src` crate.
https://jira.hyperledger.org/browse/IR-1133
Easier build of iroha2.
I think none.

Added vendored OpenSSL to build, fixes pkg-config dependency.

---

Cargo.toml
iroha_logger/Cargo.toml
iroha_logger/src/lib.rs

Captures logs in tests unless test fails
For more details see https://docs.rs/tracing-subscriber/0.2.18/tracing_subscriber/fmt/struct.TestWriter.html
Tests output will not be full of unnecessary logs, only the logs of the tests that failed will be shown.

Captures logs in tests unless test fails

---

iroha/src/smartcontracts/isi/mod.rs
iroha/src/wsv.rs

The message:
`ERROR iroha::block_sync::message: error=Failed to find block with this hash. Caused by: ef92eb136a9a499d52eb72d131aa882560a2ed74cd386a9abda8d583e0a43f8b`
Will become:
`ERROR iroha::block_sync::message: error=Block not found. Block with parent hash ef92eb136a9a499d52eb72d131aa882560a2ed74cd386a9abda8d583e0a43f8b not found`
More clear error description.
Partial repetition of error message is a drawback of current error deriving mechanism.

Fixed error message if child block not found.

---

iroha/src/wsv.rs
iroha_data_model/src/lib.rs
iroha_dsl/tests/dsl.rs

Remove assets that have zero value after some operations on them.
For example, if user has moved all assets elsewhere.
It will give storage and performance improvement.
Checks are performed after any operation. Could they slowdown or not?

Remove zero-value assets from accounts after operating upon.

---

iroha/src/event.rs
iroha/src/torii.rs
iroha_client/src/client.rs
iroha_client/src/config.rs
iroha_client/tests/permissions.rs
iroha_data_model/src/events.rs
iroha_schema/iroha_schema_bin/src/main.rs

The message means that event connection is initialized and will be supplying events starting from the next one.
This fixes the problem that client does not know at what point he will start receiving all events that are specified by its filter.
`submit_blocking` is reliable now, previously there were conditions when it might fail due to peer being faster than the client.
https://jira.hyperledger.org/browse/IR-1137

Introduces SubscriptionAccepted message

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.gitignore

Uses source based coverage with grcov.
https://github.com/mozilla/grcov#example-how-to-generate-source-based-coverage-for-a-rust-project
This should improve the correctness of coverage reports.
https://jira.hyperledger.org/browse/IR-1136

Uses source based coverage with grcov

---

docs/source/configure/index.rst
example/config.sample

Emphasized that pg_opt are depricated, made example in the docs load from https://raw.githubusercontent.com/hyperledger/iroha/main/example/config.sample
Also fixed the `example/config.sample` so it would contain "database" parameter instead of "pg_opt". 
Config example will be up to date automatically. 
Relative links are not possible here and the absolute links to the config example should lead to the default branch, which might not be yet updated. 
Not a big issue as in the description of the parameters after the example it is possible to still add the missing parameters as they are mostly optional in cases where they are not in the default branch. 
Another one is that the example in docs was way fuller - it also included parameters that are …

Docs: Fixed Config example in Docs

---

irohad/ametsuchi/impl/rocksdb_command_executor.cpp
test/module/irohad/ametsuchi/rocksdb_executor_test.cpp

Hotfix! Read precision in SubstractAssetQuantity.

[RDB] read precision in SubstractAssetQuantity

---

iroha/src/block.rs
iroha/src/lib.rs
iroha/src/smartcontracts/isi/mod.rs
iroha/src/smartcontracts/isi/permissions.rs
iroha/src/sumeragi.rs
iroha/src/tx.rs
iroha/test_network/src/lib.rs
iroha/test_network/tests/mock.rs
iroha_permissions_validators/src/lib.rs

This will enable us to check permissions for query, with the use of already written combinators.
Introduces Generic Permission Validator
This will enable us to check permissions for query, with the use of already written combinators.
More generics make code harder to read, but this is somewhat mitigated by type aliases.

Introduces Generic Permission Validator

---

iroha/src/queue.rs

Previously if signature in transaction did nod pass condition described in account, then nothing was logged and there is no way to define if something wrong. Such situation can occur, for example, when transaction was signed with key that was not associated with the account
A little help to define what happened
Additional computation during handling transactions ready to be comitted

Added logging if transaction does not passed signature check condition IR-1168

---

docs/source/references/config.md
iroha/benches/validation.rs
iroha/src/block.rs
iroha/src/block_sync.rs
iroha/src/genesis.rs
iroha/src/kura.rs
iroha/src/sumeragi/mod.rs
iroha/src/sumeragi/network_topology.rs
iroha/src/sumeragi/view_change.rs
iroha/src/torii.rs
iroha/src/tx.rs
iroha/test_network/tests/sumeragi_with_mock.rs
iroha_client/src/client.rs
iroha_client/src/config.rs
iroha_crypto/src/lib.rs
iroha_data_model/src/lib.rs

Closes #1123 
- Store proofs
- Use these proofs in BlockCreated to be up to date
- Refactor view change handling logic (now it is universal)
If several peers join the network late they will not only get blocks, but also view changes on top of these blocks. This will help them with syncing.

Store proof of view changes

---

docs/source/develop/api/queries.rst
irohad/ametsuchi/impl/postgres_specific_query_executor.cpp
shared_model/backend/protobuf/queries/impl/proto_tx_pagination_meta.cpp
shared_model/backend/protobuf/queries/proto_tx_pagination_meta.hpp
shared_model/builders/protobuf/builder_templates/query_template.hpp
shared_model/interfaces/queries/impl/tx_pagination_meta.cpp
shared_model/interfaces/queries/tx_pagination_meta.hpp
shared_model/schema/queries.proto
shared_model/validators/protobuf/proto_query_validator.cpp
shared_model/validators/validators_common.cpp
shared_model/validators/validators_common.hpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/shared_model/mock_objects_factories/mock_query_factory.cpp
test/module/shared_model/mock_objects_factories/mock_query_factory.hpp
test/module/shared_model/query_mocks.hpp
test/module/shared_model/validators/protobuf/proto_query_validator_test.cpp

This is prove of concept for extending queries with time interval (from,to). Protobufs were modified and some basic logic was added. Validation of passed strings is not provided yet. Modified queries are getAccountTransactions and GetAccountAssetTransactions
Protobufs were modified, then neccesary getters were added.
Passed parameters are attached to sql query in executeTransactionsQuery, by applyer lamba function,
created separately in each function
What benefits will be realized by the code change? 
Allowing to query for Transactions in given time interval and beetwen two given block heights
What are the possible side-effects or negative impacts of the code change? 
Usage of many if's in GetAccountTransactions/GetAccountAssetTransactions in postgres_specific_query_executor.cpp
By …

Extending queries by modifing TxPaginationMeta

---

Cargo.lock
iroha/Cargo.toml
iroha/src/merkle.rs
iroha_crypto/Cargo.toml
iroha_crypto/src/lib.rs
iroha_p2p/Cargo.toml

Ursa version bump from 0.3.5 to 0.3.6
1. Compatibility with latest wasmtime.
2. In general we should update crates to most recent versions.
3. 0.3.5 seems to have problems with a recently deprecated crate `aesni`

Ursa version bump from 0.3.5 to 0.3.6

---

iroha/src/torii.rs
iroha_network/src/lib.rs
iroha_network/src/mock.rs
iroha_network/src/network.rs

Currently we dont modify state itself, so we dont need rwlock on top of it, as every access is safe.
Less boilerplate, faster execution.

Remove rwlock from torii

---

iroha/src/block_sync.rs
iroha/src/kura.rs
iroha/src/queue.rs
iroha/src/sumeragi/mod.rs
iroha/test_network/tests/sumeragi_with_mock.rs
iroha_actor/src/broker.rs
iroha_actor/src/lib.rs

1. Unsubscribe from broker on actor stop
2. Support multiple subscriptions from the same actor type (previously a TODO)
3. Fixes a bug where broker always put self as an actor id.
Check out `Broker bug - test showcase` commit and run the tests added there - you will notice it fails.
The test case just tries to send a message of one type to two subscribers - should be perfectly okay logically.
Broker in the function `subscribe_recipient` adds self in the place, where I deduce should have been an actual actor type id. Therefore as this place always contains one value - type id of the broker - when several actors/channels subscribe to one message type - only the first actor/channel that subscribed to it will receive it.
While the *expected …

Introduces multiple broker fixes 

---

.github/build-iroha1.src.yml
.github/chatops-gen-matrix.sh
.github/workflows/build-iroha1.yml
docker/iroha-builder/Dockerfile
irohad/synchronizer/impl/synchronizer_impl.cpp
libs/common/permutation_generator.cpp
test/integration/acceptance/get_transactions_test.cpp

* Now **build** takes **much less time** 🕰, with vcpkg binarycaching and ccache shared between workflow runs and jobs: no need to build vcpkg deps (minus 24..30 mins on every run), ccache hit rate is about 15-20% so it saves up to 6 minutes on each debug build, and about 10 mins on release build.
* After pressing button `Update branch`(i.e. merge base branch into PR head) now triggers `/build before-merge` buildspec, so **will be able to merge after CI passed**. Earlier we have had to push a commit with message `/build ...` (it is still best way to tell CI about it is ready to merge). Try it yourself `.github/chatops-gen-matrix.sh --help`
* **Release** build on MacOS and Ubuntu GCC-10 is **fixed**
* **Docker** images iroha-builder, iroha, iroha-burrow, iroha-ursa are pushed to **ghcr.io** …

[GHA] faster with caches, enable github docker registry ghcr.io

---

irohad/subscription/async_dispatcher_impl.hpp
irohad/subscription/scheduler.hpp
irohad/subscription/scheduler_impl.hpp

Adds atomic busy check. Minor refactoring.

[SE] atomic task upload to external handler

---

Cargo.lock
iroha/Cargo.toml
iroha/src/genesis.rs
iroha_schema/iroha_schema_bin/Cargo.toml
iroha_schema/iroha_schema_bin/src/main.rs

Added RawGenesisBlock to schema introspection
Clients will be aware of Iroha2 genesis format. It is very useful for integration tests - allows to specify initial state of the blockchain. Also knowing of genesis format helps for deployment configuration due Genesis in client's code can be serialised and shared

Added `RawGenesisBlock` to schema introspection

---

Cargo.lock
iroha_data_model/src/lib.rs
iroha_schema/Cargo.toml
iroha_schema/src/lib.rs

Altered representation of fixed point
Previously was: 
```json
"iroha_schema::iroha_data_model::fixed::Fixed": "Fixed",
```
Now will be:
```json
"iroha_data_model::fixed::Fixed": {
"TupleStruct": {
"types": [
"FixedPoint<i64>"
]
}
},
"FixedPoint<i64>": {
"FixedPoint": {
"base": "i64",
"decimal_places": 9
}
}
```

Altered  representation

---

iroha/src/init.rs
iroha/src/lib.rs
iroha/src/tx.rs
iroha/test_network/src/lib.rs
iroha_client/benches/torii.rs
iroha_dsl/tests/dsl.rs
iroha_p2p/src/network.rs

Removal of arguments from test_network crate
It is a failure point for us to have arguments in tests, as they force us to read from disk. Also that forces us to take with us 3 configs and put them everywhere in tests.
Less errors due to disk failures. Easier genesis usage in tests.

Removal of arguments from test_network crate

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-pr.yml
Cargo.lock
iroha/Cargo.toml
iroha/src/genesis.rs
iroha/src/lib.rs
iroha/src/queue.rs
iroha/src/sumeragi/mod.rs
iroha/src/torii/mod.rs
iroha/src/tx.rs
iroha/test_network/src/lib.rs
iroha/test_network/tests/sumeragi_with_mock.rs
iroha_client/tests/asset_amount_should_be_the_same_on_a_recently_added_peer.rs
iroha_client/tests/multisignature_transaction.rs
iroha_data_model/src/lib.rs
iroha_p2p/src/peer.rs

https://jira.hyperledger.org/browse/IR-1149
We only read state in torii, so we can safely remove rwlock from there
Removing queue actor in favor of multi producer single consumer queue from crossbeam.
It will be faster and always available in contrast to actor. It will also remove congestions because there will be by one actor less.

Remove queue actor. Substitute with lock free queue

---

.github/build-iroha1.src.yml
.github/chatops-gen-matrix.sh
.github/workflows/build-iroha1.yml
irohad/migration-tool/CMakeLists.txt
irohad/wsv_checker/CMakeLists.txt

* push docker images only with gcc-9 builds
* enable 'latest' for all tags, earlier were 'v*'
* reduce number of docker tags: remove commit-*
* `-DBENCHMARKING=ON`

Add wsv_checker and migration-tool to docker image

---

.github/workflows/iroha2-dev.yml
docker-compose-local.yml
iroha/src/queue.rs
iroha/src/sumeragi/mod.rs
iroha/src/torii/mod.rs
iroha/test_network/tests/sumeragi_with_mock.rs
iroha_client/tests/tests/multisignature_transaction.rs

- Separates gossiping from round in Sumeragi (therefore fixing MST edge case) see #1433
- Fixes a `panic` in queue on `unreachble()!` macro. It seems it is quite reachable :) Under high load and due to parallelism it can be invoked. We might improve the design here later. But for now it can be just replaced with `continue`
- Adds a docker-compose-local.yml setup to build and start containers locally for testing.
Local machine, docker compose with local images on latest dev commit
Submit txs with high frequency manually through iroha_client_cli
Several peers stop doing anything, invalid state is reported by tokio due to `unreachable` macro in queue
After fix I tested locally with the same setup to verify that it is working. Later we can try to come up with appropriate test. See next steps. …

Gossip and queue fixes

---

iroha_logger/src/lib.rs
iroha_logger/tests/log_level.rs
iroha_macro/iroha_derive/tests/from_variant/03-container-enums.rs
iroha_macro/iroha_derive/tests/from_variant/04-container-from.stderr

closes #1484
Fix display of logs with log level less than info.
Beforehand maximum log level withing tracing was set to `INFO`, now we override it with minimum.

Log level fix

---

core/src/block.rs
core/src/queue.rs
core/src/sumeragi/mod.rs
core/src/tx.rs
data_model/src/lib.rs
data_model/src/query.rs
docs/source/references/config.md

Make `Queue` determine if a transaction has been tampered to have a future timestamp,
based on configurable threshold
Close #1494
Prevent future timestamps and make transaction TTLs work well
`DEFAULT_FUTURE_THRESHOLD_MS` may be debatable

Detect future timestamp on queue push

---

hooks/README.md
hooks/commit-msg.sample

* add commit-msg hook which ensures signoff is included
Sometimes dev might forget to include signoff in the commit, this hook will automatically add signoff if missing
Developer has the option to automatically sign-off their commits. 
The developer must understand what `sign-off` means in order to use the feature. And can unwittingly, commit code that they cannot. 
```
$ cp hooks/commit-msg.sample .git/hooks/commit-msg
```
Encouraging the developer to create an alias for commit. Also encouraging the developer to create GPG-signed commits.

add commit-msg git hook to include signoff

---

Cargo.lock
docs/source/references/config.md
telemetry/Cargo.toml
telemetry/src/config.rs
telemetry/src/lib.rs
telemetry/src/retry_period.rs
telemetry/src/ws.rs

Signed-off-by: Alexey Kalita <kalita.alexey@outlook.com>
If telemetry fails to send a message, the node is going to reconnect in a few seconds.
While the telemetry is down, messages are skipped.
The period between reconnects can be customized with MIN_PERIOD and MAX_POWER
Closes #1546

Reconnect telemetry

---

client/tests/tests/events.rs
core/src/sumeragi/mod.rs
core/test_network/src/lib.rs
docs/source/references/api_spec.md
p2p/src/network.rs

Transaction status events are tested:
- By connecting for events to each peer
- By submitting transactions in turn to each peer 
#1492
Thoroughly testing potential bug cases described in the issue.

Transaction status events tested for each of 7 peers

---

client/tests/tests/asset_propagation.rs
client/tests/tests/multisignature_transaction.rs
client/tests/tests/unregister_peer.rs
core/src/samples.rs
core/src/sumeragi/mod.rs
core/test_network/src/lib.rs
core/test_network/tests/sumeragi_with_mock.rs
data_model/src/lib.rs
docs/source/references/config.md

1. Fixes a bug accidentally introduced by FuturesUnordered pr
2. Fixes usual failures of `unregister_peer` test, which did not wait for needed amount of time
In `test_network` and `sumeragi_with_mock` tests in several places there were dependencies on particular order of the responses that `Network::send` (now `Network::send_to_actors_on_peers`) would return. With introduction of `FuturesUnordered` the order is now random there, so tests started failing from time to time.
The general problem was that code that used the function assumed a specific behavior of the function which was neither documented nor contained in a type.
#1637 
We can rely on mock tests again.

Fix mock tests - futures unordered bug

---

Cargo.lock
README.md
client/src/client.rs
configs/prometheus.yml
core/src/block.rs
core/src/queue.rs
core/src/samples.rs
core/src/sumeragi/mod.rs
core/src/torii/mod.rs
core/src/wsv.rs
core/test_network/src/lib.rs
data_model/Cargo.toml
data_model/src/lib.rs
docs/source/references/api_spec.md
docs/source/references/config.md
logger/src/config.rs
logger/src/lib.rs
p2p/src/lib.rs
p2p/src/network.rs
p2p/src/peer.rs

Added a [`prometheus`](https://prometheus.io/docs/introduction/overview/) end-point to iroha2. 
Closes #1216 
Prometheus Monitoring is possible. 
The following metrics are gathered:
- uptime since genesis. 
- currently connected peers
- block height
- total transactions
Small overhead to block commit. 
Install `prometheus`. 
Run an iroha peer (or network) using either 
`docker compose up`
or directly. 
run 
```bash
prometheus --config.file=configs/prometheus.yml
```
to scrape for the metric. 
Transactions per second should be handled by prometheus. 
Could compute a running average of TPS and send it to the status endpoint. 
This is error-prone and unnecessary, since the TPS can be computed while processing the `prometheus` data.

[feature] #1216: Add Prometheus endpoint. 

---

core/src/kura.rs

There is a chance to fail to allocate buffer for block deserialization if its size was corrupted.
At the time try_allocate was still experimental and I coudn't use it. Now it's stable, so this is a planned enchancement.
We no longer depend on some particular "max buffer size" constant.

[feature] #1678: `try_allocate`

---

Cargo.lock
client/tests/integration_tests/add_account.rs
client/tests/integration_tests/add_asset.rs
client/tests/integration_tests/add_domain.rs
client/tests/integration_tests/asset_propagation.rs
client/tests/integration_tests/config.rs
client/tests/integration_tests/events.rs
client/tests/integration_tests/multiple_blocks_created.rs
client/tests/integration_tests/multisignature_account.rs
client/tests/integration_tests/multisignature_transaction.rs
client/tests/integration_tests/offline_peers.rs
client/tests/integration_tests/pagination.rs
client/tests/integration_tests/permissions.rs
client/tests/integration_tests/restart_peer.rs
client/tests/integration_tests/status.rs
client/tests/integration_tests/transfer_asset.rs
client/tests/integration_tests/tx_history.rs
client/tests/integration_tests/tx_rollback.rs
client/tests/integration_tests/unregister_peer.rs
client/tests/integration_tests/unstable_network.rs
core/Cargo.toml
core/src/genesis.rs
core/src/torii/tests.rs
core/test_network/src/lib.rs
core/test_network/tests/sumeragi_with_mock.rs
docs/source/references/config.md

Wait for peers to commit genesis in tests.
Also adds a genesis submission delay, which is useful as peers can take some time to connect to each other.
Faster tests, less uncertainty points in tests that can cause failures.

[feature] #1643: Wait for peers to commit genesis in tests

---

.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-unstable.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-pr-heavy.yml

Moved back to self-hosted runners with a smarter cache. 
closes #1630 
Faster CI time. 
Self hosted runners could be unstable.

[ci] #1630: Move back to self-hosted runners.

---

.github/workflows/iroha2-add-label.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-title.yml
.github/workflows/iroha2-dev-pr-unstable.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-pre1-rc1.yml

[CI] Enable PR CI in branch

---

docs/source/references/api_spec.md

Clarify that there are 2 groups of endpoints:
- `API_URL` based endpoints
- `STATUS_URL` based endpoints
Close #1695
Readability
None

[documentation] #1695: Clarify different ports for endpoints

---

data_model/src/lib.rs
data_model/src/metadata.rs

- Moved metadata module into its own file. 
- Added a `LimitedMetadata` variant  to `Value`, 
- Adding an `Unlimited` variant can cause problems in preserving code invariants.
- Added the `nested_` family of `fn`s, which all operate on a `&Path`, which is a type alias for `Vec<String>` (for now). 
- Nested get, remove and insert functions fail fast if the path is either empty, incorrect, or malformed. 
- Added tests to verify functionality. 
Closes #1144 
Nested metadata. 
None

[feature] #1144: Add metadata nesting

---

configs/peer/config.json
core/src/genesis.rs
core/src/queue.rs
core/src/samples.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/view_change.rs
core/src/wsv.rs
core/test_network/tests/sumeragi_with_mock.rs
docs/source/references/config.md
p2p/src/peer.rs

View change handling fixes
- View change proofs made independent of particular transaction hashes
- Reduced message passing
- Collect view change votes instead of sending messages right away (improves network resilience)
- Fully use Actor framework in Sumeragi (schedule messages to self instead of task spawns)
Improves fault injection for tests with Sumeragi
- Brings testing code closer to production code
- Removes overcomplicated wrappers
- Allows Sumeragi use actor Context in test code
Batch transaction gossiping
Significantly reduces message passing
Also fixes transaction count metric calculation, which previously was providing results delayed by 1 block.
#1715
- Network is more resilient - will recover in cases of faulty peers or after high load (when the load normalizes)
- Network is …

[fix] #1715: Consensus fixes to handle high load

---

core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/domain.rs
core/src/smartcontracts/isi/expression.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/tx.rs
core/src/smartcontracts/isi/world.rs
core/src/smartcontracts/mod.rs
core/src/torii/mod.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/fixed.rs
data_model/src/lib.rs
data_model/src/metadata.rs
data_model/src/transaction.rs

Opaque `eyre::Report`s have been replaced with specific `Error` enums. 
Closes #1742 
Opaque error types that could only have been printed are now also possible to handle and match. 
None

[fix] #1742: Concrete errors returned in `core` instructions.

---

core/src/kura.rs
core/src/sumeragi/mod.rs

- Sumeragi awaits wsv block commit
- Update for network topology now directly from sumeragi
#1751
Fixes double spend attack, and general bug with same transaction being committed more than once. For more detailed overview please read the issue.
Previously wsv was updated after kura when it received the message from sumeragi. The bug was in the fact that sumeragi assumed it committed the block and updated its state, therefore able to approve next blocks, but the message might arrive to Kura a lot later. This made possible for the `is_in_blockchain` checks for transactions to pass sometimes even as some of them were in previous block. And therefore leaders could create blocks with same txs and other peers might approve it.

[fix] #1751: Sumeragi awaits wsv block commit

---

client/src/client.rs
client/src/config.rs
client/tests/integration_tests/asset_propagation.rs
client/tests/integration_tests/connected_peers.rs
client/tests/integration_tests/events.rs
client/tests/integration_tests/multiple_blocks_created.rs
client/tests/integration_tests/multisignature_account.rs
client/tests/integration_tests/multisignature_transaction.rs
client/tests/integration_tests/restart_peer.rs
client/tests/integration_tests/unstable_network.rs
configs/client_cli/config.json
core/src/torii/mod.rs
core/test_network/src/lib.rs
docker-compose-local.yml
docker-compose-single.yml
docker-compose.yml
docs/source/references/api_spec.md

- Fix JSONs according to #1743 `Domain` struct change
- Fix `status` term to `telemetry` according to #1725
Close #1755

[fix] #1755: Minor fixes for #1743, #1725

---

Cargo.lock
client/src/client.rs
client/tests/integration_tests/add_asset.rs
client/tests/integration_tests/events/pipeline.rs
client/tests/integration_tests/multisignature_transaction.rs
client/tests/integration_tests/tx_history.rs
client_cli/src/main.rs
core/Cargo.toml
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/genesis.rs
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/mod.rs
core/src/smartcontracts/wasm.rs
core/src/tx.rs
core/src/wasm.rs
core/src/wsv.rs
core/test_network/tests/sumeragi_with_mock.rs
data_model/src/transaction.rs

This PR adds support for executing wasm smartcontracts to Iroha. 
Function parameters and return values are exchanged through **linear memory** via offset and length of the allocation. Since dealing with linear memory is very low-level(it's just a contiguous array of bytes) Rust types/values must be serialized to binary format before writing them to wasm memory. 
Wasm binary to be able to execute must export:
* `WASM_MAIN_FN` - function which the host calls to execute smartcontract
* `WASM_MEMORY` - linear memory (used to exchange more complex data than integers/floats)
* `WASM_ALLOC_FN` - function which hosts uses to allocate memory from wasm's linear memory
Notes:
* Note that since wasm is sandboxed there is no way for the module …

[feature] #1425: add wasm runtime

---

data_model/src/lib.rs

Compare PeerId only by key.
Comparison is done by public key only, so that full domain names can be present in trusted peers and local address in this peer config without a conflict.
The problem was found during longevity stand setup. When:
1. `TORII_P2P_ADDR` was `0.0.0.0:1337`
2. `SUMERAGI_TRUSTED_PEERS` had `[{"address": "some.test.domain:1337", ...}, ... ]`
The peers therefore did not discover themselves in trusted peers and were not considering themselves to be validators, leading to genesis block not being committed.

[fix] #1714: Compare PeerId only by key

---

client/Cargo.toml
client/benches/torii.rs
client/tests/million_accounts.rs

Fixes the benchmarks.
Closes #1783 
Benchmarks work
None
```
cd client
cargo bench
```

[fix] #1783: Fixed torii benchmark.

---

core/src/sumeragi/mod.rs
docs/source/references/config.md
logger/src/config.rs
logger/src/lib.rs
logger/tests/configuration.rs

- events log moved to trace level
- ctx removed from log capture
- terminal colors are made optional (for better log output to files)
#1802
The need for these improvements was discovered during longevity testing - it was very difficult to read logs with special (color formatting) symbols from file.

[fix] #1802: Logging readability improvements

---

crypto/src/hash.rs
crypto/src/signature.rs
data_model/src/expression.rs
data_model/src/isi.rs
schema/bin/src/main.rs
schema/src/lib.rs

…schemas are missing
* Fixes schema serialization of `HashOf`, `SignatureOf`
* adds test to ensure all schemas are in place
Closes #1801 
`IntoSchema` macro can be improved to account for `PhantomData` fields. Maybe in the future

[fix] #1801: fix schema generation for HashOf, SignatureOf

---

Cargo.lock
core/src/config.rs
core/src/sumeragi/mod.rs
crypto/src/lib.rs

Added more sanity checks to the configuration reading process. 
Closes #1811 
More safety.
The `configuration.json` file is read twice.

[fix] #1811: added tests and checks to dedup trusted peer keys.

---

Cargo.lock
Cargo.toml
core/src/block.rs
tools/kura_inspector/Cargo.toml
tools/kura_inspector/src/lib.rs
tools/kura_inspector/src/main.rs
tools/kura_inspector/src/print.rs

Add a CLI tool to inspect the disk storage
Closes #1754
Now we can inspect the disk storage regardless of the operating status of Iroha
None
- `kura_inspector print` prints the latest block
- Tested by `kura_inspector::print::tests::test_print_default`
- `kura_inspector -f 100 print -n 5` prints every block, if exists, whose height is between 100 and 104
- Tested by `kura_inspector::print::tests::test_print_range`
- `kura_inspector -f 100 print -n 5 >/dev/null` same as above, but prints only block read errors

[feature] #1754: Add Kura inspector CLI

---

client/tests/integration_tests/burn_public_keys.rs
client/tests/integration_tests/mod.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/mod.rs
data_model/src/expression.rs
data_model/src/lib.rs

Add a validation to the `Burn<Account, PublicKey>` execution
Closes #1848
First-aid for the issue:
- Prevent accidentally burning the last key for the account
- Prevent users from assuming that they can delete the account by burning its last key
- Direct them to `Unregister<Account>`
None
The true solution will be the new account structure #1594 where an account is identified by its public key

[fix] #1848: Prevent public keys from being burned to nothing

---

core/benches/validation.rs
data_model/src/lib.rs
permissions_validators/src/public_blockchain/mod.rs

Add new field into Domain structure. Field represents IPFS link into Domain logo.
Add `IpfsPath` structure to superficially validate path
I haven't find good IPFS paths specifications, so I was inspiring these realisations:
1. [ipfs crate](https://docs.rs/ipfs/latest/src/ipfs/path.rs.html#42-75)
2. [cid crate](https://docs.rs/cid/0.5.1/src/cid/cid.rs.html#196-224)
Resolves #1606 
Now domains can have logo
IPFS paths isn't fully validated. Full validation requires hash decoding and possible requesting IPFS system to check, if image really exists.
Checkout #1885 
See `client/integration_tests/add_domain.rs`

[feature] #1606: Add ipfs link to domain logo in Domain structure

---

core/src/event.rs
core/src/stream.rs
core/src/torii/routing.rs
core/src/torii/tests.rs

* Now `torii` checks for WebSocket `Close` messages on `/events` path and gracefully handles them.
* Also added test for it.
* As a bonus I refactored some error types from `eyre::Report` to custom Error enums. I thought, that it will help me, but it doesn't. I can reset it, if everybody else think it wasn't necessary
Resolves #1195 
I was working only with that `handle_subscription()` method, cause it's mentioned in the issue. I don't know if issue appears somewhere else
Closing WebSocket requires waiting for response. `torii` wasn't doing it, so clients had to interrupt connection.
Now this works as it shoud be.
Any suggestions about additional tests will be helpful. May be it should be tested with js-client, as it was mentioned in #1195
See `torii/tests.rs`

[feature] #1195: Close a websocket connection cleanly

---

core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/kura.rs
core/src/lib.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/triggers.rs
core/src/sumeragi/mod.rs
core/src/triggers.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/events/data.rs
data_model/src/events/mod.rs
data_model/src/events/pipeline.rs
data_model/src/lib.rs
data_model/src/transaction.rs
tools/kura_inspector/src/print.rs

Add `TriggerSet` and carry trigger recommendations through the lifecycle of a block. 
`TriggerSet` is stored in WSV. 
Closes #1619
Closes #1859
Related to #1771 
Event triggers
Prototype implementation, so both UX and reliability are untested. 
Event processing is quadratic.
Opens #1889 
Opens #1890
Opens #1891
Opens #1892

[feature] #1619: Introduce event-based triggers

---

config/src/runtime_upgrades.rs
core/src/config.rs
core/src/genesis.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/domain.rs
core/src/smartcontracts/isi/expression.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/tx.rs
core/src/torii/mod.rs
core/src/torii/routing.rs
core/src/torii/tests.rs
core/src/torii/utils.rs
data_model/src/query.rs
data_model/src/transaction.rs
docs/source/references/api_spec.md
version/src/lib.rs

Please see [`api_spec.md`](https://github.com/s8sato/iroha/blob/feat/1815/docs/source/references/api_spec.md#query).
Closes #1815
Opens #1934
Now clients can handle query errors based on types.
- Query responses depends on `iroha_core::smartcontracts::isi`
- `iroha_version::error::Error` loses some details for SCALE compatibility

[feature] #1815: Make query responses more type-structured

---

Cargo.lock
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
docs/source/references/api_spec.md
schema/bin/src/main.rs
version/Cargo.toml
version/src/lib.rs

`iroha_core::smartcontracts::isi::query::Error` implements `IntoSchema` and is added to `iroha_schema_bin::build_schemas`
Closes #1943
None

[fix] #1943: Add query errors to the schema

---

client/src/config.rs

Fix of `WebLogin` deserialization bug, when `:` can be passed from config. It was missed in #1942 
Resolves #1955
Now users can't pass invalid `web_login` for basic authentication

[fix] #1955: Fix possibility to pass `:` inside `web_login`

---

.github/workflows/iroha2.yml

Final PR to be merged into RC2. 
Changes the tag for the push of the main docker container to the appropriate version number. 
None
Finality
None

[ci]: add proper tag to push workflow on main.

---

actor/src/lib.rs
cli/src/config.rs
cli/src/torii/config.rs
cli/src/torii/routing.rs
core/src/block_sync.rs
core/src/kura.rs
core/src/queue.rs
core/src/smartcontracts/wasm.rs
core/src/sumeragi/config.rs
core/src/sumeragi/fault.rs
data_model/src/lib.rs
data_model/src/pagination.rs
docs/source/references/config.md
logger/src/config.rs
logger/src/lib.rs
p2p/src/network.rs
schema/src/lib.rs

In all the locations where a struct derives Serialize or Deserialize usize has been replaced
with either u64 or u32. No instances of isize existed. In the cases where code using the
data required a usize u32 was chosen as the replacement. There is no point in avoiding usize
in the on disk formats if 32-bit platforms can't read and use the values written.
Resolves #1897 
No chance of crashing due to serializing on 64-bit then deserializing on 32-bit or vice versa.
This change limits the size of certain configuration values to 4 billion. Probably a non issue.

[fix] #1897: Removed usize/isize from serialization

---

rust-toolchain.toml

Added toolchain file setting up rustc to version 1.57
Closes #2048 
Now project can be build without additional steps like `rustup override`
Not a drawback, but at first I thought that will be a way to set different toolchains for different tools.
Unfortunatly we still have to use `cargo +<toolchain> ...` for `clippy` and `fmt`.
This situation looks a bit like `clippy` problem with multiple sub-crates, so that we have to use `cargo lints`

[feature] #2048: Add toolchain file

---

CONTRIBUTING.md
data_model/src/asset.rs

Created a variadic declarative macro that implements FromStr for C like enums.
#1917 
Future FromStr implementations for C like enums can be a lot smaller codesize.
May be harder to read and understand for some.

[fix] #1917: Added easy_from_str_impl macro for use with AssetValueType

---

client/src/client.rs
client/tests/integration/events/data.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/offline_peers.rs
client_cli/src/main.rs

Remove unnecessary `&mut` references from the client. 
HotFix
Fewer Mutexes needed
None

[refactor]: Remove unnecessary `&mut` from the API.

---

.github/workflows/iroha2.yml

Signed-off-by: Vasilii Zyabkin <vzyabkin@soramitsu.co.jp>
Add action to trigger the CI workflow for `iroha2-longevity-load-rs` in order to build and push its image:release to docker registry.
Currently we don't have CI for `iroha2-longevity-load-rs` at all.
It should be automatically triggers to run iroha2-longevity-load-rs CI from other repository at the successful ending of iroha2 release deploy workflow job.
Some possibility for issue with token permissions since it's required to use third-party creds.
https://github.com/soramitsu/iroha2-longevity-load-rs/actions

DOPS-1722: CI for iroha2-longevity-load-rs

---

MAINTAINERS.md

Last activity:
2019/07/24 06:25:12 issue_comment.update bakhtin
2018/12/11 14:07:33 issue_comment.update grimadas
2019/12/25 14:09:13 repository_vulnerability_alert.resolve igor-egorov
2019/01/16 12:36:58 issue_comment.update l4l
2018/09/25 11:34:38 issue_comment.update laSinteZ
2018/02/16 15:38:38 issue_comment.update luckychess
2018/07/19 16:06:05 issue_comment.destroy muratovv
2019/02/20 10:16:17 issue_comment.update neewy
2018/12/21 14:47:14 issue_comment.destroy nickaleks
2018/05/03 04:59:54 issue_comment.update Solonets
2018/07/10 13:27:31 issue_comment.update stinger112
2018/06/29 18:16:18 issue_comment.update tyvision
2018/03/20 14:42:37 issue_comment.update victordrobny
2018/03/27 10:07:33 issue_comment.update x3medima17
2017/06/28 05:35:19 org.oauth_app_access_requested yannoban …

[skip ci] Retire inactive maintainers

---

client/tests/integration/events/pipeline.rs
core/test_network/src/lib.rs

Refactored.
- Closes #2109
- Stable test result
- Shorter CI time
None

[refactor] #2109: Make `integration::events::pipeline` test stable

---

crypto/src/hash.rs
crypto/src/lib.rs
crypto/src/merkle.rs
crypto/src/signature.rs
data_model/Cargo.toml
data_model/src/expression.rs
data_model/src/role.rs
schema/bin/src/lib.rs
schema/derive/src/lib.rs
schema/src/lib.rs
schema/tests/struct_with_named_fields.rs
schema/tests/struct_with_unnamed_fields.rs
tools/parity_scale_decoder/src/generate_map.rs
wasm/src/lib.rs

* define stable schema type names
* introduce sorted collections to schemas
Considering that we make abundant use of digital signatures, serialized formats of our internal structures must have a defined ordering, e.g. `BTreeMap` must be represented as a sorted vector of tuples. While it may be possible that there will be `BTreeMap`s that won't be part of a structure that is signed(and require a defined ordering of tuples), I find it to be quite unlikely and don't think it worth to support such exception.
Closes #2114

[schema] #2114: Sorted collections support in schemas

---

Cargo.lock
client/tests/integration/connected_peers.rs
client/tests/integration/unstable_network.rs
config/src/lib.rs
core/src/block.rs
core/src/genesis.rs
core/src/sumeragi/config.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/network_topology.rs
core/test_network/src/lib.rs
docs/source/references/api_spec.md
docs/source/references/config.md
telemetry/src/metrics.rs
tools/kura_inspector/Cargo.toml
tools/kura_inspector/src/main.rs

- Give an true solution to the failure
- ~~Give an mitigation by exposing the number of the last view changes as the network sanity indicator~~
- As a bonus, expose the number of the view changes in the current round as the network sanity indicator
- Refactor `kura_inspector` with `clap` version bump
- Closes #1716

[fix] #1716: Fix consensus failure with f=0 cases

---

cli/src/config.rs
cli/src/samples.rs
client/benches/torii.rs
client/src/client.rs
client/src/config.rs
client/tests/integration/multisignature_transaction.rs
client_cli/src/main.rs
core/src/genesis.rs
core/src/sumeragi/config.rs
core/test_network/src/lib.rs
crypto/src/lib.rs
crypto/src/signature.rs
data_model/tests/data_model.rs

I thought it might be useful to fail fast on invalid configuration. Should save us some debugging time. The gist of the change is in the `KeyPair::new` method
Closes #2121

[feature] #2121: Check keypair is valid when constructed

---

.gitchangelog.rc
CHANGELOG.rst
gitchangelog-clean.py

Addressed Aleksandr's input about changelog
- Added the script to remove the names at the end of log messages after the log is built
- Updated gitchangelog config to automatically remove signed-off part of the commit and the PR number.
- Updated gitchangelog to ignore commits about codeowners
- Cleaned up the logs (partially), mainly addressing the issue with nested lists of changes.
[gitchangelog output](https://github.com/outoftardis/iroha/blob/doc-changelog/CHANGELOG.rst)
Fixes #2177

[documentation] #2177: Clean up gitchangelog output

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2.yml

- Add a step to add `llvm-tools-preview` component
- Closes #2153
- Opens #2165
- Enables the coverage by fixing [the error](https://github.com/hyperledger/iroha/runs/6213237858?check_suite_focus=true#step:6:8) that #2154 did not resolve
- CI cost by the duplicated step which [should have been done in the container](https://github.com/hyperledger/iroha/blob/7e338a5c762f7e0e25b79937e6215c10ae53b290/Dockerfile.ci#L51), which could be cut off

[ci] #2153: Fix #2154

---

CHANGELOG.rst
cli/src/torii/routing.rs
client/src/client.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/triggers.rs
core/src/smartcontracts/isi/world.rs
core/src/triggers.rs
data_model/src/query.rs
data_model/src/trigger.rs
permissions_validators/Cargo.toml
permissions_validators/src/private_blockchain/query.rs
tools/kagami/Cargo.toml
tools/parity_scale_decoder/src/generate_map.rs
tools/parity_scale_decoder/src/main.rs

Add a few more queries. 
Closes #2050 
Closes #1986 
Can now query both roles and triggers.
None

[feature] #2050: Add role-related queries.

---

Cargo.lock
schema/Cargo.toml
schema/tests/architecture-dependent.rs

Add a unit test that fails when `usize`/`isize` are `Encode`/`Decode`/`IntoSchema`
Closes #2004 
Impossible to add structures which utilise `usize`, `isize` inside the schema, and thus cause UB in decoding if the pointer size on the host machine is smaller than the encoded integer.
None
```
cargo test -p iroha_schema --test architecture-dependent
```

[feature] #2004: Forbid `isize` and `usize` from becoming `IntoSchema`.

---

Dockerfile
docker-compose-local.yml
docker-compose-single.yml
docker-compose.yml

Removed sample configurations from the docker file. Adjusted docker compose to work from the root of the repository clone. 
Closes #1883 
No problems with unspecified or incorrectly specified configuraion/genesis. 
More involved process of running an iroha peer. 
```
docker compose up
```
Inside existing docker compose fields, please add a line with the following: 
```
volumes: 
- <path-to-config-and-genesis>:config
```

[feature] #1883: Remove embedded configuration files.

---

client/build.rs

Signed-off-by: Daniil Polyakov <arjentix@gmail.com>
`cargo fmt` usage was replaced by `rustfmt` directly. This is a more clean way to avoid cargo recursion problem (instead of just removing `CARGO_RECURSION` env-variable)
* Closed #2150 
More *legal* way to solve cargo recursion problem for formatting smartcontract
Maybe non-trivial for multi-files smartcontracts

[fix] #2150: Use `rustfmt` instead of `cargo fmt` in `client/build.rs`

---

docs/source/guides/hot-reload.md

Add guidance on how to hot reload Iroha in a Docker container: https://github.com/outoftardis/iroha/blob/doc-hot-reload-guide/docs/source/guides/hot-reload.md
Closes #2119

[documentation] #2119: Add guidance on how to hot reload Iroha in a Docker container

---

.github/workflows/iroha2-dev-pr.yml
client/build.rs
client/src/client.rs
client/tests/integration/mod.rs
client/tests/integration/queries/account.rs
client/tests/integration/queries/mod.rs
client/tests/integration/triggers/time_trigger.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/fault.rs
data_model/src/query.rs
permissions_validators/src/private_blockchain/query.rs
tools/parity_scale_decoder/src/generate_map.rs

* Added `FindAccountsWithAsset` query
* Added test for it
* Fixed bug when block events (including `Committed` event) were sent before actual block applying to *WSV*
* Cause of this bugfix some of previously flaky tests are no longer such. Tested with `cargo flaky` running every test for **100** times for about 4 hours
* Smartcontract test is enabled back as it seems not being flaky anymore. But still takes about 50 secs to complete on my machine
Results of running ```cargo flaky``` (edited for readability):
```
====== FOUND 4 FAILING TESTS ======
- test: two_networks stdout
failures: 1/100 (1%)
- test: integration::unregister_peer::unstable_network_stable_after_add_and_after_remove_peer stdout
failures: 2/100 (2%)
- test: config::tests::parse_example_json stdout
failures: 100/100 (100%) …
```

[feature] #2100: Add query to find all accounts with asset

---

.github/workflows/iroha2-dev-pr-unstable.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
Cargo.lock
client/build.rs
data_model/Cargo.toml
data_model/src/asset.rs

Removed the requirement for having the `nightly-2022-04-20` installed with the right components for building Iroha. The client test with the WASM smartcontract is now only ran if the `+nightly` toolchain was used to run cargo. 
Closes #2215
Opens #2225 
Easier to compile for users. 
None

[fix] #2215: Make nightly-2022-04-20 optional for `cargo build`

---

client/benches/tps/README.md

Updated readme in `client/benches/tps`: https://github.com/outoftardis/iroha/tree/doc-tps-bench/client/benches/tps#benchmarks-transactions-per-second-tps

[documentation] #2193: Update benchmarks documentation

---

client/benches/torii.rs
client/benches/tps/lib.rs
client/examples/million_accounts_tx.rs
client/examples/ten_million_accounts.rs
client/src/client.rs
client/src/http.rs
client/src/http_default.rs
client/tests/integration/add_account.rs
client/tests/integration/add_asset.rs
client/tests/integration/add_domain.rs
client/tests/integration/asset_propagation.rs
client/tests/integration/connected_peers.rs
client/tests/integration/events/data.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/multiple_blocks_created.rs
client/tests/integration/multisignature_account.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/pagination.rs
client/tests/integration/permissions.rs
client/tests/integration/queries/account.rs
client/tests/integration/roles.rs
client/tests/integration/triggers/by_call_trigger.rs
client/tests/integration/tx_history.rs
client/tests/integration/tx_rollback.rs
client/tests/integration/unregister_peer.rs
client_cli/src/main.rs
core/test_network/src/lib.rs
data_model/tests/data_model.rs

The idea is the same as in #2147, but now it is about WebSocket side.
Iroha Events API and Blocks Stream API are built on top of the same WebSocket flow:
1. Open a WS connection
2. Client sends some "subscription" message
3. Server responses with some "accepted" message
4. Client waiting for some events and responses to them with some "accepted" message, not same as for p.3
In this PR I've normalized this flow with a few traits. They are binded to each. Their relationship aims to provide API that targets these goals:
- don't have `dyn`s, but clear abstraction
- prevent "invariant violation" by scoping flow stages in separate traits
- be functional and data-oriented
Also, I've refactored `trait RequestBuilder`. Now it forces to call `.body()` fn anyway to get the output of the builder. It …

[refactor] #2145: refactor client's `WebSocket` side, extract pure data logic

---

Dockerfile

These changes work fine on my Apple Silicon (M1) machine.
I met this problem and I had to fix it in order to do my task.
The reason for the problem is that the toolchain is incorrect here:
`rustup component add rust-src --toolchain nightly-2022-04-20-x86_64-unknown-linux-gnu`

[fix] #2170: Fixes build in docker container on M1 machines

---

cli/src/torii/routing.rs
data_model/src/uri.rs
docs/source/references/api_spec.md

Added a new endpoint that gives back the current API version as a JSON string. 
Resolves #1413.
As we're about to introduce versioning, this will allow end users to check if their client and our API versions match.
Set to grab the version from the genesis block, so the endpoint should be usable at all times when a minimal network is up. `ChainIterator` in `wsv`'s `blocks()` method was mentioning possible deadlock, but it should be safe in this case in all I can tell.
Added some documentation describing the change in `api_spec.md`.

[feature] #1413: Add API version endpoint

---

Cargo.lock
core/src/lib.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/triggers.rs
core/src/wsv.rs
data_model/Cargo.toml
data_model/src/trigger/mod.rs
data_model/src/trigger/set.rs
permissions_validators/src/private_blockchain/query.rs

Initially it suppose to close #1889 but in the middle of work it was decided to wait until we get dynamic wasm linking. Dynamic linking is important, cause it will remove `no_std` limitations from `data_model` and `TriggerSet` is not compatible with `no_std`.
So this PR contains only `TriggerSet` moving to `data_model`. It should be useful for the future.
None
* `TriggerSet` now is stored there it should be
* Errors produced by `TriggerSet` make more sense
None

[refactor]: Move `TriggerSet` to `data_model`

---

cli/src/lib.rs
cli/src/torii/tests.rs
client/tests/integration/restart_peer.rs
core/src/genesis.rs
core/src/sumeragi/fault.rs
core/src/tx.rs
core/test_network/src/lib.rs
data_model/src/transaction.rs

Signed-off-by: Daniil Polyakov <arjentix@gmail.com>
* Added error message when can't process genesis transaction
* Logger initialization now starts eralier to be able to capture genesis creating logs
* Closes #2232 
* Opens #2238 
Now users will get more meaningful message when they have too many instructions inside transactions
None
You can take a big genesis from issue description and run Iroha with it to check this out.
I don't think I can write a test for it. This is UI-specific problem

[fix] #2232: Make Iroha print meaningful message when genesis has too many isi

---

core/src/kura.rs

Take what was the previous file name, prepend with zeroes, then interpret that as dir + file name. So block files are ex 2/003, 0/032 et cetera.
#1149 
Most operating systems will freak out if there are too many files in a directory. This solves that.
We still iterate over all existing files to figure out which block file we want to edit/create. I think this needs to change in the long run. We should using a simple formula map from block number to block file number. That way you only touch the the file you want to operate on. That is a seperate issue from #1149 though, so the point is irrelevant for this PR.

[feature] #1149: Restrict block number to 1 million per dir

---

.github/build-iroha1-fork.src.yml
.github/workflows/build-iroha1-fork.yml

1. Set context points accessible by user to env vars
2. Set read-all permissions to jobs other than deploy
3. Restrict changing dependency files from forks
https://hackerone.com/reports/1548870
Remove potential injection

Fix security issues, remove build from commit option

---

client/src/client.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/query.rs
data_model/src/query.rs
permissions_validators/src/private_blockchain/query.rs
tools/parity_scale_decoder/src/generate_map.rs

Add a new query to get `AssetDefinitionId` as input and find `AssetDefinition`. 
Resolves #2125 
New possibilities for get asset definition.
None

[feature] #2125: Add FindAssetDefinitionById query

---

cli/src/torii/tests.rs
client/tests/integration/queries/account.rs

Add some tests for 'FindAssetDefinitionById' query.
Resolves #2272 
It tests the query.
None

[test] #2272: Add tests for 'FindAssetDefinitionById' query

---

core/src/smartcontracts/isi/account.rs
data_model/src/events/data/events.rs
data_model/src/events/data/filters.rs

This PR makes `Revoke` role emit `RoleRevoked` instead of `Permission` event. 
`Revoke` role emits `Permission` events which is a misleading since roles are a collection of permission events.
More accurate information about the user.
Not sure about drawbacks because I am new to the codebase.

[feature] #2257: Revoke<Role> emits RoleRevoked event

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2.yml

Remove all coverage jobs which would not show up in the CI. 
Closes #2267 
Less work done in CI. 
None

[ci]: Remove unnecessary coverage reporting.

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/derive/Cargo.toml
cli/derive/src/lib.rs
cli/src/torii/utils.rs

Replaced the declarative macro generating `endpointN` functions with a procedural one in a separate crate.
Resolves #2132.
Improved readability and extensibility.
As the macro expansion uses `WarpResult` wrapper defined in `cli/src/torii/utils.rs`, all the users of macro should reexport that struct as well. Alternatively, the macro implementation could be amended to ditch the use of that altogether.

[feature] #2132: Add `endpointN` proc macro

---

config/derive/src/lib.rs
config/src/lib.rs
config/tests/simple.rs
docs/source/references/api_spec.md
tools/kagami/src/main.rs

The `configuration` endpoint now returns all the inner fields as well when queried for docs.
Resolves #1638.
More helpful doc API calls.
The only way to return a `&'static str` while also making it custom formatted that I found was by boxing a `String` and then leaking it explicitly. Hopefully it doesn't introduce security issues.

[feature] #1638: `configuration` return doc subtree

---

core/src/wsv.rs

Issue #1896 occured because `produce_event` function has misleading statement: 
```rust
return warn!("wsv does not equip an events sender");
```
So to avoid confusion it was decided to refactor `produce_event`.
Resolves #1896.
No confusion.
None.
Firstly alternative `produce_event` implementation was considered, but clippy rejects it.
Clippy error: ```error: use Option::map_or_else instead of an if let/else```
Alternative implementation: 
```rust
/// Send [`Event`]s to known subscribers.
fn produce_event(&self, event: impl Into<Event>) {
if let Some(events_sender) = &self.events_sender {
drop(events_sender.send(event.into()));
} else {
warn!("wsv does not equip an events sender");
}
}
```

[refactor] #1896: Simplify `produce_event` implementation

---

client/src/client.rs
client/tests/integration/queries/mod.rs
client/tests/integration/queries/role.rs
client/tests/integration/roles.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/world.rs
data_model/src/query.rs

Signed-off-by: Shanin Roman [shahin1000@yandex.ru](mailto:shanin1000@yandex.ru)
- Add `Role`-related match arm in `UnregisterBox` execution;
- Fix `Unregister<Role>::execute` by: 
- removing double deletion of role from account;
- returning correct event after revoking role from account;
- correctly early exiting if role doesn't exist;
- Add `Role`-related queries to client;
- Add tests:
- to check that role removed from account after unregistering;
- to check `Role`-related queries. 
Resolves #2017 
- New tests;
- Bug fixes.
None.
```bash
cargo test --package iroha_client --test mod -- integration::roles::unregistred_role_removed_from_account --exact --nocapture
```
```bash
cargo test --package iroha_client --test mod -- integration::queries::role
```

[fix] #2017: Fix role unregistration

---

client/tests/integration/queries/role.rs
client/tests/integration/roles.rs

- Edit `register_metadata_role` test to represent #2081 case, renaming to `register_and_grant_role_for_metadata_access`
- Closes #2081
- Prevent regressions in the future
- Show a minimum example of how to grant roles
None

[fix] #2081: Fix the test case to grant the role

---

client/benches/torii.rs
client/examples/million_accounts_genesis.rs
client/examples/million_accounts_tx.rs
client/examples/ten_million_accounts.rs
client/tests/integration/add_account.rs
client/tests/integration/add_asset.rs
client/tests/integration/add_domain.rs
client/tests/integration/burn_public_keys.rs
client/tests/integration/config.rs
client/tests/integration/events/data.rs
client/tests/integration/multisignature_account.rs
client/tests/integration/non_mintable.rs
client/tests/integration/pagination.rs
client/tests/integration/permissions.rs
client/tests/integration/queries/account.rs
client/tests/integration/queries/role.rs
client/tests/integration/query_errors.rs
client/tests/integration/restart_peer.rs
client/tests/integration/roles.rs
client/tests/integration/transfer_asset.rs
client/tests/integration/triggers/by_call_trigger.rs
client/tests/integration/triggers/event_trigger.rs
client/tests/integration/triggers/time_trigger.rs
client/tests/integration/tx_history.rs
client/tests/integration/tx_rollback.rs
client/tests/reload.rs
core/test_network/src/lib.rs
data_model/tests/data_model.rs

This replaces nested methods which creates `Peer` with `PeerBuilder` structure (Builder pattern).
Resolves #2238
Makes creating a test environment more flexible and convenient.
Idk may increase test run time.
Make `Peer` structure a builder itself. But in that design, will need to keep parameters (`genesis`, `configuration`, `instruction_validator`, `query_validator`, `temp_dir`) inside the `Peer` structure to start the peer's task - it will makes `Peer` structure a huge.

[refactor] #2238: Add peer builder for tests

---

core/src/block.rs
data_model/src/block_value.rs

This PR introduces `current_block_hash` field to `BlockHeaderValue`. This field contains the hash of the latest `VersionComittedBlock`. 
When we query for block headers we cannot reliably compute the hash of the block, since it's computed from the byte representation of the block and can be architecture dependent.
The Hash of a block will no longer be architecture dependent. 
Not that I know of.

[feature] #2276: Include current Block hash into BlockHeaderValue

---

cli/src/torii/routing.rs
cli/src/torii/tests.rs

The `total` is the number of values returned in the top-most level of an iterable container after applying filter and before pagination.
- Fix `total` field calculation in `handle_queries`;
- Extend test `torii_pagination` to check that `total` field value is unaffected by pagination. 
Closes #2202.
The `total` field is now what the SDK developers expect.
None.
```bash
cargo test --package iroha --lib -- torii::tests::torii_pagination --exact --nocapture
```

[fix] #2202: Fix total field in query response

---

client/src/client.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/triggers.rs
data_model/src/query.rs
permissions_validators/src/private_blockchain/query.rs
tools/parity_scale_decoder/src/generate_map.rs

Just add `FindTriggersByDomainId` as a stub.
Partially resolves #2302 
Can be quickly introduced into the explorer.
None.
Research and try to find a short way for adding domain-scoped triggers, [related to.](https://github.com/hyperledger/iroha/issues/1889)

[feature] #2302: Add 'FindTriggersByDomainId' stub-query

---

Cargo.lock
client/Cargo.toml
client/benches/tps/oneshot.rs
logger/src/lib.rs

Adds the ability to generate folded stack information from the oneshot tps benchmark. That data can then be used in performance analysis.
#2294 
We can now generate flamecharts.
There are no drawbacks per say. But we don't currently instrument that much so the charts generated are not that informative. That does not mean we should instrument everything since that would slow the application to a grinding halt. It simply means there is more work to do when optimizing, but this is a good start.

[fix] #2294: Add flamegraph generation to oneshot.rs

---

core/src/smartcontracts/isi/asset.rs
data_model/primitives/src/lib.rs
data_model/src/lib.rs

As mentioned by @appetrosyan in #2204 we have very similar implementations for asset-related operations (`Mint`, `Burn`, `Transfer`), purpose of this PR make them generic.
The approach i took was to extract parts where implementation diverge (arithmetic operations, conversation to `f64`, default values, expected value type is assertion) for different asset value types and encapsulate them in traits. 
- Add traits `InnerMint`, `InnerBurn`, `InnerTransfer` that contains generic blanket implementations;
- Add traits `CheckedAdd`/`CheckedSub` to encapsulate differences between asset value `checked_add`/`checked_sub`;
- Add trait `FloatMetricFrom` to encapsulate differences between asset value conversation to `f64`.
- Add trait …

[refactor] #2204: Make Asset-related operations generic

---

data_model/src/query.rs
permissions_validators/src/private_blockchain/mod.rs

Add tests to the asset-related queries in private blockchain. 
Partially resolves #2053 .
New tests.
None.

[feature] #2053: Add tests to the asset-related queries in private blockchain

---

data_model/primitives/src/conststr.rs
data_model/primitives/src/lib.rs
data_model/src/lib.rs
data_model/src/name.rs

- Add `ConstString`: immutable, inlinable string, which uses `union` internally to store boxed and inlined variants in the same space;
- Replace `String` with `ConstString` in `Name` struct.
Closes #1985.
All structs that uses `Name` take up less space.
We win at least one machine word for every instance of `Name` and up to 23 byte for strings 15 bytes long on 64-bit architecture, also strings shorter than 15 bytes are stored on the stack, which avoids allocation.
`ConstString` uses `unsafe` code, which increases the risk of bugs and vulnerabilities.
Run unit tests:
```
cargo test --package iroha_data_primitives --lib -- conststr::tests --nocapture
```
Run unit tests with miri to find leaks and UB:
```
cargo +nightly-2022-04-20 miri test --package iroha_data_primitives --lib -- …
```

[refactor] #1985: Reduce size of `Name` struct

---

cli/src/lib.rs
cli/src/main.rs
client/benches/torii.rs
client/examples/million_accounts_genesis.rs
core/src/genesis.rs
core/test_network/src/lib.rs
data_model/tests/data_model.rs

Pretty much wrapping `GenesisConfiguration` from `cli` crate into an `Option` to allow peer startup without a `genesis.json` if they're not submitting genesis.
Resolves #2360 .
More flexibility with deployment.
Slightly wordier initialization of all the related structs, as we have to wrap in `Some`.

[feature] #2360: Make `genesis.json` optional again

---

Cargo.lock
Dockerfile

Version bump, which fixes the build failure. This is a stopgap until #2278 is merged
- Closes #2393
- Docker can build
- None

[ci] #2393: Bump the version of the Docker base image

---

actor/src/lib.rs

Deadlock described in #1649 is no longer reproducible. Tested under load for about an hour, periodically restarting and re-regestering peers.
Closes #1649 
Performance
None (if deadlock really is gone)

[fix] #1649: remove `spawn` from `do_send`

---

client/tests/integration/permissions.rs
client/tests/integration/query_errors.rs
core/src/smartcontracts/isi/query.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/name.rs
permissions_validators/src/public_blockchain/mod.rs
tools/parity_scale_decoder/src/main.rs

This PR disallows to use empty strings for `iroha_data_model::Name`. Thus, it forbids empty `AccountId`, `DomainId` etc. In case of `Name`'s initialization from an empty string, an error is raised. For discussion see the linked issue (#2000).

[feature] #2000: Disallow empty names

---

cli/src/lib.rs
core/src/wsv.rs

- Change `events_sender` in `WorldStateView` from `Option<EventsSender>` to `EventsSender`: this change is possible because previously `WorldStateView::with_events` was called single time during `Iroha` initialization just after `WorldStateView::from_configuration`. 
- Add `events_sender` parameter to `WorldStateView::from_configuration` constructor. 
Closes #2307.
Avoid overhead of checking if `events_sender` is `Some` with every call to `produce_event`.
In `WorldStateView::new` fake `events_sender` is created, but since `new` called only in tests it should be fine.

[refactor] #2307: Make `events_sender` in `WorldStateView` non-optional

---

cli/src/torii/mod.rs
cli/src/torii/routing.rs
cli/src/torii/tests.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/query.rs
core/src/wsv.rs

Closes #2228
Added `iroha_core::smartcontracts::query::Error::Unauthorized` to better mirror semantics of unauthorized request (i.e. without an account in this case). Also, in case of querying without an account, **HTTP 401 UNAUTHORIZED** status is returned.
Previously, in case of query without an account `FindError::Account` returned. And the corresponding **HTTP 404 NOT_FOUND** status code returned. That appeared to be semantically incorrect.
Now `POST /query` in case of request without an account returns `Error::Unauthorized` and **HTTP 401 UNAUTHORIZED** status code.
At first glance, this can be moved to `Error::Permission` and the `Unauthorized` variant could be added to `DenialReason`, but it doesn't share semantics with **HTTP 401 UNAUTHORIZED** (it's **HTTP 403 FORBIDDEN** …

[feature] #2228: Add Unauthorized variant to smartcontracts query error

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/lts-bug.yml
.github/ISSUE_TEMPLATE/stable-bug.yml
.github/issue_template.md

This PR adds detailed forms to fill into the issues. To see the issue form, open [this page](https://github.com/6r1d/iroha/issues/new/choose).
This PR closes #2446 and covers all the items in it.
* Contributors sending the bug requests will fill the form with all the details that are needed for quicker debugging.
* The supported branches of Iroha are immediately visible.
* Contributors also see who to tag, so the issue gets resolved faster.
* People who have questions will immediately see Discord and Telegram community links.
~~I have several questions I'll be marking as resolved here~~.
**UPD**: these questions were resolved.
At a later date, there may be an internal command to collect most of the current Iroha environment data: LibC version, OS info, etc. I am not sure if this can be …

[documentation] #2446: improve issue templates

---

.github/ISSUE_TEMPLATE/lts-bug.yml
.github/ISSUE_TEMPLATE/stable-bug.yml

Signed-off-by: 6r1d <vic.6r1d@gmail.com>
Adds a spoiler to issue templates, like in #2456.
Fixes #2446
* Adds a spoiler with highlight as a default value, potentially improving readability
* Asks user to format logs if formatting is broken for some reason
* Hints a code highlight is needed for Rust MWE
None
Creating an example issue in [this fork](https://github.com/6r1d/iroha/issues/new/choose) can show the current form.

[documentation] hyperledger#2446 adds a spoiler to issue templates

---

client_cli/src/main.rs

* Added `grant` subcommand for `account` command
* Added `list-permissions` subcommand for `account` command as @s8sato suggested
* Closes #2467
Now users can grant permissions using `iroha_client_cli`
* Not a drawback of this PR, but still no support for roles
* We might need to introduce server response cheking in `Client::submit_transaction()` so that user can see if something has failed on the server-side
* I've mentioned that the documentation for `iroha_client_cli` tells about possibility to pass empty line for key when registering new account. This does not work now
1. Run docker compose:
``` bash
docker compose up
```
2. Open new terminal window and go to `configs/client_cli`
3. Run this commands:
```bash
cargo run --bin iroha_client_cli -- domain register --id looking_glass
cargo …
```

[feature] #2467: Add account grant subcommand into iroha_client_cli

---

client/build.rs

Buildscript for `client` relies on parsing `RUSTUP_TOOLCHAIN` to check whether we are using nightly, which fails for non-rustup rust installations. This changes it to parse output of `rustc --version`.
#2473 
More build environments supported.
None

[fix] #2473: parse rustc --version instead of RUSTUP_TOOLCHAIN

---

Cargo.lock
cli/Cargo.toml
cli/src/config.rs
cli/src/lib.rs
docs/source/references/config.md

Signed-off-by: Ales Tsurko <ales.tsurko@gmail.com>
Added configuration to enable Iroha shutting down on panic. This prevents the tests expecting panic to fail. Also, the test for the responsible panic hook is now sequential, to prevent side effects on parallel run, while the hook is enabled.
We [introduced](https://github.com/hyperledger/iroha/pull/2445) a panic hook, which shuts down Iroha on panic (which just shutting down the thread by default). But the hook affects other tests and make them flaky.
Prevents tests flakiness. Allows users to choose the behavior on panic.
The biggest one is the difference between the test and the production environment. Also, as the test case for the hook is running sequentially, the overall tests performance has a very little degradation.
It may seem …

[fix] #2457: Fix tests flakiness related to shut down on panic

---

Dockerfile.base

Remove the version specification from the base image of `iroha2:base`
None
`iroha2:base` can be built
Different images can be built at the same commit

[ci]: Remove the version specification of `archlinux:base-devel`

---

.github/workflows/iroha2-dev.yml

1. Revert to `docker/login-action@v1`
2. Remove `Rename lcov report file` step in `upload_coverage` job
`deploy` and `upload_coverage` jobs doesn't work in `I2::Dev::Deploy` workflow.
- Resolves partially #2461
Hopefully to resolve the current `I2::Dev::Deploy` workflow failing.
`I2::Dev::Deploy` might still to be failed.
1. [Upload coverage](https://codecov.io/gh/BAStos525/soramitsu-iroha/commit/630c2877f6abaf8e2642686b6b8539ce814307e4/build)
2. [Uploaded iroha2 image from fork's runner](https://hub.docker.com/layers/iroha2/bastos525/iroha2/dev/images/sha256-593958d9ed760bfe864b7ee62a4a2c5a99bdb1c11e27316195a0eaacb4d384b2?context=explore)

[ci] #2461: Reverse docker login ver

---

.github/workflows/iroha2-dev-upload-coverage.yml
.github/workflows/iroha2-dev.yml

1. Move `upload_coverage` job to a separate workflow.
2. Revert `I2::Dev::Deploy` workflow to `branch: push` trigger.
3. Come back to `docker/login-action@v2`.
We can not use secrets in `I2::Dev::Deploy` as it was changed to `pull_request: closed` trigger because of `upload_coverage` job. So, it means that we had failed step to login to Docker Hub.
- Resolves partially #2461
1. Secrets should be accessible for `I2::Dev::Deploy` now.
2. `docker/login-action@v2` should work now.
Some unexpected fails on CI process could be.

[ci] #2461: Move coverage uploading to a new workflow

---

tools/kagami/src/main.rs

Adds options for Kagami tool crypto algorithms:
* `ed25519`
* `secp256k1`
* `bls_normal`
* `bls_small`
Resolves https://github.com/hyperledger/iroha/issues/2564
Kagami tool's usability will improve
None
```bash
cargo run --bin kagami  -- crypto --help
```
None, this is simply an update to the Kagami docs

[documentation] #2564: Kagami algorithm options

---

cli/src/lib.rs
cli/src/torii/routing.rs
client/benches/tps/lib.rs
core/src/block.rs
core/src/genesis.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
p2p/src/network.rs
p2p/tests/integration/p2p.rs

Sumeragi now runs on it's own thread and is a relatively simple statemachine. To the eye it might seem more complicated because it is laid out flat. But that is to make explicit everything that is done. The final form of the code is not this. But it is a very malleable intermediate stage. Which is why it's going on the staging branch.
#2465
It's actually very possible to debug this implementation as opposed to the previous version.
None
The best way to get an understanding for the code is to run
`cargo test integration::unstable_network::unstable_network_4_peers_1_fault -- --nocapture`.
I have left in prints to stdout that should help you follow the execution.

[fix] #2465: Reimplement sumeragi node as singlethreaded state machine

---

cli/src/lib.rs
core/src/sumeragi/fault.rs
core/src/sumeragi/mod.rs

Added a sumeragi thread shutdown function call that gets called via a drop trait on Iroha.
#2559

[fix] #2559: Added sumeragi thread shutdown.

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-lts.yml
.github/workflows/iroha2-stable.yml

Add build-args corresponding tags values for workflows.
The step of `iroha2:build` image building can not identify TAG value in `Dockerfile.base` ARG pointer,
Make CI step of `iroha2:base` image build workable.
Should be none.

[ci]: Fix `iroha2:build` image build

---

primitives/tests/ui_fail/no_conversion.stderr

This error appeared after switching from 1.61 to 1.62 because error messages are a mismatch.
None
Fixes [this problem](https://github.com/hyperledger/iroha/runs/7793931336?check_suite_focus=true#step:7:1296)
None

[ci]: Updates an expected error in ui_fail tests

---

ffi/Cargo.toml
ffi/derive/src/convert.rs
ffi/src/handle.rs
ffi/src/lib.rs
ffi/src/owned.rs
ffi/src/primitives.rs
ffi/tests/ffi_export.rs
ffi/tests/gen_shared_fns.rs

- Add `wasm` feature to `iroha_ffi` crate;
- Add `PrimitiveRepr` trait to substitute unsupported types with supported ones;
- Refactor `Vec`  transfer through ff-boundry.  
Closes #2511.
Protect from various errors (when user can pass u32 where u8 supposed to be).
More complex implementation.

[feature] #2511: Restrict FFI types on wasm

---

macro/derive/src/lib.rs

Fix doctest for `VariantCount` derive macro.
#2623 
Doctest passes
None

[fix] #2623: fix doctest for VariantCount

---

cli/src/lib.rs
config/src/iroha.rs
core/src/kura.rs
core/test_network/src/lib.rs
docs/source/references/config.md

So I’ve been debugging #2457, and the problem there is as follows:
When we start a peer for tests, we [create](https://github.com/hyperledger/iroha/blob/a2b373d7fb21dc24f27cf83bf1c8cb9a6b187b98/core/test_network/src/lib.rs#L673) a [TempDir](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html) for kura storage. It is then [held](https://github.com/hyperledger/iroha/blob/a2b373d7fb21dc24f27cf83bf1c8cb9a6b187b98/core/test_network/src/lib.rs#L502) until the peer is dropped to prevent its deletion. But kura thread receiving new blocks actually [lives on its own](https://github.com/hyperledger/iroha/blob/a2b373d7fb21dc24f27cf83bf1c8cb9a6b187b98/core/src/kura.rs#L77) and periodically …

[fix] #2457: Forcibly shut down kura in tests

---

scripts/test_env.sh

- Modify `test_env.sh` to allocate storage for each peer
- Nothing special before
- Closer to the actual situation about storages
- None
```bash
bash scripts/test_env.sh setup
bash scripts/tests/register_mint_quantity.sh
```

[fix] #0: Modify `test_env.sh` to allocate storage for each peer

---

docker-compose-single.yml

- Fix `KURA_BLOCK_STORE_PATH` in `docker-compose-single.yml`
- As of f26263ad, `docker-compose -f docker-compose-single.yml up` does not work
- It works with [this modification](https://github.com/hyperledger/iroha/issues/2640#issuecomment-1225673675)
- None

[fix] #0: Fix `docker-compose-single.yml`

---

data_model/src/name.rs
ffi/derive/src/convert.rs
ffi/derive/src/ffi_fn.rs
ffi/derive/src/impl_visitor.rs
ffi/derive/src/lib.rs
ffi/derive/tests/ui_pass/valid.rs
ffi/src/lib.rs
ffi/tests/ffi_export.rs
ffi/tests/transparent.rs

- Before transparent structs cross ffi as opaque pointers, now conversion to ffi delegated to inner field;
- Remove special handling of `fn(T) -> T` because this case was created under assumption that every struct passed as opaque pointer (implementation use `read/write/is_null` methods) which not hold in general for transparent and non-opaque structs.
Closes #2628.
Reduce number of indirections.
Case `fn(T) -> T` now uses 2 allocations instead of 1 and a bit less convenient to write.

[feature] #2628: Add support for `repr(transparent)` in FFI

---

Dockerfile

- Cherry-pick of 1d4a9499 from #2680
- Docker fails to build
- Fix
- None

[fix] #0: Remove `/iroha/rust-toolchain.toml` from the builder image

---

client/src/lib.rs
config/src/client.rs
configs/client_cli/config.json

- Removed logger config from Client config
AFAIK Rust libraries are [disallowed](https://crates.io/crates/log#usage) to activate logs by themself. Binaries should enable it. And user should decide if he want to run with logs and with which level of logs.
You can try to create a binary, import `iroha_client` and use something like [`env_logger`](https://crates.io/crates/env_logger) to enable logs. Then run your binary with `RUST_LOG=debug` env var. This will enable logs.
We don't have a lot of logs inside our `iroha_client` crate so that you won't see much of them, especially if you are not doing something. But in you can experiment with some methods or insert your logs in `iroha_client` crate manually to see, that it works.
- Closes #2734
- No more useless config
None
I don't think, that …

[fix] #2734: Remove logger config from client config

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release.yml

- Apply [the diff](https://github.com/s8sato/iroha/commit/aade1ee304301c89d883926b41c33553025a110b) between [a reproduction](https://github.com/s8sato/iroha/actions/runs/3044140289/jobs/4904192521) and [a fix](https://github.com/s8sato/iroha/actions/runs/3044430691/jobs/4904811102) on my fork
- https://github.com/hyperledger/iroha/actions/runs/3042899274/jobs/4902058622
- Publish `iroha2:<tag>` images
- None

[ci]: Fix `buildx` error with `docker/build-push-action`

---

.github/workflows/iroha2-dev-nightly.yml

Add default git context execution to `build-push-action` Action.
`iroha2:nightly` image could not be compiled due to the same error as `iroha2:dev` image had with the same workflow configuration.
Allow to build and publish `iroha2-nightly` image.
None.

[ci]: Fix iroha2:dev-nightly image build

---

p2p/src/peer.rs

Remove restriction on max message size (remove `MAX_MESSAGE_LEN` constant and checks associated with it).
Closes #2764.
Not it's possible to send large genesis block through network.
Malicious peer could try to ddos other peers.

[fix] #2764: Remove limit on max message size

---

tools/kagami/src/main.rs

- Generate key for every `Account`;
- Extend synthetic genesis with default domain (`wonderland`) and account (`alice`) to be able to perform query;
- Make genesis generation mode subcommand instead of flag.
Closes #2774, #2775.
Improved UX and generation.
None.
Generation of default genesis left unchanged:
```bash
cargo run --bin kagami -- genesis
```
Generation of synthetic genesis:
```bash
cargo run --bin kagami -- genesis synthetic --domians 100 --accounts-per-domain 10 --assets-per-domain 10
```

[feature] #2774, #2775: `kagami` genesis improvments

---

.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-release-pr.yml

Replace self-hosted runners inside `tests` workflows with the default `ubuntu-latest` Gihub Runners.
Some long tests are failed on self-hosted runners due to undetected reason.
Long tests should not be failed when they are run on the deault GH Runners.
Should be none, but we have to re-implement self-hosted runners.

[ci]: move jobs to github runners

---

Cargo.lock
client/src/client.rs
client/src/lib.rs
config/Cargo.toml
config/base/src/lib.rs
config/iroha_test_config.json
config/src/block_sync.rs
config/src/client.rs
config/src/genesis.rs
config/src/iroha.rs
config/src/kura.rs
config/src/logger.rs
config/src/network.rs
config/src/queue.rs
config/src/sumeragi.rs
config/src/telemetry.rs
config/src/torii.rs
config/src/wsv.rs
core/test_network/src/lib.rs
crypto/src/lib.rs
primitives/src/small.rs
tools/kagami/src/main.rs

* Added property testing to the Iroha and Iroha client `ConfigurationProxy` structs
* Expanded default `config.json` to allow them to be built from proxies immediately upon reading
* Updates some docs, error messages, trait derives 
Closes #2712.
More confidence in current proxy implementation's robustness.
I've struggled a bit with a generation strategy that would be compact yet showing the intended invariant, so I hope nothing's missing.
`cargo test --package iroha_config --lib -- iroha::tests client::tests --nocapture`

[feature] #2712: Config proptests

---

.github/workflows/iroha2-dev.yml
codecov.yml

1. Remove duplicated step for `load-rs` script compilation (an unintelligible oversight).
2. Set up Codecov Coverage default branch.
3. Enable Codecov Coverage `commits offsets` feature.
4. Enable old deprecated feature to compare it against the parent commit.
5. Enable to See coverage on CI test failures (Codecov will not wait for all other statuses to pass before sending its status).
1. We accidentally admitted double step to trigger `longevity load-rs` script compilation.
2. Codecov Coverage `diff` value continues to work incorrectly. [Issue #2781](https://github.com/hyperledger/iroha/issues/2781)
Perhaps here are some of the latest possible ideas to fix Codecov Coverage `diff` by own strength. I am not sure which one definite change …

[ci] #2781: add coverage offsets

---

cli/src/lib.rs
cli/src/torii/routing.rs
client/benches/tps/config.json
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/world.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
data_model/src/trigger/set.rs

Consolidate structure of `WorldStateView` object. Remove unnecessary duplication and allow things to be accessed from a more appropriate object. 
Closes #2819 
Smaller memory footprint. 
None

[fix] #2819: Move non-essential members out of WSV.

---

config/src/client.rs
config/src/iroha.rs

Improved error messages in cases where configuration failed to get parsed. 
None
Better UX. 
None

[refactor]: improve error messages on configuration failure.

---

client_cli/README.md
client_cli/src/main.rs
config/src/client.rs
data_model/src/transaction.rs

Add a new subcommand to the Client CLI that accepts wasm binaries and executes them.
Closes #2508
Allow executing wasm binaries from the Client CLI.
None
Save it into a WAT file.
```wasm
(module
;; Import host function to execute instruction
(import "iroha" "execute_instruction"
(func $exec_isi (param i32 i32)))
;; Import host function to execute query
(import "iroha" "execute_query"
(func $exec_query (param i32 i32) (result i32)))
;; Embed ISI into WASM binary memory
(memory (export "memory") 1)
(data (i32.const 0) "\00\0d\09\00\04\30\00\00\06\00\0d\09\00\04\31\00\00\05\0d\02\00\08\2c\75\6e\72\65\61\63\68\61\62\6c\65\01\07\08\00\0d\09\00\04\32\00\00\00\0d\09\00\04\33\00\00")
;; Variable which tracks total allocated size
(global $mem_size …
```

[feature] #2508: Add a new client CLI subcommand that accepts wasm

---

vcpkg/patches/0007-repaired-ambiguous-template-usage.patch

When building according to the instruction: https://iroha.readthedocs.io/en/develop/build/index.html#installing-dependencies-with-vcpkg-dependency-manager, which is with command:
```
./vcpkg/build_iroha_deps.sh $PWD/vcpkg-build
```
Suddently building is stopping with message:
```
Starting package 1/120: abseil:x64-linux
Building package abseil[core]:x64-linux...
-- Downloading https://github.com/abseil/abseil-cpp/archive/997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz -> abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz...
-- Extracting source /home/student/Desktop/iroha_code/baziorek/iroha/vcpkg-build/downloads/abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz
-- Applying patch fix-cxx-standard.patch
-- Using source at …
```

Repaired building iroha according to instruction: Added patch file to make sure abseil library is building without changes

---

.github/build-iroha1-fork.src.yml
.github/build-iroha1.src.yml
.github/workflows/build-iroha1-fork.yml
.github/workflows/build-iroha1.yml

Add Iroha select label and restore temporary changes

---

CMakeLists.txt
iroha-lib/CMakeLists.txt
iroha-lib/README.md
iroha-lib/examples/BatchExample.cpp
iroha-lib/examples/CMakeLists.txt
iroha-lib/examples/QueryExample.cpp
iroha-lib/examples/TxExample.cpp
iroha-lib/grpc_client/CMakeLists.txt
iroha-lib/grpc_client/GrpcClient.cpp
iroha-lib/grpc_client/GrpcClient.hpp
iroha-lib/model/CMakeLists.txt
iroha-lib/model/ClassDeclarations.h
iroha-lib/model/LibsAndClassDeclarations.h
iroha-lib/model/Query.cpp
iroha-lib/model/Query.hpp
iroha-lib/model/Tx.cpp
iroha-lib/model/Tx.hpp
iroha-lib/model/TxBatch.cpp
iroha-lib/model/TxBatch.hpp
iroha-lib/model/generators/CommandGenerator.cpp
iroha-lib/model/generators/CommandGenerator.hpp
iroha-lib/model/generators/QueryGenerator.cpp
iroha-lib/model/generators/QueryGenerator.hpp
iroha-lib/model/utils/Utils.cpp
iroha-lib/model/utils/Utils.h

This is a source code for HL Iroha C++ library.
Currently, the latest HL Iroha 1.5 release (hyperledger/iroha:latest Docker image) is supported.
Possible actions:
- transactions
- batch transactions
- queries

Implement iroha-lib separate module for Hyperledger Iroha 1

---

client_cli/README.md
client_cli/src/main.rs

More details about the suggestion you can find [here.](https://github.com/hyperledger/iroha/issues/2899)
I spent some time trying to reuse `GenesisTransaction`s format (`configs/peer/genesis.json`) but it's a bad way cause demand depends on `iroha_core` and a lot of boilerplate code being converted. But I noticed that we can just use `Serialize/Deserialize` which already implemented for `Instruction`s and use those traits to represent instructions as JSON. As a result, I got a way to make a more convenient and simple implementation of this command.
Closes #2899 
Submit multiple instructions using one command
None
Save these instructions into a file:
```json
[
{
"Register": {
"Identifiable": {
"NewDomain": {
"id": "neverland",
"logo": null, …
```

[feature] #2899: Add multi-instructions subcommand into `client_cli`

---

client/benches/tps/lib.rs
client/tests/integration/add_account.rs
client/tests/integration/add_domain.rs
client/tests/integration/asset.rs
client/tests/integration/asset_propagation.rs
client/tests/integration/burn_public_keys.rs
client/tests/integration/connected_peers.rs
client/tests/integration/events/data.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/multiple_blocks_created.rs
client/tests/integration/multisignature_account.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/non_mintable.rs
client/tests/integration/offline_peers.rs
client/tests/integration/queries/role.rs
client/tests/integration/query_errors.rs
client/tests/integration/restart_peer.rs
client/tests/integration/roles.rs
client/tests/integration/sorting.rs
client/tests/integration/triggers/by_call_trigger.rs
client/tests/integration/triggers/data_trigger.rs
client/tests/integration/triggers/time_trigger.rs
client/tests/integration/unregister_peer.rs
client/tests/integration/unstable_network.rs
core/test_network/src/lib.rs
data_model/tests/data_model.rs
p2p/tests/integration/p2p.rs

For each test that is run by nextest in `iroha_client`, `iroha_data_model` and `iroha_p2p`, replace usage of `prepare_for_nextest!` macro with hardcoded ports. 
Closes #2909.
Nextest now doesn't fail on either of those packages and finishes successfully. Full manual control.
If any new tests are added, the programmer will have to keep track of ports already in use and maybe do some simple arithmetic. Also might have some debugging involved in case of failing to get it right at first. Also some code duplication introduced with parallel methods that just allow specifying a port.
`cargo nextest run -p iroha_client` or any other of the mentioned crates
Making that `unique_port` crate work by making an inhouse solution with other primitives?..

[refactor] #2909: Hardcode ports for nextest

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release.yml

1. Substitute default GitHub Actions runners with the `self-hosted` demand persistent instances _[s(1-4)-dev-iroha2-iroha-tech]_ with the following characteristics:
- CPU: 1 x Intel(R) Xeon(R) E-2278G
- RAM: 32 Gb
- Drive: 2 x 500 Gb
- OS: Ubuntu 22.04 LTS
For the following CI test jobs into `I2::Dev::Tests` workflow:
- check
- with_coverage
- integration
- unstable
2. Update links to `load-rs` CI.
1. A long and heavy jobs from iroha2 CI take too much time on the default GitHub Actions runners.
2. Wrong configuration to call `load-rs` image compiltation.
1. Increase the speed, effectiveness and reliability of the heavy parts of iroha2 CI.
2. Fix `load-rs` CI trigger.
1. Using a `self-hosted` runners, especially demand instances, for PR trigger workflows for open repositories is not a good …

[ci]: Switсh dev tests to Equinix self-hosted runners

---

client/examples/tutorial.rs

Signed-off-by: 6r1d <vic.6r1d@gmail.com>
Addresses https://github.com/hyperledger/iroha-2-docs/issues/207 and https://github.com/hyperledger/iroha-2-docs/issues/208
Documentation examples need to cover more topics.
None
Those are the code examples to be used in the documentation

[documentation]: Extend tutorial with asset-related docs

---

iroha-lib/README.md
iroha-lib/model/generators/CommandGenerator.hpp
iroha-lib/model/generators/QueryGenerator.hpp

Describe how Hyperledger Iroha C++ library works. Provide examples. Show how to install and use the current version of the library.
Show how to run examples with transactions, batch and commands.
Benefits:
End user will know what the library is responsible for and how to use it properly.

Added more descriptive Readme file.

---

docs/source/build/index.rst
docs/source/requirements.txt
vcpkg/build_iroha_deps.sh

Full description from https://github.com/hyperledger/iroha/pull/2944. Because of security reason those changes must be done from main hyperledger repository, not forks.
_________________________
Lets start with what is not really important - history:
Few years ago I managed to build Iroha 1.1.3 on RPI3 and RPI4, I created special tutorial:
https://wiki.hyperledger.org/pages/viewpage.action?pageId=41584046
After that I was suggested to create PR (https://github.com/hyperledger/iroha/pull/728) and @lebdron created his PR (https://github.com/hyperledger/iroha/pull/864/) to make building on RPI as automatic as possible.
During those few years I was thinking that I should create similar PR for `develop` version, but it was really hard (as You see PR from @lebdron). Recently somebody from …

Changes in `vcpkg/build_iroha_deps.sh` file and documentation to inform users that Iroha 1 is working in Raspberry Pi 4 (from HL main repo)

---

.gitignore

This PR hides from Git the annoying `storage/` folder, which appears after every running of the Iroha.
None
It slightly improves the developer experience using the Iroha locally. 
None

[refactor]: Add `storage` folder into gitignore

---

core/benches/validation.rs
core/src/block.rs
core/src/block_sync.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
docs/source/references/schema.json

Add mechanism to detect soft forks during block sync.
Closes #2995.
Easier to debug problems with inconsistent blockchain state.
Added complexity to sumeragi.

[feature] #2995: Soft fork detection

---

Cargo.lock
crypto/src/hash.rs
ffi/.cargo/config.toml
ffi/Cargo.toml
ffi/derive/src/convert.rs
ffi/src/ir.rs
ffi/src/lib.rs
ffi/src/primitives.rs
ffi/src/repr_c.rs
ffi/src/std_impls.rs
ffi/tests/ffi_export.rs
ffi/tests/gen_shared_fns.rs
ffi/tests/generics.rs
ffi/tests/getset.rs
ffi/tests/transparent.rs
ffi/tests/unambiguous.rs
primitives/src/conststr.rs

* Opening this PR as a precursor to the FFI wrapper PR
* rename `NonTransmute` to `Cloned`
* annotate tests with `webassembly_test`
* make `Hash` transparent
Closes #2854 #2993

[feature] #2993: enable all references in FFI

---

permissions_validators/src/public_blockchain/mod.rs

[fix] #3013: properly chain burn validators: backport for LTS

---

Cargo.lock
cli/src/lib.rs
cli/src/main.rs
client_cli/Cargo.toml
client_cli/src/main.rs
config/Cargo.toml
config/base/Cargo.toml
config/base/derive/src/proxy.rs
config/base/src/lib.rs
config/src/lib.rs
config/src/path.rs

Added JSON5 support in user-provided configs, such as:
- config and genesis for `iroha`
- config, metadata, signature, instructions for `iroha_client_cli`
- #3019 
Better human-reading format
`json5` crate I use has lack of some functions and features unlike `serde_json`. But it should be enough to interact with user properly.
You can try running `iroha` or `iroha_client_cli` as always but also you can:
- use `json5` file extension (for default and your own configs)
- use all features of `json5` in your configs (which should not necessarily have `json5` extension), i.e. comments

[feature] #3019: Add JSON5 support

---

client/tests/integration/restart_peer.rs
core/benches/kura.rs
core/src/kura.rs
core/test_network/src/lib.rs
tools/kura_inspector/src/main.rs

Introduced a lockfile mechanism to Kura to prevent running multiple writing instances over one store.
#3027 
As per #3027
More complexity in Kura.
- This PR uses typestate pattern to encode lock state in attempt to prevent accidental misuse when changing Kura code. One could argue for a simpler design that would allow slightly more room for mistakes.
- Storage is locked for full lifetime of Kura. There was an alternate design discussed where lock is acquired only when writing blocks, however it is worse for performance and still allows starting multiple Iroha instances backed by the same storage, postponing failure for indeterminate time in the future.

[feature] #3027: implement lockfile for Kura

---

core/src/queue.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
telemetry/src/metrics.rs

- Add queue size to metrics;
- Fix Queue to correctly remove transactions;
Closes #2963.
- No infinite growth of the transaction queue;
- More diagnostic information in the `/status` response.  
None.
Queue size field in the status response: 
```
curl http://127.0.0.1:8180/status
```
Multi-signatures are still not handled correctly by the queue, i would suggest fix this in the separate PR.

[fix] #2963: Queue remove transactions correctly 

---

cli/src/torii/routing.rs
core/src/block.rs
core/src/block_sync.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
core/src/sumeragi/view_change.rs
core/src/tx.rs
core/src/wsv.rs
crypto/src/signature.rs
docs/source/references/schema.json

I believe you will find it much more easier to understand now
I also left some comments in the code
The hanging issue still persists:
1. `Failed to push into queue err=InBlockchain` is observed:
```
2023-01-12T22:42:41.821378Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:54960}: iroha::torii::routing: Failed to push into queue tx_hash=d543e665272d74fd5f6733d1ca01869c78ac8633e7b5a49c36b563fb6baa51b9 err=InBlockchain
2023-01-12T22:42:41.821378Z  WARN request{method=POST path=/transaction version=HTTP/1.1 remote.addr=127.0.0.1:54955}: iroha::torii::routing: Failed to push into queue tx_hash=5b042f8b52a4d9cc1fca8f57d237cb8c5ff8f92aa58333f61314eb859dc5ae37 err=InBlockchain
2023-01-12T22:42:41.821378Z …
```

[refactor]: simplify sumeragi

---

ffi/derive/src/convert.rs
ffi/derive/src/lib.rs
ffi/derive/tests/ui_fail/fieldless_enum_with_expicit_discriminant.rs
ffi/derive/tests/ui_fail/fieldless_enum_with_expicit_discriminant.stderr

Derive macro `FfiType` now rejects fieldless enums with explicit discriminants.
Closes #2794.
Less space to make errors.
None.

[feature] #2794: Reject Fieldless enums with explicit discriminants in FFI

---

cli/src/torii/routing.rs
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/genesis.rs
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/tx.rs

- Add const generic to avoid limit check if transaction is part of genesis block.
- Genesis block early return error if it contains zero accepted transactions.
Closes #2456.
Provide possibility for users to submit large genesis which should play well with block store merge tool. 
User can try to submit too large genesis which would cause issues during network transfer.
```
cargo test --package iroha_core --lib -- tx::tests::genesis_transaction_ignore_limits --exact --nocapture
```

[fix] #2456: Make genesis block unlimited

---

docs/source/index.rst

Update the information on the change of core team attention from I1 towards I2.
Described in https://github.com/hyperledger/iroha/issues/3070
* Users won't be misdirected by the information on the parallel development
* Iroha 2 will get more attention from the community
None

[documentation] #3070: mention reduced dev activity

---

docs/source/requirements.txt

This change reintroduces the `m2r2` dependency, since Read the Docs builds are broken for Iroha 1.
Documentation for Iroha 1 isn't building correctly.
Documentation updates will show for Iroha 1.
More dependencies may be broken.

[documentation] #3079: reintroduce m2r2 dependency

---

client/tests/integration/unstable_network.rs
core/src/sumeragi/main_loop.rs

[fix] #3087: Collect votes from observing peers after view change.

---

cli/src/torii/routing.rs
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/genesis.rs
core/src/lib.rs
core/src/queue.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/tx.rs

Relevant [discussion](https://github.com/hyperledger/iroha/pull/3047#discussion_r1091485179)
If many of you disagree we'll reject this PR

[refactor]: Remove adt_const_generics nightly feature

---

.github/workflows/iroha2-release-pr.yml
scripts/test_env.sh
tools/kagami/README.md
tools/kagami/src/main.rs

Extend `./scripts/test_env.sh` to work with arbitrary number of nodes.
Add option to kagami to generate peers in compact format.
Closes #3094
Easier to test iroha with different number of peers.
None.
```bash
./scripts/test_env.sh setup bare 10
./scripts/test_env.sh setup docker 10
```

[feature] #3094: Generate network with `n` peers

---

.github/workflows/iroha2-dev.yml

1. Add four more self-hosted runners for `I2::Dev::Tests` workflow.
2. Add a new self-hosted runner for `I2::Dev::Publish` workflow.
3. Make `load-rs` job inside `I2::Dev::Publish` workflow conditional.
1. We can not run a two `I2::Dev::Tests` workflows in parallel on self-hosted runners (increase their amount from 4 to 8 for four tests jobs).
2. A `dockerhub` job  inside `I2::Dev::Publish` workflow takes a lot of time.
3. `I2::Dev::Publish` workflow fails if `load-rs` job was failed or `load-rs` job doesn't run.
1. Now a two`I2::Dev::Tests` workflows could be run in parallel.
2. Increase `dockerhub` job  inside `I2::Dev::Publish` speed.
3. Do not failI `2::Dev::Publish` workflow if `load-rs` job was fails.
None.

[ci]: Adding five more self-hosted runners

---

core/src/block_sync.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/view_change.rs

Changes tend to improve sumeragi message processing speed.
- Fix bug when iroha sleep after role-agnostic message
- Refactor view change proof chain and improve it's processing speed.
Closes #3109.
Better sumeragi message processing speed.
None.
There is still problem with: 
```
This peer is faulty. Incoming messages have to be dropped due to low processing speed.
```
This happens because sumeragi blocks on committing/revalidating block and if it takes time greater than `pipeline` `ViewChangeSuggested` start flooding queue. 
When queue is full it's staring to drop messages which in turn provoke even more `ViewChangeSuggested` messages.

[fix] #3109: Prevent sumeragi sleep after role agnostic message

---

cli/src/torii/routing.rs
client/src/client.rs
client/tests/integration/sorting.rs

Now we can sort by any values from metadata. Not only by u128. Also, this sorting implementation places all elements that cannot be sorted at the head of a result list. 
Resolves #3116 
Better sorting feature.
None
Take a look at tests in these changes.
Another design is to remove all elements that we can't sort.

[feature] #3116: Add sorting of any values (not only u128)

---

.github/workflows/iroha2-dev.yml

Enable `iroha2-dev` image uploading  to Soramitsu images registry.
Some time ago we did the same thing for `stable&lts` tags: #3049. Now we have a need to upload the `dev` tag as well. 
We will have the opportunity to test the freshest iroha2 features like #3120 within k8s deployment and do not encounter pulling limitation on DockerHub.
None.

[ci]: Upload i2-dev image tag to Soramitsu Harbor

---

Cargo.lock
cli/Cargo.toml
cli/src/lib.rs

See #3155 for bug details.
To fix it I used [thread-local-panic-hook](https://crates.io/crates/thread-local-panic-hook) crate. It's not popular at all, but it solves our problem.
So when `test-network` feature is enabled I set thread local panic hook instead of basic panic hook (process local).
Also I removed useless invocation of previously set hook.
- #3155 
Panic in one test won't cause Iroha shutdowns in another tests.
When `test-network` feature is activated all sub-threads (e.g. Sumeragi thread) won't have specified panic-hook. Instead they will have a default one.
I and @appetrosyan decided that this this acceptable because of this:
- Sumeragi and etc. are designed to not panic because of client actions
- It works normally right now
- There will be no new integration tests in …

[fix] #3155: Fix panic-hook for tests

---

core/src/sumeragi/main_loop.rs

Closes #3166 
Related to #3103

[fix] #3166: don't do view changes when system is idle

---

core/src/smartcontracts/isi/asset.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/events/data/events.rs
docs/source/references/schema.json
permissions_validators/src/public_blockchain/burn.rs
permissions_validators/src/public_blockchain/key_value.rs
permissions_validators/src/public_blockchain/mint.rs
permissions_validators/src/public_blockchain/mod.rs
permissions_validators/src/public_blockchain/transfer.rs
permissions_validators/src/public_blockchain/unregister.rs
tools/parity_scale_decoder/src/generate_map.rs

- Implement Transfer for AssetDefinition
- Change terminology from asset registrar to asset owner
Split into two commits for reviewing/discarding convenience.
#3105 
Genesis transactions can assign asset ownership to accounts other than genesis.
Probably could be useful in other use-cases.
AIUI none.

[feature] #3105: Implement Transfer for AssetDefinition

---

Jenkinsfile

Add `Jenkinsfile` to connect iroha2 CI `iroha2:pr` building with this image Kubernetes deployment from Soramitsu private Jenkins library.
Sometimes we need to have an opportunity to deploy iroha2 image from Pull Request branch before merging to the base branch to confirm that it's workable.
For the particular PRs we will able to deploy this PR-image on the fly and quickly test it if it works as expected.
1. It will work only if the PR comes from branch inside `hyperledger/iroha` repository. Work with PRs from forks is impossible.
2. To run this job trigger, you should add `experimental_environment` label to your PR.
Actually nothing from GH Actions iroha2 CI process. Only outside PR-deployment Jenkins job could not work.

[ci]: Add Jenkinsfile for i2-PR-image k8s deployment generator

---

.github/workflows/iroha2-dev.yml

1. Change `I2::Dev::Publish` workflow trigger from `pull_request` to `pull_request_target`.
2. Remove unnecessary workflow permissions.
`permissions: pull-requests: read` probably won't help to share the secret. `write` permission for PR will not work according to the GH Actions documentation. `on: workflow_run` trigger could be used, but this trigger only works on the default branch, which iroha2-dev is not. And if we put it in the default `main` branch, then the context is read from there.
Make "workflow to check that the docker containers are properly buildable" to be working.
`pull_request_target` trigger is not so safe and base-repository permissions limited. It allows to have much more permissions for forks. But we have the policy about outside collaborators PRs limitation, so this …

[ci]: Use pull_request_target trigger for I2::Dev::Publish workflow

---

Cargo.lock
cli/Cargo.toml
client/Cargo.toml
client_cli/Cargo.toml
config/Cargo.toml
config/base/Cargo.toml
core/Cargo.toml
crypto/Cargo.toml
data_model/Cargo.toml
data_model/derive/Cargo.toml
data_model/src/events/data/filters.rs
data_model/src/expression.rs
data_model/src/lib.rs
futures/Cargo.toml
logger/Cargo.toml
p2p/Cargo.toml
permissions_validators/Cargo.toml
primitives/Cargo.toml
schema/Cargo.toml
telemetry/Cargo.toml
tools/kagami/Cargo.toml
tools/parity_scale_decoder/Cargo.toml
version/Cargo.toml
version/derive/Cargo.toml

Fixed deserialization of `#[serde(untagged)]` enums with `u128` leaf types. 
Closes #3330  
Can use `u128` in `Expression` and `FilterOpt`.

BACKPORT [fix] #3330: Fix `untagged` enum de-serialization with `u128` leaves

---

cli/src/torii/routing.rs
data_model/src/transaction.rs

I've researched for possible ways on how to configure logging in `warp`. I found that it's not easy.
Provided warp's tracing filter has hard-coded log levels. To implement something similar, but with patched levels, we need to implement `Filter`. This is not possible because [library authors decided](https://github.com/seanmonstar/warp/issues/555#issuecomment-622568143) that this should be kept internally and consumers should build their filters in a "convenient" way with `warp::any()`.
So, we decided to exclude `/health` route from logging at all, as this is the primary issue.
Also, I found that `WasmSmartContract` debug repr was not that is expected, and fixed it.
Closes #2581  
- less noise in logs
- less noise in TRACE logs (fixed WASM debug repr)

[fix] #2581: reduce noise in logs

---

client/benches/tps/utils.rs
client/tests/integration/config.rs
client/tests/integration/multiple_blocks_created.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/pagination.rs
client/tests/integration/permissions/mod.rs
client/tests/integration/permissions/runtime_validators.rs
client/tests/integration/queries/account.rs
client/tests/integration/queries/asset.rs
client/tests/integration/roles.rs
client/tests/integration/transfer_asset.rs
client/tests/integration/triggers/event_trigger.rs
client/tests/integration/triggers/time_trigger.rs
client/tests/integration/tx_history.rs
client/tests/integration/tx_rollback.rs
client/tests/integration/unregister_peer.rs
client/tests/integration/unstable_network.rs

- fix benchmark
- add missing ports
Closes #3360 
- benchmark works
- tests work more stable

[fix] #3360: Fix tps benchmark

---

core/src/smartcontracts/wasm.rs

This created permission problems for devops
It's being removed as unnecessary ATM 
Revert a change in  #3106 that enabled `wasmtime` cache. 
Whether this should be implemented is to be investigated in #3400

[refactor]: Disable wasmtime cache

---

core/src/smartcontracts/wasm.rs

This reverts commit d7f59a3d91f9df390e685085cf5ddd0aab7f1f61.
seems that disabling of wasmtime caching affects start-up time of our integration tests. My suspicion is that this is because `wasmtime` cache is shared between tests. In particular, validator from `genesis` seems to be cached.
I'll explore this after #3231 , until then I'm reverting this commit

[refactor]: Revert disable caching

---

p2p/src/lib.rs
p2p/src/network.rs
p2p/src/peer.rs
p2p/tests/integration/p2p.rs

- Prevent simultaneous connections by selecting who will be passive and active when connecting.
- Prevent connection duplication by keeping track of outgoing connections.
- If simultaneous connection happen add policy to resolve which connection to preserve. 
Closes #3411.
Test flakes at much smaller rate, i run it like 10000 times without any error + works a lot faster.
There still can be cases where we can lose message (and thus `multiple_networks` test can fail).

[fix] #3411: Properly handle peers simultaneous connection

---

config/base/src/runtime_upgrades.rs
core/src/sumeragi/main_loop.rs
data_model/derive/Cargo.toml
data_model/derive/src/lib.rs
data_model/derive/src/partially_tagged.rs
data_model/src/block.rs
data_model/src/events/data/events.rs
data_model/src/events/data/filters.rs
data_model/src/lib.rs

As a workaround for the upstream issue in `serde` we must manually implement the code that would be generated by `serde(untagged)`. This also has the added benefit of preserving the error messages, but unfortunately comes at the cost of using `serde_json::Value`, and a `Clone::clone` call to the entire candidate value. 
Unfortunately, until the issue is fixed upstream, there is no better way to handle this. 
Closes #3330 in `iroha2-dev`. Fix was already implemented in `iroha2-lts`. 
Fully-functional deserialization.

[fix] #3330: Manually implement `serde::de::Deserialize` for partially tagged enums

---

docs/source/references/schema.json
schema/src/lib.rs
schema/tests/enum_with_default_discriminants.rs
schema/tests/struct_with_generic_bounds.rs

Although it's inconsistent, sdk wants it this way
Closes #3533

[feature] #3533: Rename `Bool` to `bool` in schema

---

cli/src/lib.rs

Make config params not specified in env or config file fall back to defaults. 
Helps #3461. 
Less tedium

[fix] #3461: Logic error in defaults handling

---

data_model/Cargo.toml
data_model/derive/src/partially_tagged.rs
data_model/src/lib.rs
data_model/src/metadata.rs
data_model/src/numeric.rs
primitives/src/fixed.rs

Implemented manual deserialisation for `NumericValue` to circumvent https://github.com/serde-rs/json/issues/846. 
All `NumericValue` instances can now be deserialised from a string directly. 
All instances of `NumericValue::U128` are now preferentially serialised as tagged string-valued enums. Literal syntax deserialisation is supported but discouraged, given the slowness of processing. 
Closes #3330 
Closes #3539 
More flexible syntax
Potentially slower deserialsation

[feature] #3330: Extend `NumericValue` deserialisation

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release-pr.yml
Jenkinsfile
README.md

1. Change `README.MD` badge from `Codecov` to `Coveralls` tool.
2. Update PR-generator `Jenkinsfile`.
3. Add `docker.soramitsu.co.jp/iroha2/iroha2:dev-${{ github.event.pull_request.head.sha }}` iroha2 image tag to push to Soramitsu registry for PR-generator.
4. Add JDK distribution to `Set up JDK 11` step into `java-api` job inside `I2::Release::Tests` workflow.
1. We don't have `Coveralls` coverage tool badge.
2. PR-generator deployment hasn't bee finished.
3. #3562 
1. `Coveralls` badge.
2. PR-generator should work after merging the corresponding PR with Jenkins library (I'LL NOTIFY WHEN IT WILL BE ABLE TO BE TESTED)!
3. Fix JDK 11 Set up in the `Release-PR` workflow.

[ci] #3562: Fix PR-generator Jenkinsfile & Add Coverall badge & Set up JDK 11

---

core/src/smartcontracts/isi/world.rs
core/src/smartcontracts/wasm.rs
core/src/tx.rs
core/src/validator.rs
wasm_codec/derive/src/lib.rs
wasm_codec/src/lib.rs

This PR is based on PR #3588 branch, so most of the code diff is not related directly no this PR.
So, please, review only the latest commit.
I plan to merge this after #3588.
- Implemented a new state for `wasm::Runtime` related to `permission_tokens()` *Validator* entrypoint
- Added execution of this new entrypoint
- Added permission tokens replacement in `Upgrade<Validator>` execution
- Closes #3597  
- Support for permission token analysis on Iroha side
- After the merge of #3588

[feature] #3597: Permisison Token Analysis (Iroha side)

---

client/benches/tps/utils.rs
client/tests/integration/burn_public_keys.rs
client/tests/integration/connected_peers.rs
core/benches/apply_blocks/apply_blocks.rs
core/src/block.rs
core/src/queue.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
data_model/src/block.rs
data_model/src/query.rs
data_model/src/transaction.rs
docs/source/references/schema.json
schema/gen/src/lib.rs

Adds an index on rejected transactions that is then used to revalidate in the same order as when the block was created.

#3318: Interleave rejected and accepted transactions in block

---

Dockerfile.build

1. Add rustup toolchain `nightly-2023-06-25`.
2. Add [musl-x86_64](https://aur.archlinux.org/packages/musl-x86_64) Arch package. Probably should help to fix ` error occurred: Failed to find tool. Is `musl-g++` installed?` error.
[Broken iroha2-dev compilation](https://github.com/hyperledger/iroha/actions/runs/5346333962/jobs/9693207108).
Should help to fix `registry` job in `I2::Dev::Publish` workflow.

[ci]: Update rustup toolchain & add musl-x86_64 component

---

Dockerfile

Update rustup toolchain iroha2 `Dockerfile`.
[Failed CI after updating Dockerfile.build](https://github.com/hyperledger/iroha/actions/runs/5388372729).
Should help to fix `registry` jon in `I2::Dev::Publish` workflow.

[ci]: Update rust toolchain in the Dockerfile

---

tools/kagami/src/main.rs
tools/kagami/src/swarm.rs

#3475 introduces `kagami swarm` command, but it works only in directory mode. Now it is possible to produce both a "battery-included" directory and just a single file. The latter usage is especially helpful to generate sample docker-compose configurations to store them in the repo (`docker-compose.yml`, `docker-compose.single.yml` etc):
```bash
kagami swarm file ./docker-compose.yml --build . --config-dir ./configs/peer --p 4 --seed "Kagami"
kagami swarm dir ./test-swarm --build . -p 4 --seed "Kagami"
```
Closes #2373
We can automatise Docker Compose configurations generation and avoid problems with having outdated files in the repo. It will help the community.
- #3648

[feature] #2373: `kagami swarm file` and `kagami swarm dir`

---

cli/src/lib.rs
client/benches/tps/README.md
core/benches/kura.rs
core/benches/validate_blocks/validate_blocks.rs
core/benches/validation.rs
core/src/block.rs
core/src/kura.rs
core/src/smartcontracts/isi/query.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs

Reuse wsv created during validation.
Partially closes #3615 
Improve performance by executing instructions only once.
```
validate_blocks/validate_blocks                                                                          
time:   [705.06 ms 709.27 ms 713.55 ms]
change: [-46.177% -45.775% -45.415%] (p = 0.00 < 0.10)
Performance has improved.
```

[refactor] #3615: Preserve wsv after validation

---

.github/workflows/iroha2-dev.yml
Dockerfile.build

[ci]: Remove i2 PR-build & Update rust nightly toolchain
1. Remove PR-trigger from `I2::Dev::Publish` workflow. It doesn't make sense it is always executed in base branch context. `pull_request` trigger makes sense only if PR is coming from internal repo PR branch. But it fails while PR from fork. Increasing workflow permission doesn't help as well. Instead of this, to check if PR-image is buildable, we can try PR-generator feature soon with the whole k8s CI/CD process when it's really necessary. Or to invent an another approach like keeping Actions secrets in an external place.
[Failed Actions](https://github.com/hyperledger/iroha/actions/runs/5517090208)

[ci]: Remove i2 PR-build trigger

---

data_model/src/transaction.rs

Fail deserializing/decoding transactions with invalid signatures 
Closes #3613 
1. There are other places where the "retain valid signatures" logic is used: https://github.com/hyperledger/iroha/blob/c0a59c002b822a9dbca9bba376651d0e7457547a/core/src/sumeragi/network_topology.rs#L233 and https://github.com/hyperledger/iroha/blob/c0a59c002b822a9dbca9bba376651d0e7457547a/core/src/sumeragi/main_loop.rs#L1042 Maybe the logic in these places should be changed too? Or would it break some assumptions?
2. Error handling here is a bit funky. It returns an ad-hoc `&'static str` as an error type, potentially losing some context. It _could_ make sense to defined another error type just for this.

[fix] #3613: Do not tolerate invalid signatures on transactions

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml

1. Add the trigger to build iroha2 PR-image from INTERNAL repository `hyperledger/iroha` branch if it's a PR-generator case.
1. INTERNAL branch should start from `iroha2-pr-deploy/`
2. PR should has `experimental_environment` label
Check if iroha2 PR-image is properly buildable when it's necessary.

[ci]: Trigger iroha2 PR-build only for PR-generator case

---

Dockerfile.build.glibc
Dockerfile.glibc

Add `Dockerfile.build.glibc` and `Dockerfile.glibc` files to build `iroha2-ci` and `iroha2` images on GNU libc library and without `musl`.
#3654 
1. To have a `iroha2` CI on GNU libc and without `musl`.
2. To reduce the sizes of `iroha2-ci` and `iroha2` final images.

[ci] #3654: Add Dockerfiles to build iroha2 on GNU libc

---

client/src/client.rs
client/tests/integration/burn_public_keys.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/query_errors.rs
client/tests/integration/triggers/by_call_trigger.rs
core/src/smartcontracts/isi/account.rs
core/src/smartcontracts/isi/asset.rs
core/src/smartcontracts/isi/block.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/triggers/mod.rs
core/src/smartcontracts/isi/world.rs
core/src/tx.rs
core/src/wsv.rs
core/test_network/src/lib.rs
data_model/derive/src/model.rs
data_model/src/isi.rs
data_model/src/name.rs
data_model/src/query.rs
data_model/src/transaction.rs
data_model/src/visit.rs
wasm/src/lib.rs
wasm_codec/derive/src/lib.rs

the less functionality we expose in public API the better

[refactor]: move instruction len from data_model into core

---

iroha-lib/model/Tx.cpp

Add missing removeSignatory command to iroha_lib_model
Add missing `removeSignatory`  command implementation to **iroha_lib_model**

Add removeSignatory cmd to iroha-lib

---

Dockerfile
Dockerfile.build.glibc
Dockerfile.glibc

1. Fix `Dockerfile.build.glibc` and `Dockerfile.glibc` to be adopted for fully deployment scenario.
2. Bump `alpine` base image version to the stable one iroha2 musl-based image.
#3654 
Closes #3654

[ci] #3654: Fix iroha2 glibc-based Dockerfiles to be deployed

---

Dockerfile
docker-compose.dev.local.yml
docker-compose.dev.single.yml
docker-compose.dev.yml
tools/kagami/src/genesis.rs
tools/kagami/src/swarm.rs

The docker build on M1 was failing because of lacking `platform` tag at first, and then because of some missing links to `wasm-opt`'s musl binaries.
Closes #3451. 
Finally local docker launching as expected on M1 machines, abysmal build times notwithstanding.

[fix] #3451: Fix docker build on M1

---

Cargo.lock
Cargo.toml
dsl/Cargo.toml
dsl/src/lib.rs

Implement skeleton DSL crate. Arithmetic and boolean logic handled as a procedural macro. Uses `data_model::expression`. 
Closes #3688 
DSL for expressions.

[feature] #3688: Implement basic arithmetic as proc macro

---

tools/kagami/src/genesis.rs
tools/kagami/src/swarm.rs
tools/kagami/src/validator.rs

Getting rid of `tempdir` was a driveby fix I did in the CI PR that wasn't merged. Also fixing two other smaller bugs that didn't even have an issue assigned.
Closes #3741. 
`kagami validator` and `kagami swarm` working as expected.

[fix] #3741: Fix tempfile error in `kagami validator`

---

Cargo.lock
Cargo.toml
core/src/smartcontracts/wasm.rs
wasm_codec/Cargo.toml
wasm_codec/derive/src/lib.rs
wasm_codec/src/lib.rs

1. Replaces error lifting from `Trap` with `wasmtime::Error` that is `anyhow::Error` actually.
2. Replaces all codec errors with structured errors.
3. Replaces `eyre` with `wasmtime::Error` in structured errors related to executing smart-contracts.
Closes #3309 
Upgrades `wasmtime` to the latest version.

[feature] #3309: Bump `wasmtime`

---

Cargo.lock
cli/src/lib.rs
core/src/kura.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/validator.rs
core/src/wsv.rs
data_model/src/events/mod.rs

Implement `Serialize`/`Deserialize` for `WorldStateView` and down the tree.
Initial implementation of `Fast` init mode for Kura - for now just saves serialized WSV on Kura shutdown, restore when Kura is in `Fast` init mode. In the future this behaviour could be expanded to save snapshots periodically and/or on request, snapshot pruning, etc.
#3651
Faster start-up time.
Possibly useful for debugging of block stores - WSV snapshot is easier to inspect than a blockchain.
Contains manual implementations of serde traits that will need to be maintained. Deriving doesn't seem possible, since there's no support for `DeserializeSeed` in `serde_derive` (and [not planned](https://github.com/serde-rs/serde/issues/881#issuecomment-1627865581)). 
Instead of `serde` we could possibly use Parity SCALE, …

[feature] #3651: WSV snapshots

---

core/src/smartcontracts/isi/asset.rs
core/src/sumeragi/mod.rs
core/src/validator.rs
core/src/wsv.rs

The previous implementation was wrong because of my misunderstanding of prometheus histograms.
Closes #3709

[fix] #3709: Correct how tx_amounts histogram is calculated.

---

tools/kagami/src/swarm.rs

A small Kagami help update
Closes #3802

[documentation] #3802: Unicode "kagami swarm" seed

---

data_model/src/block.rs

Get rid of unnecessary `iter::cloned()` call.
Closes #3674.

[refactor] #3674: Elide `.cloned()` in `data_model/src/block.rs`

---

data_model/src/events/notification.rs
macro/derive/src/lib.rs

Slightly amended `#[derive(FromVariant)]` macro to account for the degenerate case of a single variant enum, thus fixing the lint.
Closes #3762. 
No annoying warnings

[fix] #3762: Fix `irrefutable_let_patterns` in the `#[model]` macro

---

cli/src/lib.rs
config/iroha_test_config.json
config/src/iroha.rs
config/src/lib.rs
config/src/snapshot.rs
configs/peer/config.json
core/src/kura.rs
core/src/lib.rs
core/src/snapshot.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/wsv.rs
docs/source/references/config.md
scripts/test_env.py

Separate wsv snapshots into separate actor.
Closes #3796, #3798, #3800  
More configuration options.

[refactor] #3796: Add `SnapshotMaker` actor

---

core/benches/kura.rs
core/src/kura.rs
scripts/test_env.py

Implement `fast` kura init mode.
Which can skip loading blocks from disk and thus bootstrap startup time. 
Closes #1915 
Improve startup time.
Take additional space for storing hashes on disk (32 bytes per hash) time/memory tradeoff.
`fast` init mode should be used with caution because it can detect some mutations in hashes file. 
1. Run iroha with `strict` kura init mode
2. Create couple of blocks
3. Check that `storage/blocks.hashes` is created
4. Shutdown iroha peer
5. Switch to `fast` kura init mode in the configuration
6. Start peer again
7. Check that peer is running correctly
8. Shutdown iroha peer ones more
9. Make backup of `storage/blocks.hashes` (`storage/blocks.hahses.old`)
10. Remove some data from data from `storage/blocks.hashes` or whole file entirely
11. Start peer
12. …

[feature] #1915: Implement Fast kura init mode

---

.github/workflows/iroha2-release.yml

In `I2::Release::Publish`, add third-party Action step to commit and push the changes by `sorabot` user PAT to the protected branch
#3849 
This Action should help to solve the problem of pushing changes to the `iroha2-dev` protected branch. However, it's an experiment and might not work due we are not able to use `sorabot` bot-user on forks.

[ci] #3849: Fix stable/lts configs pushing job

---

core/src/kura.rs

TBH, I am lazy to prepare a proper reproduction of the bug. In my case, Iroha repeatedly failed to start, complaining about existence of the lock file all the time. After all, it turned out that `./storage/kura.lock`, created by Iroha, **is a directory, not a file**.
This PR makes variables naming clearer, and passes actual block-store path into `mkdir -r`, not the path of the lockfile.

[fix]: `mkdir -r` with store path, not lock path

---

Cargo.lock
data_model/derive/Cargo.toml
data_model/derive/src/filter.rs
data_model/derive/src/has_origin.rs
data_model/derive/src/id.rs
data_model/derive/src/lib.rs
data_model/derive/src/model.rs
data_model/derive/src/partially_tagged.rs
data_model/derive/src/partially_tagged/mod.rs
data_model/derive/src/partially_tagged/resolve_self.rs
data_model/derive/tests/filter.rs
data_model/derive/tests/has_origin.rs
data_model/derive/tests/has_origin_generics.rs
data_model/derive/tests/id_eq_ord_hash.rs
data_model/derive/tests/partial_tagged_serde.rs
data_model/derive/tests/partial_tagged_serde_self.rs
data_model/derive/tests/ui_fail/has_origin_multiple_attributes.rs
data_model/derive/tests/ui_fail/has_origin_multiple_attributes.stderr
data_model/derive/tests/ui_pass/filter.rs
data_model/src/predicate.rs
ffi/derive/Cargo.toml
ffi/derive/src/convert.rs
ffi/derive/src/getset_gen.rs
ffi/derive/src/impl_visitor.rs
ffi/derive/src/lib.rs
ffi/derive/src/wrapper.rs
macro/utils/Cargo.toml
macro/utils/src/emitter.rs
macro/utils/src/lib.rs

Introduces various improvements to `iroha_data_model_derive`:
- updated to use syn 2.0
- add tests (where possible, see [1])
- use darling derives and traits to parse macro inputs
- add support for `Self` type in serde partially tagged enums (#3737)
- address problems in `derive(Filter)` outlined in #2437
[1] I am a bit unhappy with the testing of `derive(Filter)`, but it seems so intertwined with all the parts of `iroha_data_model` that it's really hard to test. Additionally, testing the generated `Filter` impl requires the `transparent_api` feature
Closes #3882, #3737, #2437

[refactor] #3822, #3737, #2437: Refactor iroha_data_model_derive

---

client_cli/README.md
client_cli/src/main.rs

There is inconsistency of what `iroha_client_cli` accepts:
- JSON5 input for `iroha_client_cli json` command
- JSON input for filters, e.g.
```bash
iroha_client_cli domains list filter '{"Identifiable": {"Is": "wonderland"}}'
```
This chore PR adds support for JSON5 for filters:
```bash
iroha_client_cli domains list filter '{Identifiable: {Is: "wonderland"}}'
```
It makes examples of `iroha_client_cli` usage _a little_ more clear and consistent.

[feature]: parse filter as JSON5 in `iroha_client_cli`

---

Cargo.lock
crypto/src/lib.rs
futures/derive/Cargo.toml
futures/derive/src/lib.rs

Update `iroha_futures_derive` to use syn 2.0
Would be nice to be able to use the `Emitter` type from #3897, will update the PR when it will be merged
Also, a drive-by fix to silence the "unused" lints in some other feature combinations
Closes #3911

[refactor] #3911: Migrate `iroha_futures_derive` to syn 2.0

---

.github/workflows/iroha2-dev-pr-ui.yml
.github/workflows/iroha2-release-pr.yml

Some CI jobs have a lack of space problem on the default GitHub runners.
#3825 
This possible fix might help to free up approximate 10G disk size.

[ci] #3825: Clean default runner free space

---

ffi/derive/src/attr_parse/getset.rs
ffi/derive/src/attr_parse/repr.rs
ffi/derive/src/convert.rs

Actually, `Span::join` doesn't work on stable at all (and returns `None`), so care should be taken to have a fallback
This means that on stable we will have error spans that are slightly incorrect
Closes #3939

[fix] #3939: Fix the usage of `Span::join`

---

Dockerfile
Dockerfile.glibc
docker-compose.stable.yml

Wasm cache directory is being created in the Dockerfile and all required permissions are being granted to the user.
- Closes #3955 
Working Iroha stable image

[BACKPORT] #3995: Fix wasm cache directory permission bug in docker image

---

.github/workflows/iroha2-dev-pr-wasm.yaml
Cargo.lock
Cargo.toml
Dockerfile.build
Dockerfile.build.glibc
ffi/.cargo/config.toml
tools/wasm_test_runner/Cargo.toml
tools/wasm_test_runner/src/main.rs
wasm/.cargo/config.toml
wasm/README.md
wasm/src/debug.rs
wasm/src/lib.rs
wasm/src/log.rs

Add a new `iroha_wasm_test_runner` tool. It mostly duplicates the `webassembly-test-runner`, but actually returns a non-zero exit code if there are any test failures. As an added bonus 
This tool is expected to be installed on the developer's system with `cargo install`. It's not going to change often, so I don't think there's a risk of it going out-of-sync with the state of the repo.
Also fix the `evaluate_expression` test, which was never passing before due to a typo.
Closes #3928 
- Actually makes the CI check that the wasm test
An alternative would be to continue to use the upstream test runner when/if https://github.com/matklad/webassembly-test/pull/1 gets merged, but I wouldn't bet on it.

[fix] #3928: Make failing the wasm tests actually fail the CI

---

tools/wasm_builder_cli/Cargo.toml
tools/wasm_builder_cli/src/main.rs
wasm_builder/src/lib.rs

This adds a progress bar to `wasm_builder_cli` by exposing cargo's output (which already implements progress bar).
Closes #3237 
The user can see the progress of the build

[feature] #3237: Expose cargo's output in wasm_builder_cli to have build progress information

---

.github/build-iroha1.src.yml
.github/chatops-gen-matrix.sh
.github/workflows/build-iroha1.yml
iroha-lib/examples/CMakeLists.txt
vcpkg/patches/0014-gtest-remove-werror-compile-flag.patch

develop -> master is failing to compile in MacOs: https://github.com/hyperledger/iroha/pull/3960
That is why I need to repair the compilation. It looks that GTest is not compilling for MacOS because compiler is now newer than before (newer compiler usually is more strict). Newer compiler signals some things as warnings, but GTest has `-Werror` compilation flag. So the solution is to create patch for vcpkg port of gtest to remove the flag (how to create patch is here: https://stackoverflow.com/questions/72588408/vcpkg-how-to-edit-package-file-when-compilation-fails-when-installing-package).
Details of what was done: https://github.com/hyperledger/iroha/pull/3977#issuecomment-1771606416
We will be able to upgrade `main` branch with changes from `develop`

Repairing MacOs build on develop

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs

Fix for bug with `TopologyMismatch`. 
Root cause for the problem was that after handling message peer state wasn't cleared.
In case if `view_change_index` of previous block was `1` than peer will submit block with wrong topology (because state is not cleared).
After reset new `Leader` would submit new block if this would arrive too late to `ProxyTail`, it would be corrupted without ability to recover. 
With current implementation of consensus it's troublesome to provide any test to verify that bug is 100% fixed...
I've created stand where i was able to successfully submit `263_975` blocks (run out of memory after that on my laptop).
Before the fix peers usually fail before that point (around `20_000` blocks or even earlier).
<details>
<summary>Relevant logs</summary>  
```plain …
```

[fix] #3995: Fix topology mismatch

---

client/src/client.rs
client_cli/src/main.rs
data_model/src/query/mod.rs
tools/kagami/src/main.rs

[fix] #4014: Use method(not field) access in client

---

client/src/client.rs
data_model/src/query/pagination.rs
data_model/src/query/sorting.rs

@Arjentix suggested that strange casts from Pagination and Sorting to Vec of tuples is not very readable and suggested refactoring these casts to a methods
Closes #3740

[refactor] #3740: Replace impl From<Pagination> for Vec<...> with a method

---

Cargo.lock
client/tests/integration/smartcontracts/executor_with_admin/src/lib.rs
client/tests/integration/smartcontracts/executor_with_custom_token/src/lib.rs
client/tests/integration/smartcontracts/executor_with_migration_fail/src/lib.rs
default_executor/src/lib.rs
smart_contract/executor/derive/Cargo.toml
smart_contract/executor/derive/src/default.rs
smart_contract/executor/derive/src/lib.rs
smart_contract/executor/derive/src/validate.rs
smart_contract/executor/src/lib.rs

Now the different flavors of validators can be generated with less repetition.
Closes #3856. 
Less non-obvious boilerplate when defining custom validators.

[refactor] #3856: Proc macro for default validator boilerplate

---

client_cli/src/main.rs

[feature] #4041: Add git commit SHA to client_cli

---

.github/workflows/iroha2-release-pr.yml

I noticed that with soft disk space free up on the default runner for `long` tests into `I2::Release::Tests` we still receive the error `[long](https://github.com/hyperledger/iroha/actions/runs/6850948216/job/18626197954)
System.IO.IOException: No space left on device`.
I propose to use the specific Action for hard disk space free up.
[Failed long tests job](https://github.com/hyperledger/iroha/actions/runs/6850948216/job/18626197954)
Free up more disk space as much it's possible to be able to execute long release tests.

[ci]: Get more free space on the runner for release's long tests

---

client/Cargo.toml
client_cli/Cargo.toml

Deploying behind an HTTPS proxy seems like a common occurrence, so we should have some TLS implementation by default.
Rustls brings less problems with linking under musl, so use it
Closes #4070
Make a sane choice so that the user does not have to. If they don't like the choice, they can disable the default features and make their own.

[fix] #4070: Enable `tls-rustls-native-roots` `iroha_client` feature by default

---

client/tests/integration/domain_owner.rs
client_cli/pytests/src/client_cli/client_cli.py
client_cli/pytests/src/client_cli/have.py
client_cli/pytests/src/client_cli/iroha.py
client_cli/pytests/test/domains/conftest.py
client_cli/pytests/test/domains/test_register_domains.py
client_cli/pytests/test/domains/test_transfer_domains.py
client_cli/src/main.rs

This pull request adds command to transfer domains between accounts into `iroha_client_cli`.
Closes one of subtasks from #3974  
Extends the functionality of `iroha_client_cli`.

[feature] #3974: Add subcommand into `iroha_client_cli` to transfer domains

---

cli/src/torii/routing.rs
core/src/queue.rs

- `warp::trace::request()` was attached twice for some endpoints, which lead to noise in logs
- logging error inside queue push was redundant because error should be handled on caller site
Closes #4097 
Less noise in logs.

[fix] #4097: Fix warp noise in logs

---

client/src/http_default.rs

Fixed the web socket bug which gives HTTP 400.
All library versions saved as-is
- Closes #4099:

[fix] #4099: Fix of the websocket request builder

---

Cargo.lock
Cargo.toml
client/Cargo.toml
client/src/http_default.rs

Re-exported does not have the TLS fully functional if we only enable it on `tokio-tungstenite`, so a direct dependency is required
Fixes #4120

[fix] #4120: Do not use the `tungstenite` re-exported from `tokio_tungstenite`

---

Cargo.lock
client/benches/torii.rs
client/benches/tps/utils.rs
client/examples/tutorial.rs
client/src/client.rs
client/src/lib.rs
client/tests/integration/asset.rs
client/tests/integration/asset_propagation.rs
client/tests/integration/burn_public_keys.rs
client/tests/integration/domain_owner.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/multiple_blocks_created.rs
client/tests/integration/multisignature_account.rs
client/tests/integration/multisignature_transaction.rs
client/tests/integration/permissions.rs
client/tests/integration/queries/asset.rs
client/tests/integration/roles.rs
client/tests/integration/transfer_asset.rs
client/tests/integration/unregister_peer.rs
client/tests/integration/upgrade.rs
client_cli/Cargo.toml
smart_contract/executor/derive/src/validate.rs

[refactor]: Export iroha_crypto through iroha_client

---

.github/workflows/iroha2-dev-pr.yml

Use default settings for Coveralls action
#4131 
Fix tests coverage should be compared against the iroha2-dev branch, not iroha2-stable.

[ci]: Use default settings for Coveralls action

---

client/tests/integration/offline_peers.rs
core/src/sumeragi/mod.rs

[BACKPORT] #4164: Fix topology update on restart

---

client/tests/integration/triggers/by_call_trigger.rs
core/src/smartcontracts/isi/triggers/set.rs

- See also #4159 
- Closes #4133

[BACKPORT] #4133: Count identical wasm for triggers

---

docker/develop/Dockerfile
docker/iroha-builder/Dockerfile

During working on PR (https://github.com/hyperledger/iroha/pull/4003) unfortunately dependency (not connected with the PR) stopped working. Inside the PR it can't be repaired "Pull requests from forks are not allowed to change Dockerfiles", so I'm trying to correct its from another branch of main iroha repository (not fork)
Iroha Hyperledger 1 starts compiling again

Trying to repair dependency which stopped working (protoc for golang)

---

.github/workflows/iroha2-ci-image.yml
.github/workflows/iroha2-dev-nightly.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-ui.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release-pr.yml
.github/workflows/iroha2-release.yml
Dockerfile
Dockerfile.build
Dockerfile.build.glibc
Dockerfile.glibc
wasm_builder/src/lib.rs

1. Update `iroha2ci-image` to the latest nightly toolchain (`2024-01-12`).
2. Bump `ci-contaier` in workflows to `hyperledger/iroha2-ci:nightly-2024-01-12`
3. Revert to the custom base branch comparison for Coveralls
#4184 #4131 
1. Use the freshest rust nightly toolchain in CI
2. Attempt to normalize the Coveralls work
Since we have updated the ci-image, WE MUST build and push it before the actual workflows will start to use it in CI. Previously we did it outside iroha repo (usually from forks) using the special HL DockerHub credentials that Hyperledger provided to us. Unfortunately, as Ry Jones told, they decided to remove these credentials since they can't continue to pay for that. Thus, we must to build and push the new ci-image asap when this PR will be merged.
Ry Jones decided to …

[ci] #4184: Bump to 2024-01-12 toolchain & Revert to custom Coveralls settings

---

cli/src/lib.rs
client/tests/integration/connected_peers.rs
core/src/block_sync.rs
core/src/lib.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs

[refactor] #3657: Split view changes from normal messages

---

client_cli/pytests/src/client_cli/client_cli.py
client_cli/src/main.rs

In asset subcommand in the CLI operations like `mint`, `burn`, `get`, `transfer` had `register`. I refactored the subcommand to follow the suggestions in #4167.
Closes #4167
```bash
./iroha_client_cli asset  --definition-id="tea#looking_glass" --value-type=Quantity 
```
```bash
./iroha_client_cli asset mint --asset-id="tea##mad_hatter@looking_glass" --quantity="100"
```
```bash
./iroha_client_cli asset burn --asset-id="tea##mad_hatter@looking_glass" --quantity="10"
```
```bash
./iroha_client_cli asset get --asset-id="tea##mad_hatter@looking_glass"  
```
```bash
./iroha_client_cli asset transfer --to="white_rabbit@looking_glass" --asset-id="tea##mad_hatter@looking_glass" --quantity="5"  
```

[refactor] #4167: asset subcommand in client CLI to be consistent

---

.dockerignore
CONTRIBUTING.md
Cargo.toml
Dockerfile.glibc
core/src/smartcontracts/wasm.rs

Add compilation profile `profiling` which preserve some debuginfo + force frame pointers (used by porfilers to symbolize functions in the stack trace).
Add dockerfile with profiling support (used glibc instead of musl to be able to integrate with parca).  
Add support to profile running wasm smartcontracts.
Closes #4083 
Data driven approach to optimization.

[feature] #4089: Add profiling support to iroha

---

.github/workflows/iroha2-ci-image.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-profiling-image.yml

1. Add `I2::GLIBC::Publish` worflow
2. Update `I2::CI::Publish` to make this parameterized
#4131 #4083 
1. Build and push iroha2 `glibc` image manually
2. Make `I2::CI::Publish` workflow parameterized

[ci]: Add glibc image publishing workflow

---

client/src/client.rs
client/tests/integration/multisignature_transaction.rs
client_cli/src/main.rs
config/src/torii.rs
data_model/src/transaction.rs
torii/src/lib.rs
torii/src/routing.rs

Update endpoint that returned `Vec<SignedTransaction>` that were in a queue to return `Vec<SignedTransaction>` that are equal (by equality function) to our demanded transaction instead.
Closes #4183 
It decreases the amount of traffic through the network.

[feature] #4183: change endpoint to return Vec of matching transactions

---

CMakeLists.txt
docs/source/build/index.rst
docs/source/concepts_architecture/architecture.rst
docs/source/deploy/single.rst
docs/source/develop/api/queries.rst
example/burrow_integration/permissions.py

1. fix variable error in `example/burrow_integration/permissions.py`
2. fix some typos

fix variable error

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/network_topology.rs

[fix] #4256: Introduce predictable ordering after too many failed view changes

---

CONTRIBUTING.rst
docker/develop/Dockerfile
docker/iroha-builder/Dockerfile
irohad/model/commands/subtract_asset_quantity.hpp
shared_model/backend/protobuf/impl/proto_block_factory.cpp
test/framework/integration_framework/fake_peer/behaviour/honest.cpp

After successful merges:  https://github.com/hyperledger/iroha/pull/4003 and https://github.com/hyperledger/iroha/pull/4032 I was compiling entire Iroha 1.
1. I've noticed some warning, which may cause that the command is not working properly.
2. I've also corrected warnings connected with unused includes.
3. I remember that many times I was asking @6r1d how to merge approved Pull Request, he suggested that this information should be in CONTRIBUTION.rst - so I've added its.
1. Fix of undetected bug
2. Faster compilation time and less warnings from IDE
3. No more questions to @6r1d about what button to press:)

Fixing warning in command SubtractAssetQuantity, removing unnecessarily includes, small documentation change

---

.github/workflows/iroha2-profiling-image.yml
Dockerfile.glibc

Backport of profiler `Dockerfile.glibc` and `iroha2-profiling-image.yml` (check https://github.com/hyperledger/iroha/pull/4220, https://github.com/hyperledger/iroha/pull/4221, https://github.com/hyperledger/iroha/pull/4250).

[ci]: Fix pprof-rs Dockerfile and workflow

---

client/benches/tps/utils.rs
client/src/client.rs
client/tests/integration/events/pipeline.rs
client/tests/integration/tx_history.rs
core/benches/blocks/common.rs
core/src/block.rs
core/src/gossiper.rs
core/src/kura.rs
core/src/queue.rs
core/src/smartcontracts/isi/block.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/tx.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs
core/src/tx.rs
core/src/wsv.rs
data_model/src/block.rs
data_model/src/predicate.rs
data_model/src/query/mod.rs
data_model/src/transaction.rs
data_model/src/visit.rs
smart_contract/executor/src/default.rs
torii/src/routing.rs

Encapsulated the next structs:
* SignedTransactionV1
* SignedBlockV1
The next structs were changed:
* ValidBlock(pub(super) Signedblock)
* CommitedBlock(pub(super) ValidBlock)
Closes #3887

[refactor] #3887: Hide an internal structure of the versioned structs.

---

example/config.docker

In one of our config file we had database default address: "some-postgres". Those sample files are for Iroha's beginners to run Iroha as fast as possible. Telling them to change sample configs to run Iroha IMO is not helping them. Also it is making our life harder, because many times somebody was asking about "I'm doing as in instruction and it is not working".
What is more - we have few config files in `example/` directory:
```
ls config*
config.docker  config.postgres.sample  config.sample  config-win.sample
```
in all of config files the host for DB is `localhost`, only in one of them (which I'm changing now) it is `some-postgres`.
- https://github.com/hyperledger/iroha/blob/88de1c6ca640eacf563bc24ae05c11dd14403c38/example/config-win.sample#L5
- …

Changed "some-host" to "localhost" in example/config.docker

---

config/src/parameters/actual.rs
config/src/parameters/user.rs
config/src/parameters/user/boilerplate.rs
config/tests/fixtures.rs
configs/swarm/genesis.json
core/benches/blocks/common.rs
core/src/executor.rs
core/src/wsv.rs
data_model/src/lib.rs
tools/kagami/src/genesis.rs

- Closes #3354 
Now users can specify different limits for Executor and for other WASM

[feature] #3354: Different fuel limit for Executor

---

.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release.yml

Fix Docker Compose path for tests after #4239 merge.
#4303
Closes #4303
Make available to run Docker Compose files tests before image pushing.

[ci] #4303: Fix Docker Compose path for tests

---

.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-profiling-image.yml
.github/workflows/iroha2-release-pr.yml

Migrate to AWS spot runners for some heavy CI jobs.
Make available CI runners after deprivation of instances from other cloud provider.
Merge it at `23-26.02.2024`

[ci]: Migrate to AWS spot runners CI

---

.github/labeler.yml
.github/workflows/iroha2-label.yml

1. The bot was observed to remove a label manually added to PR: https://github.com/hyperledger/iroha/pull/4309#issuecomment-1958760549
2. At the same time, the bot was observed to notify false-positive `config-changes` due to its wrong definition
- Closes #4278
1. Always prioritize manual labeling/unlabeling
2. Necessary and sufficient `config-changes` notifications

[ci]: Unsync auto-labels. Fix `config-changes` condition

---

.github/CODEOWNERS

As @0x009922 requested Kshitij Roodkee to be removed from `CODEOWNERS`: Kshitij would contribute, but he's busy with his new internship, as far as I am aware.

Update CODEOWNERS: remove Kshitij Roodkee

---

client/src/client.rs
client/src/lib.rs
client/tests/integration/mod.rs
client/tests/integration/status_response.rs
telemetry/src/metrics.rs

While checking #4116 I found helpful to verify that scale encoded response was equal to plain with this test.
It also might come in handy when we eventually move from warp to something like axum.
Relates to  #4116

[feature] #4116: Add test for plain == scale encoded verification for status request

---

cli/src/samples.rs

When running tests in parallel, they race for the same snapshot file.
Since persistency isn't required in tests it's better to disable snapshot in tests.

[fix] #0000: Disable snapshot read/write in tests

---

cli/src/lib.rs
client/benches/torii.rs
client/examples/million_accounts_genesis.rs
config/tests/fixtures/empty_ok_genesis.json
configs/swarm/genesis.json
core/test_network/src/lib.rs
docs/source/references/schema.json
genesis/Cargo.toml
genesis/src/lib.rs
schema/gen/src/lib.rs
tools/kagami/src/genesis.rs

- remove inline executor mode
- rename field to `executor_file`
- remove genesis from schema (revert #1391).
- **Why?**
- Because it doesn't belong here. It's not a part of the data model, but rather of the configuration system. The original reasoning about "ease for SDK developers" doesn't work (genesis is JSON, but schema is about SCALE; types are straightforward).
Closes #4291

[refactor] #4291: update genesis config & schema

---

data_model/derive/src/event_set.rs
data_model/src/events/data/events.rs
data_model/src/events/data/mod.rs
docs/source/references/schema.json
schema/src/lib.rs
schema/src/serialize.rs

Add a new kind of schema metadata - BitmapMeta - and use it to expose `*EventSet` bitfields in schema
Closes #4350

[feature] #4350: Expose event set bitfields in schema

---

client/benches/tps/utils.rs
core/src/block.rs
core/src/gossiper.rs
core/src/sumeragi/main_loop.rs

Send blocks to observing peers.
Closes #4387 
Observing peers are up to sync with voting peers.

[refactor] #4387: Send blocks to observing peers 

---

Cargo.lock
core/src/queue.rs
data_model/src/transaction.rs
primitives/Cargo.toml
primitives/src/lib.rs
primitives/src/time.rs

This PR adds a `TimeSource` to `iroha_primitives` - a mockable time source. It then proceeds to make the queue tests use the mock time source to make them deterministic.
Closes #4397
- less flaky CI
- ability to mock transaction times (useful [here](https://github.com/hyperledger/iroha/pull/4382#discussion_r1540619904))

[fix] #4397: Make queue tests use a mock time source

---

Cargo.lock
ffi/derive/Cargo.toml
ffi/derive/src/attr_parse/getset.rs
ffi/derive/src/attr_parse/repr.rs

Remove the `parse_display` dependency since `strum` provides the needed derives.
Closes #4290.

[refactor] #4290: Replace `parse_display` crate with `strum`

---

crypto/src/signature/secp256k1.rs

Currently, the `signature::secp256k1::test::secp256k1_sign` test fails intermittently due to `r` sometimes producing a vector of 31 bytes instead of 32, which makes `EcdsaSecp256k1Sha256::verify` fail on the total `r + s` length check (==64). 
Maybe it's possible that `s` does the same, so I padded `s` too to be safe – but I don't have the cryptography background to confirm that (failing cases have pointed to `r` only). I'm also unaware if it's possible for `r` or `s` to be >32 bytes long.
Closes #4307.
Test should no longer be flaky.

[fix] #4307: Pad `r` and `s` to 32 bytes in `secp256k1_sign` test

---

.github/chatops-gen-matrix.sh

Try fix gcc-10 push

---

CONTRIBUTING.md
README.md
client/README.md
client/benches/tps/README.md
docs/source/release_procedure.org
macro/README.md
scripts/update_configs.sh

Replace references to `iroha2-dev` with `main`, and `iroha2-stable` with `stable`. Leave `iroha2-lts` untouched for now, delete later.
Related to #4433.

[chore] #4433: Reflect branch changes in files

---

.github/build-iroha1-fork.src.yml
.github/build-iroha1.src.yml
.github/workflows/build-iroha1-fork.yml
.github/workflows/build-iroha1.yml

Prepare updates for iroha1 CI new main branch

---

.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-no-incorrect-image.yml
Dockerfile.build
Dockerfile.build.glibc
sonar-project.properties

1. Substitute `llvm-cov` coverage tool by `grcov` (only `grcov` generates coverage reports that are compatible with Sonarqube).
2. Add jobs and steps into workflows to set up `lcov` and `clippy` reports uploading to Sonarqube and Defectdojo.
3. Bump `actions/checkout` somewhere.
4. Update `Dockerfiles.build`.
iroha2 dev code will be analyzed in Sonarqube and Defectdojo tools. Links to services URL will be provide in DM. It has access via corporate LDAP account.
It would be much better to send generared `clippy` and `lcov` reports from PR workflow where are they actually are generated. But we can't do it since GitHub actions security policies. So, we might try at least to upload them during pushing to dev branch. Hopefully, `dawidd6/action-download-artifact` has a magic to search for the …

[ci]: Configure Sonarqube and Defectdojo in iroha2 CI

---

core/src/smartcontracts/isi/world.rs

Triggers that are living in a domain are now deleted when that domain is deleted.
Closes #4332 
Fixes the bug.
None

[fix] #4332: Remove corresponding triggers on `Unregister<Domain>`

---

client/tests/integration/triggers/data_trigger.rs
core/src/smartcontracts/isi/triggers/set.rs

Check linked issue with description of the problem.
Closes #4429 on the stable branch.

[fix] #4429: Dont clear trigger execution queue (STABLE)

---

cli/src/lib.rs
config/tests/fixtures.rs
crypto/src/lib.rs
crypto/src/secrecy.rs
crypto/src/signature/ed25519.rs
crypto/src/signature/mod.rs
tools/kagami/src/crypto.rs

* Added `Secret` to `PrivateKey`. Access to inner `PrivateKeyInner` now requires import of `ExposeSecret` trait via `expose_secret` method
* `Display`, `Debug` and `Serialize` implementations for `PrivateKey` now returns `"[REDACTED]"`
* Added `ExposedPrivateKey` wrapper which can be formatted and serialized as usual
* Note that I don't used `secrecy` crate because it requires to implement `Zeroize` trait, but inner key struct (`ed25519_dalek::SigningKey`) implement only `ZeroizeOnDrop`, and not `Zeroize`. So I used modified version of `Secret` which requires `ZeroizeOnDrop` instead of `Zeroize`. This potentially could be controversal, so any suggestions are welcome
Closes #3240

[refactor] #3240: Guard against secrets leakage

---

cli/src/lib.rs
core/src/lib.rs
core/src/metrics.rs
core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
telemetry/src/metrics.rs
torii/src/lib.rs
torii/src/routing.rs

- sumergai no longer responsible for handling metrics for torii
- fix bug with not proper view change index in metrics
Closes #4075

[refactor] #4075: Move metrics related functionality into MetricsReporter

---

Cargo.lock
crypto/Cargo.toml

This version was [yanked](https://crates.io/crates/zeroize/1.8.0), it will break iroha builds when the lockfile gets updated (on any change in dependencies)

[chore]: Revert "Bump zeroize from 1.7.0 to 1.8.0 (#4506)"

---

README.md

A one-liner solution for https://github.com/hyperledger/iroha/issues/4234:
> It seems I1 README is being displayed. I intend to add a small link to iroha.tech and ignore a [whitepaper](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/iroha_2_whitepaper.md#28-consensus) as it may be revised.

[documentation] #4234: Iroha 2 README YAC

---

.github/workflows/iroha2-dev-pr-title.yml

Enforce Conventional Commits style in PR titles.
Closes #4502.
See [here](https://www.conventionalcommits.org/en/v1.0.0/#why-use-conventional-commits).

[ci] #4502: Enforce Conventional Commits in PR titles

---

.github/labeler.yml

Stop labeling PRs with the `iroha2` label. 
Linked to #4501.

[ci] #4501: Remove `iroha2` labeler matcher

---

.github/workflows/iroha2-dev-pr.yml

Trigger PR CI when `.lock` files are updated. 
pytests will run on dependabot version updates

ci: trigger PR CI on lockfile updates

---

CHANGELOG.md
Cargo.lock
Cargo.toml
client/tests/integration/smartcontracts/Cargo.toml
data_model/src/isi.rs
default_executor/Cargo.toml
wasm_codec/Cargo.toml

serde cannot flatten `String`s and `O::Id` is always serialized as string. As a consequence it's impossible to serialize/deserialize `SetKeyValue`/`RemoveKeyValue` in genesis

fix: remove serde(flatten) from SetKeyValue/RemoveKeyValue

---

core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/triggers/mod.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/smartcontracts/isi/world.rs
core/src/state.rs

As for WSV, make trigger set make trigger set transactional.
Closes #4378
For large amount of triggers and frequent trigger execution transactional model allow not to clone trigger set all the time saving time and space.
Might be not so efficient when there is small amount of triggers.

refactor: Transactional trigger set

---

.github/workflows/iroha2-dev-pr.yml
client/tests/mod.rs
p2p/tests/mod.rs

1. redefine `with_coverage` step to exclude client integration tests 
- and to include p2p integration tests
2. expand the exception of the client integration tests from `unstable_network` to `extra_functional`
1. closes https://github.com/hyperledger/iroha/issues/4488#issuecomment-2103228798
- opens https://github.com/hyperledger/iroha/issues/4584
2. sometimes `integration` step fails due to some flaky `extra_functional` tests
2. isolation of flaky tests more in line with current realities

ci: fix `with_coverage`, isolate not `unstable` but `extra_functional`

---

data_model/src/transaction.rs

[BACKPORT]: make TransactionValue::error field public

---

cli/src/lib.rs
core/benches/kura.rs
core/src/kura.rs

Due `init` was separate functions error was introduced where `start` was called before initialization which cause panic in kura.
Fix for that is to inline `init` inside constructor.
Closes #4603 
1. start iroha
2. submit few blocks
3. restart iroha
Previously kura would crash, but iroha would continue working without ability to write new blocks to the disk.

fix(kura): Inline kura initialization into constructor

---

core/src/wsv.rs

When 2 transactions follow each other and the 2nd fails the events from the 1st are not emitted

fix: don't clear events buffer on wsv clone

---

core/src/sumeragi/main_loop.rs

Currently we may ignore `BlockMessage::BlockCreated` if it's view change index is less then view change index of control message received in same invocation of `receive_network_packet` function. E.g. currently we have such behaviour:
```
function receive_network_packet invoked
received block message with vc#1
received control message with vc#2
=> ignored block message with vc#1
```
This PR extends this behaviour to support more cases, e.g.:
```
function receive_network_packet invoked
received control message with vc#2
function receive_network_packet invoked
received block message with vc#1
=> ignored block message with vc#1
```
Closes #4223

refactor: Reject `BlockMessages` eagerly

---

client/tests/integration/triggers/time_trigger.rs
core/src/smartcontracts/isi/triggers/mod.rs
data_model/src/account.rs
data_model/src/events/time.rs
data_model/src/isi.rs
docs/source/references/schema.json

While original issues doesn't state it clearly I think that the problem was premature execution of time triggers.
So that trigger could be executed even before `start`. I fixed this.
- Now it's forbidden to register schedule-based time-trigger with `start` point before `latest_block_timestamp + consensus_estimation` time, where `consensus_estimation = 4 secs` and is a hardcoded constant. Everithing before this timestamp is considered already analyzed by Iroha. In other words -- **time-triggers in the past are forbidden**.
- As a consequence it's forbidden to register such trigger in genesis
- Now premature time-trigger look up is forced to not to execute trigger `start` point is in future
- This behavior is tested by a fixed `change_asset_metadata_after_1_sec` test
Forbidding …

fix: Don't prematurely execute time-triggers before their `start` timestamp

---

smart_contract/executor/derive/src/default.rs
smart_contract/executor/derive/src/lib.rs

While working on #4599, I noticed that in custom executor it is possible to derive `Visit` with invalid `#[visit(custom())]` functions which will be ignored (only rustc error that function is unused). This PR adds check for custom visit function names to avoid potential bugs. Also I updated documentation of some proc-macros related to custom executor.
```rust
#[derive(Constructor, ValidateEntrypoints, Validate, Visit)]
#[visit(custom(visit_register_domain2))]  // typo in visit_register_domain
struct Executor {
verdict: Result,
block_height: u64,
}
fn visit_register_domain(...) { ... }
```

refactor(executor): Check custom visit functions in `#[derive(Visit)]`

---

CONTRIBUTING.md

Updated the contributing guide with reference to issues #4502, #4501, #4433.
Closes #4585

docs: update the contributing guide

---

crypto/src/signature/ed25519.rs

Change the conversion of unsized slice to array reference to be infallible and form a better error message.
This prevents a panic during `parity_scale_cli`'s type probing
Closes #4649

fix(crypto): do not panic if the passed Ed25519Sha512 public key is of invalid length

---

Cargo.lock
Cargo.toml
crypto/Cargo.toml

Use the fix from https://github.com/yaahc/displaydoc/pull/47 until it is merged into the upstream.
Closes #4567
Reduces warnings noise

chore: use temporary `displaydoc` fix

---

.github/workflows/iroha2-dev-code-quality.yml

1. Remove coveralls tool for coverage since it's useless while having it in the workflow trigger type (btw, it's still might be possible to fix). However, coverage is uploading in Sonarqube now.
2. Modify concurrency.
3. Run clippy and lcov jobs in the head branch context.
4. Remove defecdojo output print.
5. Trigger workflow within one parent workflow onlyto reduce parallel jobs creation.
Remove coveralls that doesn't work.
Reduce the possible amount of parallel runs of I2::Dev::CodeQuality workflow.

ci: Remove coveralls

---

Cargo.lock
cli/src/lib.rs
tools/parity_scale_cli/Cargo.toml
tools/parity_scale_cli/README.md
tools/parity_scale_cli/src/main.rs

- add color detect support in partiy_scale_decoder
- fix typo (colour -> color) in cli
Closes #4487
Users don't have to rebuild `parity_scale_cli` when disabling terminal-colors. 
Which seems not happening right now since no color is used in parity_scale_cli for now.

feat: Add detect support for `parity_scale_decoder`

---

client/src/client.rs
client_cli/README.md
client_cli/src/main.rs
core/test_network/src/lib.rs

Extend `json` subcommand to allow pass json queries.
```bash
echo '{"FindAllParameters": null }' | ./iroha --config client.toml json query
```
Simplify troubleshooting.

feat(client cli): extend client cli to request json queries

---

Cargo.lock
client/Cargo.toml
client/src/config.rs

Fixed usage of `ConfigReader` in `iroha_client`.
Closes #4623

fix: avoid early drop of `ConfigReader` in `iroha_client`

---

Dockerfile
configs/swarm/docker-compose.local.yml
configs/swarm/docker-compose.single.yml
configs/swarm/docker-compose.yml
tools/swarm/src/compose.rs

Since the Dockerfile only supports building for `linux/amd64`, let's pin it for now before we introduce multi-arch builds. Unused (seemingly) dependencies and unnecessary `RUN` layers have been removed/compressed.
Related to #4687.
Docker builds should be faster, unneeded stuff doesn't clutter the Dockerfile.

build(Dockerfile): pin platform to `linux/amd64`, refactor

---

config/src/parameters/actual.rs
core/src/block.rs
core/src/smartcontracts/isi/world.rs
core/src/state.rs
core/src/sumeragi/main_loop.rs
data_model/src/block.rs

While working on #4516, I experimented with extreme reduction of consensus timings, i.e. `block_time` and `commit_time`. Those are configured by `NewParameter` and `SetParameter` ISIs (until #4028). It turned out that there are a few issues in `iroha_core`:
- In some places it relies on hardcoded `DEFAULT_CONSENSUS_ESTIMATION` (4 seconds) for no reason, leading to some bugs, e.g. improper time triggers execution. I made it rely on the values in the actual State config.
- Config in the State was not updated immediately when relevant ISI executed, leading Iroha to ignore updates that actually affect its behaviour, which caused desynchronisation and unexpectedly long block times when the config values are small.
So, this PR "tightens" these gaps and makes parameters application preciser. …

refactor: fix application of the core chain-wide parameters; chores

---

cli/src/lib.rs
configs/swarm/genesis.json
genesis/src/lib.rs

refactor(genesis)!: remove _id and _file suffix from genesis fields

---

p2p/src/network.rs
p2p/src/peer.rs

Backport of #4398.
Closes #4267 
No problem with connectivity on rc20.

fix: Introduce p2p idle timeout

---

cli/src/samples.rs
client/examples/register_1000_triggers.rs
client/src/config.rs
client/src/config/user.rs
config/base/src/util.rs
config/base/tests/misc.rs
config/src/parameters/actual.rs
config/src/parameters/defaults.rs
config/src/parameters/user.rs
config/tests/fixtures.rs
config/tests/fixtures/full.toml
configs/client.template.toml
configs/peer.template.toml
core/benches/blocks/common.rs
core/src/smartcontracts/wasm.rs
core/src/snapshot.rs
core/src/state.rs
tools/kagami/src/genesis/generate.rs
torii/src/lib.rs

Since there is still no consensus about using human readable types in configuration (#4294, #4295), I decided to at least make it explicit that they aren't supported.
- Reverted use of `_ms` suffix for millisecond numbers
- Used `_bytes` suffix for <code>torii.max_content_length<b>_bytes</b></code>
- Updated config templates
- Refactored internals:
- Renamed `HumanDuration` to `DurationMs`, and `HumanBytes` to just `Bytes`
- Chore refactors

refactor!: revert `_ms` and `_bytes` suffixes in config

---

.github/workflows/iroha2-dev-pr-wasm.yaml
Cargo.lock
smart_contract/utils/Cargo.toml
smart_contract/utils/src/debug.rs
smart_contract/utils/src/lib.rs
smart_contract/utils/src/log.rs

This PR adds support for `iroha_smart_contract_utils`'s `log` and `dbg` functions to be used outside of wasm. This allows writing tests to be ran against the host target and to still use those wasm-specific functions.
Both implementations just print the requested object to stderr.
As a drive-by, this also makes sure to run wasm tests from `iroha_smart_contract_utils`, which was omitted in CI for some time.
Fixes #4721

fix: Make `iroha_smart_contract_utils` `log` and `dbg` functions work outside of wasm

---

core/src/sumeragi/main_loop.rs

Exit early from `handle_block_sync` if received block is the same or has smaller or equal view change index.
Improve performance of block sync by avoid doing work where not necessary.

fix(sumeragi): early exit from handle_block_sync

---

Cargo.lock
Cargo.toml

Now that the displaydoc has released a version which fixed the nightly warnings, we can migrate back to it.
(We were previously using a git version because of #4567)

chore: move back to the upstream displaydoc

---

.github/workflows/iroha2-dev-code-quality.yml

Attempt to fix `CodeQuality` workflow `checkout` actions that always points to repository defaults branch even if PR is coming from not-default branch.
https://github.com/orgs/community/discussions/66784
https://github.com/orgs/community/discussions/25220
Perhaps will fix `CodeQuality` workflow.

ci: Modify CodeQuality job branch checkout variable

---

CONTRIBUTING.md
docs/source/guides/hot-reload.md
docs/source/iroha_2_whitepaper.md

docs(md): fix typos in CONTRIBUTING, iroha_2_whitepaper, hot-reload

docs(md): fix typos in CONTRIBUTING, iroha_2_whitepaper, hot-reload

---

cli/README.md
cli/src/lib.rs
client/benches/tps/utils.rs
client/tests/integration/extra_functional/genesis.rs
client/tests/integration/extra_functional/mod.rs
client/tests/integration/extra_functional/normal.rs
client/tests/integration/extra_functional/offline_peers.rs
client/tests/integration/extra_functional/restart_peer.rs
client/tests/integration/extra_functional/unstable_network.rs
client/tests/integration/triggers/by_call_trigger.rs
configs/swarm/docker-compose.local.yml
configs/swarm/docker-compose.single.yml
configs/swarm/docker-compose.yml
core/src/sumeragi/main_loop.rs
core/test_network/src/lib.rs
scripts/test_env.py
tools/swarm/src/lib.rs
tools/swarm/src/schema.rs

Continuation of #4739:
* Topology stored in genesis block will be used as initial topology, as a result multiple peers can submit genesis
* Removed `--submit-genesis` flag
* Changed `scripts/test_env.py`, it will submit genesis for all peers
Closes #4696

feat: Allow multiple peers submit genesis block

---

configs/swarm/docker-compose.local.yml
configs/swarm/docker-compose.single.yml
tools/swarm/README.md
tools/swarm/src/lib.rs
tools/swarm/src/schema.rs
tools/swarm/src/schema/serde_impls.rs

Image for Compose is now built by the first peer service instead of the dummy builder. Solves [the CI failure](https://github.com/hyperledger/iroha/actions/runs/9739223415/job/26874072004) when testing generated Compose configs caused by https://github.com/docker/compose/issues/10596.
No need for a dummy service to build images.

refactor(swarm): build with `irohad0` instead of dummy builder

---

configs/swarm/genesis.json
data_model/src/parameter.rs
schema/gen/src/lib.rs
tools/kagami/src/genesis/generate.rs

Include parameters into default genesis.json.
While parameters may have default values i still think it's useful to include them into default genesis as an example.
I've got contacted by our QA and they didn't have a way to know how new parameters are expressed in the genesis.

feat: include parameters into generated genesis

---

client/benches/torii.rs
client/examples/million_accounts_genesis.rs
client/src/client.rs
client/tests/integration/asset.rs
client/tests/integration/asset_propagation.rs
client/tests/integration/events/notification.rs
client/tests/integration/extra_functional/multiple_blocks_created.rs
client/tests/integration/extra_functional/unregister_peer.rs
client/tests/integration/multisig.rs
client/tests/integration/non_mintable.rs
client/tests/integration/pagination.rs
client/tests/integration/permissions.rs
client/tests/integration/status_response.rs
client/tests/integration/transfer_asset.rs
client/tests/integration/triggers/orphans.rs
client/tests/integration/tx_chain_id.rs
client/tests/integration/tx_rollback.rs
client/tests/integration/upgrade.rs
core/benches/validation.rs
core/src/block.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/query.rs
core/test_network/src/lib.rs
data_model/src/isi.rs
data_model/src/transaction.rs

Converts `impl Instruction` to an explicit type parameter in functions accepting multiple instructions.
Lets users avoid converting heterogeneous instructions to `InstructionBox`es in a separate variable before submitting to a client, which is more ergonomic.

refactor(client): allow turbofish with multiple `Instruction`s

---

client_cli/pytests/src/client_cli/client_cli.py
client_cli/pytests/src/client_cli/have.py
client_cli/pytests/src/client_cli/iroha.py
client_cli/pytests/test/assets/test_register_asset_definitions.py
client_cli/pytests/test/conftest.py
client_cli/src/main.rs
core/benches/validation.rs
core/src/smartcontracts/isi/asset.rs
core/src/state.rs
data_model/src/asset.rs

* fix client cli pytests
* rename `--asset-id` to `--id` in client CLI
* add `asset definition` subparameter in CLI

fix(tests): correctly list asset definitions in CLI tests

---

data_model/benches/time_event_filter.rs
tools/kagami/src/genesis/generate.rs

Fix account ids handling in `kagami genesis generate synthetic`
Closes #4851

fix: Fix `kagami genesis generate synthetic`

---

core/benches/kura.rs
core/src/kura.rs
tools/kura_inspector/src/main.rs

Originally `kura.lock` [was introduced](https://github.com/hyperledger/iroha/issues/3027) to prevent multiple iroha instances running with the same data directory. However if iroha doesn't remove `kura.lock`, e.g. in case of non-graceful shutdown, it causes problem that iroha couldn't start after restart. Also usually iroha is deployed using k8s cluster where each peer lives in different container so original problem is not relevant in this case. So it is proposed to remove `kura.lock`.
Related: #4830
Related: #4848
Remove `kura.lock`, allowing Iroha to restart after non-graceful shutdown

fix: Remove kura.lock

---

client_cli/pytests/src/client_cli/iroha.py
configs/swarm/genesis.json
core/src/block.rs
data_model/derive/src/id.rs
data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/parameter.rs
data_model/src/peer.rs
data_model/src/role.rs
data_model/src/trigger.rs
docs/source/references/schema.json
schema/derive/src/lib.rs

* add support for handling `serde(rename)` attributes with `IntoSchema`
* attach `serde(rename = "type")` to `type_` fields in data model
Closes #4770

fix(schema): rename `type_` to `type` in schema

---

core/src/block.rs
core/src/state.rs
core/src/sumeragi/main_loop.rs

This change allow to preserve voting block during block sync until iroha have to drop it to process transactions.
It is done in two ways: 
1. check block signatures before verification
2. try verify block without discarding voting block
Closes #4834 
Preserve voting block in more cases.
Resulting code is not pretty.
Because it has to handle soft-fork case explicitly and not just revert previous block and proceed.
```
cargo test --package iroha_core --lib -- sumeragi::main_loop::tests::block_sync_commit_err_keep_voting_block --exact --show-output
```

refactor: preserve voting block during block sync

---

core/src/state.rs

While restarting iroha i've noticed that snapshot is inconsistent.
After some investigation i've noticed that assumption i had about the State was wrong (check this [issue](https://github.com/kanidm/concread/issues/97)).
This PR fix this inconsistency by introducing lock which is used to guard block commit and prevent creation of inconsistent views of  the State.
Views are consistent.
Rwlock has problems with writer starvation.

fix(state): use rw lock to prevent inconsitent state view

---

core/src/smartcontracts/isi/triggers/mod.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/smartcontracts/isi/triggers/specialized.rs
data_model/src/events/mod.rs
data_model/src/isi.rs
data_model/src/query/mod.rs
data_model/src/trigger.rs
docs/source/references/schema.json
schema/gen/src/lib.rs

I love static typing. It prevents many errors.
But there is a tradeoff between static typing and an API that is easy to use.
Sometimes too much static typing is difficult for end users
Closes #4376

refactor: remove `TriggeringEventFilterBox`

---

data_model/src/account.rs
data_model/src/asset.rs
data_model/src/domain.rs
data_model/src/metadata.rs
data_model/src/role.rs
docs/source/references/schema.json

* make `Role` transparent in schema
* rename `NewXXX` to `XXX` when serializing as json
This is how schema looked like:
```json
"NewRole": {
"Struct": [
{
"name": "inner",
"type": "Role"
}
]
},
```
but in genesis it was:
```json
{
"Register": {
"Role": {
"id": "ALICE_METADATA_ACCESS",
"permissions": [
{
"name": "CanRemoveKeyValueInAccount",
"payload": {
"account": "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03@wonderland"
}
},
{
"name": "CanSetKeyValueInAccount",
"payload": {
"account": "ed0120CE7FA46C9DCE7EA4B125E2E36BDB63EA33073E7590AC92816AE1E861B7048B03@wonderland"
}
}
]
}
}
},
```
which is the consequence of the fact that we have no way of representing transparency in schema
Related to #1660

fix(schema): make `Role` transparent

---

core/src/gossiper.rs
core/src/queue.rs
core/src/sumeragi/main_loop.rs
core/src/tx.rs

- fix a bug in retain that actually non expired transactions were removed
- qol improvment to print transactions by hash in the logs
- i find it really hard to debug iroha on TRACE level in presence of heavy transactions because all logs are polluted by tx printing 
- fewer bugs
- more clear logs

fix(sumeragi): remove expired transaction from cache

---

core/benches/blocks/common.rs
core/benches/kura.rs
core/benches/validation.rs
core/src/block.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/wasm.rs
core/src/sumeragi/main_loop.rs
data_model/src/block.rs
docs/source/references/schema.json
schema/gen/src/lib.rs

removed `event_recommendations` from block. It was unused

refactor!: remove `event_recommendations` from block

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
client_cli/pytests/common/json_isi_examples/unregister_asset.json
client_cli/pytests/src/client_cli/client_cli.py

This PR implements the ability to run Docker Compose tests within the context of pull requests (PR) instead of after merging. 
We have also developed a CI process that executes Torii API and Client CLI tests on real containers rather than on bare metal. This has reduced the job execution time by 30% thanks to the optimization of the testing process using Torii API and Client CLI tests.
Closes #4925 
Docker Compose tests are now run within the context of PRs, allowing us to identify and fix errors before merging.
Optimization of the testing process using real containers has reduced job execution time by 30%, speeding up the CI process.

ci: conterized testing

---

p2p/src/network.rs
p2p/src/peer.rs

When 2 peers try to send each other huge messages they end up deadlocked.
I suspect that this happen when message is large enough that it's not possible to fully put it in the OS buffer.
Here is minimal [example](https://github.com/Erigara/tcp_deadlock) i was able to came up with which suffers from the same issue.
Solution was to lift sending data up to the `select!` statement so peer can either read or write data simultaneously. 
No deadlock.

fix(p2p): prevent deadlock on simultaneous sending large message

---

core/src/block_sync.rs

There was a problem during TPS testing where block sync could not occur quickly because it would re-request the
same blocks from each peer. Here is a solution that should be robust against that scenario but doesn't introduce
any new issues.

fix: prevent redundant blocksync block messages

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update the PR template.
Related to #4941.
- adds a section on review notes and guidelines
- adds a section on the migration guide
- removes checklist items enforced with CI

docs: update PR template

---

torii/src/lib.rs

Blocks stream endpoint doesn't work with standard WebSocket clients because it uses `POST`. The standard says it should be `GET`: https://stackoverflow.com/questions/50386211/should-websocket-server-only-handle-get-requests
Use `GET` for blocks stream route.
Events stream already uses `GET` (discrepancy btw).

fix(torii): use `GET` for blocks stream

---

primitives/numeric/src/lib.rs

`Numeric` is missing some mathematical operations and it's not possible to use it

fix: add missing mathematical operations to `Numeric`

---

client/benches/tps/utils.rs
client/tests/integration/roles.rs
core/src/block_sync.rs
core/src/kura.rs
core/src/smartcontracts/isi/block.rs
core/src/smartcontracts/isi/query.rs
core/src/smartcontracts/isi/tx.rs
core/src/state.rs

* validate received block sync messages
* optimize FindBlockHeaderByHash
* add start to all_blocks

fix: validate block sync messages

---

crypto/src/signature/mod.rs
data_model/src/block.rs
data_model/src/transaction.rs
primitives/numeric/src/lib.rs

While working on Explorer and using Iroha crates as libraries, found a few minor yet hardly workaroundable issues. Some of them related to not using `iroha_data_model` with `transparent_api` feature, which revealed some inconsistencies with data access.
- Expose getters for the following structs: `BlockSignature`, `TransactionSignature`, `NumericSpec`
- `iroha_crypto::Signature`: make serialization transparent instead of `{ "payload": "..." }`. This field is redundant and inconsistent with other `iroha_crypto` structures - they all serialize as plain strings.
If you passed `Signature` in JSON, do not nest it into an object with `payload` field anymore.
---

fix(data-model,crypto,primitives)!: misc chores

---

scripts/test_env.py

1. Kill iroha but keep logs if waiting for genesis fails
2. Rename log files to make them not hidden by UNIX conventions
Closes #4814 
1. Allows you to debug problems that lead to genesis not being committed
2. Log files not being hidden reduces surprises (I had to look into code two times already to find them)

feat(test-env): Preserve test env logs on crash

---

core/Cargo.toml
core/src/executor.rs
core/src/smartcontracts/isi/world.rs
core/src/smartcontracts/wasm.rs
data_model/src/transaction.rs

I am debugging tps of a single peer (#4727), measured performance of `Sumeragi::try_create_block`, and noticed that executor cloning takes about 25% of `try_create_block`. This is because of `LoadedExecutor::raw_executor` which was added for snapshot creation. Could be fixed by adding `Arc`.
It is also interesting that other wasm-related code takes a lot of time, e.g. `wasmtime::Linker::instantitate` and `wasmtime::Store::into_data`.
Related: #4727
Slightly optimize block creation performance

perf: Fix cloning of executor

---

core/src/block.rs
data_model/src/block.rs
docs/source/references/schema.json
schema/gen/src/lib.rs

it's not necessary to sign the whole block payload since block header holds the merkle tree root hash
this will enable us to work on #4914

refactor: sign only block's header, not the whole payload

---

.github/workflows/iroha2-profiling-image.yml

Sometimes we need to build iroha2 `glibc` image without `profiling` features for longevity testing. Currently we do it manually and locally only.
- Modify `I2::Profiling::Publish` workflow to build either `profiling` image (by new git tag publishing) or vanilla `glibc` image by `workflow_dispatch` event.
- Consider to chose the needed git SHA to build `glibc` image when is required.

ci: Unify CI to build profiling and glibc iroha image

---

core/Cargo.toml
core/src/executor.rs
core/src/smartcontracts/isi/world.rs
core/src/smartcontracts/wasm.rs
data_model/src/transaction.rs

See https://github.com/hyperledger/iroha/pull/4955#issuecomment-2309382255 for details
Use WASM code for snapshot instead of `wasmtime::Module`

fix: Serialize WASM code for snapshots

---

.github/workflows/iroha2-dev-pr.yml
client/tests/integration/extra_functional/connected_peers.rs
client/tests/integration/extra_functional/unstable_network.rs
core/test_network/src/lib.rs

The bug was that the node selection for the client was random. This meant that the node the client was using to observe the tests were being frozen. I fixed it so that the client always is connected to the genesis peer which never gets frozen.

fix: Fix bug in test harness for unstable network

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/block.rs
core/src/metrics.rs
core/src/smartcontracts/isi/mod.rs
core/src/smartcontracts/isi/triggers/set.rs
core/src/state.rs
core/src/tx.rs

Use published on `crates.io` version of `mv` crate (previous name `storage`) to be able to publish iroha itself.
Partially unblock #2933.

refactor: use `mv` crate

---

client/src/query.rs
client/tests/integration/pagination.rs
client_cli/src/main.rs
core/src/query/cursor.rs
core/src/query/pagination.rs
core/src/query/store.rs
data_model/src/query/builder.rs
data_model/src/query/mod.rs
docs/source/references/schema.json
smart_contract/src/lib.rs
wasm_samples/query_assets_and_save_cursor/src/lib.rs

This PR allows the client to inspect the amount of items that is returned by the query without requesting all batches.
Closes #4984
- I rely on `ExactSizeIterator` implementation applied to the pagination combinator. Filtering is not a problem, because we currently eagerly collect all items into a vector before returning anything.
- To not introduce additional split between the type of result of initial and continuation queries, each iterable query response returns the remaining number of items in addition to the batch. This allows us to implement `ExactSizeIterator` on `QueryIterator` pretty naturally.

feat(queries): Report amount of remaining items in query

---

crypto/src/encryption/chacha20poly1305.rs

Closes #4994
- instead of XORing with `ciphertext[1]` which can happen to be `0`, XOR with a constant `0x01`, always flipping one bit

fix: make sure that chacha20poly1305::tests::decrypt_should_fail is not flaky

---

.github/PULL_REQUEST_TEMPLATE.md

We had to disable required status checks because GitHub doesn't provide a clean way to ignore them conditionally. This PR returns the item on CI checks passing back into the PR template
---

chore: add an item on CI checks to PR template

---

p2p/src/peer.rs

It was observed that iroha consume a lot CPU in idle state, turned out it was due to accidental busy loop in p2p code.
Closes: #5033
Add conditional disabling sending message in `Peer` even loop when there is no data to be sent to prevent busy loop.

fix(p2p): disable sending message when not ready to prevent busy loop

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/message.rs
core/src/sumeragi/view_change.rs

Instead of sending every view change proof only view change proof for current round and previous verified proof are sent.
Closes #4926 
This help peer which is lagging behind to directly jump to most recent view change and participate in consensus.

refactor(view_change): only send current and previous view change proof

---

data_model/src/parameter.rs
defaults/genesis.json
docs/source/references/schema.json
genesis/src/lib.rs
schema/gen/src/lib.rs

Fixes #4813
Changes format of `genesis.json` from:
```json5
{
...
"parameters": [
{
"Sumeragi": {
"BlockTimeMs": 2000
}
},
{
"Sumeragi": {
"CommitTimeMs": 4000
}
},
...
{
"Transaction": {
"MaxInstructions": 4096
}
},
...
```
to:
```json5
{
...
"parameters": {
"sumeragi": {
"block_time_ms": 2000,
"commit_time_ms": 4000,
...
},
"transaction": {
"max_instructions": 4096,
...
},
...
```
* `kagami genesis generate` will generate genesis in the new format. Custom genesis generator tools should be changed to new format. 
* Note that schema.json has type entry `RawGenesisTransaction` corresponding to genesis.json file

refactor: Change parameters format in genesis.json

---

schema/gen/src/lib.rs

This gives the IDE a hint that it's a type name and allows one to navigate to the type definition and see name resolution errors
---

feat(schema): use the type names passed to schema's `types!` macro in type position

---

core/src/sumeragi/main_loop.rs
core/src/sumeragi/mod.rs
core/src/sumeragi/network_topology.rs

Closes #4883.
Don't use block signatures for topology update.

fix(topology): dont depend on signatures for update

---

crates/iroha/tests/integration/pagination.rs
crates/iroha/tests/integration/status_response.rs
crates/iroha_data_model/src/parameter.rs
crates/iroha_genesis/src/lib.rs

Fixes #5049
* Moved `apply_parameter` function to the `data_model`
* Also fixed port for some tests:
* `reported_length_should_be_accurate` used port 11_170 which conflicts with `register_offline_peer`
* `json_and_scale_statuses_equality` used port 11_200 which conflicts with `restarted_peer_should_have_the_same_asset_amount`

fix: Fix `iroha_genesis` compilation without `transparent_api` feature

---

crates/iroha_core/src/gossiper.rs
crates/iroha_core/src/kura.rs
crates/iroha_core/src/query/store.rs
crates/iroha_futures/src/supervisor.rs

#4716 broke some tests.
This PR fixes `kura_not_miss_replace_block`, increases timeout for `can_monitor_os_thread_spawn` (broken in #4996), and does some other chores.
It doesn't fix `restarted_peer_should_have_the_same_asset_amount` as it requires deeper refactoring (WiP).

fix(supervisor): failing tests, chores

---

.github/workflows/iroha2-dev-pr-wasm.yaml
Cargo.lock
crates/iroha_crypto/src/lib.rs
crates/iroha_smart_contract/Cargo.toml

Fixes #5038
Make `PublicKey` decoding lazy inside WASM, since `PublicKey` in WASM is used mostly for comparison operations (`==`), and comparison can be performed without decoding (see #5038 for details). This givess approximatelly 400tps increase for single peer (from ~2450 to ~2850).

perf: Make `PublicKey` decoding lazy inside WASM

---

crates/iroha_schema/src/lib.rs
crates/iroha_schema/src/serialize.rs
crates/iroha_schema/tests/enum_with_default_discriminants.rs
crates/iroha_schema/tests/enum_with_various_discriminants.rs
crates/iroha_schema/tests/fieldless_enum.rs
crates/iroha_schema/tests/numbers_compact_and_fixed.rs
crates/iroha_schema/tests/struct_with_generic_bounds.rs
crates/iroha_schema/tests/struct_with_named_fields.rs
crates/iroha_schema/tests/struct_with_unnamed_fields.rs
crates/iroha_schema/tests/transparent_types.rs
crates/iroha_schema_gen/src/lib.rs

Fixes #5041.
- Make `MetaMap` preserve the type id (the one reported by iroha's `TypeId::id`). Unlike type name, this string is not affected by the transparent types, and now adequately reports the problem with a missing `Box`ed type
- Expose the type id in the `no_extra_or_missing_schemas` test
<details>
<summary>Error before</summary>
```
Missing types: {
(
"CompoundPredicate<AccountPredicateBox>",
Enum(
EnumMeta {
variants: [
EnumVariant {
tag: "Atom",
discriminant: 0,
ty: Some(
TypeId {
t: (
10095233817367655734,
3465063886364562919,
),
},
),
},
EnumVariant {
tag: "Not",
discriminant: 1,
ty: Some(
TypeId {
t: (
14448333017410507765,
1039736120081770805,
),
},
),
},
EnumVariant {
tag: "And",
discriminant: 2,
ty: Some(
TypeId {
t: (
13976757441058666220,
14378548965820588092,
),
},
), …
```

fix: report schema type id in no_extra_or_missing_schemas test

---

crates/iroha/tests/integration/queries/smart_contract.rs
crates/iroha_core/src/query/cursor.rs
crates/iroha_core/src/query/store.rs
crates/iroha_data_model/src/query/mod.rs
crates/iroha_torii/src/lib.rs
docs/source/references/schema.json

- Makes the `UnknownCursor` error more specific. There are several places with different logic where this error is returned (query not found, cursor mismatch, not enough items). Moves the error thrown on a query not being found in the store from `UnknownCursor`.
- Part of investigation of #5085.

refactor: make query cursor errors more specific

---

crates/iroha_core/src/block.rs
crates/iroha_data_model/src/query/predicate/predicate_atoms/block.rs
crates/iroha_data_model/src/transaction.rs
crates/iroha_schema_gen/src/lib.rs

Related: #5083
`CommittedTransaction::error` takes 200 bytes and is `None` in case of a successful transaction. Using `Option<Box<...>` reduces memory usage of iroha approximately by 10% (considering that all transactions are successful and with testing configuration as in #5083)

perf: Reduce memory usage of `CommittedTransaction`

---

crates/iroha_ffi/src/option.rs

- Describe the objective or issue this PR addresses, as well as the impact of the change.
- Try to keep the description accessible to newcomers.
- If you're resolving a specific issue, add "Fixes #issue_number" or "Closes #issue_number".
---

fix(ffi): Add implementation of Niche for `Option<Box<R>>`

---

crates/iroha_core/src/gossiper.rs
crates/iroha_core/src/queue.rs

Closes #4952.
Solution is not to broadcast the same transactions indefinitely and do that in batches at most once.

refactor(gossiper): gossip txs at most once

---

crates/iroha_data_model/src/block.rs

Currently, genesis block might be created with time equal to genesis transaction creation time. We have invariant that "transaction creation time" < "block creation time" (added in #4928), so this will result in error:
```
thread 'tokio-runtime-worker' panicked at crates/iroha_core/src/kura.rs:331:14:
INTERNAL BUG: Failed to decode block: ParityScale("Could not decode `SignedBlock::V1.0`:\n\tCould not decode `SignedBlockCandidate::payload`:\n\t\tTransaction creation time is ahead of block creation time\n")
```
Ensure that genesis block time is at least 1 millisecond ahead of genesis transaction time.

fix: Fix timestamp of genesis block

---

.github/workflows/iroha2-custom-image.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-release.yml
crates/iroha_swarm/src/lib.rs
crates/iroha_swarm/src/schema.rs
defaults/docker-compose.local.yml
defaults/docker-compose.single.yml
defaults/docker-compose.yml

1. Use Debian based image by default for iroha2 image.
2. Set the default retention policy for `executor.wasm` artifact as we need it to be able to be downloaded.
3. Enable checkout branch/commit option for all custom images build & push job.
Close #5100 
Building iroha based on glibc and Debian increases compilation time in aboit two times.
iroha based on glibc and Debian increases image size in about three times.

ci: Switch iroha2 default image to debian-based

---

crates/iroha/tests/integration/asset.rs
crates/iroha/tests/integration/events/data.rs
crates/iroha/tests/integration/multisig.rs
crates/iroha/tests/integration/permissions.rs
crates/iroha/tests/integration/queries/role.rs
crates/iroha/tests/integration/roles.rs
crates/iroha/tests/integration/transfer_domain.rs
crates/iroha/tests/integration/triggers/by_call_trigger.rs
crates/iroha/tests/integration/upgrade.rs
crates/iroha_core/src/kura.rs
crates/iroha_core/src/smartcontracts/isi/account.rs
crates/iroha_core/src/smartcontracts/isi/world.rs
crates/iroha_core/src/state.rs
crates/iroha_data_model/src/isi.rs
crates/iroha_data_model/src/role.rs
crates/iroha_executor/src/default.rs
crates/iroha_executor/src/lib.rs
crates/iroha_executor/src/permission.rs
crates/iroha_executor_data_model/src/permission.rs
crates/iroha_kagami/src/genesis/generate.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_test_network/src/lib.rs
defaults/genesis.json
docs/source/references/schema.json
wasm_samples/executor_with_custom_permission/src/lib.rs
wasm_samples/multisig_register/src/lib.rs

- added `CanManagePeers`, `CanRegisterDomain` and `CanManageRoles` permissions
- unified `CanSetKeyValueXXX` + `CanRemoveKeyValueXXX` = `CanModifyXXXMetadata`
- unified `CanMintAsset` + `CanBurnAsset` + `CanTransferAsset` = `CanModifyAsset`
- changed `FindPermissions` so it returns only inherent permissions, not from roles 
- fixed validation of grant/revoke for roles
closes #4206

refactor(permissions): define default permission set

---

crates/iroha_core/src/block_sync.rs

Closes #5072.
After more than 2 blocks was shared through block stream this problem appeared.
Bug was that code checked that `blocks[i].height -1 == blocks[i + 1].height`, when should be `blcoks[i].height + 1 == blocks[i + 1].height`.
Tests were added to check this validation.

fix(block_sync): check that next block has height +1

---

.github/workflows/iroha2-custom-image.yml
.github/workflows/iroha2-dev-nightly.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-wasm.yaml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev-sonar-dojo.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-no-incorrect-image.yml
.github/workflows/iroha2-pr-ui.yml
.github/workflows/iroha2-release.yml
crates/iroha/tests/integration/permissions.rs
crates/iroha/tests/integration/upgrade.rs
crates/iroha_cli/.gitignore
pytests/iroha_cli_tests/README.md
pytests/iroha_cli_tests/common/settings.py
pytests/iroha_cli_tests/src/iroha_cli/__init__.py
pytests/iroha_cli_tests/src/iroha_cli/configuration.py
pytests/iroha_cli_tests/src/iroha_cli/iroha_cli.py
pytests/iroha_cli_tests/test/conftest.py

This PR sets up `cargo nextest` for running Rust tests, and makes other CI-related improvements:
- Run unit tests with `no-default-features` (closes #4854)
- Retry client pytests (follow-up ticket: https://github.com/hyperledger/iroha/issues/5014)
- Do not build/download the default executor where it's not needed (post #4931)
- ~Caching dependencies should actually work now (switch from [`rust-cache`](https://github.com/Swatinem/rust-cache) to [`cargo-cache`](https://github.com/Leafwing-Studios/cargo-cache)), cache is shared between similar jobs~
- Self-hosted runners don't work with `cargo-cache`, and `rust-cache` never seems to hit the cache even though it writes to it.
- Fixes #4499 (specifies the exact Ubuntu version)
---

ci: use Nextest, remove broken rust-cache, more unit test coverage

---

crates/iroha_core/src/smartcontracts/wasm.rs
crates/iroha_executor/src/lib.rs
crates/iroha_executor_derive/src/entrypoint.rs

Fixes #5074
From the issue:
> when wasm is executed it's `entrypoint` function is always without arguments and does a callback to `get_xxx_context` to initialize. We should remove that (as it saves us one call to host) and directly provide an encoded argument when calling the `entrypoint` function.

perf: Directly provide payload to WASM entrypoints

---

crates/iroha/tests/integration/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/smartcontracts/isi/triggers/mod.rs
crates/iroha_core/src/state.rs
crates/iroha_data_model/benches/time_event_filter.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/events/time.rs
crates/iroha_data_model/src/parameter.rs
crates/iroha_schema_gen/src/lib.rs
docs/source/references/schema.json

Closes #5053.
Remove consensus estimation.
Time trigger execution based on `(prev_block_creation_time; current_block_creation_time]`.
Require recompilation of executor and triggers.

feat: remove consensus estimation

---

Cargo.lock
crates/iroha_schema_derive/Cargo.toml
crates/iroha_schema_derive/src/lib.rs

This PR does applies a refactor to use an error emitter instead of bailing early in the iroha_schema derive macros, like was done in https://github.com/hyperledger/iroha/pull/3897.
The second commit is just a drive-by refactor removing some code duplication in where clause generation.
This is in preparation for a PR adding smart trait bound derivation (#5130).

refactor(schema_derive): use error emitter instead of bailing out early

---

crates/iroha_config/Cargo.toml
crates/iroha_config/src/parameters/actual.rs
crates/irohad/src/lib.rs

_Split from #5087_
When there was one trusted peer, it decided that there are no.
Fix the check
None
---
None

fix(iroha_config): broken trusted peers check

---

crates/iroha_torii/Cargo.toml
crates/iroha_torii/src/lib.rs
crates/irohad/src/lib.rs

Split from #5087 
Chore refactor: there was extra code complexity in Torii due to `iroha_primities::SocketAddr` not implementing `tokio::ToSocketAddrs`.
Workarounded with a match construction.
None
---
None

refactor(iroha_torii): spawn a single server task with only one `TcpListener`

---

crates/iroha_core/src/block.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs

fix: Leader as transaction ordering service

---

crates/iroha/tests/integration/triggers/time_trigger.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_core/src/sumeragi/mod.rs
crates/iroha_data_model/src/parameter.rs

- Commit time is now linear function of view change index (capped at Duration::MAX)
- Add more logs to track messages arriving to sumeragi
Note: #4929 would also nice to have because it prevents degradation of view change updates.
Closes #4265 
This allow to consensus to pass heavy transactions which cause infinite loop previously.
Currently it's not possible to modulary test consensus :(
So i've did my tests on bare metal iroha with 4 nodes.
Parameters:
config.toml:
```toml
[network]
transaction_gossip_period_ms = 10_000
[transaction]
time_to_live_ms = 3_600_000
```
genesis.json:
```json
{
"Sumeragi": {
"BlockTimeMs": 100
}
},
{
"Sumeragi": {
"CommitTimeMs": 100
}
}
```
Notice that `transaction_gossip_period_ms` was crucial here, because without it i faced #4952.  
Check this …

feat(sumeragi): dynamic commit time based on view change index

---

Cargo.lock
crates/iroha/src/client.rs
crates/iroha_torii/Cargo.toml
crates/iroha_torii/src/block.rs
crates/iroha_torii/src/event.rs
crates/iroha_torii/src/lib.rs
crates/iroha_torii/src/routing.rs
crates/iroha_torii/src/stream.rs

Closes #5004.
Problem was that iroha tried to unconditionally closed websocket by writing into it.
During another problems were discovered as well:
- on client side sync and async websocket stream wasn't properly closed (not reads until handshake completion)
- on client async websocket `Stream` implementation was incorrect by not registering itself on receiving non binary message
Fix mentioned problems + refactoring.

fix(torii): close ws properly in blocks/events stream

---

Cargo.toml
crates/iroha_crypto/src/lib.rs
crates/iroha_data_model/src/lib.rs
crates/iroha_derive/tests/ui.rs
crates/iroha_telemetry/Cargo.toml
crates/iroha_telemetry_derive/Cargo.toml
crates/iroha_telemetry_derive/src/lib.rs
wasm_samples/default_executor/src/lib.rs
wasm_samples/executor_with_migration_fail/src/lib.rs
wasm_samples/query_assets_and_save_cursor/src/lib.rs

Close #4993 (see context there)
I found yet another time that metrics & telemetry is broken in Iroha. This PR doesn't fix it, but disables more parts of it to remove noisy warnings. Main issue is #5134 
---

fix: address `check-cfg` warnings + chores

---

crates/iroha_data_model/src/isi.rs
crates/iroha_schema_derive/Cargo.toml
crates/iroha_schema_derive/src/lib.rs
crates/iroha_schema_derive/src/trait_bounds.rs
crates/iroha_schema_derive/tests/ui_pass/derive_into_schema.rs

Part of the solution for #5130.
This PR changes the way `iroha_schema_derive` generates trait bounds to the same algorithm that is used by `parity-scale-codec`.
In general, it adds a bound on `IntoSchema` for types of all the fields that use the generic parameters, with some special handling for `#[codec(skip)]`, `#[codec(compact)]` and recursive types.
See docs for `trait_bounds::add` for more details.
All of the `#[schema(bounds = ...)]` attributes are removed now, as there's no need for them anymore.
---
- beware: if #5131 hasn't been merged yet, the commits for that PR will be included in the diff

refactor(schema_derive): use a smarter algorithm for auto-generated trait bounds

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev-sonar-dojo.yml

Possible fix for `llvm-cov` (instead of `grcov`) coverage report compatibility within the Sonarqube analysis.
Based on https://community.sonarsource.com/t/cant-get-llvm-cov-reports-to-show-up-in-sonarqube-project/20833/4 topic.
We might revert back to `lcov.info` coverage format instead of `coverage.txt`. The last one is a kinda of tested and recommended.

ci: Add llvm-cov parameter for sonar

---

crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_p2p/src/network.rs

The bug is triggered if a a peer is unregistered from the topology while Sumeragi Messages are still in flight. This
is the only place where we use and array index operation that can panic. It is very hard to write a test for this case
that is guaranteed to show the issue each time.
Closes #5104 
---

fix: Add range check to signature index

---

Cargo.lock
Cargo.toml
crates/iroha_core/Cargo.toml
crates/iroha_core/benches/kura.rs

Fixes #5172
`cargo audit` founds 4 warnings and no critical errors.
---
* RUSTSEC-2024-0370 `proc-macro-error` is unmaintained
```
proc-macro-error 1.0.4
└── syn_derive 0.1.8
└── borsh-derive 1.5.1
└── borsh 1.5.1
└── rust_decimal 1.36.0
```
This is a false-positive caused by [Cargo.lock containing optional dependencies](https://github.com/rust-lang/cargo/issues/10801). However I noticed that we have dependency `byte-unit` used only once in bench code. I removed this dependency and the warning disappears
---
* Two warnings related to `atty`:
* RUSTSEC-2024-0375 `atty` is unmaintained
* RUSTSEC-2021-0145 Potential unaligned read
```
atty 0.2.14
└── supports-color 1.3.1
└── owo-colors 3.5.0
```
Fix: Update `owo-colors` to v4
---
* `futures-util` 0.3.30 is …

fix: Fix `cargo audit` warnings

---

crates/iroha/tests/queries/mod.rs
crates/iroha/tests/tx_history.rs
crates/iroha_core/src/smartcontracts/isi/tx.rs

feat: Sort descending in `FindTransactions` query

---

crates/iroha/tests/extra_functional/multiple_blocks_created.rs
crates/iroha/tests/extra_functional/normal.rs
crates/iroha/tests/extra_functional/offline_peers.rs
crates/iroha/tests/extra_functional/restart_peer.rs
crates/iroha/tests/extra_functional/unregister_peer.rs
crates/iroha/tests/queries/account.rs
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/queries/query_errors.rs
crates/iroha/tests/queries/role.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/mod.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha/tests/triggers/trigger_rollback.rs

I think we should mark `I2::Dev::Tests` workflow as required for PR merge, since there are no more flaky tests on CI

fix: Fix `cargo check` and `cargo fmt`

---

Cargo.lock
crates/iroha_core/src/kura.rs
crates/iroha_data_model/src/parameter.rs
crates/iroha_genesis/Cargo.toml
crates/iroha_genesis/src/lib.rs
crates/iroha_kagami/src/genesis/generate.rs
crates/iroha_kagami/src/genesis/sign.rs
crates/iroha_test_network/src/config.rs
crates/irohad/src/main.rs

- in `iroha_genesis` there is room to reduce some functions and their arguments
- currently both `GenesisBuilder` and `RawGenesisTransaction` can e.g. `append_instruction`
- streamline `GenesisBuilder` `RawGenesisTransaction` `GenesisBlock` flow
- clarify the responsibility boundary between `GenesisBuilder` and `RawGenesisTransaction`
- only `GenesisBuilder` has building methods like `append_instruction`
- allow `RawGenesisTransaction` to revert `into_builder` to rebuild

refactor: streamline `GenesisBuilder` `RawGenesisTransaction` `GenesisBlock` flow

---

.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev-sonar-dojo.yml

Sonar coverage doesn't work with `llvm-cov`.
Add more possible coverage params.

ci: Add more possible sonar coverage params

---

crates/iroha/src/client.rs
crates/iroha/src/config.rs
crates/iroha/src/lib.rs
crates/iroha/src/secrecy.rs

fix: Protect `BasicAuth::password` from being printed

---

Cargo.toml
crates/iroha/tests/queries/mod.rs
crates/iroha_cli/src/main.rs
crates/iroha_config/Cargo.toml
crates/iroha_numeric/Cargo.toml
crates/iroha_primitives/Cargo.toml
crates/iroha_schema/Cargo.toml
crates/iroha_version/Cargo.toml
crates/iroha_version_derive/Cargo.toml
crates/iroha_wasm_codec/Cargo.toml

Currently some crates can't be tested individually, e.g.:
```
cargo test --package iroha_swarm
```
=>
```
Compiling iroha_config v2.0.0-rc.1.0 (/home/dima/soramitsu/fresh/iroha/crates/iroha_config)
error[E0277]: `strum::ParseError` doesn't implement `std::fmt::Display`
--> crates/iroha_config/src/kura.rs:17:5
```
This PR fixes it. I used the following commands to test it:
<details>
```
cargo test --no-run --package iroha &&
cargo test --no-run --package iroha_cli &&
cargo test --no-run --package iroha_codec &&
cargo test --no-run --package iroha_config &&
cargo test --no-run --package iroha_config_base &&
cargo test --no-run --package iroha_config_base_derive &&
cargo test --no-run --package iroha_core &&
cargo test --no-run --package iroha_crypto &&
cargo test --no-run --package …
```

fix: Fix running tests for individual crates

---

crates/iroha_genesis/src/lib.rs
crates/iroha_swarm/src/lib.rs
crates/iroha_swarm/src/schema.rs
defaults/docker-compose.local.yml
defaults/docker-compose.single.yml
defaults/docker-compose.yml
scripts/build_wasm.sh
scripts/test_env.py

#5027 made test environments generate `genesis.json` by themselves, which took away the means to reflect local `genesis.json` changes to the test environments
Partially revert #5027 for `docker compose` and `test_env.py` to inherit and modify local `genesis.json`
---
- `executor` `wasm_dir` paths are resolved at the modified `genesis.json`. They aren't affected by the second resolution in `RawGenesisTransaction::from_path` during `kagami genesis sign`

fix: test environments inherit and modify local `genesis.json`

---

.github/workflows/iroha2-dev-pr.yml

`llvm-cov` coverage doesn't work with SonarQube.
Add Action to upload coverage report to `Coveralls`.

ci: Add back Coveralls coverage tool

---

.github/workflows/iroha2-dev-pr.yml

Doc tests are disabled by default [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#known-limitations)
Enable it

ci: enable doc tests

---

.github/workflows/iroha2-dev.yml

We need to trigger java-sdk tests to upload these results to Allure.
Add the corresponding webhook trigger.

ci: Add webhook trigger for iroha-java tests upload to Allure

---

crates/iroha/tests/status_response.rs
crates/iroha_core/src/lib.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/smartcontracts/isi/world.rs
crates/iroha_core/src/state.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_core/src/sumeragi/mod.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_torii/src/lib.rs
crates/iroha_torii/src/routing.rs
crates/iroha_torii_const/src/lib.rs
docs/source/references/schema.json
pytests/iroha_torii_tests/common/schemas/get_status_response.json

Ever since #5117 clients have lost the ability to find about other nodes in the network except for the node they are connecting to. This is because `FindPeers` doesn't return address anymore, just peers's public key. We can't return data that is not on chain in this query so I've implemented another `torii` endpoint
- add new torii endpoint `/peers`
I see that we have `/status` and `/metrics`. I'm not sure why we have both since, from what I can see, `/status` is a superset of `/metrics. Considering this, I can make it so that peers are returned on one of those endpoints instead of adding a new point. I implemented this functionality on a separate endpoint because:
1. there can be lots of peers returned and we may want to batch this response
2. we don't want the client to pay the price of …

feat: add /peers API endpoint to torii

---

crates/iroha_executor/src/default/mod.rs
crates/iroha_executor/src/permission.rs

While working on #4087, I noticed that in default executor we have a relatively complex code fragment related to revoking permissions that has been duplicated four times. In #4087, I need it to be duplicated a fifth time, so I think it is worth abstracting it into a separate function.

refactor: Simplify revoking permission in default executor

---

crates/iroha_core/benches/validation.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/executor.rs
crates/iroha_core/src/smartcontracts/wasm.rs
crates/iroha_core/src/smartcontracts/wasm/cache.rs
crates/iroha_core/src/tx.rs

Meta issue: optimizing single peer tps #4727.
It was identified that executor related things takes noticeable amount of time (https://github.com/hyperledger/iroha/issues/3716#issuecomment-2348417005).
Fixes #3716
Single executor WASM instance will be used for validating all transactions of a block. It gives approximately 10-15% improvement of single peer tps (from 2900 to 3300). However there is a problem with lifetimes and I have to use a hack with `std::mem::transmute` to bypass borrow checker. Would be glad to hear opinions/suggestions about it.
Primary change is that data stored in `wasmtime::Store` was changed from `CommonState<...>` to `Option<CommonState<...>>`

perf: Persistent executor

---

pytests/iroha_cli_tests/common/consts.py
pytests/iroha_cli_tests/common/helpers.py
pytests/iroha_cli_tests/common/json_isi_examples/grant_permission.json
pytests/iroha_cli_tests/common/json_isi_examples/revoke_permission.json
pytests/iroha_cli_tests/common/json_isi_examples/unregister_asset.json
pytests/iroha_cli_tests/src/iroha_cli/have.py
pytests/iroha_cli_tests/src/iroha_cli/iroha_cli.py
pytests/iroha_cli_tests/test/conftest.py
pytests/iroha_cli_tests/test/permissions/__init__.py
pytests/iroha_cli_tests/test/permissions/test_grant_permissions.py
pytests/iroha_cli_tests/test/permissions/test_revoke_permissions.py

- Improved test coverage for Iroha CLI permission management commands.
- Enhanced error handling and code readability.
- Added new tests for edge cases (invalid permissions, nonexistent accounts, data format errors).
- Scenarios for granting and revoking permissions.

test: add grant and revoke tests

---

crates/iroha/src/lib.rs
crates/iroha/src/secrecy.rs

Basic auth is defined as
```
pub struct BasicAuth {
pub web_login: WebLogin,
pub password: SecretString,
}
```
Since the constructor of `SecretString` is not public, a client can't construct a config without using `load()`. It is currently required by Python lib.
This PR makes `SecretString` public.

fix: make secret string public

---

crates/iroha/src/lib.rs
crates/iroha/src/secrecy.rs

Basic auth is defined as
```
pub struct BasicAuth {
pub web_login: WebLogin,
pub password: SecretString,
}
```
Since the constructor of `SecretString` is not public, a client can't construct a config without using `load()`. It is currently required by Python lib.
This PR makes `SecretString` public.

fix: Make SecretString public

---

.github/workflows/iroha2-dev-nightly.yml
.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr-title.yml
.github/workflows/iroha2-dev-pr-wasm.yml
.github/workflows/iroha2-dev-pr.yml
.github/workflows/iroha2-dev.yml
.github/workflows/iroha2-doc-links.yml
.github/workflows/iroha2-no-incorrect-image.yml
.github/workflows/iroha2-pr-ui.yml
Cargo.lock
README.md
crates/iroha/src/config.rs
crates/iroha/src/config/user.rs
crates/iroha/src/secrecy.rs
crates/iroha_config_base/Cargo.toml
crates/iroha_config_base/src/util.rs
crates/iroha_data_model/src/lib.rs
crates/iroha_kagami/src/genesis/generate.rs
crates/iroha_test_network/src/config.rs
defaults/genesis.json
docs/source/references/client.template.toml

In testnet,
- Alice needs to be more administrative
- Client needs to be configured by env vars

feat(testnet): test-genesis as a default, env vars for client config

---

crates/iroha_cli/src/main.rs
crates/iroha_executor/src/default/isi/multisig/transaction.rs
crates/iroha_executor_data_model/src/isi.rs
docs/source/references/schema.json

- Fix misdefined `NonZeroU64` to `u64`

fix: revise NonZeros

---

.github/workflows/iroha2-dev-pr-static.yml
.github/workflows/iroha2-dev-pr.yml
crates/iroha_core/src/smartcontracts/wasm/cache.rs
lychee.toml
pytests/iroha_cli_tests/README.md
pytests/iroha_torii_tests/README.md

Since the latest poetry update, some warnings have been treated as errors, causing CI to fail.
[Example](https://github.com/hyperledger-iroha/iroha/actions/runs/12828450212/job/35773040722?pr=5282)

ci: fix poetry usage

---

crates/iroha_torii_const/src/lib.rs

chore: remove redundant consts from `iroha_torii_const`

---

crates/iroha_test_network/src/lib.rs

It is quite difficult to read logs of local tests in json format, so I propose to use pretty format for them. Also fixed newlines in such logs.

refactor(iroha_test_network): use pretty format for logs

---

crates/iroha_cli/CommandLineHelp.md
crates/iroha_cli/src/main.rs
crates/iroha_numeric/src/lib.rs
defaults/genesis.json

Fixes #5335
https://github.com/hyperledger-iroha/iroha/pull/5308#discussion_r1968589667
Use default JSON serialization for `NumericSpec`. 
Custom `Display` implementation is kept for ISI display formatting.
This PR should be considered as part of #5308, so see "Migration Guide" section in #5308
---

refactor!: Simplify serialization of `NumericSpec` in `genesis.json`

---

CHANGELOG.md
crates/iroha/tests/extra_functional/connected_peers.rs
crates/iroha/tests/queries/mod.rs
crates/iroha/tests/status_response.rs
crates/iroha/tests/triggers/by_call_trigger.rs
crates/iroha/tests/triggers/time_trigger.rs
crates/iroha_core/src/block.rs
crates/iroha_core/src/metrics.rs
crates/iroha_core/src/sumeragi/main_loop.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/events/pipeline.rs
crates/iroha_data_model/src/query/dsl/predicates.rs
crates/iroha_schema_gen/src/lib.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
docs/source/references/schema.json

Fixes #5317
If there are no transactions after a timeout period, and the previous block has transactions, then an empty block will be created. Note that there can't be two sequential empty blocks.
An empty block will be added after a non-empty one if there are no transactions, therefore e.g. pre-commit trigger might get executed more times than you expected.
Also note about `/status` endpoint response fields:
* `blocks` - existing field (no change), note that it will include empty blocks
* `blocks_non_empty` - new field, count of non-empty blocks

feat!: Finalize non-empty blocks by allowing empty blocks after them

---

Dockerfile.build

Unzip package is missed for `Sonarqube` action.
Add unzip package to ci-image. Need to recompile `ci-image` after that.

ci: Add unzip package to ci-image

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/extra_functional/connected_peers.rs
crates/iroha/tests/status_response.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

Fixes #5349
(note that CI tests should fail without `blocks_non_empty`)

fix(Backport): Revert adding `blocks_non_empty` to `/status` endpoint

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/iroha/tests/extra_functional/connected_peers.rs
crates/iroha/tests/status_response.rs
crates/iroha_telemetry/src/metrics.rs
crates/iroha_test_network/src/lib.rs
wasm/Cargo.toml
wasm/samples/mint_rose_trigger/Cargo.toml

Fixes #5349
(note that CI tests should fail without `blocks_non_empty`)

fix(Testnet, Backport): Revert adding blocks_non_empty to /status endpoint

---

.github/workflows/iroha2-dev-pr-static.yml

Looks like we now use poetry v2 on CI, as a result python static analysis workflow fails with error
> The option "--no-update" does not exist
* [Example of failed workflow](https://github.com/hyperledger-iroha/iroha/actions/runs/13901677856/job/38894759162?pr=5373)
* [Workflow history](https://github.com/hyperledger-iroha/iroha/actions/workflows/iroha2-dev-pr-static.yml)
---
In poetry v2 option `--no-update` was removed (it became default behaviour). See https://github.com/python-poetry/poetry/issues/9136

fix(CI): Fix python static analysis workflow for poetry v2

---

Cargo.toml

IMO, setting `unused` to `deny` is a terrible default. It is an obstacle in development. It doesn't have impact on build.
It is of course good to have code clean, and I think `warn` is sufficient to achieve it.
Feel free to reject this PR if you disagree.

build: warn on `unused`, not `deny`

---

crates/iroha_torii/src/lib.rs
crates/iroha_torii/src/routing.rs
crates/irohad/Cargo.toml

Close #5383 
- Covered endpoints gated by `telemetry`, `schema`, and `profiling` features
- Added `profiling-endpoint` feature to `irohad`
When endpoints are feature-gated away, they no longer return `404 Not Found`, but `501 Not Implemented` with a descriptive message. For example, for `GET /status`:
```
HTTP/1.1 501 Not Implemented
content-type: text/plain; charset=utf-8
content-length: 115
date: Mon, 31 Mar 2025 02:03:48 GMT
This endpoint is not available on this version of "irohad", as it was compiled without the "telemetry" feature flag
```

feat(iroha_torii): stubs for feature-gated endpoints

---

crates/iroha_ffi_derive/src/lib.rs

chore: fix some comments

---

.github/workflows/iroha2-dev-sonar-dojo.yml

Pipelines are failed due to `DefectDojo` ruined job. It's failed since it doesn't available more at this time.
Disable `DefectDojo` CI job do not failed pipelines. I would still continue to keeping it commented because it could be become actual again in future. Or be free to remove it to keep a clean code.

ci: disable defectdojo job

---

Cargo.lock
Cargo.toml
crates/iroha_core/Cargo.toml
crates/iroha_core/src/block.rs
crates/iroha_core/src/queue.rs
crates/iroha_core/src/snapshot.rs
crates/iroha_core/src/state.rs
crates/iroha_core/src/state/storage_transactions.rs
crates/iroha_core/src/sumeragi/main_loop.rs

This PR reduces memory usage of Iroha ~3 times.
* Currently:
* ~270 bytes per transaction
* ~2.7 GB after 10 million transactions
* This PR:
* ~80 bytes per transaction
* ~0.9 GB after 10 million transactions
(numbers for "bytes per transaction" correspond only to transaction hashes map, without actual transaction details; numbers for "after 10 million transactions" correspond to total Iroha memory usage)
Related: https://github.com/hyperledger-iroha/iroha/issues/5083#issuecomment-2379804636
Related: https://github.com/hyperledger-iroha/iroha/issues/5378#issuecomment-2801936386
Implement custom version of storage for `State::transactions` map. It uses concurrent map from [`dashmap`](https://github.com/xacrimon/dashmap) crate to implement memory efficient storage for transaction hashes. …

perf: Implemented custom storage for transactions hashes

---

crates/iroha_cli/samples/permission.json
crates/iroha_executor/src/default/mod.rs
crates/iroha_kagami/src/genesis/generate.rs
defaults/genesis.json
scripts/build_wasm.sh
wasm/libs/default_executor/src/lib.rs
wasm/libs/trigger_default_roles/Cargo.toml
wasm/libs/trigger_default_roles/src/lib.rs

Describes the runtime upgrade on the [testnet](https://explorer.fujiwara.sora.org), including the executor and a trigger called `default_roles`:
> Transaction `4C008F982B592B9C75CDBA60E531474BC28B26C186F448402B94542CF2E7C36D`:
> 
> - Upgraded the executor to allow the admin to modify role permissions
> 
> Transaction `2ABBA254385409676E4791E221848868D3D0424D61E0E6F752E08D5000B11D73`:
> 
> - Registered a role `volunteers`
> 
> Transaction `F6105B5A9903933BA68316DB7AC2DD95A268A4542477E1F023220A33171D5421`:
> 
> - Allowed `volunteers` to register domains
> 
> Transaction `2F450000BEB773D6D195AC45D32F5552C3208540F1A1D262CE20E7435F1254CB`:
> 
> - Registered a trigger `default_roles` that grants the `volunteers` role to new accounts
These changes are included in the default setup, which is …

feat(testnet): add default roles with modifiable permissions

---

.github/workflows/publish.yml

This PR restores Docker image build and push by migrating from the deprecated legacy cache service.
- https://github.com/hyperledger-iroha/iroha/actions/runs/14902602396/job/41858558945
- https://github.com/hyperledger-iroha/iroha/actions/runs/14902602396/job/41858558558
- https://github.com/docker/setup-buildx-action/discussions/414#discussioncomment-12693195

ci: fix Docker image build and push by upgrading to latest buildx

---

.github/workflows/ci_image.yml
.github/workflows/pr.yml
.github/workflows/pr_docker_compose.yml
.github/workflows/pr_python_static.yml
.github/workflows/publish.yml
.github/workflows/publish_custom.yml
.github/workflows/publish_dev.yml
Dockerfile
Dockerfile.build
crates/iroha_wasm_builder/src/lib.rs
hooks/pre-commit.sample
rust-toolchain.toml

Bump Rust toolchain from `nightly-2024-09-09` to `nightly-2025-05-08` across project configs.
- Bump `rust-toolchain.toml`, CI workflows, and Dockerfiles to `nightly-2025-05-08`

chore(rust): bump Rust toolchain to nightly-2025-05-08

---

.github/workflows/pr.yml
.github/workflows/pr_labels.yml

Labeler jobs fails with no good reason.
**Example: on the first step**
https://github.com/hyperledger-iroha/iroha/actions/runs/14928905341/job/42104002157?pr=5420
```
Warning: The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions
Error: Resource not accessible by integration
```
**Example: on the second step**
https://github.com/hyperledger-iroha/iroha/actions/runs/14987302747/job/42103506612?pr=5394
```
Error: Resource not accessible by integration
```
The permissions are clearly there, so the errors are confusing.
~~Moving the job back to a dedicated workflow file, as it was before. Maybe this will fix something.~~
- Dedicated workflow file, `on: …

ci: fix labeler

---

crates/iroha_crypto/src/lib.rs
crates/iroha_crypto/src/signature/ed25519.rs
crates/iroha_crypto/src/signature/mod.rs

Related: #5280
Related: https://github.com/hyperledger-iroha/iroha/issues/5280#issuecomment-2904395318
Related: #5048
This PR changes the storage of the `PublicKey` struct. Now, public keys are always stored in compact (encoded) format. In such format, keys can be compared with each other, which is what iroha mostly does with public keys. Public keys will be decoded when signing functionality is needed (e.g., query/transaction signature check).
---
Comparison of memory usage:
* `Account` struct (as is):
* main: 354 bytes
* pr: 116 bytes
* `Account` struct in `World`:
* main: 1006 bytes per account
* pr: 485 bytes per account
I used this code to check memory usage:
<details>
```rust
#![allow(warnings, unused)]
//! .
use iroha_core::{prelude::*, smartcontracts::Registrable};
use …
```

perf: Store public keys in compact format

---

.github/workflows/publish_xx.yml

Image was built successfully, but failed to push there.
I think Dockerhub is sufficient.

ci(xx): do not push to Soramitsu Harbor (auth problems)

---

crates/iroha_core/src/state.rs
integration_tests/tests/upgrade.rs
wasm/Cargo.lock
wasm/samples/executor_with_fuel/Cargo.toml
wasm/samples/executor_with_fuel/src/lib.rs

Initially, I intended to apply a quick patch to #5442 as a workaround until #5358 was completed, but it turned out that routing trigger execution to the executor did not function correctly. This PR only partially documents that behavior.

test(executor): describe error behavior in trigger context

---

crates/iroha_core/examples/memory.rs
crates/iroha_core/src/smartcontracts/isi/account.rs
crates/iroha_core/src/smartcontracts/isi/asset.rs
crates/iroha_core/src/smartcontracts/isi/domain.rs
crates/iroha_core/src/smartcontracts/isi/mod.rs
crates/iroha_core/src/smartcontracts/isi/nft.rs
crates/iroha_core/src/state.rs
crates/iroha_core/src/tx.rs
crates/iroha_data_model/src/account.rs
crates/iroha_data_model/src/asset.rs
crates/iroha_data_model/src/lib.rs
crates/iroha_data_model/src/nft.rs
crates/iroha_data_model/src/query/dsl/compound_predicate.rs

Closes #5034
Related #5280
This PR changes `World::accounts`, `World::assets` and `World::nfts` maps. I choose only these maps (and not e.g. `World::domains`) because it is most likely that they will have a lot of entries and thus it is worth optimizing their memory usage. See https://github.com/hyperledger-iroha/iroha/issues/5034#issuecomment-2940939359 for overview of all maps in `World`.
---
Comparison of memory usage:
* `Account` struct in `World`:
* master: 485 bytes per account
* pr: 338 bytes per account
* `Asset` struct in `World`:
* master: 672 bytes per account
* pr: 423 bytes per account
* `Nft` struct in `World`:
* master: 586 bytes per account
* pr: 454 bytes per account
I used this code to check memory usage:
<details>
```rust
#![allow(warnings, unused)]
//! .
use …
```

perf: Reduce memory usage of `World::accounts` and similar maps

---

crates/iroha_core/src/block.rs
crates/iroha_core/src/queue.rs
crates/iroha_core/src/smartcontracts/isi/account.rs
crates/iroha_core/src/smartcontracts/isi/asset.rs
crates/iroha_core/src/smartcontracts/isi/domain.rs
crates/iroha_core/src/smartcontracts/isi/mod.rs
crates/iroha_core/src/smartcontracts/isi/nft.rs
crates/iroha_core/src/smartcontracts/isi/query.rs
crates/iroha_core/src/smartcontracts/isi/world.rs
crates/iroha_core/src/smartcontracts/wasm.rs
crates/iroha_data_model/src/account.rs
crates/iroha_data_model/src/asset.rs
crates/iroha_data_model/src/domain.rs
crates/iroha_data_model/src/lib.rs
crates/iroha_data_model/src/nft.rs
crates/iroha_data_model/src/role.rs

There are functions such as `Account:new`, which create not `Account`, but `NewAccount`. Sometimes it is not desirable and I, as a user of `iroha_data_model` crate, want to simply create an `Account` itself. The only way to do so without `transparent_api` feature is to use `Registrable` trait (transforming e.g. `NewAccount` to `Account`), which is for some reason defined in `iroha_core`.
This commit moves `Registrable` from `iroha_core` to `iroha_data_model`.

refactor(iroha_core, iroha_data_model): move `trait Registrable` to the data model

---

crates/iroha_core/src/state.rs
crates/iroha_core/src/tx.rs

In my latest assessment, the failure of the `domain_owner_trigger_permissions` test after PR #5457 is not because this PR introduced a bug, but because correctly routing trigger execution to the executor revealed a flaw in the previous implementation: by-call triggers should have sourced authority from the execution-time `event.authority` rather than the registration-time `action.authority`. This PR fixes that.
Also make data triggers inherit the [entrypoint](https://github.com/hyperledger-iroha/iroha/pull/5471#issue-3152413250)'s authority, closing #5441.

fix: inherit trigger authority from entrypoint authority

---

crates/iroha_core/src/block.rs
crates/iroha_crypto/src/lib.rs
crates/iroha_crypto/src/merkle.rs
crates/iroha_data_model/src/block.rs

> I've split out the cryptographic part of the trigger execution logs (from #4968) into a separate PR: #5467
This PR introduces Merkle proof generation and verification to support inclusion checking, as a prerequisite for #4968 (and possibly #4637). It also includes a fix to the construction of the Merkle tree to ensure correct transaction indexing.
* Added `MerkleProof<T>` struct that includes:
* `leaf_index`: the position of the leaf in the tree
* `sibling_hashes`: the list of sibling hashes from the leaf up to the root (excluding the root itself)
* Implemented `MerkleTree::get_proof(leaf_index)` to generate an inclusion proof
* Implemented `MerkleProof::verify(root, max_height)` to verify the proof against a given root
* Fixed the binary operation used to compute parent hashes from …

feat(merkle): implement inclusion proof generation and verification

---

crates/iroha_core/src/block.rs
crates/iroha_core/src/state.rs
crates/iroha_core/src/sumeragi/mod.rs
crates/iroha_core/src/tx.rs
crates/iroha_data_model/src/block.rs

The primary objective of this PR is to enable Explorer to replay blocks without extra validation.
There is **one notable change to the validation flow**: transactions are now checked eagerly as part of block's overall static check. _Before:_ transactions check is mixed with their actual execution.
Other changes:
- Add `ValidBlock::validate_unchecked` and `ValidBlock::commit_unchecked`. These skip static checks. Thus, Explorer can replay the blocks without having to pass genesis account, chain id, topology etc.
- Remove duplication from `NewBlock::validate_and_record_transactions` (now uses `ValidBlock::validate_unchecked`)
- Properly document the different flows of block validation
- Slight refactors

refactor(iroha_core): refactor & document block validation

---

integration_tests/tests/transfer_asset.rs

This PR adds test coverage for transfer operations that use the wrong AssetId. The objective is to ensure comprehensive test coverage for error scenarios in asset transfer functionality, making the codebase more robust and helping prevent regressions.
The change adds a new test case that verifies the system properly handles and reports errors when attempting to transfer assets with incorrect or mismatched asset identifiers.
Closes #4125
Added a new test function `should_fail_if_asset_not_found` that:
- Creates an asset definition but does not mint any assets to an account
- Attempts to transfer a non-existent asset from that account
- Verifies that the operation fails with the appropriate error message
- Ensures the error chain contains the expected "Failed to find asset" message
This …

test: add test for transfer with wrong AssetId

---

Cargo.lock
crates/iroha_kagami/Cargo.toml
crates/iroha_kagami/CommandLineHelp.md
crates/iroha_kagami/src/main.rs
crates/iroha_kagami/src/wasm.rs
crates/iroha_wasm_builder/src/lib.rs
scripts/build_wasm.sh

While working on #5443 and trying to set `--locked` as one of the ways to fix the problem (https://github.com/hyperledger-iroha/iroha/issues/5443#issuecomment-2903877041), I found that it is not possible to pass this argument to Cargo in `build_wasm.sh`.
Now it is possible:
```shell
kagami wasm check path/to/wasm \
--out-file test.wasm \
--cargo-args='--locked'
```

feat(kagami wasm): forward extra arguments to cargo

---

crates/iroha_core/src/query/store.rs

Add a simple constructor for `LiveQueryStoreHandle`. This makes it possible to construct the handle right from `Arc<LiveQueryStore>`, bypassing the need to invoke `LiveQueryStore::start` or `LiveQueryStore::start_test`.
**Rationale:** `State` requires `LiveQueryStoreHandle` on creation. In Explorer, there is a lifecycle stage of having an uninitialised, "dummy" empty state (until any blocks are received). It simplifies internal implementation if there is no need to spawn any tasks and "just create a dummy state and wait for at least the first block" (the first, genesis block contains the genesis account, which Explorer extracts and creates a new `World` and non-dummy `State` with the given account).
Anyway, this PR is pretty straightforward.

feat(core): add a constructor for `LiveQueryStoreHandle`

---

crates/iroha_core/src/state.rs
crates/iroha_core/src/tx.rs
crates/iroha_data_model/src/block.rs
crates/iroha_data_model/src/lib.rs
crates/iroha_schema_gen/src/lib.rs

- Include the entire `iroha_crypto` into `iroha_data_model::prelude` - these types are mentioned and returned everywhere
- Include block-related structs into prelude
- Make `trait TransactionsStorage` public (for Explorer)
I've been long facing annoying incompleteness of the prelude, but never ended up fixing it. I probably missed something this time.

refactor(data-model, core): extend prelude & re-exports

---

crates/iroha_core/src/kura.rs
crates/iroha_core/src/snapshot.rs

- Added `Kura::blocks_count` to read the current storage height
- Made Kura accept `impl Into<Arc<SignedBlock>>` instead of `CommittedBlock`. It is not in the domain of Kura to decide what blocks to store (they just must be `SignedBlock`s), while enforcing `CommittedBlock` forces some code in Explorer to do extra conversion
- Chores

refactor(core, kura): `Kura::blocks_count`; change some Kura signatures & docs

---

crates/iroha_genesis/src/lib.rs
integration_tests/tests/misc.rs

Triggers defined in `wasm_triggers` are registered **after** the `instructions` in the genesis. This disallows to put in instructions referencing the triggers.
IMO registering triggers first is the right approach.

fix(genesis): register triggers before other instructions
